### ISSUE TITLE
Dark mode for website

### ISSUE THREAD

**Issue by Prithwi32** [apu52/Travel_Website#1]
Since in modern days many would like to choose view web pages in dark mode ...

**Comment by Prithwi32** [comment]
I would Like to implement this feature for this project...@apu52 please may this task assigned to me?

**Comment by rahatt2134** [comment]
please describe the issue in proper way with some screenshots, and how it will look after the feature, add a good title for issue as its good practise.Happy coding.

**Comment by rahat2134** [comment]
please describe the issue in proper way with some screenshots, and how it will look after the feature, add a good title for issue as its good practise.Happy coding.

**Comment by Prithwi32** [comment]
> please describe the issue in proper way with some screenshots, and how it will look after the feature, add a good title for issue as its good practise.Happy coding.

Okay sure

**Comment by apu52** [comment]
@Prithwi32 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts

**Comment by Prithwi32** [comment]
> @Prithwi32 Welcome to the repo. Sorry to close this issue. Make sure to open the issues after coding period starts

hello @apu52  Sure sir. I will open this issue after coding phase starts.

**Comment by apu52** [comment]
> > @Prithwi32 Welcome to the repo. Sorry to close this issue. Make sure to open the issues after coding period starts
> 
> hello @apu52 Sure sir. I will open this issue after coding phase starts.

I will suggest you to open an new issue instead of reopening this old one

**Comment by Prithwi32** [comment]
> > > @Prithwi32 Welcome to the repo. Sorry to close this issue. Make sure to open the issues after coding period starts
> > 
> > 
> > hello @apu52 Sure sir. I will open this issue in the same topic after coding phase starts.
> 
> I will suggest you to open an new issue instead of reopening this old one
Okay, U want me to work on dark mode feature or different feature you like me to contribute?

**Comment by apu52** [comment]
> > > > @Prithwi32 Welcome to the repo. Sorry to close this issue. Make sure to open the issues after coding period starts
> > > 
> > > 
> > > hello @apu52 Sure sir. I will open this issue in the same topic after coding phase starts.
> > 
> > 
> > I will suggest you to open an new issue instead of reopening this old one
> > Okay, U want me to work on dark mode feature or different feature you like me to contribute?

You can raise any issue you want to work on . Just look at the existing issues before raising new issues.
