### ISSUE TITLE
[FEATURE REQUEST] Create a contact us form.

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#10]
- I wish to build a contact us form for your website that will be linked to the contact us button on the navbar. 
- it will be placed just above the subscribe section.
- It will be linked to your gmail and users can directly mail you through your website without redirecting them to gmail.
- I am willing to work on this feature, please assign this to me once the coding phase starts (JWOC'24). Thanks.
@apu52 

![Contact1](https://github.com/apu52/Travel_Website/assets/110532770/10800f76-17b1-4987-9fff-b3bae359b51a)

This is somewhat how the form will look like, It will be customized according to your websites's theme and will be updated with your links
![Screenshot 2024-01-11 144248](https://github.com/apu52/Travel_Website/assets/110532770/337b143b-4e79-4df8-8628-fcff834392a2)

**Comment by DarshSohaliya** [comment]
I would like to contribute this issue

**Comment by PranavBarthwal** [comment]
> I would like to contribute this issue

I've opened this issue, for myself. You can find some other issues. Thanks.
