### ISSUE TITLE
BUG: Missing link to "Watch Our Story"

### ISSUE THREAD

**Issue by clanang** [apu52/Travel_Website#100]
**Describe the bug**

When clicking on the "Watch Our Story" under the "Book Now" heading, nothing happens.

**Expected behavior**

Users expect to see a video detailing information about the goals or purpose of the website when clicking the link.

**Screenshots (Mandatory)**

<img width="999" alt="website-screenshot" src="https://github.com/apu52/Travel_Website/assets/78218638/7b87e0ff-d554-4b5b-8fee-7d4585cce72f">

**Additional Context (Mandatory )**
This issue was brought up by @rahat2134 last week, but closed before being addressed. I'd like to link a general video supporting travel agencies and highlighting the benefit of using a travel agency over going through OTAs (online travel agency) like Airbnb, etc.
***Are you contributing under any open-source program ?***

Please assign this issue to me under JWOC2k24
Thank you!

**Comment by apu52** [comment]
@clanang You are assigned you can start working on this issue. Just a advice attach a video or a webpage which will be accessed by under when they click the WATCH OUR STORY button

**Comment by prakharsingh-74** [comment]
@apu52 I would like to work on this issue. could you please assign me that?

**Comment by apu52** [comment]
> @apu52 I would like to work on this issue. could you please assign me that?

This issue is already assigned. you can raise any new issue you want to work on
