### ISSUE TITLE
[Bug]: Text is overlapping in the signup page.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Text on the left is overlapping with the arrow and with the top of the window in the sign up page.

### Expected behavior

Kindly assign me this and I can fix this issue.

### Add ScreenShots

![Screenshot (643)](https://github.com/apu52/Travel_Website/assets/143121854/8d10d3ab-2a35-4aa3-a83a-fb533f47cb99)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@itsekta @apu52  I have fixed this issue.

**Comment by itsekta** [comment]
Fixed in #1012, will be merged soon.
