### ISSUE TITLE
Re-Create Cursor Trail Effect to The Website

### ISSUE THREAD

**Issue by MastanSayyad** [apu52/Travel_Website#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 

I would like to Re-create add a Cursor trail effect matching to the website design theme across all the pages of the website (for consistency)

The current one is not working properly nor it is sync to the cursor

**I will make sure:**

- It is smooth without lag.
- Aesthetically pleasing
- The trail effect does not interfere with other interactive elements on the page.
- It does not irritate to users instead it will be fun to play with!

### Expected behavior

It should work properly 

### Add ScreenShots

**Some examples of my works are:**

https://github.com/Indie-Kart/ecommerce-store/assets/101971980/9d9e741e-065e-4f65-893a-9a01b8ecba54

https://github.com/Indie-Kart/ecommerce-store/assets/101971980/2ec1964f-6ce8-4029-86f7-62d5df520211

https://github.com/Its-Aman-Yadav/Community-Site/assets/101971980/95dd3a00-a331-4cf3-ae8b-28319878190d

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@itsekta Please assign this issue to me

**Comment by itsekta** [comment]
Fixed in #1033

**Comment by MastanSayyad** [comment]
@itsekta so it is fixed bt me na? The #1033 Pull request is Mine

**Comment by MastanSayyad** [comment]
without merging the PR pls don't close the issue @itsekta

**Comment by itsekta** [comment]
Hey @MastanSayyad, the PR is created by you, it will be updated by your name. I have close it so that no one else will ask to assign this issues and also I can manage the other opened issues easily

**Comment by itsekta** [comment]
Hey @MastanSayyad, the PR is created by you, it will be updated by your name. I have close it so that no one else will ask to assign this issues and also I can manage the other opened issues easily

**Comment by MastanSayyad** [comment]
@itsekta I get it. Thank You!
