### ISSUE TITLE
[Bug]:  re-creating the destinations section

### ISSUE THREAD

**Issue by SMD111-git** [apu52/Travel_Website#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 
.The Desgin is not appealing .
.In this we cann't display as many we destination are they in the site olny few of them is showed in this

### Expected behavior

. i will recreatre this section by adding scroller where user can just scroll and see all the desnation
.with much more responsive desgin 

### Add ScreenShots

![vsoc](https://github.com/apu52/Travel_Website/assets/111645920/151d1487-6d42-443e-aa8a-1a69a6f437e4)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @SMD111-git, do you have any design templates for this? Can you share the screenshot

**Comment by SMD111-git** [comment]
![Travel Destinations - Google Chrome 08-07-2024 15_55_25](https://github.com/apu52/Travel_Website/assets/111645920/8bfc639d-e4ed-468d-9a51-cb37f8c034f8)
 i have added the scroll bar where the user can easily see all destinations

**Comment by SMD111-git** [comment]
https://github.com/apu52/Travel_Website/assets/111645920/816206d9-c9a7-420c-88e4-dc70a2cc52a1

demo

**Comment by SMD111-git** [comment]
https://github.com/apu52/Travel_Website/assets/111645920/4744b596-3ddd-498e-88f4-7d4aff25e937

Desgin 2
Hey there @itsekta i got another layout section

**Comment by itsekta** [comment]
Hey @SMD111-git, the videos you have shared aren't working. Can you please check it once again

**Comment by SMD111-git** [comment]
https://github.com/apu52/Travel_Website/assets/111645920/b17146e6-cdd4-4c96-92d9-26eafa84568b

check now @itsekta

**Comment by itsekta** [comment]
Hey @SMD111-git, Go ahead make the changes

**Comment by apu52** [comment]
@SMD111-git u are assigned .start working on it .7 submit your PR ASAP

**Comment by apu52** [comment]
@SMD111-git  as VSOC time period is over , I am closing this issue
