### ISSUE TITLE
[Bug]: Redirecting to /story page instead of the desired url

### ISSUE THREAD

**Issue by itsekta** [apu52/Travel_Website#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On landing page when the popup modal appears and clicking on **close icon** it is redirecting to /story page instead of the main landing page and while on the /story page clicking on any navigation link it is still redirecting to /story page instead of the link that we have clicked. This thing doesn't happens with which click on **no thanks** on the modal.

https://github.com/apu52/Travel_Website/assets/60789158/e84f194c-c609-43ef-b34a-4d26cfdeb67e

Anyone interested can solve this bug.

### Expected behavior

Similar to when clicked on **no thanks** on the popup modal when clicked on the **close icon** on that modal should not redirect us to /story page and same for the other links as well

### Add ScreenShots

Main Landing page

![image](https://github.com/apu52/Travel_Website/assets/60789158/56adac2a-7716-4cd3-a7cf-eb822ccbb1d3)

When clicked on **close icon** on popup modal

![image](https://github.com/apu52/Travel_Website/assets/60789158/83f02253-de75-4409-bc7c-18dcdeecd1fe)

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@itsekta  I want to work on this issue.

**Comment by itsekta** [comment]
@meetarora10 assigned.
