### ISSUE TITLE
[Bug]: No effect on the navbar on the FAQ page in dark mode.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no effect of the dark mode on the navbar on the FAQ page.

### Expected behavior

I can make the required changes to fix this issue.

### Add ScreenShots

![Screenshot (656)](https://github.com/apu52/Travel_Website/assets/143121854/1dc5de3b-237a-4ea3-90cc-711d0e495716)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @meetarora10, this has already been fixed in #1011
