### ISSUE TITLE
[Bug]: Links on the navbar of FAQ page are not working.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The links of the navbar on the FAQ's page are not working.

### Expected behavior

Kindly assign this task to me and I can fix this issue.

### Add ScreenShots

https://github.com/apu52/Travel_Website/assets/143121854/9be1375d-6ea3-469d-b8ba-a8409a1532d9

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @meetarora10, this has already been fixed in #1011
