### ISSUE TITLE
[Bug]: Chatbot not working

### ISSUE THREAD

**Issue by DevNandini02** [apu52/Travel_Website#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The chatbot is not responding to the queries. Also it is not embedded in the home page.

### Expected behavior

I can create a chatbot that answers to all the queries of users. It will be able to answer the queries using the given knowledge base as well as AI.

### Add ScreenShots

![travel_bug](https://github.com/apu52/Travel_Website/assets/124669890/55a52f34-85a7-4de4-8ec4-5d23c20d1693)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ankitmodanwall** [comment]
tell error @DevNandini02  ??

**Comment by DevNandini02** [comment]
> tell error @DevNandini02 ??

@ankitmodanwall sir the chatbot is not working. It is not able to reply to the queries. I screenshot added above shows the error, it is saying the chatbot is unavailable.

**Comment by DevNandini02** [comment]
@ankitmodanwall please assign me this issue, i can make the chatbot fully functional.

**Comment by ankitmodanwall** [comment]
@DevNandini02 sorry for that as i don't have access to provide to you for this chatbot but you should mention the owner here...

**Comment by DevNandini02** [comment]
@apu52 please assign me this task.

**Comment by apu52** [comment]
@DevNandini02 u are assigned .thanks for raising this issue. u can start working on it

**Comment by apu52** [comment]
> tell error @DevNandini02 ??

@ankitmodanwall I just want to request u please don't ask unnecessary questions to the contributors otherwise they get confused. PA & mentors are already present in the repo to review the issues . I think u will understand

**Comment by ankitmodanwall** [comment]
@apu52 see I answered only those questions which was important for this project..
