### ISSUE TITLE
[Bug]: Footer is unorganized

### ISSUE THREAD

**Issue by Rajul-29** [apu52/Travel_Website#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The go to top button is outside the footer and is ruining the look of the website

### Expected behavior

The go to top button should be inside the footer

### Add ScreenShots

![Screenshot 2024-07-10 125759](https://github.com/apu52/Travel_Website/assets/165317476/31ca34ca-6c23-4412-8e31-63763161fdb6)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Rajul-29 u are assigned
