### ISSUE TITLE
[Bug]: Bubbles covering content

### ISSUE THREAD

**Issue by AnjPR** [apu52/Travel_Website#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The background bubbles are covering content in the home page its difficult to see the content sometimes.

### Expected behavior

The bubble should roam behind the content , so its beuatiful and the content is visible.

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by AnjPR** [comment]
Can you assign this to me

**Comment by apu52** [comment]
@AnjPR now the bubble animation is not present in the website . so I think is this issue is not relevant now . So I am closing this issue for now .But u can still make new issue on which u want to work.
