### ISSUE TITLE
Add Contributors Page to Display Project Contributors

### ISSUE THREAD

**Issue by pani2004** [apu52/Travel_Website#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The contributors page will display the details of the contributors who have contributed to this project

### Use Case

Since this repo is part of a open source program it would be great to have a contributors page

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by pani2004** [comment]
@apu52 @KrishnenduDG Can I work on this?

**Comment by apu52** [comment]
@pani2004 u are assigned. But can u share some SS of the page u are suggesting so that I will get an idea on which features u want to add in the website

**Comment by pani2004** [comment]
Done by me - 
![15 07 2024_02 34 43_REC](https://github.com/user-attachments/assets/ab317428-a001-47f9-b050-baddf1573f6f)
 @apu52

**Comment by apu52** [comment]
go ahead & submit your PR
