### ISSUE TITLE
[Feature Request]: Adding a blog section

### ISSUE THREAD

**Issue by ayush-848** [apu52/Travel_Website#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

User will be able to see other people's blog who booked their tickets from Travel_Website for a particular location 

### Use Case

User will be able to see other people's blog who booked their tickets from Travel_Website for a particular location 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ayush-848 we already have a testimonial section .as u have suggested the blog section...it maybe the same type of things ,....so instead of adding can u enhance the testimonial section or u have other plans regarding the blog section??
please provide some SS about the features u want to add

**Comment by ayush-848** [comment]
> @ayush-848 we already have a testimonial section .as u have suggested the blog section...it maybe the same type of things ,....so instead of adding can u enhance the testimonial section or u have other plans regarding the blog section?? please provide some SS about the features u want to add

U have different plans
I can make it 
If you like it then you can accept the PR

**Comment by apu52** [comment]
okk then I am assigning u .u can start working on this issue.

**Comment by ayush-848** [comment]
@apu52 I did the page

**Comment by ayush-848** [comment]
![image](https://github.com/user-attachments/assets/94288e27-9165-49ff-9787-f91abccd35ba)
![image](https://github.com/user-attachments/assets/71178c89-1140-4d4c-a412-024d3e703b62)
@apu52

**Comment by ayush-848** [comment]
@apu52 I have put in a lot of efforts here. This is not yet completed as I have not added the images. But do you like it till now?
are you going to add it

**Comment by ayush-848** [comment]
@apu52 You can also see the site https://www.awesomescreenshot.com/video/29610250?key=5d6ad868a6a3fc571462193c6cf1dd9b

**Comment by ayush-848** [comment]
@apu52 please say do you like it??

**Comment by apu52** [comment]
> @apu52 You can also see the site https://www.awesomescreenshot.com/video/29610310?key=f7b08f4ea6d3a803e98d317c66ff822f

It's really impressive . the changes u have made in the blog section it's really great . Just complete the whole blog section 7 then go ahead with your PR

**Comment by ayush-848** [comment]
> > @apu52 You can also see the site https://www.awesomescreenshot.com/video/29610310?key=f7b08f4ea6d3a803e98d317c66ff822f
> 
> It's really impressive . the changes u have made in the blog section it's really great . Just complete the whole blog section 7 then go ahead with your PR

Sure
