### ISSUE TITLE
[Bug]: Wrong theme of Testimonials in Dark-Mode

### ISSUE THREAD

**Issue by VijaySamant4368** [apu52/Travel_Website#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Even after switching the mode to dark mode, there is no change of color theme in the Testimonials

### Expected behavior

When the mode changes, the theme of the testimonials should also change.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6accfe99-6d48-4db4-9945-eafa572026b6)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@VijaySamant4368 under which programme do u want to contribute?? otherwise I can't assign u.

**Comment by VijaySamant4368** [comment]
@apu52 it is under GSSoC 2024

**Comment by VijaySamant4368** [comment]
I am sorry for not mentioning it in my original comment.

**Comment by apu52** [comment]
> I am sorry for not mentioning it in my original comment.

no probs .I have assigned u . u can start working.

**Comment by VijaySamant4368** [comment]
@apu52 @itsekta please add the level tag.
