### ISSUE TITLE
[Feature Request]: Integrating Docker into the project

### ISSUE THREAD

**Issue by Ratangulati** [apu52/Travel_Website#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Docker is a must for open-source projects nowadays as it has its benefits.

I will also be updating the docs for it.

### Use Case

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
#965 already present in this repo .so sorry it's a duplicate issue .sorry I can't assign u . but u can still work on new issues on which u want to work on.
