### ISSUE TITLE
[Bug]: The Email Input box is not aligned properly on Newsletter Section.

### ISSUE THREAD

**Issue by vishanurag** [apu52/Travel_Website#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- The Email Input box is not aligned properly on Newsletter Section.
- There is a black border on email input box that should be removed.

### Expected behavior

- The Email Input box should be aligned center vertically.
- Also that black border should be removed.

### Add ScreenShots

![Screenshot 2024-07-14 183017](https://github.com/user-attachments/assets/cca771ed-bd8c-40f6-90c1-7811262ea610)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by vishanurag** [comment]
Please this issue to me under GSSoC'24

**Comment by ankitmodanwall** [comment]
@apu52 please assign this issue to me..

**Comment by itsekta** [comment]
This issues is already present chech issue #1052
