### ISSUE TITLE
[Feature Request]: Enhancing login page UI

### ISSUE THREAD

**Issue by DevNandini02** [apu52/Travel_Website#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the login page looks like this.

![travel4](https://github.com/user-attachments/assets/99c7223b-7762-4098-b016-24882f2e850a)

I can make the UI better , such that at one side the user is able to register and then it slides and user can login on the other side.
Also currently the login button is not working. 

### Use Case

It would make it easier for users to login and register. Also I would be adding form validation.

### Benefits

It would enhance the UI and make it easy for user to register and login.

### Add ScreenShots

https://github.com/user-attachments/assets/d38f6dfe-887b-4eec-98ac-e18abc0cde2b

The functionality would be same but its UI would be on travel theme only.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by DevNandini02** [comment]
@apu52 sir please assign me this task.

**Comment by itsekta** [comment]
Hey @DevNandini02, the current login page UI looks the same that you are suggesting. Have you checked it?

![image](https://github.com/user-attachments/assets/36d886d7-2be6-4028-a6a0-cc4940ff9d0e)

**Comment by DevNandini02** [comment]
@itsekta sorry it might have updated later.
