### ISSUE TITLE
Adding horizontal text scroll

### ISSUE THREAD

**Issue by KavyaBS123** [apu52/Travel_Website#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding horizontal text scroll on the website landing page 

### Use Case

It improves the UX of the website

### Benefits

It improves the UX of the website

### Add ScreenShots

Uploading horizontaltextscroll.mp4…

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KavyaBS123** [comment]
Hey @itsekta I would like to work under VSOC and not GSSOc can please relabel the issue

**Comment by apu52** [comment]
@KavyaBS123 U CAN START WORKING

**Comment by KavyaBS123** [comment]
Suree

**Comment by apu52** [comment]
@KavyaBS123  as VSOC time period is over , I am closing this issue
