### ISSUE TITLE
"Go To Top" button not visible in the home page. 

### ISSUE THREAD

**Issue by anijit18** [apu52/Travel_Website#1067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The button "Go To Top" in the home page is not visible, the button has the same backgound as the page.
It gets visible only on hover.

### Use Case

By changing the background colour of the button appropriately, I will make it visible so that the visibilty and functionality of the project increases.
This increases the functionality of the project.

### Benefits

Implementing this feature increases the project usability.

### Add ScreenShots

![Screenshot 2024-07-14 212907](https://github.com/user-attachments/assets/1d3f9cb2-e534-4f91-a8d9-9c470fca84bb)
![Screenshot 2024-07-14 212944](https://github.com/user-attachments/assets/c6d3ad18-482b-4aac-aff5-66e0f733bd08)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by anijit18** [comment]
@itsekta @apu52  Please add the Level tag. I have the changes and would like to push them.

**Comment by Innocentcoder01** [comment]
Hi,  @itsekta @apu52 
I want to work on this issue. I also worked on many proects of frontend development. Waiting for you response. Thank you!

**Comment by Shukla000** [comment]
hey, I want to work upon this. Waiting for your response

**Comment by PoojithaReddyKandula** [comment]
Hello @apu52 I am a contributor @GSsoc-extd I have worked on this issue I have solved it. Please assign me this issue under @GSsoc-extd level-2.
-Thank You
![Screenshot (884)](https://github.com/user-attachments/assets/0d0ed05e-2132-46b4-99a8-0d63d72a5f5d)
Please look into this and assign me the project
