### ISSUE TITLE
Font Mismatch in the Footer Section

### ISSUE THREAD

**Issue by anijit18** [apu52/Travel_Website#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Footer Section of the home page has very small Font compared to the whole page, decreasing the readability of the project.

### Use Case

By correcting the font in the Footer Section, the Readability and Visibilty of the project is enhanced and the links and references are put to better use.

### Benefits

The functionality and Readability of the project is increased.

### Add ScreenShots

![Screenshot 2024-07-14 214425](https://github.com/user-attachments/assets/727f1287-1f73-4147-8efb-0bb799647bc4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by anijit18** [comment]
@itsekta @apu52  Please add the Level tag. I have made the necessary changes and would like to push them

**Comment by Innocentcoder01** [comment]
Hi, @itsekta @ 
I want to work on this issue. I also worked on many proects of frontend development. Waiting for you response. Thank you!
