### ISSUE TITLE
{FEATURE} : Payment Portal Using Only HTML CSS

### ISSUE THREAD

**Issue by daksh1210jain** [apu52/Travel_Website#107]
**Describe the solution you'd like**

I am thinking to add a payment portal which is not actually a portal but a interface looking like a payment portal using HTML and CSS

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/137384322/bfd79d13-c85f-4ac0-9a55-2c24a9fcac1d)
![image](https://github.com/apu52/Travel_Website/assets/137384322/65a78788-c08c-4fc4-a942-332e4c8eeaed)
![image](https://github.com/apu52/Travel_Website/assets/137384322/b418683e-bfc2-47d1-ab1b-f217c768b447)

***Are you contributing under any open-source program ?***
JWOC

**Comment by daksh1210jain** [comment]
Kindly assign me this issue

**Comment by akarshi19** [comment]
Please assign me this task under JWOC'2024

**Comment by apu52** [comment]
@daksh1210jain this is really a good issue . thank you . But already there is already an issue assigned #65 . But you can still wait . if I can I will surely assign u this

**Comment by apu52** [comment]
@daksh1210jain this issue is already completed. sorry to close this issue. you can make any new issue as per your choice
