### ISSUE TITLE
[Bug]: Wrong Hover Animation

### ISSUE THREAD

**Issue by Rajul-29** [apu52/Travel_Website#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hovering on the buttons (Membership, Plan a trip, Book now) on the landing page gives 2 effects at once

### Expected behavior

They should show only 1 effect

### Add ScreenShots

![Screenshot 2024-07-15 045814](https://github.com/user-attachments/assets/1969d137-05e9-4f9a-b0a0-5240a9e6f4bc)
![Screenshot 2024-07-15 045821](https://github.com/user-attachments/assets/3422dc76-67b9-4401-957d-9331cde5a778)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @Rajul-29, nice catch. There is no issues with two animations, but one thing you can do is that move the underline effect just below the text instead of the outside of the buttons and also the color should be similar to the hovering color of the text that is white

**Comment by Rajul-29** [comment]
Hey @itsekta 
I have made a PR can you look please look into it
Thank you
