### ISSUE TITLE
We can add an assist feature

### ISSUE THREAD

**Issue by KavyaBS123** [apu52/Travel_Website#1072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 we can add an assist feature at the right bottom of the landing page which improves the UX of the website.

### Use Case

 improves the UX of the website allowing better interaction of user with the website.

### Benefits

 improves the UX of the website allowing better interaction of user with the website.

### Add ScreenShots

![Screenshot (628)](https://github.com/user-attachments/assets/35730f7a-ffea-43c4-b4f6-2e8113dfba2c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@KavyaBS123 I have assigned u .But first please try to complete previously assigned pR's.

**Comment by apu52** [comment]
@KavyaBS123  as VSOC time period is over , I am closing this issue
