### ISSUE TITLE
Allignment looks merged - Guides tours & Destinations 

### ISSUE THREAD

**Issue by 21pa1a6149** [apu52/Travel_Website#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In about section the count of number of guides,tours and destination part looks merged and itis not looking good as all numbers are are like merged
![Screenshot 2024-07-15 095440](https://github.com/user-attachments/assets/d1ffb4a8-4410-49ca-9db5-32401848668e)

### Expected behavior

I will reallign that part so the three parts tours guides and destination will look good

### Add ScreenShots

![Screenshot 2024-07-15 095440](https://github.com/user-attachments/assets/f0f7ba44-2156-4ec8-b714-8ef176cf7704)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@21pa1a6149 under which open source programme u are contributing ?? otherwise I can't assign u

**Comment by 21pa1a6149** [comment]
I am contributing under GSSOC'24

**Comment by apu52** [comment]
@21pa1a6149 u are assigned .but try to complete the issues one by one
