### ISSUE TITLE
Navbar Hover 

### ISSUE THREAD

**Issue by 21pa1a6149** [apu52/Travel_Website#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In navbar the hover on nvabar component like home, about,destination the hover underline is coming outside the navbar
![Screenshot 2024-07-15 103436](https://github.com/user-attachments/assets/edbcea5c-62be-4cc7-99d9-7b2b4cdfe133)

### Expected behavior

I will perform changes on hover navbar so the underline will come just below the components inside navbar

### Add ScreenShots

![Screenshot 2024-07-15 103436](https://github.com/user-attachments/assets/22c9d172-278f-4671-b3a3-a333eb0ba1fb)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@21pa1a6149 u are assigned

**Comment by ASP124** [comment]
I can work on the styling part of this navbar. Could you please assign this task to me.

**Comment by apu52** [comment]
> I can work on the styling part of this navbar. Could you please assign this task to me.

This issue is already assigned . U can make other new issues

**Comment by vaishnavi-jais** [comment]
It looks like our navbar is having a bit of a styling hiccup—the hover underline on elements like Home, About, and Destination is straying outside the navbar's bounds, making it look like it’s breaking free from its constraints!

I’m excited to step in and reel in that wayward underline, ensuring it stays neatly within the navbar's borders and adds a polished touch to our design. Could you please assign me this task for GSoC '24? I’m ready to fine-tune the styling and bring harmony back to our navbar!

Thanks for considering my request!

**Comment by apu52** [comment]
> It looks like our navbar is having a bit of a styling hiccup—the hover underline on elements like Home, About, and Destination is straying outside the navbar's bounds, making it look like it’s breaking free from its constraints!
> 
> I’m excited to step in and reel in that wayward underline, ensuring it stays neatly within the navbar's borders and adds a polished touch to our design. Could you please assign me this task for GSoC '24? I’m ready to fine-tune the styling and bring harmony back to our navbar!
> 
> Thanks for considering my request!

Okay.please make a complete new issue on this & implement & comment all of your changes there.
