### ISSUE TITLE
Revamp the feedback page according to the existing theme of website.

### ISSUE THREAD

**Issue by Aashi19234** [apu52/Travel_Website#108]
**Describe the bug**
The current feedback page is little off theme.

**Expected behavior**
User expects a feedback page according to the theme of website as given below.
**Screenshots (Mandatory)**
![Screenshot (63)](https://github.com/apu52/Travel_Website/assets/140010647/5f93c6e8-bcfd-4550-8cdb-b43b205de5bd)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes I am contributing to jwoc 2024

**Comment by Aashi19234** [comment]
@apu52 I would like to contribute to this issue under jwoc 2024

**Comment by apu52** [comment]
@Aashi19234 thank you for raising the issue but on  Which feedback page you want to work on as I can't see any feedback page...can you please share some proper SS

**Comment by Aashi19234** [comment]
@apu52 Here is the feedback page i am talking about, 
![Screenshot (64)](https://github.com/apu52/Travel_Website/assets/140010647/3ccf9b0e-5ba0-46a2-b896-24a2de042a29)

**Comment by apu52** [comment]
@Aashi19234 You are assigned. you just have 1 day to complete this issue
