### ISSUE TITLE
✨Feature: Implement "Feedback Page" to TravelWebsite!

### ISSUE THREAD

**Issue by aslams2020** [apu52/Travel_Website#1080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 and @itsekta ,

I Want to implement a feedback form/page on the website to gather user feedback and improve the Website services. 
The feedback form page should be accessible from the main navigation and allow users to easily provide their thoughts and suggestions.

### Here's What Will I Do 
- Form Fields **(Name, email, Rating, Feedback)**
- I Will **Add a "Modal" Button** On Clicking which the **Feedback Page will open** (for ex below)
- Additionally, will add a "Tooltip" for the modal feedback button.
- Will Ensure that **email field contains a valid email address.**
- **"Star Rating System" that must be between 1 and 5.**
- **The form will match the current website's design and aesthetics.**
- Provide a **thank you alert upon successful submission.**

**Here's Example of My Previous Work -**

https://github.com/user-attachments/assets/8105c34e-5dd0-4b8e-a2ea-b9d19ce8c66d

Please 

### Use Case

For a Travel Website, Having a feedback form to improve its services is a must, So that the Visitors will have a chance to convey their thoughts.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@aslams2020 we already have a well designed star rating page as well as a feedback page in our website . So I think there is no need of this issue .Sorry to close this issue .but u  can still submit new issues
