### ISSUE TITLE
[Bug]: Email input field is not same as of name and other input field .

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Email input field is not same as of name and other input field .

### Expected behavior

I can make this input field similar to the other two .

### Add ScreenShots

![Screenshot (730)](https://github.com/user-attachments/assets/f623af8f-767f-49a8-aff0-32a5d166661f)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@itsekta kindly consider this issue .

**Comment by apu52** [comment]
@meetarora10 u are assigned

**Comment by malvika-sinha** [comment]
I want to resolve the issue, Kindly assign me the task

**Comment by itsekta** [comment]
A PR is already present for this bug. Please refer to #1079
