### ISSUE TITLE
[Bug]: Subscribe option is not visible clearly .

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The subscribe option is not visible properly in the section above the footer .

### Expected behavior

Assign this task to me and I can fix this issue .

### Add ScreenShots

![Screenshot (729)](https://github.com/user-attachments/assets/76a9c1bf-6820-4007-9ba8-60997157a26e)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 u are assigned .but at first please try to complete previously assigned issues.

**Comment by meetarora10** [comment]
Okay
