### ISSUE TITLE
Enhancing About Section

### ISSUE THREAD

**Issue by AshmitaBarthwal** [apu52/Travel_Website#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Would like to add a background to ABOUT section as it seems simple compared to rest of the website.

### Use Case

This would enhance the look of the  website making it visually appealing to the viewers.

### Add ScreenShots

![Screenshot 2024-07-15 233604](https://github.com/user-attachments/assets/b95bc024-99c3-4093-a903-f30fb2b88682)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@AshmitaBarthwal u are assigned
