### ISSUE TITLE
Google logo adjustment

### ISSUE THREAD

**Issue by AshmitaBarthwal** [apu52/Travel_Website#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Logo of Google is not clearly visible and also not visually appealing at the bottom of the website.

### Use Case

Improves the interface of website.

### Add ScreenShots

![Screenshot 2024-07-15 234255](https://github.com/user-attachments/assets/1ee31c65-b919-4804-93cc-28d72009c9bd)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by AshmitaBarthwal** [comment]
@itsekta @apu52 Please assign this issue to me and Mark the level under Gssoc.

**Comment by apu52** [comment]
@AshmitaBarthwal u are assigned .but please at first try to complete previously assigned issues.

**Comment by AshmitaBarthwal** [comment]
@itsekta Please mark the LEVEL of contribution Label.
