### ISSUE TITLE
Enhancing Contact Us Section

### ISSUE THREAD

**Issue by AshmitaBarthwal** [apu52/Travel_Website#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The contact us section is not visualling appealing i would like to make it more attractive so the the options are clearly visible.

### Use Case

Improving the UI of website

### Add ScreenShots

![Screenshot 2024-07-15 234958](https://github.com/user-attachments/assets/2e7fceea-c293-4c2c-9800-e2c394f6ae0f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by AshmitaBarthwal** [comment]
@itsekta @apu52 Please assign this issue to me and mark the LEVEL under Gssoc.

**Comment by apu52** [comment]
@AshmitaBarthwal please don't more than 2 issues at at a time .please try to follow the rules mentioned in the CONTRIBUTING.md file . I am not closing this issue now . But after successful completion of previously assigned issues ping me here , I will assign u this issue.

**Comment by malvika-sinha** [comment]
I want to resolve the issue, Kindly assign me the task

**Comment by AshmitaBarthwal** [comment]
@apu52 Sir I have successfully completed the previous 2 issues.
Please assign these 2 new issues to me.

**Comment by AshmitaBarthwal** [comment]
#1086 #1087 are marked waiting. @apu52 I am ready to work upon them now.

**Comment by apu52** [comment]
@ssyy21 I think this issue is not relevant now , this issue has now already been solved , so sorry to close this issue
