### ISSUE TITLE
Fixing Login option

### ISSUE THREAD

**Issue by AshmitaBarthwal** [apu52/Travel_Website#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The login/sign up and view Section seems odd in terms of their color and font. I would like to fix it to make it visually appealing.

### Use Case

Improvement of UI

### Add ScreenShots

![Screenshot 2024-07-15 235440](https://github.com/user-attachments/assets/15a1bd62-471e-457c-b402-71f21f019ec8)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by AshmitaBarthwal** [comment]
@itsekta @apu52 Please assign this issue to me and Mark the LEVEL under Gssoc 24.

**Comment by apu52** [comment]
@AshmitaBarthwal please don't more than 2 issues at at a time .please try to follow the rules mentioned in the CONTRIBUTING.md file . I am not closing this issue now . But after successful completion of previously assigned issues ping me here , I will assign u this issue.

**Comment by AshmitaBarthwal** [comment]
@apu52 Sir I have successfully completed the previous 2 issues.
Please assign these 2 new issues to me that have been marked waiting.
