### ISSUE TITLE
Feature_Request  Add Scrolling Animations to make the website Impressive .

### ISSUE THREAD

**Issue by SohanRC** [apu52/Travel_Website#109]
**Is your feature request related to a problem? Please describe.**
Add Scrolling Animations to make the website Impressive  and much more Professional.

***Are you contributing under any open-source program ?***
Yes , I am contributing Under JWOC 2024. Please assign this issue to me under JWOC 2024.

**Comment by apu52** [comment]
@SohanRC You are assigned. you just have 1 day to submit your PR

**Comment by SohanRC** [comment]
@apu52 I have submitted a PR. Please check and review it.
