### ISSUE TITLE
[Feature Request]: Better Mobile Responsive for Nav-Bar

### ISSUE THREAD

**Issue by VijaySamant4368** [apu52/Travel_Website#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A better view for Mobile devices is required for the Nav-Bar.

### Use Case

If the website had good UI for mobile devices, the website will have more traffic

### Add ScreenShots

![image](https://github.com/user-attachments/assets/495e084d-07e3-4e4b-aea0-ce4a747bf7f0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@VijaySamant4368 u are assigned

**Comment by VijaySamant4368** [comment]
@apu52 PR sent

**Comment by VijaySamant4368** [comment]
@apu52 @itsekta  please add the level tag.
