### ISSUE TITLE
Enhance License and Acknowledgments Section Clarity

### ISSUE THREAD

**Issue by Zoha-Waheed** [apu52/Travel_Website#1095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Without clear licensing information, users may hesitate to engage with or contribute to the project due to uncertainty about usage rights. Inadequate acknowledgment of contributors diminishes morale and recognition within the community.

### Suggested Change

Without clear licensing information, users may hesitate to engage with or contribute to the project due to uncertainty about usage rights. Inadequate acknowledgment of contributors diminishes morale and recognition within the community. Add a heartfelt message of gratitude to encourage further p
articipation and collaboration.

Assign this issue to me as a GSSOC 24 contributor

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Zoha-Waheed the licensee is already added in the repo ...so what do u want to add more in this?? Can u please explain??

**Comment by Zoha-Waheed** [comment]
> @Zoha-Waheed the licensee is already added in the repo ...so what do u want to add more in this?? Can u please explain??

License Clarity: Clearly specify the project's licensing terms (e.g., MIT License) in a dedicated section at the end of the README. Provide a brief summary of what the license permits and requires.
Acknowledgments Enhancement: Create a separate subsection under acknowledgments to highlight the contributions of individual contributors. Include links to their profiles or other forms of recognition to foster community engagement and appreciation.

Clearly specify the project's licensing terms (e.g., MIT License) in a dedicated section at the end of the README. 
Create a separate subsection under acknowledgments to highlight the contributions of individual contributors.

**Comment by apu52** [comment]
> > @Zoha-Waheed the licensee is already added in the repo ...so what do u want to add more in this?? Can u please explain??
> 
> Currently, the license and acknowledgments section in the README lacks clarity and detail. This hinders users' understanding of the project's licensing terms and fails to adequately recognize contributors.
> 
> Clearly specify the project's licensing terms (e.g., MIT License) in a dedicated section at the end of the README. Create a separate subsection under acknowledgments to highlight the contributions of individual contributors.

okk I understand .I am assigning u this issue . u can start working
