### ISSUE TITLE
[Feature Request]: change the UI of the about us page

### ISSUE THREAD

**Issue by heli0707** [apu52/Travel_Website#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Redesign the "About Us" page with a modern, clean layout featuring a hero section with a high-quality background image, bold typography, and streamlined content sections highlighting team members, company mission, and values. Add interactive elements like hover effects on team photos and a smooth scroll for better user engagement.

### Use Case

The new "About Us" page enhances user engagement by providing a visually appealing and interactive experience, which can increase user retention and trust in the company. This redesign also facilitates better storytelling, effectively communicating the company's mission and values to visitors.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/26c92f33-36e0-48e6-8a53-f5417cc15d33)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Nikhilkumar111** [comment]
Hello, Plz assigns to me this issue.
