### ISSUE TITLE
[Bug]: Footer of Trip Package page

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The components are not properly aligned and not even responsive .

### Expected behavior

It must be properly align , must have social media icons , google translator similar to other pages.
Also It should be responsive for all screens.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a1fbfb77-34d4-48e1-aef1-ff7056114cf1)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by TBorundia** [comment]
@apu52 @itsekta , Please assign this issue under GSSoC'24.

**Comment by KrishnenduDG** [comment]
@TBorundia you can go ahead with the issue.. Assigned it to you..
