### ISSUE TITLE
[Feature Request]: Adding Contributor's page

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.

### Use Case

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and 
                    support.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by TBorundia** [comment]
@apu52 @itsekta ,
Assign this issue to me under GSSoC'24.
Thank You!

**Comment by TBorundia** [comment]
@apu52 @itsekta @KrishnenduDG  ,
Assign this issue to me under GSSoC'24.
Thank You!

**Comment by apu52** [comment]
@TBorundia Contributors page is already added in this project sorry maybe mistakenly this issue is assigned . Sorry to close this issue .
