### ISSUE TITLE
[Feature Request]: add hover on social of login page 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/Travel_Website#1108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add hover on social of login sign up page 

### Use Case

good looking effect 

### Benefits

good looking effect 

### Add ScreenShots

before : 

https://github.com/user-attachments/assets/342fe723-e3d1-4242-b871-3cbecc70a6de

after : 

https://github.com/user-attachments/assets/05c66f44-19d2-4f0a-a6fb-d2512e11c262

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@apu52 please assign me this issue

**Comment by Programmer80101** [comment]
Hello there, it seems like you want to add a cool looking hover effect on those social media icons. I believe that I can work on this issue and make it as quickly as possible! 

Can you please assign me on this issue?

**Comment by ANKeshri** [comment]
@itsekta can you please let me know what is "1-POINT" label ?

**Comment by itsekta** [comment]
You will get 1 additional point for this issue

**Comment by ANKeshri** [comment]
> You will get 1 additional point for this issue
 @itsekta thank you
