### ISSUE TITLE
Feature_Request : Add quick booking chatbot

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#111]
**Is your feature request related to a problem? Please describe.**

add a quick booking chatbot on the bottom right corner.

**Describe the solution you'd like**

this chatbot would help to make quick registrations

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/110532770/529f01b7-4890-4564-a560-fe9dc0047c1f

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
@PranavBarthwal this is really a very good issue. But as per rule I can't assign u this issue right now. but after the complete submission of the previous PR I will surely assign u this

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal this is really a very good issue. But as per rule I can't assign u this issue right now. but after the complete submission of the previous PR I will surely assign u this

Can you assign it to me. I have done the work. Ill raise pr within 5 mins. Then I'll work on that previous issue

**Comment by apu52** [comment]
@PranavBarthwal You are assigned now
