### ISSUE TITLE
[Bug]: improving the  ui of hotel booking form 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/Travel_Website#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

improving ui of hotel booking form 

### Expected behavior

improving ui of hotel booking form 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/95e300e1-2361-4321-a57d-26568a2a1623)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@apu52 please assign me this issue

**Comment by KrishnenduDG** [comment]
@ANKeshri , can you please throw some light on how you are going to improve the UI. I mean, plz state any type of design changes or some style elements to be added for the purpose...

**Comment by ANKeshri** [comment]
> @ANKeshri , can you please throw some light on how you are going to improve the UI. I mean, plz state any type of design changes or some style elements to be added for the purpose...

I will add background image or colour to it , add box shadow give colour to text .
I will make and show you the page tomorrow .

**Comment by KrishnenduDG** [comment]
Okk coolzz.. Assigned this issue to you @ANKeshri. Go ahead and make a PR..
