### ISSUE TITLE
[Feature Request]: Improve Adventure Page

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- I wish to add filters
- I wish to add some icons that will show exactly what adventures are available in the place
- Improve the UI
- add search bar

### Use Case

UI/UX both will be improved this way

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2fc73c86-fdef-41ed-8376-f2842e11cad2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
@sau-mili Nice feature description. Just if you could clarify about how you are going to manage the filters, I mean the whole procedure of filtering, then I can assign you this issue..

**Comment by sau-mili** [comment]
I added some icons in the packages.html if you see one of my previous PRs. i want to do similar but this time with adventure sports icons for this page. Also, add a search bar for this

**Comment by KrishnenduDG** [comment]
Okk cool... Assigned this issue to you @sau-mili .. Go ahead and make a PR.

**Comment by sau-mili** [comment]
@KrishnenduDG can you please check my pull

**Comment by itsekta** [comment]
Hey @sau-mili, can you please add the screenshot by comparing to the current /package url. As i am unable to find any difference

**Comment by sau-mili** [comment]
sure, one sec.

**Comment by sau-mili** [comment]
## BEFORE

![image](https://github.com/user-attachments/assets/2fc73c86-fdef-41ed-8376-f2842e11cad2)

## AFTER
![Screenshot 2024-07-20 002321](https://github.com/user-attachments/assets/a9381787-3af4-4609-be48-46f78afeaf1c)
![Screenshot 2024-07-20 002334](https://github.com/user-attachments/assets/7a78e39d-43ed-45ea-940c-7c6dcb07c174)

**Comment by sau-mili** [comment]
Please check @itsekta

**Comment by itsekta** [comment]
Your deployed link
![image](https://github.com/user-attachments/assets/7064f096-401f-4b6c-9f1c-bc80952e661f)


Currently deployed 
![Arpan Codes _ Tourguide - Google Chrome 20-07-2024 12_22_59 PM](https://github.com/user-attachments/assets/03719bdb-c6f5-4a71-88f6-934da77b2ff3)

**Comment by sau-mili** [comment]
https://travel-website-git-patch2-sau-milis-projects.vercel.app?_vercel_share=aIAawH67NKoJXtzKnxvPhLKwhZqCG7tA

**Comment by sau-mili** [comment]
Currently delployed is
![image](https://github.com/user-attachments/assets/86a05d5b-abcb-4bfa-a4f3-aee0a6836511)

Both the screenshot you are showing are my deployment
