### ISSUE TITLE
Subscription section - Email in Dark mode

### ISSUE THREAD

**Issue by 21pa1a6149** [apu52/Travel_Website#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During Dark mode in subscription section the email part is not changing to dark mode fully leaving white space in it, which is looking odd
![Screenshot 2024-07-17 155634](https://github.com/user-attachments/assets/d9256645-de3c-4c83-b241-8b6efa30060c)

### Expected behavior

I will perform the CSS changes to the subscription email part to fully darken in dark mode

### Add ScreenShots

![Screenshot 2024-07-17 160036](https://github.com/user-attachments/assets/c0ed5a22-792a-4334-ac0a-097dc9054507)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
Assigned this to you @21pa1a6149 
Create a PR with the necessary changes and link that here for further considerations.
