### ISSUE TITLE
[Bug]: CSS mistake

### ISSUE THREAD

**Issue by VijaySamant4368** [apu52/Travel_Website#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The 'Book Now' button and the card below it are overlapping, in three places which is resulting in an ugly interface.

### Expected behavior

There should be enough vertical distance between them.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6ee78b75-baaf-438b-bad3-4cdc24752854)
![image](https://github.com/user-attachments/assets/ce5ddc77-9201-41e7-ba4c-7b6209dccbf8)
![image](https://github.com/user-attachments/assets/ea7607f2-6b7f-4ee5-b4ac-c748fc351647)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
@apu52 check this out plz..

**Comment by nihasinghania22** [comment]
@VijaySamant4368 Could you please assign me this issue

**Comment by VijaySamant4368** [comment]
@apu52 @itsekta can you please merge the pr for this issue?
