### ISSUE TITLE
[Bug]: Little Mistake in Contact Us section for mobile devices

### ISSUE THREAD

**Issue by VijaySamant4368** [apu52/Travel_Website#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When in mobile view (less than 920px wide), the Contact Us section has a little CSS error.

### Expected behavior

The E-mail logo should be in the similar place as the other two.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/dff2aec3-e6d9-4b6a-b122-d1a7c5968b63)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
@apu52 check this out
