### ISSUE TITLE
BUG:Dark theme not working for the whole page

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [apu52/Travel_Website#112]
**Expected behavior**
dark theme is very inconsistent for the whole website

ASSIGN ME UNDER JWOC

**Comment by apu52** [comment]
@NaveenChandraAdhikari thank you for raising this issue. Make the dark theme feature properly to the whole screen & make correct color gradients

**Comment by vishapraj** [comment]
pls assign me this issue under "JWOC"

**Comment by apu52** [comment]
> @NaveenChandraAdhikari thank you for raising this issue. Make the dark theme feature properly to the whole screen & make correct color gradients

Where is your PR.. As your issue has already crossed the deadline I am forced to unassign you

**Comment by apu52** [comment]
> pls assign me this issue under "JWOC"

@vishapraj You are assigned. You have 2-3 days to submit your PR

**Comment by NaveenChandraAdhikari** [comment]
@apu52 I'm going to merge today but before I do that  you have unassigned me

**Comment by apu52** [comment]
> @apu52 I'm going to merge today but before I do that you have unassigned me

ok. I am reassigning you . But if you are not able to submit your issue by tonight I can't do anything but unassign you.
& please follow the deadline rule of JWOC later on strictly

**Comment by NaveenChandraAdhikari** [comment]
@apu52 sure I'll merge by tonight

**Comment by NaveenChandraAdhikari** [comment]
[Screencast from 2024-01-26 01-44-50.webm](https://github.com/apu52/Travel_Website/assets/44281971/83f61ea9-fc90-46ab-92b2-b3b2a97041d7)
is this right or some changes

**Comment by NaveenChandraAdhikari** [comment]
> [Screencast from 2024-01-26 01-44-50.webm](https://github.com/apu52/Travel_Website/assets/44281971/83f61ea9-fc90-46ab-92b2-b3b2a97041d7) is this right or some changes

@apu52

**Comment by apu52** [comment]
> > [Screencast from 2024-01-26 01-44-50.webm](https://github.com/apu52/Travel_Website/assets/44281971/83f61ea9-fc90-46ab-92b2-b3b2a97041d7) is this right or some changes
> 
> @apu52

Cool That's really great
