### ISSUE TITLE
[Feature Request]:  Add Cookie Pop-up to the Website

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a cookie pop-up to the website. This pop-up will inform users about the use of cookies on the site, request their consent, and provide a link to the privacy policy. The pop-up should be designed to match the website's theme and aesthetics to ensure a consistent user experience.

### Use Case

Adding a cookie pop-up will enhance the website by ensuring compliance with data protection regulations. It will also increase transparency with users regarding data usage, which can build trust and improve user experience.

### Benefits

A user visits the website for the first time. The cookie pop-up informs them about the use of cookies and asks for their consent. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by anshulagr5** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by itsekta** [comment]
Hey @TBorundia, there are already many issues assigned to you please complete them first, then i will assign this one to you

**Comment by TBorundia** [comment]
> Hey @TBorundia, there are already many issues assigned to you please complete them first, then i will assign this one to you

@itsekta , I have completed my previous task.
Now please assign this issue to me.

**Comment by TBorundia** [comment]
> Hey @TBorundia, there are already many issues assigned to you please complete them first, then i will assign this one to you

@apu52 @itsekta ,
 I have completed my previous task.
Now please assign this issue to me.
