### ISSUE TITLE
Improve Navbar Visibility

### ISSUE THREAD

**Issue by lovelymahor** [apu52/Travel_Website#1129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current navigation bar (navbar) is not sufficiently visible, which impacts user experience and navigation ease. Enhancing the navbar's visibility will improve user interaction and ensure that essential links are easily accessible.

### Expected behavior

Ensure appropriate spacing between text elements in the navbar for clarity and ease of reading. The spacing should be sufficient to prevent text from appearing cramped and to enhance overall visual appeal.

### Add ScreenShots

![Screenshot (244)](https://github.com/user-attachments/assets/46cae9b7-9200-4d73-9851-fdc172e61535)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @lovelymahor, while improving the navbar can you also combine different section in a dropdown container like this
The image is just for reference.

![image](https://github.com/user-attachments/assets/f0f24382-de27-4a2b-bef7-b011518c7269)
