### ISSUE TITLE
[Bug]:  Stretched / Extra wide Google logo

### ISSUE THREAD

**Issue by DevanshPaliwal** [apu52/Travel_Website#1131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Stretched / Wide Logo
Google logo which is present at the end of the home page is stretched unintended.
Opening an issue to fix that.

### Expected behavior

Logo should be proper and not stretched.

### Add ScreenShots

![Screenshot 2024-07-19 215408](https://github.com/user-attachments/assets/b042fad7-6e4b-44e0-b91a-9d3ef9838519)
Please assign this issue to me.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hi @DevanshPaliwal, there is already a PR present for this #1114
