### ISSUE TITLE
[Bug]: Two Tourguide logos on the T&C page .

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Two Tourguide logos are present on the navbar of the T&C page .

### Expected behavior

Assign this task to me and I can remove the duplicate logo.

### Add ScreenShots

![Screenshot (778)](https://github.com/user-attachments/assets/8bc015c2-565f-4a27-8a62-02e37f2fb3cf)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ayushkamboj18** [comment]
I can do this, please assign to me

**Comment by meetarora10** [comment]
@itsekta please have a look .
