### ISSUE TITLE
[Bug]: Book Now button and image overlap in the Hotel & Resorts section . 

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Book Now button and image overlap in the Hotel & Resorts section . 

### Expected behavior

I can add required spacing between the button and the images .

### Add ScreenShots

![Screenshot (777)](https://github.com/user-attachments/assets/7fc817f1-418f-4b08-810a-2026c5c27f63)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 this issue is now solved in the project .Sorry to close this issue .
