### ISSUE TITLE
[Bug]: Login without entering any email or password

### ISSUE THREAD

**Issue by itsekta** [apu52/Travel_Website#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The user is logging in without any validation for the email and password fields. Both fields are left unchecked, allowing the user to proceed without entering any information.

### Expected behavior

Add validations for login so that the user can only log in when the email and password are verified. Show an error message if the fields are empty.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/801596b9-b0c9-4c2b-9eb9-2a4d7fcc4ff8)

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by anwesha2002** [comment]
@itsekta @apu52 I am a gssoc'24 contributor , I would like to solve this issue, please assign this to me

**Comment by itsekta** [comment]
Hey @anwesha2002, have you completed this issue

**Comment by anwesha2002** [comment]
> Hey @anwesha2002, have you completed this issue

@itsekta  please check the PR
