### ISSUE TITLE
[Bug]: Underline hover effect of navbar links

### ISSUE THREAD

**Issue by itsekta** [apu52/Travel_Website#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The underline hover effect of the navbar links should be below the text instead of above it.

### Expected behavior

The navbar links currently have an underline hover effect that appears above the text. This effect should be adjusted so that the underline appears below the text instead. This will ensure a more conventional and visually appealing navigation experience for users.

### Add ScreenShots

https://github.com/user-attachments/assets/2abece86-44fb-4bb0-b1de-b02dbed8d5b0

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sau-mili** [comment]
Please assign me this @itsekta
