### ISSUE TITLE
[Feature Request]: Improving the custom scrollbar

### ISSUE THREAD

**Issue by itsekta** [apu52/Travel_Website#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current scrollbar only works when scrolling down, which is not correct. Users should also be able to click and scroll through content using the scrollbar. This functionality needs to be fixed to allow proper scrolling. 

**Bonus for improving the UI of the scrollbar to match with the website UI** 

### Use Case

A user is browsing a travel website to plan their vacation. They scroll down through a long list of destinations and travel packages. Later, they decide to go back and review some earlier options. However, the current scrollbar only allows them to scroll down, making it difficult to navigate back up. By fixing the scrollbar to enable both upward and downward scrolling, the user can easily explore all travel options, compare packages, and make better-informed decisions about their trip.

### Benefits

1. **Improved Navigation**: Users can easily scroll both up and down, allowing for more intuitive exploration of travel options and details.
2. **Enhanced User Experience**: Smooth scrolling in both directions helps users review and compare different destinations and packages without frustration.
3. **Increased Engagement**: Users are more likely to spend time exploring the site and finding the best options for their trip, leading to higher satisfaction and potential bookings.
4. **Efficient Information Access**: Users can quickly navigate back to previously viewed sections, making it easier to make informed decisions about their travel plans.

### Add ScreenShots

https://github.com/user-attachments/assets/5b08eb2b-0a60-432f-a59b-ff25f7a8b599

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@itsekta assign me this issue .
