### ISSUE TITLE
[Feature Request]:  Optimising the navbar styling

### ISSUE THREAD

**Issue by Dilpreet0501** [apu52/Travel_Website#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @apu52 , I would like to optimise the navbar , change the styling and icons to it .

Kindly assign me this issue under GSSoC'24. I''ll do my best.

### Use Case

This feature would increase the engagement of website and enhance the look of website.

### Add ScreenShots

I would style navbar by adding icons similar to below screenshot but on hover they will display contents name such as home, about so that navbar can be made more spacious.

![Screenshot 2024-07-20 110846](https://github.com/user-attachments/assets/0695969e-9aa0-4680-987d-ce635b51c282)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @Dilpreet0501, there is already an issues present related to this issues check #1129

**Comment by apu52** [comment]
@Dilpreet0501 there is some new changes in the navbar , after that changes can u implement the features u are asking in this issue , so that I will reopen this issue

**Comment by Dilpreet0501** [comment]
Sure Sir @apu52 , I will do it.

**Comment by Dilpreet0501** [comment]
Hello @apu52 , Kindly assign me this issue so I can update the navbar styling
