### ISSUE TITLE
[Bug]: Images are not loading

### ISSUE THREAD

**Issue by mehrun171** [apu52/Travel_Website#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the sections like Connect with guide , Best place for beautiful trip , Trip gallery , Tourist Guide...i would like to resolve all those src link problems

### Expected behavior

We need to give crct img source, i would like to do it

### Add ScreenShots

![Screenshot 2024-07-21 111822](https://github.com/user-attachments/assets/21babab3-e447-48d1-9718-c66228e919e9)
![Screenshot 2024-07-21 111829](https://github.com/user-attachments/assets/ec572b50-0764-47bf-b763-e2b3aeb71cc1)
![Screenshot 2024-07-21 112834](https://github.com/user-attachments/assets/6ec9d013-3ba4-40c3-9b4c-299e4aef2682)
![Screenshot 2024-07-21 112840](https://github.com/user-attachments/assets/793e2590-6f33-4279-b991-f8c8a2319f2d)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by mehrun171** [comment]
Please assign me this @apu52

**Comment by apu52** [comment]
@mehrun171 I have checked the website ,the images are now loading properly , so I think there is no need of this issue now . Closing this issue.
