### ISSUE TITLE
[Bug]: View option is not showing anything

### ISSUE THREAD

**Issue by mehrun171** [apu52/Travel_Website#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The View option in the navbar is not opening up the maps

### Expected behavior

I would like to resolve the issue by linking the appropriate maps to it and fix the bug

### Add ScreenShots

![Screenshot 2024-07-21 112204](https://github.com/user-attachments/assets/b048156d-f2d2-460a-b90d-b390cc82b9b6)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
Please assign this issue to me

**Comment by Mayanksaininh** [comment]
Please assign this issue to me

**Comment by apu52** [comment]
@mehrun171 It's because I haven't boy the credits to activate it .later on i will add that . So don't worry , I will fix it . Closing this issue.
