### ISSUE TITLE
➕Enhancement: Improving the Current "About Us" Section in TourGuide!

### ISSUE THREAD

**Issue by aslams2020** [apu52/Travel_Website#1159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 and @itsekta 

Here is the feature i want to request -
Currently the About Us Section is a little bit Unreadable and is not following the website's theme.
Also, It is divided into subsections which is not readable.

**Here -** 
![image](https://github.com/user-attachments/assets/79e33819-acd8-418c-b409-6fe5b9f68062)

### Here's What Will I Do - 
- I Want to make it Readable with Brief and Clear Information regarding the "TourGuide" Website .
- I Also Like to change the Alignment/UI of the Section, As a Introductory page should be readable and understandable for the Visitors to know more about the Website.
- I would also like to Style the Section to follow the website's Color theme.
- Adding Animations, hovering effects wherever necessary 
- And also, changing the background of the page with an image related to Travelling website 

Please assign me this under GSSoC'24 .

Thankyou!

### Use Case

The About us section is the main highlight of any page, especially the Travel website and the visitors will get to know more about the services provided by this organization.
So, It should be well aligned, better styled and readable to any kind of visitors.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aslams2020** [comment]
@apu52 @itsekta

**Comment by itsekta** [comment]
hey @aslams2020, There is already a PR for this #1138
