### ISSUE TITLE
[Feature Request]: footer ui change

### ISSUE THREAD

**Issue by dhairyagothi** [apu52/Travel_Website#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

footer enhancement

### Use Case

footer responsiveness

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1918b8fb-0712-4cf0-a3f6-a96fca834860)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
Please assign this issue to me

**Comment by gollaanusha249** [comment]
please assign me this issue

**Comment by apu52** [comment]
@dhairyagothi which features do u want to add in the footer section???
Can u please explain properly.....

**Comment by dhairyagothi** [comment]
I want to fix css of footer in mobile view it not looks so good.,.

**Comment by apu52** [comment]
@dhairyagothi u are assigned
