### ISSUE TITLE
[Feature Request]: Add dark mode for Rate us page

### ISSUE THREAD

**Issue by Asymtode712** [apu52/Travel_Website#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The website's Rate us page doesn't support the dark mode.

I would like to add the dark mode toggle button and add the dark theme for the Rate us page

### Use Case

It would provide good visibility and the users can switch between different themes according to their convenience

### Add ScreenShots

![Screenshot (104)](https://github.com/user-attachments/assets/8e73e237-4164-4d9f-aed7-ceb323104685)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Asymtode712** [comment]
@itsekta @apu52 please assign me this issue

**Comment by Vaibhav-kesarwani** [comment]
@itsekta @apu52 please assign this issue to me

**Comment by Asymtode712** [comment]
@Vaibhav-kesarwani I have authored this issue, please search for some other issues
