### ISSUE TITLE
[Feature Request]: Make the website Home page responsive for all the screen

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [apu52/Travel_Website#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The navbar on the website is not very attractive when viewed on a mobile device, and the website is not responsive on many screen sizes.

![Screenshot from 2024-07-21 17-18-16](https://github.com/user-attachments/assets/9f787795-b85c-448b-a2a8-e805c9b0f6f7)

### Use Case

This makes it easier for users to navigate the website, which is beneficial for user experience and retention.

### Add ScreenShots

![Screenshot from 2024-07-21 17-18-16](https://github.com/user-attachments/assets/faea355c-a5f7-4310-9ddb-ee003badd14f)
![Screenshot from 2024-07-21 17-25-05](https://github.com/user-attachments/assets/01957565-dd84-49b4-93ca-d0fe418f47ae)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
Please assign this issue to me

**Comment by Mayanksaininh** [comment]
Please assign this issue to me.
website is not responding for all screen. I will solve this issue.

**Comment by Mayanksaininh** [comment]
Please assign this issue to me.
![eg of ios](https://github.com/user-attachments/assets/47fc8d82-c952-4559-9c34-56e7ea83f73f)

**Comment by Nikhilkumar111** [comment]
please assign to me this issue.

**Comment by dushyantkanav** [comment]
i can resolve this issue. you can assign me
