### ISSUE TITLE
[Bug]: No view page showing

### ISSUE THREAD

**Issue by anwesha2002** [apu52/Travel_Website#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no page while clicking upon view button

### Expected behavior

There should be a page for view button in the navbar

### Add ScreenShots

https://github.com/user-attachments/assets/4beff302-c068-4e95-9542-e55f8d3de7ee

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by anwesha2002** [comment]
@apu52 please assign this to me

**Comment by apu52** [comment]
@anwesha2002 It's because I haven't bought the credits to activate it .later on I will add that . So don't worry , I will fix it . Closing this issue.
