### ISSUE TITLE
BUG : Alignment 

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#118]
**Describe the bug**

Hello all,
there is a problem in the alignment problem in the home & review portion without making any further changes

**Expected behavior**

I want it to be in the full screen version of the review & as well as the review portion
**Screenshots (Mandatory)**

**HOME**
![image](https://github.com/apu52/Travel_Website/assets/114172928/d4f49b71-e0fa-4189-9553-6546ae35ebf7)
**REVIEW**
![image](https://github.com/apu52/Travel_Website/assets/114172928/8a27a452-dbfd-4157-aeb1-94293e97a219)

**Additional Context (Mandatory )**

Those whoever wants to work on this issue comment first with JWOC mentioned in it 

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
### Those whoever wants to work on this issue comment first with JWOC mentioned in it

**Comment by AryanPahuja21** [comment]
@apu52 please assign this issue to me under JWOC'24

**Comment by Prithwi32** [comment]
@apu52 I would like to work on this issue under JWOC

**Comment by SharmaDhruv2511** [comment]
@apu52 I would like to fix this issue if you can assign me it would be great

**Comment by Divyanshgarg-04** [comment]
@apu52 I would love to work on this issue under JWOC. Please assign this issue to me

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?

**Comment by apu52** [comment]
@AryanPahuja21 You are assigned on this issue. I want to suggest you to make only the alignment changes not other changes.
