### ISSUE TITLE
[Feature Request]: Automatic redirection to home page on login

### ISSUE THREAD

**Issue by DevNandini02** [apu52/Travel_Website#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a feature such that when the user is successfully logged in then it should automatically redirect to the home page.

### Use Case

Right now the user has to use the back arrow for going back. My feature will make it easier for user to automatically return to home page after login.

### Benefits

Make the website more dynamic and increase user experience.

### Add ScreenShots

https://github.com/user-attachments/assets/b16d2ead-6c19-4c24-9315-05f71e9dff06

As you can see right now nothing is happening after successfully logging in. Whereas it should redirect to the homepage.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@DevNandini02 u are assigned 3 issues . But please try to complete all the issues in separate PR's one by one
