### ISSUE TITLE
[Feature Request]:  Add a Slide show feature in view trending tab 

### ISSUE THREAD

**Issue by DevNandini02** [apu52/Travel_Website#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The trending tours images are very thin due to which the UI is not looking good. I want to make a slide show of these trending places and when hovered on these images it will show the blog page button where people could could know more about these places.

### Use Case

Better visibility 
Improve UI

### Benefits

We can add more trending places later in this slide show.
It will enhance user experience.

### Add ScreenShots

Now
![travelbug6](https://github.com/user-attachments/assets/e54bb865-3a8a-4a03-aa7e-f228013dba80)

Feature to be added

https://github.com/user-attachments/assets/fbb7fb89-186f-44b0-8b17-ed49b08aabd1

I want to add this kind of slide show and when user will hover on them the blog page button will appear.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @DevNandini02, Please complete the other assigned issues first

**Comment by DevNandini02** [comment]
@itsekta please assign me this issue. I will also complete the rest tasks soon.

**Comment by itsekta** [comment]
Hey @AsmitaMishra24, you can create a new issues if you want to work on one
