### ISSUE TITLE
[Bug]: Map in the View tab not working

### ISSUE THREAD

**Issue by DevNandini02** [apu52/Travel_Website#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The map in the view tab is showing error. 

### Expected behavior

On clicking the view tab the map should be visible which will enable users to navigate to places in the map and plan their trip accordingly.

### Add ScreenShots

![travelbug8](https://github.com/user-attachments/assets/da93a058-6523-4666-8560-43eb5bbb752a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @DevNandini02, Please complete the other assigned issues first

**Comment by apu52** [comment]
@DevNandini02 please don't raise more than 2 issues at a time . it's simply violating the rules of GSSOC'24 & also the rules of the repo . please try to follow the rules mentioned in CONTRIBUTING.md file from next time please.

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me

**Comment by abishek1740P** [comment]
@apu52 assign me this issue.

**Comment by Atharvverma1234** [comment]
Hello, I would like to work upon this issue. Please assign it to me. Thank You

**Comment by apu52** [comment]
@Atharvverma1234 this issue has already been solved , don't worry , u can still make new issues on which u want to work on
