### ISSUE TITLE
[Bug]: Adventure travel footer

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#1203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Footer is not similar to other pages, some points are missing.
It is not responsive

### Expected behavior

no

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3c134a52-879d-4d10-904d-8f349df7c2fb)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @TBorundia, please complete the assigned issues first.

**Comment by apu52** [comment]
@TBorundia please don't raise more than 2 issues at a time . it's simply violating the rules of GSSOC'24 & also the rules of the repo . please try to follow the rules mentioned in CONTRIBUTING.md file from next time please.

**Comment by ASP124** [comment]
@apu52 I'd Like to work on this issue.

**Comment by apu52** [comment]
@ASP124 this issue is already assigned . U can make other new issues
