### ISSUE TITLE
[Bug]: Text not visible on landing page

### ISSUE THREAD

**Issue by Rajul-29** [apu52/Travel_Website#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text is covered by photos

### Expected behavior

The text should be clearly visible

### Add ScreenShots

![Screenshot 2024-07-24 230203](https://github.com/user-attachments/assets/36a340f4-96c8-434e-a353-8179d399b112)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Rajul-29** [comment]
Hey @apu52 @itsekta 
Can you please assign me this issue
Thank you

**Comment by itsekta** [comment]
Hey @Rajul-29, Could you please tell on which device you are facing this issue?

**Comment by Rajul-29** [comment]
@itsekta Chrome

**Comment by Rajul-29** [comment]
Should i work on this? @apu52 @itsekta

**Comment by ASP124** [comment]
The styling is not good here i.e the shadow with red color. I'd like to work on this

**Comment by itsekta** [comment]
Hey @Rajul-29, the issues that you have mentioned I am unable to see it on any screen, Can you please add a video of the screen.

Here is a screenshot of my screen
![image](https://github.com/user-attachments/assets/51145bbf-3a3d-4eb1-a235-d2a7634ff783)

**Comment by Rajul-29** [comment]
Hey @itsekta 
I am adding a full screenshot of my chrome
![Screenshot 2024-07-27 182621](https://github.com/user-attachments/assets/65c825d1-169e-4fd2-bef3-9f8065c9df9f)

**Comment by Rajul-29** [comment]
Hey @itsekta 
I just noticed that this issue can be seen only on bigger screens
![Screenshot 2024-07-27 213245](https://github.com/user-attachments/assets/cb3ac784-864c-4f57-a4c0-b2ddf61cc6f7)
![Screenshot 2024-07-27 213300](https://github.com/user-attachments/assets/28da4472-c119-49f5-89f2-42c2287ec56e)

**Comment by Rajul-29** [comment]
@itsekta Should i work on this issue?

**Comment by itsekta** [comment]
Sure you can start working on it
