### ISSUE TITLE
[Bug]: Registration Page Unorganized

### ISSUE THREAD

**Issue by Rajul-29** [apu52/Travel_Website#1209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The registration page looks very unorganized

### Expected behavior

A more organized registration page will look much more professional

### Add ScreenShots

![Screenshot 2024-07-24 230726](https://github.com/user-attachments/assets/a82a5dc0-43b3-4b1e-aed7-069ff7238b58)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Rajul-29** [comment]
Hey @apu52 @itsekta 
Can you please assign me this issue
Thank you

**Comment by itsekta** [comment]
Hey @Rajul-29, this is the old login page we aren't using this. Please check the current login page (https://apu52.github.io/Travel_Website/newLogin.html)
