### ISSUE TITLE
[Feature Request]: Dark mode for contributors page

### ISSUE THREAD

**Issue by ANKeshri** [apu52/Travel_Website#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Dark mode for contributors page

### Use Case

Dark mode for contributors page

### Benefits

Dark mode for contributors page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/dfb16167-1983-46be-94eb-a4528c61555b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@apu52 @itsekta please assign me this issue

**Comment by itsekta** [comment]
Hey @27-Atul, you can raise a separate issues if you want to add new functionality

**Comment by ANKeshri** [comment]
@27-Atul i have already raise pr for this
