### ISSUE TITLE
[Feature Request]: dark mode for membership page 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/Travel_Website#1214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

dark mode for membership page 

### Use Case

good visibility 

### Benefits

new feature to the page 

### Add ScreenShots

https://github.com/user-attachments/assets/9881c98f-9684-45eb-be1e-aab0014c8602

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@itsekta please assiugn me this issue

**Comment by TBorundia** [comment]
Hey @ANKeshri ,
How do you open multiple PR at the same time in the same repo ? Can you help me with that?

**Comment by apu52** [comment]
> Hey @ANKeshri , How do you open multiple PR at the same time in the same repo ? Can you help me with that?

maybe by making different branches for different issues in the forked repo & then push the commits as PR
