### ISSUE TITLE
[Feature Request]: Add a scroll to top button on the contributor page.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to add a scroll to top button on the contributor page similar to other pages .

### Use Case

This will help to automatically scroll to top just on click of a button .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@itsekta  please have a look .

**Comment by apu52** [comment]
@meetarora10 please complete the issues one by one

**Comment by meetarora10** [comment]
Okay @apu52
