### ISSUE TITLE
[Bug]: No link to the contributor page in whole website .

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no link to the contributor page in whole website .

### Expected behavior

I want to add a contributor link in the footer of every page that will open the contributor page .

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by raju2109** [comment]
@apu52 assign this issue to me

**Comment by apu52** [comment]
@raju2109 this issue is PENDING section , so I can't assign u this issue.
