### ISSUE TITLE
[Bug]: Improvement of footer in home page

### ISSUE THREAD

**Issue by Vaishnavigunti2801** [apu52/Travel_Website#1224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello PA,
Google icon in the footer got compressed and Select language list is not styled properly.

### Expected behavior

Increased height of Google icon and increased height of Select Language bar for better visibility.

### Add ScreenShots

Before:
![image](https://github.com/user-attachments/assets/4ab73aa5-6feb-47bd-8ad2-6943a5cecff1)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaishnavigunti2801** [comment]
@apu52 @KrishnenduDG @itsekta @Ghanshyam89 
Kindly assign this issue to me, also assign the labels.
Thank you.

**Comment by apu52** [comment]
@Vaishnavigunti2801 which changes u want to improve in the footer section??

**Comment by Vaishnavigunti2801** [comment]
@apu52 
In footer Google Icon got compressed and also the styling of "Select Language" List is not proper. 
I will Increase height of Google icon and also increase height of Select Language bar for better visibility. 
Kindly assign this issue to me, also assign the labels.
Thank you.

**Comment by apu52** [comment]
@Vaishnavigunti2801 there is a change in the google translate section in the footer . I am assigning u this issue .Start working on this issue .
