### ISSUE TITLE
[Feature Request]: Improvement of Navbar

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#1231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Misaligned , bad UI. I wish to improve it a lot

### Use Case

UI UX improvement

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sau-mili** [comment]
@apu52  is it okay if I reduce the number of options in navbar? 10 options in navbar looks very cluttered

**Comment by apu52** [comment]
> @apu52 is it okay if I reduce the number of options in navbar? 10 options in navbar looks very cluttered

its already reduced .u can make other changes of the navbar

**Comment by sau-mili** [comment]
I mean not just reducing. I will do other changes as well. But, it is one of the changes that I wish to make.

**Comment by apu52** [comment]
> I mean not just reducing. I will do other changes as well. But, it is one of the changes that I wish to make. for example: i wish to remove the extra options like tour guide, pricing, and keep the important ones that link to other pages or important parts of the pages. Then I will be adding on scroll sticky animation using vanilla JS, some UI changes etc

go ahead. u are already assigned.
