### ISSUE TITLE
[Feature Request]: Addition of visitors count

### ISSUE THREAD

**Issue by Anjaliavv51** [apu52/Travel_Website#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of visitors count

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f3e3c911-e657-45dd-9446-ad69f9ff4063)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjaliavv51** [comment]
@apu52 please assign me the issue.

**Comment by apu52** [comment]
@Anjaliavv51 we already have visitors count section in the footer of our website . Sorry to close this issue .But u can still make other new issues .
HAPPY CODING!!!!!!!!
