### ISSUE TITLE
[Feature Request]:  Floating Animation to the Rate us Image

### ISSUE THREAD

**Issue by Damini2004** [apu52/Travel_Website#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Floating Animation to the Rate us Image

### Use Case

Floating Animation to the Rate us Image

### Benefits

Floating Animation to the Rate us Image

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7e3519ba-7012-42d3-849e-f0424d681290)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
@Damini2004 Plz elaborate on the feature..

**Comment by Damini2004** [comment]
> @Damini2004 Plz elaborate on the feature..

Here the image will levitate in upward and downward manner continuously.

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
