### ISSUE TITLE
NOT GOOD About us section for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [apu52/Travel_Website#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It should have proper padding and margin according to the screen size to have a better readability on all devices

### Use Case

It should be fixed to have a better user experience

![image](https://github.com/user-attachments/assets/731a929a-3daa-4df2-ba67-0fe3ce6b9347)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Utsavladia please don't raise more than 2 issues at a time . We already have assigned u 2 issues .try to Complete them first & then ping me or mentors here to get assigned on this issue.

**Comment by apu52** [comment]
@Utsavladia please don't raise more than 2 issues at a time . We already have assigned u 2 issues .try to Complete them first & then ping me or mentors here to get assigned on this issue.

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
