### ISSUE TITLE
DropDown should close automatically on choosing any option on it 

### ISSUE THREAD

**Issue by Utsavladia** [apu52/Travel_Website#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It should be closed automatically to have a better user experience

### Use Case

![image](https://github.com/user-attachments/assets/ac4e5aae-e66d-4a66-9212-46b9860c9ede)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
@Utsavladia Good one. Assigned this to you. Make a relevant PR and link it here.
