### ISSUE TITLE
Tourist Guide section is not responsive at all

### ISSUE THREAD

**Issue by Utsavladia** [apu52/Travel_Website#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It should be responsive to have a better user experience on all devices

### Use Case

It should be loaded properly on all devices

### Add ScreenShots

![image](https://github.com/user-attachments/assets/14d4c7d5-cb54-471d-a35b-0cc549562e48)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by raju2109** [comment]
Hii please assign me this issue under GSSoC '24 i will make it responsive.

**Comment by Utsavladia** [comment]
@raju2109 hey I already wanna work on this issue which i created..
kindly find aother or create you own if you find any

**Comment by apu52** [comment]
@Utsavladia please don't raise more than 2 issues at a time . We already have assigned u 2 issues .try to Complete them first & then ping me or mentors here to get assigned on this issue.

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
