### ISSUE TITLE
Change Footer Alignment

### ISSUE THREAD

**Issue by lovelymahor** [apu52/Travel_Website#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current alignment of the footer does not meet the desired design specifications and affects the overall aesthetic and usability of the website. We need to adjust the alignment to improve visual appeal and consistency.

### Use Case

This feature will enhance the website's visual appeal and usability by ensuring the footer is properly aligned and responsive. A well-aligned footer contributes to a professional look, improving user experience and engagement.

### Benefits

Enhances visual appeal and professional look of the website.
Improves user experience and engagement.
Ensures consistency and responsiveness across different screen sizes.
Contributes to a more polished and cohesive design.

### Add ScreenShots

![Screenshot (287)](https://github.com/user-attachments/assets/65e581f1-5261-4b63-83d7-04eb658a9209)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by lovelymahor** [comment]
hii @apu52,
I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by KrishnenduDG** [comment]
@lovelymahor Assigned to you. Make a relevant PR and link here.

**Comment by Innocentcoder01** [comment]
Hi,  @lovelymahor  
I want to work on this issue. I also worked on many projects of frontend development. Waiting for you response. Thank you!

**Comment by amanver45** [comment]
hi @apu52 @lovelymahor . I'd like to contribute in this issue.can you assigned me
