### ISSUE TITLE
Adding Emojis in Rate Us Page to understand User Experience .

### ISSUE THREAD

**Issue by Vaishnavigunti2801** [apu52/Travel_Website#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello PA,
By adding happy , sad , moderate ,satisfied  emojis , there will be better understanding of user Experience  in Rate US page.

### Use Case

for better understanding of user Experience in Rate US page we include emojis.

### Benefits

By adding happy , sad , moderate ,satisfied  emojis in Rate Us page , there will be better understanding of user Experience .

### Add ScreenShots

![image](https://github.com/user-attachments/assets/37328ac5-1547-4837-8c26-6f406f260151)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by KrishnenduDG** [comment]
@Vaishnavigunti2801 Assigned to you. Make a relevant PR and link here.
