### ISSUE TITLE
BUG : book now in hero section

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#125]
**Describe the bug**

I dont think so this little "book now" should be there in the Hero section

**Expected behavior**

i guess there's no need of this book now in the hero section, if still needed it needs a better placement

**Screenshots (Mandatory)**

![book](https://github.com/apu52/Travel_Website/assets/110532770/4d018b19-f98a-47a3-befb-7a4f76d7f6c9)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

JWoC'24

**Comment by apu52** [comment]
@PranavBarthwal I have assigned you. I just want o suggest you not to remove the button instead place the button properly in a appropriate place
