### ISSUE TITLE
[Bug]: Fix hover animation on butttons

### ISSUE THREAD

**Issue by Rajul-29** [apu52/Travel_Website#1269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The buttons show 2 hover effects at once which don't look good

### Expected behavior

The buttons should show a better and organized hover animation

### Add ScreenShots

![Screenshot 2024-07-30 011315](https://github.com/user-attachments/assets/a7d8dc60-bf86-4ee4-b0e4-0e451200f39f)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Rajul-29** [comment]
Hey @apu52  @itsekta 
Can you please assign me this issue
Thank you

**Comment by ayush786hack** [comment]
Hey @apu52 @itsekta
Can you please assign me this issue
Thank you
