### ISSUE TITLE
[Feature Request]: Adding footer to trending page

### ISSUE THREAD

**Issue by Rajul-29** [apu52/Travel_Website#1270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a footer with links for better navigation

### Use Case

The footer links will provide convenient navigation for other webpages in the website

### Add ScreenShots
![Screenshot 2024-07-30 152101](https://github.com/user-attachments/assets/1108b868-e4de-4c7e-8822-e2f1c1d05258)

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Rajul-29** [comment]
Hey @apu52  @itsekta 
Can you please assign me this issue
Thank you

**Comment by itsekta** [comment]
The current footer have the link to other pages. Can you explain the issue

**Comment by Rajul-29** [comment]
This webpage doesn't have a footer

**Comment by itsekta** [comment]
Can you share the url for this

**Comment by Janhavi078** [comment]
i want to work for this uncder gssoc ext'24 assign me this @apu52
