### ISSUE TITLE
[Feature Request]: Add light / dark mode effect in Privacy and T&C Pages.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add light/dark mode toggle effect on Privacy as well as T&C page.

### Use Case

This will make the website look more attractive .

### Add ScreenShots

![Screenshot (887)](https://github.com/user-attachments/assets/52bcccad-2f95-4003-ab44-369036f524fa)
![Screenshot (888)](https://github.com/user-attachments/assets/874287a9-5306-45eb-bc8e-bd2f671864bb)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sachan13harshit** [comment]
@apu52 @itsekta please assign this issue to me.
