### ISSUE TITLE
[Feature Request]: Bad background of Login/SignUp Page

### ISSUE THREAD

**Issue by iarmaanx** [apu52/Travel_Website#1282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Background should be changed to a better one.

### Use Case

It will improve the UI of the project.

### Add ScreenShots

![Uploading Screenshot 2024-07-31 155953.png…]()

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @iarmaansingh, can you please add the screenshot again

**Comment by Jay-ARORA-5572** [comment]
Please assign the difficulty of level according to GSSoC24.

**Comment by sachan13harshit** [comment]
@apu52  please assign this issue to me

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me

**Comment by sambedan1** [comment]
please assign this to me
