### ISSUE TITLE
[Feature Request]: Add scroll to top button on Privacy Policy , T&C , Licensing pages . 

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Scroll to top button is not present on Privacy Policy , T&C , Licensing pages . 

### Use Case

This will make the website look more attractive .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sachan13harshit** [comment]
@apu52 @itsekta please assign this issue to me.
