### ISSUE TITLE
[Feature Request]: Add a progress bar on the top of the navbar . 

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to add a progress bar on the top of the navbar which progresses as the page scrolls up and down . and also the UI of the progress bar matches with the UI of the website .

### Use Case

This will make the website look more attractive .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 this issue already exists in this repo & even this PR has already been merged . So sorry to close this issue
