### ISSUE TITLE
[Feature Request]: add  smooth scrolling 

### ISSUE THREAD

**Issue by Subhams-GIT** [apu52/Travel_Website#1308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The ui is very laggy .Adding a smooth scroll effect can make it slight better.

### Use Case

Enhancing User Experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Ranj8521Kumar** [comment]
Hii, I want to tackle this issue, So please assign to me.

**Comment by apu52** [comment]
> Hii, I want to tackle this issue, So please assign to me.

u are assigned
