### ISSUE TITLE
[Feature Request]: Want to Make Searchbar of Packages Work

### ISSUE THREAD

**Issue by nishant0708** [apu52/Travel_Website#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/e2f15e85-6c00-44d8-bac0-96c83145e77c)

### Use Case

It will be easy for user to search for where they want to go

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Jay-ARORA-5572** [comment]
@apu52 
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.

**Comment by nishant0708** [comment]
Hey @Jay-ARORA-5572 I am currently working on it
