### ISSUE TITLE
[Bug]: One of the image is not visible in the testimonials section .

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#1316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

One of the image is not visible in the testimonials section .

### Expected behavior

Assign this task to me and I can add proper image .

### Add ScreenShots

![Screenshot (971)](https://github.com/user-attachments/assets/c2089349-6682-4a51-8abd-127de6b63e58)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 this issue has already been solved . Sorry to close this issue for now .
