### ISSUE TITLE
make dark theme button responsive

### ISSUE THREAD

**Issue by GhoshAditi** [apu52/Travel_Website#132]
**Describe the bug**
the dark theme button is not responsive

**Expected behavior**
on clicking the button the whole website will be on dark theme mode

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/144611267/05d36745-7186-4f84-9ba2-de94a8c7ec4e)
even on clicking dark theme button the website is on light theme mode

**Additional Context (Mandatory )**
i am contributing this under jwoc'24.
plz assign this issue to me under jwoc'24.

**Comment by GhoshAditi** [comment]
@apu52 i would like to work on it. plz assign this issue to me under jwoc'24.

**Comment by apu52** [comment]
@GhoshAditi Where is your PR??

**Comment by apu52** [comment]
you have already crossed the deadline of the issue. sorry to close this issue
