### ISSUE TITLE
[Feature Request]:  Want to add dark mode to the signin page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [apu52/Travel_Website#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the dark mode to the login and signup page 

### Use Case

This will looks cool 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f7667481-9051-497f-a5ba-9efd238a065e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aryansoni13** [comment]
i will like to work on this, kindly assign me the task
