### ISSUE TITLE
Scroll to testimonials is not working 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [apu52/Travel_Website#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When i am clicking on testimonials in the navbar then it is not scrolling to the testimonials sections 

### Use Case

This is a bug 

### Add ScreenShots

https://github.com/user-attachments/assets/ebe0d216-9b71-40d8-8022-85fc8ff883c6

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
