### ISSUE TITLE
[Feature Request]: Improve the Checkout page

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#1338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish to make it look more modern and professional, fix the other components as well

### Use Case

UI/UX

### Add ScreenShots

![image](https://github.com/user-attachments/assets/084dd378-c493-4cf6-b6a5-dc8c337229ad)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Jay-ARORA-5572** [comment]
@apu52 
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.
