### ISSUE TITLE
Create a page for planning a trip on clicking Plan a trip button.

### ISSUE THREAD

**Issue by pranjal12-web** [apu52/Travel_Website#134]
**Is your feature request related to a problem? Please describe.**
 On clicking plan a trip button website is not directed to any page.

**Describe the solution you'd like**
Create a page for planning a trip on clicking Plan a trip button

***Are you contributing under any open-source program ?***
JWoC 24

**Comment by apu52** [comment]
@pranjal12-web You are assigned. you can start working on this issue
