### ISSUE TITLE
[Feature Request]: Improve Package.html

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#1341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improve the card designs, make sections separate, fix navbar

### Use Case

For choosing packages on the page, this will improve the experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Jay-ARORA-5572** [comment]
@apu52
hey, I'd like to contribute in this issue.
I have read the Contributing Guidelines.
I'm a GSSOC'24 contributor.
I have starred the repository.
