### ISSUE TITLE
Fix Image Not Displaying in Component

### ISSUE THREAD

**Issue by soura07** [apu52/Travel_Website#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Images are not showing up in the components, as seen in the attached screenshot. The issue seems to be related to the incorrect path or missing image files.

### Expected behavior

Images should be displayed correctly in the UI, with the appropriate images appearing in each designated area.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7d546f7d-37b8-4cb8-a569-3705e1d66724)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by soura07** [comment]
@apu52 allow me to change it : )

**Comment by soura07** [comment]
![image](https://github.com/user-attachments/assets/be5a4abf-649c-4716-a80b-0fec21a5a6bb)

<h2> Fixed Bugs</h2>
<h3> Give me approval to Push the Code : ) </h3>

**Comment by apu52** [comment]
@soura07 this issue has already been assigned to another contributor , sorry I can't assign u this issue. But u still make new issue on which u want to work on.
