### ISSUE TITLE
[Feature Request]: To create an about page

### ISSUE THREAD

**Issue by ayush-848** [apu52/Travel_Website#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/3f6f73eb-4829-42bd-bfa0-57cfb2e9127d)

I will remove the about us section section from here and I will make a separate about us page

### Use Case

I will remove the about us section section from here and I will make a separate about us page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ayush-848 I would like to suggest you don't delete this complete this , make this about us section in the home page minimal & make all the other changes in a separate page what u have mentioned in this issue.

**Comment by ayush-848** [comment]
@apu52 sure

**Comment by ayush-848** [comment]
@apu52 since tomorrow 7:00 pm is last
Will make this page before noon.
