### ISSUE TITLE
[Feature Request]: Main logo and title logo are different

### ISSUE THREAD

**Issue by Mayanksaininh** [apu52/Travel_Website#1356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

main logo and title bar logo should be same.

### Use Case

It become professional.

### Add ScreenShots

![Screenshot (5)](https://github.com/user-attachments/assets/9f703ba8-110a-440b-a819-0e9dc02d8adb)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Mayanksaininh** [comment]
Please assign this issue to me

**Comment by Ananya-vastare** [comment]
Please assign this issue to me
