### ISSUE TITLE
➕Enhancement: Improve the AboutUs Section

### ISSUE THREAD

**Issue by aslams2020** [apu52/Travel_Website#1357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 

i want to enhance the current about us section.

Currently the about us section is not well aligned and structured.
it is divided into different segments, which make it unable to recognize as a about us section.

The about section should be in brief to tell the customers about the website in a nutshell and visually appealing way

![image](https://github.com/user-attachments/assets/6ef3e259-10c4-4071-8b9e-fe17a834d240)

Also, there's a youtube video which should be removed as it doesn't provide useful info to the website.

PLease assign me this issue under gssoc.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aslams2020** [comment]
@apu52 Please assign me this issue

**Comment by apu52** [comment]
#1354 already present there & already been assigned on the same topic , sorry I can't assign u this issue. sorry to close this issue . But u can still make new issues
