### ISSUE TITLE
[Feature Request]: Nav-Bar for contributors page 

### ISSUE THREAD

**Issue by ANKeshri** [apu52/Travel_Website#1360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

nav bar for contributors page 

### Use Case

can easily visit other pages 

### Benefits

can easily visit other pages 

### Add ScreenShots

before  : 

![Screenshot 2024-08-09 104047](https://github.com/user-attachments/assets/de106aa8-df11-44bd-a541-8d7e4fe7f5ca)

want to add this  : 

![Screenshot 2024-08-09 104036](https://github.com/user-attachments/assets/52dd4386-af39-4187-bde1-8c22c80a242b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@apu52 please assign me this issue

**Comment by apu52** [comment]
@ANKeshri nav bar not needed in that page , instead make a return to home button .I am assigning u this issue .Make the changes
