### ISSUE TITLE
Enhance the responsiveness of gap between Dark Theme button and Contact Us buttons of navbar.

### ISSUE THREAD

**Issue by Niharika-Upveja** [apu52/Travel_Website#137]
**Describe the bug**
Gap between the Dark Theme button and Contact Us button is very much for width more than 1400px.
[Screencast from 22-01-24 11:39:41 PM IST.webm](https://github.com/apu52/Travel_Website/assets/127125259/789f27c1-87c4-46e0-a5d2-b1386380ed22)

**Expected behavior**
Decrease the gap between the buttons for width greater than 1400px.

I request you to please assign this issue to me

**Comment by apu52** [comment]
@Niharika-Upveja Are you contributing under JWOC?

**Comment by Niharika-Upveja** [comment]
Yes

**Comment by Niharika-Upveja** [comment]
please assign me this issue under jwoc 2024 @apu52

**Comment by apu52** [comment]
@Niharika-Upveja You are assigned. now you can submit your PR. You jus have 1 day to submit your PR
