### ISSUE TITLE
[Bug]:dark mode button it not positioned properly

### ISSUE THREAD

**Issue by singhshikha01** [apu52/Travel_Website#1373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 their is improper gap between the navbar icons and dark mode button it not positioned properly

### Expected behavior

navbar icons should proper gapping between them and dark mode button should be on more left side

### Add ScreenShots

![Screenshot 2024-08-10 032927](https://github.com/user-attachments/assets/4e745196-4f34-48be-ba4e-c80e0c3e4bfa)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sachan13harshit** [comment]
@apu52  please assign this issue to me

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
