### ISSUE TITLE
[Documentation Update]: This is for understanding google maps feature

### ISSUE THREAD

**Issue by litesh1123** [apu52/Travel_Website#1375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This will help understand how google maps feature  is working in better way

### Suggested Change

This is will more idea and depth in understanding

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by 13Sharad** [comment]
I solved this issue. If u assign me
