### ISSUE TITLE
[Bug]: improve the package tab in the website 

### ISSUE THREAD

**Issue by ujjwalshriv3** [apu52/Travel_Website#1387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Package tab the logo and some images are not showing in package plz check this out and fix it ...

### Expected behavior

Logo and Images are not Showing in Package tab

### Add ScreenShots

![screencapture-apu52-github-io-Travel-Website-packages-html-2024-08-31-15_09_42](https://github.com/user-attachments/assets/46c661f7-7c70-47f9-b125-8260347db02e)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ujjwalshriv3 u are assigned
