### ISSUE TITLE
[Bug]: Improvement on the newLogin.html page 

### ISSUE THREAD

**Issue by aadhi-i** [apu52/Travel_Website#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the name input, even numbers can get uploaded into the database.

### Expected behavior

I think only valid names, atleast only letters should pass through, not numbers and special characters.

### Add ScreenShots

![Screenshot 2024-10-01 180349](https://github.com/user-attachments/assets/228f5e09-aa22-4712-9ef6-09df82bb9f7e)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by monishkumardvs** [comment]
hey i would like to work in this project can u assign me?

**Comment by shivamv003** [comment]
I would like to request the opportunity to work on improving the Login page of the project can you assign this to me ?

**Comment by NehaBajjuri** [comment]
Hey, i would like to work on this issue, could you assign this to me?

**Comment by PraagnaVaishnavi** [comment]
hey, I would like to work on this issue, would you please assign this to me.

**Comment by Aamirakram1** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> On the name input, even numbers can get uploaded into the database.
> 
> ### Expected behavior
> I think only valid names, atleast only letters should pass through, not numbers and special characters.
> 
> ### Add ScreenShots
> ![Screenshot 2024-10-01 180349](https://private-user-images.githubusercontent.com/146866457/372470748-228f5e09-aa22-4712-9ef6-09df82bb9f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjMzMDAsIm5iZiI6MTcyODM2MzAwMCwicGF0aCI6Ii8xNDY4NjY0NTcvMzcyNDcwNzQ4LTIyOGY1ZTA5LWFhMjItNDcxMi05ZWY2LTA5ZGY4MmJiOWY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwNDUwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjEzYTI4OTgzZDI2MzNhZDgyY2Y4YWI3NGVjMDYxMjdlNWJmZjYzZGUxYWVlYTUzNzhjZWE0YTc0ZTdkOThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QlXRHuQjK3CnIF0OFxFIFHUIvdtIAZQr1bcExbcY3Tk)
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [ ]  I'm a VSOC'24 contributor
> * [x]  I have starred the repository

**Comment by Aamirakram1** [comment]
me

**Comment by apu52** [comment]
@aadhi-i U ARE ASSIGNED
