### ISSUE TITLE
[Feature Request]: Addition of extra cards and improving styling of Local Events and Festivals

### ISSUE THREAD

**Issue by DiwareNamrata23** [apu52/Travel_Website#1391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add more cards and will improve the styling using css

### Use Case

it will give attractive look to webpage

### Add ScreenShots
<img width="1440" alt="Screenshot 2024-10-01 at 6 19 43 PM" src="https://github.com/user-attachments/assets/80cce82f-5926-48b6-bdc7-3d5a1456ca2c">

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by simmi-verma** [comment]
I would like to work on this . please assign to me

**Comment by apu52** [comment]
@DiwareNamrata23 u are assigned
