### ISSUE TITLE
[Bug]: the image is not present

### ISSUE THREAD

**Issue by DiwareNamrata23** [apu52/Travel_Website#1392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Addition of image

### Expected behavior

to reduce man errors

### Add ScreenShots

![Uploading Screenshot 2024-10-01 at 6.18.41 PM.png…]()

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Apoorv-Saxena08** [comment]
Hi @DiwareNamrata23 , I have reviewed the issue regarding the missing image. I would like to work on adding the necessary image to resolve this problem. Please assign this issue to me. Thank you!

**Comment by Ayush1Deshmukh** [comment]
I could to work on these issue , please assign it to me

**Comment by ayush786hack** [comment]
i @DiwareNamrata23 , I have reviewed the issue regarding the missing image. I would like to work on adding the necessary image to resolve this problem. Please assign this issue to me. Thank you!

**Comment by apu52** [comment]
@DiwareNamrata23 the image is still uploading , I can't see the image correctly , please try to upload it properly so that I can assign u the issue.
