### ISSUE TITLE
[Bug]: There is no navigation bar for the About page.

### ISSUE THREAD

**Issue by ChathuraHasanga44** [apu52/Travel_Website#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no navigation bar for the about page. Like other pages it may be very helpful to navigate other pages in the about page. Otherwise we cannot move to another pages without clicking browser back row.

### Expected behavior

Need to add navigation bar for the about page with linking another pages.

### Add ScreenShots

![Screenshot 2024-10-01 192455](https://github.com/user-attachments/assets/4733deec-07f7-4711-ab5a-2171ce8eb7ff)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aryansoni13** [comment]
I Would like to work on this kindly assign me the task..

**Comment by shivamv003** [comment]
I would like to kindly request to be assigned the task of adding a fully functional navigation bar that links to other pages like Home, Services, Contact Us, and Cart.

**Comment by shivin21** [comment]
Hey! Please assign me this tast , i would like to work on this issue.

**Comment by apu52** [comment]
@ChathuraHasanga44 u are assigned
