### ISSUE TITLE
[Bug]: Related to the Testimonial Section Image Issue

### ISSUE THREAD

**Issue by kunalSingh026** [apu52/Travel_Website#1396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In your Testimonial section, one image is not available

### Expected behavior

So Please address this problem and solve it there should be one Image that is not there

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by 4F24L** [comment]
Can you assign me for this issue? So, I can start working on this !

**Comment by apu52** [comment]
@kunalSingh026 I think this issue has already been solved. so sorry to close this issue for now . But u can still make new issues on which u want to work on
