### ISSUE TITLE
[Bug]: In Package tab the logo and some images are not showing in package plz check this out and fix it ...

### ISSUE THREAD

**Issue by JitDey2004** [apu52/Travel_Website#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

packages ,logo ,pictures nothing is showing
![issue](https://github.com/user-attachments/assets/9c245db1-9e97-4d5b-8303-ca4666a34a4a)

### Expected behavior

logo,packages shows in a propper way

### Add ScreenShots

![image](https://github.com/user-attachments/assets/301c18b8-1975-41a6-b92a-c57c76a8af7d)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Apoorv-Saxena08** [comment]
Hi @JitDey2004 , I have reviewed the issue regarding the logo and images not showing in the Package tab. I would like to work on fixing this bug to ensure all elements display correctly. Please assign this issue to me. Thank you!

**Comment by Shantanu675** [comment]
Would you assign this to me ? I want to work on it!

**Comment by apu52** [comment]
@JitDey2004 u are assigned
