### ISSUE TITLE
[Bug]: Testimonial Cards Responsiveness and Image loading

### ISSUE THREAD

**Issue by Bhanuprakash842** [apu52/Travel_Website#1398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Testimonial cards are of very small widths and the third card image is not loading
![Screenshot 2024-10-01 205559](https://github.com/user-attachments/assets/a5ebf496-cd39-478b-87a7-c1c74236ad8c)
I would be grateful if you assign me this issue with the labels **Gssoc-ext,hacktoberfest** and my github username is @Bhanuprakash842

### Expected behavior

I would expect to increase the card width for the small screens and make the third image of the testimonials load better which makes the user experience better.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Apoorv-Saxena08** [comment]
Hi @Bhanuprakash842 , I have reviewed the issue regarding the responsiveness of the Testimonial cards and the image loading problem. I would like to work on resolving these issues to enhance the user experience. Please assign this issue to me. Thank you!

**Comment by sakshamtiwarii** [comment]
Fixed the issue, please review the code.

**Comment by Bhanuprakash842** [comment]
> Fixed the issue, please review the code.


![Screenshot 2024-10-03 222640](https://github.com/user-attachments/assets/c0f03be1-0dca-4302-b858-cb5ad0538940)
Reviewed the code.Image Issue Resolved .
but the cards width should be somewhat increased to look better in smaller screens and this issue is also included.
Please do consider that!!

**Comment by apu52** [comment]
@Bhanuprakash842 the image issue has already been resolved . u are already assigned on this issue .  so try to work on the responsiveness
