### ISSUE TITLE
[Bug]: In Package tab the logo and some images are not showing in package plz check this out and fix it ...

### ISSUE THREAD

**Issue by JitDey2004** [apu52/Travel_Website#1399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Package tab the logo and some images are not showing in package plz check this out and fix it ...
![issue](https://github.com/user-attachments/assets/772a4879-f9be-472b-a6ea-def6e422d7e1)

### Expected behavior

improve the page fix this bug for better experience

### Add ScreenShots

![issue](https://github.com/user-attachments/assets/c61d0084-0b11-4a2f-9d42-98db266dfd7b)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Amarjha01** [comment]
hi! Jit Dey, I want to fix this issue. Please assist this to me.

**Comment by JitDey2004** [comment]
> hi! Jit Dey, I want to fix this issue. Please assist this to me.
 Ok no problem

**Comment by Nelathecoder** [comment]
hello I am willing to fix this issue. Please assist this to me
