### ISSUE TITLE
[Bug]: Unnecessary spacing above navbar

### ISSUE THREAD

**Issue by Sourabh782** [apu52/Travel_Website#1400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

while scrolling the scroll indicator adds transparent spacing above navbar, wanted to remove that 

### Expected behavior

There shoud be obaque background of navbar's theme not transparent

### Add ScreenShots

![Screenshot 2024-10-01 211929](https://github.com/user-attachments/assets/45687808-297f-47f9-ab6a-5a031cdb726d)
![Screenshot 2024-10-01 212219](https://github.com/user-attachments/assets/a8be9041-c365-4c21-a9a7-3cf5e04a5095)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by S7viks** [comment]
I want to solve this issue, assign it to me, please.

**Comment by Sourabh782** [comment]
@S7viks bro according to guidelines, the issue is assigned to the one who raised the issue, if u see someone not working since a week, then u can ask for reassignment

**Comment by Nikhilkumar111** [comment]
I want to solve this issue assign me plz , I am also campus ambassador.

**Comment by devarsheecodess** [comment]
Please assign this to me with gssoc-extd label. i can do this for you

**Comment by Prathamgupta661** [comment]
Hi, @Sourabh782 assign this to me with the gssoc-extd label I have been through your code base, and I  will fix this for you.

**Comment by Prathamgupta661** [comment]
![image](https://github.com/user-attachments/assets/e0a888aa-3fd8-4d13-8bd2-aae10f2f4e04)
Is this the expected output? assign this to me so that I can create a pr

**Comment by Sourabh782** [comment]
@Prathamgupta661 I m not the admin 😅

**Comment by Prathamgupta661** [comment]
oh 😅 I thought that you were the admin

> @Prathamgupta661 I m not the admin 😅

**Comment by apu52** [comment]
@Sourabh782 u are assigned
