### ISSUE TITLE
[Feature Request]: ui

### ISSUE THREAD

**Issue by Prit16** [apu52/Travel_Website#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

home page looks like simple. 
nedds to add more CSS and animation and color contrast.

### Use Case

user can easily interface site
and it will look attractive

### Benefits

it will look eye catching.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by simmi-verma** [comment]
I would like to work on this project.

**Comment by apu52** [comment]
@Prit16 can u suggest some of the UI changes for the website with some description or some SS of the changes u want to suggest....
