### ISSUE TITLE
[Bug]: Landing page image missing

### ISSUE THREAD

**Issue by 4F24L** [apu52/Travel_Website#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Image Missing on landing page
![image](https://github.com/user-attachments/assets/c8f3f877-8e9b-4958-b550-eb0f27c1e2cf)

### Expected behavior

Image should be visible ✅

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by 4F24L** [comment]
Can you label it as hactoberfest-accepted and assign to me ?

**Comment by techgeek09** [comment]
Hi! I am a gssoc 2024 extended contributer. Please assign me this issue.

**Comment by apu52** [comment]
@4F24L this issue has already been solved . sorry to close this issue . but u can still make new issues on which u want to work on
