### ISSUE TITLE
[Feature Request]: Enhance Password Security by Implementing **bcrypt with Salt and Hash for Secure User Authentication**

### ISSUE THREAD

**Issue by Parthshukla26** [apu52/Travel_Website#1407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature request proposes the implementation of bcrypt to encrypt user passwords using hashing and salting methods. Currently, the project may store user passwords without sufficient encryption, which exposes them to potential security risks such as data breaches. By integrating bcrypt, all user passwords will be securely hashed and salted before being stored in the database, ensuring that sensitive data remains protected.

### Use Case

This feature will be used during user registration and authentication processes. When a user creates an account, their password will be hashed and stored securely, rather than being stored in plain text. When a user logs in, the system will compare the hashed password in the database with the entered password, ensuring secure authentication. This will enhance both the security and trustworthiness of the platform by safeguarding user credentials.

### Benefits

Benefits:

1. Increased Security: Implementing password hashing and salting with bcrypt will protect users from common attacks like rainbow table or brute-force attacks.

2. Compliance: Encrypting passwords helps in meeting security standards and compliance requirements for handling sensitive data.

3. Community Trust: Users will feel safer using the platform, knowing their passwords are encrypted and securely managed.

4. Scalability: As the platform grows, having secure authentication systems in place will ensure robust protection of user data.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by MihaelaBogdan** [comment]
I can work on this.

**Comment by apu52** [comment]
@Parthshukla26 really great issue. u are assigned . start working
