### ISSUE TITLE
[Documentation Update]: 

### ISSUE THREAD

**Issue by Nikhith221B** [apu52/Travel_Website#1408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot_2024-10-03-08-52-48-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/5da84168-73bb-435a-ba23-87a92ad5b0f3)

### Suggested Change

I would like to enhance the quality of the images in the website.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Nikhith221B I have assigned u this time . But from next time please try to fill up the issue with more info properly & with proper issue name 
& I will assign u the labels after reviewing the PR . Don't worry
