### ISSUE TITLE
[Bug]: Don't able to click on trip suggestion images

### ISSUE THREAD

**Issue by vri-2800** [apu52/Travel_Website#1409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In plan a trip section  dont able to click on images of trip suggestion

### Expected behavior

Upon clicking on the image the user should be directed to that place images in trip suggestions section.
_**Please assign this issue to me**_

### Add ScreenShots

![Screenshot 2024-10-03 094704](https://github.com/user-attachments/assets/41b9fc63-262c-4768-b519-ca3ba81c98c5)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@v-280 u are assigned
