### ISSUE TITLE
[Feature Request]: Top deals page card

### ISSUE THREAD

**Issue by KajalDeore04** [apu52/Travel_Website#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The top deals page cards are not readable better UI would help.

### Use Case

Better looking top deals page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by NausheenShaikhAyyub** [comment]
I would like to work on this, kindly assign me this issue @apu52

**Comment by apu52** [comment]
@NausheenShaikhAyyub Actually this issue has already been solved , so u can't work on this issue
