### ISSUE TITLE
[Feature Request]: UI can be improved

### ISSUE THREAD

**Issue by Nelathecoder** [apu52/Travel_Website#1412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

UI can be altered for clarity and better visual experience. In the top deals page there is difference in size of hotel description. Font on this page can be changed, bg image can be changed. Overall UI can be improved.

### Use Case

Better looking website, enhanced look can be given.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Nelathecoder can u just share some of the UI changes which u want to enhance in that particular page with some proper ss

**Comment by Nelathecoder** [comment]
<img width="1068" alt="Screenshot 2024-10-20 201357" src="https://github.com/user-attachments/assets/74c33d62-5b94-46a2-8bc4-7f0129af70f7">
would like to change the background, font and alignment.
Also any additional ui support if needed, can be done.

**Comment by apu52** [comment]
@Nelathecoder u are assigned

**Comment by Nelathecoder** [comment]
@apu52 sure thanks!
