### ISSUE TITLE
[Feature Request]: UI can be better and attractive 

### ISSUE THREAD

**Issue by Vaishnavigade88** [apu52/Travel_Website#1413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in front page the login and registration page can be better .

### Use Case

in front page the login and registration page can be better .

### Benefits

this will make a significant change.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by bhaviya18** [comment]
Hello sir/ma'am I would like to work on this issue, please assign me this task.

**Comment by apu52** [comment]
@Vaishnavigade88 can u just share some of the UI changes which u want to enhance in that particular page with some proper ss
