### ISSUE TITLE
[Bug]: Checkout page navbar not working and no proper routing and organising of files

### ISSUE THREAD

**Issue by tarunkumar2005** [apu52/Travel_Website#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i got to top deals from navbar and then book a service so i will be on the payment or checkout page there is navbar but when i click on home or any other link it is not redirecting me anywhere so i want to fix the routing part and the routing is not properly done.

### Expected behavior

So what i want to suggest is that we can create a express app to support it and a ejs template with it to organise all the files and put them in a single place so that developers can understand code properly as right now it is too messy and also the links are not clean like #Home, #Services and so these are not professional routes so i want to fix this. Assign me under gssoc 2024 ext and hacktoberfest and i will be on it. I will use express js for the routing.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/91a04efe-d4f1-4b51-abf4-1bcbc3ebaca3)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by tarunkumar2005** [comment]
@apu52 Assign this to me under gssoc 2024 ext and hacktoberfest, I would like to contribute to this.

**Comment by apu52** [comment]
@tarunkumar2005 u are assigned . really great issue .

**Comment by tarunkumar2005** [comment]
@apu52 I would suggest one thing your project is good but i think you should organise the files a bit means like in folders or somewhere as they are spread in the main dir which is not good this is my suggestion.

**Comment by apu52** [comment]
> @apu52 I would suggest one thing your project is good but i think you should organise the files a bit means like in folders or somewhere as they are spread in the main dir which is not good this is my suggestion. that is what i will be doing in this.

yeah . Thanks for the suggestion . & thanks for your issue also .
