### ISSUE TITLE
[Bug]: UI improvements

### ISSUE THREAD

**Issue by NehaBajjuri** [apu52/Travel_Website#1417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is misplacement of text and images. 
Regarding css, it can be improved for the mentioned buttons.
![image](https://github.com/user-attachments/assets/34cb4d74-a110-4501-9aae-28316bd7db1a)

### Expected behavior

A clear attractive homepage with the proper image and attractive CSS for the buttons 

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by techgeek09** [comment]
Hi, I would love to work on this issue, if you can assign me this task.

**Comment by Shantanu675** [comment]
Would you assign this to me ? I want to work on it!

**Comment by apu52** [comment]
@NehaBajjuri maybe there is some problem in your screen size or resolution , otherwise in my System also the page design is properly working 

![image](https://github.com/user-attachments/assets/ede8de38-545f-4763-80b2-619648f2d099)


Sorry to close this issue .But u can still work on other issues.
