### ISSUE TITLE
[Feature Request]:: Suggest a list of travel destinations based on user needs.

### ISSUE THREAD

**Issue by Tushika2024** [apu52/Travel_Website#1421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When we plan for a trip we are often confuse about tourist spot specially whenever  there is a group or family trip . As everyone has different taste and want to enjoy full . We can create a new section of filttering destinations where user provides their wishes .For example-
1-Adventorous
2-Mountains /seas/greenery areas/desserts
3-peaceful/pub or parties friendly
4-Suitable for nightouts if solo female traveller.
5-if there is any event going on at the place like - carnivals,dandiya shows etc.
6-trip type-family,friend,solo,couple
and get some suggestions of places .
This helps to find a suitable destination comprising fun of everyone.

### Use Case

This feature can be added in plan a trip sections with more drop down giving more friendly experience to user.Also besides No of members section can be added .

### Benefits

This project would become a wholecome travel guide ranging from suggesting travel destinations to planning the trip comfortably and user friendly

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by AgarwalSneh** [comment]
May I work on this issue, I really like to gather stuff about travelling so will fetch data and try to  make it good.

**Comment by SHUBHAG100520** [comment]
Can i too work on the project.

**Comment by Supraja-Gao** [comment]
please assign this issue to me also..I would like to work on this issue

**Comment by apu52** [comment]
@Tushika2024 u are assigned
