### ISSUE TITLE
[Bug]: Inconsistent Navbar Styling Between Homepage and Dedicated Destination Pages

### ISSUE THREAD

**Issue by shivam8112005** [apu52/Travel_Website#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The navbar on the homepage and the dedicated-destinations pages shows inconsistencies in:

Font Style: Navbar link fonts differ.
Background Color: Navbar background colors are not uniform.
Logo Font: The logo is not present in dedicate-destinations pages.
Button Alignment: Buttons are misaligned across the dedicate-destinations pages..

### Expected behavior

The navbar styling should remain consistent across all pages, including the homepage and the dedicated-destinations page.

### Add ScreenShots

home and other pages: 
![Screenshot 2024-10-04 181458](https://github.com/user-attachments/assets/d138f301-1887-47f5-ac57-7b94b42ae280)
dedicated-destinations pages: 
![Screenshot 2024-10-04 181444](https://github.com/user-attachments/assets/7ae0df18-7f71-4836-8c0e-1825452d9bc2)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Supraja-Gao** [comment]
please assign this issue to me. I would like to work on it

**Comment by apu52** [comment]
@shivam8112005 u are assigned

**Comment by shivam8112005** [comment]
ohk got it
