### ISSUE TITLE
[Feature Request]: Add Real-time Weather Updates for Destinations.

### ISSUE THREAD

**Issue by 13Sharad** [apu52/Travel_Website#1423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The feature I am requesting is to add real-time weather updates for each destination on the TourGuide website. This feature will provide users with essential information to plan their trips accordingly, including current temperature, humidity, wind speed, and weather conditions (e.g., sunny, cloudy, rainy, etc.).
The weather updates should be displayed on each destination's page, allowing users to easily access this information while browsing through the website. The updates should be fetched from a reliable weather API (e.g., OpenWeatherMap, Dark Sky, etc.) and updated in real-time to ensure users have access to the latest weather data.

The feature should be implemented in a user-friendly and visually appealing way, with clear and concise weather information displayed prominently on each destination's page.

### Use Case

As a TourGuide user, I want to see real-time weather updates for each destination. This would help me:

Plan my trip better
Pack the right clothes
Make informed decisions about outdoor activities
It would save me time and make my experience on the website more convenient and enjoyable.

### Benefits

Enhanced User Experience: Real-time weather updates would provide users with essential information to plan their trips more effectively, leading to a better overall experience on the website.

Increased Website Value: This feature would increase the website's value proposition, making it more attractive to users and setting it apart from competitors.

Informed Travel Decisions: Users would be able to make informed decisions about their travel plans, such as packing appropriate clothing and planning outdoor activities accordingly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@13Sharad U are assigned . But I think already in the destination page there is a live weather API is attached 

![image](https://github.com/user-attachments/assets/8658863e-be8c-44f7-aacd-b3af03423684)

although I have checked this is not working well , so u can enhance it

**Comment by 13Sharad** [comment]
@apu52 Yes
