### ISSUE TITLE
[Bug]: Uneven font size in footer section 

### ISSUE THREAD

**Issue by nishtha-902** [apu52/Travel_Website#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In footer section, font size is not uniform, please assign me this issue.

### Expected behavior

Font size of links in footer section must be same. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/70e36969-55a7-4afa-b794-a9f0592f37c7)
somewhere size is small and somewhere it is large

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Kawaljeet-943** [comment]
Hi! I would like to work on this issue as part of GSSOC 2024. Please assign it to me. I'm ready to fix the uneven font size in the footer section.

**Comment by BhavikaPachauri** [comment]
@nishtha-902  i wolud like to solve this issue

**Comment by Preethii-R** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.
