### ISSUE TITLE
 button alignment and hover effects in #destinations and #prices

### ISSUE THREAD

**Issue by Harshitha-Annam** [apu52/Travel_Website#1429]
--> The button is not centrally aligned within the image card. This misalignment affects the overall aesthetic and usability of the card.
--> For certain buttons, a red line appears through the button text when hovered over. This visual is distracting from the user experience.
 I am interested in handling these issues.

**Comment by techaakritisha** [comment]
I would like to contribute in your project . Please assign it to me

**Comment by codingblasts** [comment]
I would like to work on it please assign it to me
