### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by maadi7** [apu52/Travel_Website#143]
**Is your feature request related to a problem? Please describe.**
We can add a feedback text section on "Rate Us?" page.

**Demo Video/Screenshot (Mandatory )**
thhe red box will be our new feedback section.
![feedback](https://github.com/apu52/Travel_Website/assets/95737654/1460ae45-3ac1-459a-9de4-260e9178a52c)

***Are you contributing under any open-source program ?***
JWOC

**Comment by apu52** [comment]
@maadi7 you just have 1 day to complete this issue
