### ISSUE TITLE
[Bug]: Night mode button not clearly visible in the navbar

### ISSUE THREAD

**Issue by manikdamle** [apu52/Travel_Website#1430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Button partially visible on the navbar on the webpage and a part of it is being cut off at the right.

### Expected behavior

The button should be fully visible and aligned with the rest of the navbar items.

### Add ScreenShots

![bug_night_mode_button](https://github.com/user-attachments/assets/e4429dad-51ca-42c2-8e1e-0980aac7f750)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by manikdamle** [comment]
Please assign the issue to me, so that I can start working on it.

**Comment by Kawaljeet-943** [comment]
Hi! I would like to work on this issue as part of GSSOC 2024.  Please assign it to me. I'm ready to fix the visibility and alignment of the night mode button in the navbar.
