### ISSUE TITLE
[Bug]: Improvement needed in Trip gallery section

### ISSUE THREAD

**Issue by patilchaitali27** [apu52/Travel_Website#1435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Trip Gallery section of the application is not functioning as expected the images are not loading properly and the UI is not looking good changes in UI is required.

### Expected behavior

Images should display in the correct resolution without distortion and loading time for the gallery should be optimal.
Users should be able to navigate the gallery easily, with images ordered appropriately and sections should be fully responsive properly on both devices mobile and laptop .

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c459f498-5040-4e2e-b701-fabad8c97772)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@patilchaitali27 u are assigned . good issue

**Comment by SanikaBhalerao1345** [comment]
@apu52 can i work on this issue

**Comment by apu52** [comment]
@SanikaBhalerao1345 i have assigned you , you can work on this issue .

**Comment by soumya778** [comment]
Can I work on this issue

**Comment by apu52** [comment]
> Can I work on this issue

@soumya778 will u be contributing under KWOC???

**Comment by apu52** [comment]
@soumya778 Actually i want to inform u one thing , that the contribution period of kwoc will start from 5 th dec , so any contributions before that timeline will not count towards KWOC , so please try to start contributing after 5th DEC .

& regarding this issues which u have raised prior , don't worry about it , i will review & assign u this issues after the contribution period starts
