### ISSUE TITLE
[Feature Request]: UI Improvement

### ISSUE THREAD

**Issue by dhruvveragiwala** [apu52/Travel_Website#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The font size is not very appealing

### Use Case

Proper use of css and font style

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2570748a-dbc3-48e4-a80d-042d2397531a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by dhruvveragiwala** [comment]
Can you assign me this?

**Comment by bhaviya18** [comment]
Hello sir/ma'am I would like to work on this issue, can you kindly assign this task to me?

**Comment by apu52** [comment]
@dhruvveragiwala u are assigned
