### ISSUE TITLE
[Bug]: "Select Language" Dropdown Misplacement and Poor Accessibility

### ISSUE THREAD

**Issue by CodeMosaic7** [apu52/Travel_Website#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Select Language" element is poorly positioned and lacks prominence. Its placement at the bottom of the footer is not intuitive, making it harder for users to locate. Additionally, the dropdown design does not stand out visually and blends into the page, negatively affecting usability.

### Expected behavior

1. The "Select Language" feature should be replaced with a button that is always present on the right side of the screen, allowing users to easily access it from any page.
2. The button should stand out visually, using a contrasting color or icon that makes it easily noticeable and accessible across different screen sizes.
3. The design should focus on improving usability, ensuring that users can quickly find and switch languages without having to scroll or search for the option.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5ec8a0f3-7980-4eab-bfb2-c4993d08b671)

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush786hack** [comment]
Hi @CodeMosaic7! Thanks for opening this issue. We appreciate your contribution to this open-source project.

**Comment by CodeMosaic7** [comment]
I'll be working on it.
