### ISSUE TITLE
UPDATION OF PAGE

### ISSUE THREAD

**Issue by RAJIV81205** [apu52/Travel_Website#1439]
YOUR PACKAGES PAGE HAS BEEN SPOILED , PLEASE ASSIGN ME TO FIX IT 
![image](https://github.com/user-attachments/assets/0362e538-c2ef-4a49-be20-5384985b9a52)

**Comment by apu52** [comment]
@RAJIV81205 this issue already existed in this page
Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.

Sorry to close this issue for now .
