### ISSUE TITLE
[Feature Request]: Enhancement of the trending page

### ISSUE THREAD

**Issue by Ananya-vastare** [apu52/Travel_Website#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The trending page did not set well with the websites concept so I have enhanced it to make it readable

### Use Case

I will enhance the feature by adding background color and also alignment of the cards 

### Benefits

This will make it even more user friendly

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aditi13y** [comment]
Please assign it to me.

**Comment by Ananya-vastare** [comment]
@apu52 the pr number is #1395 and pr number is https://github.com/apu52/Travel_Website/pull/1395/commits/513b7d45fbd47d2959cab7d856084260a36efe02 please add the level also
