### ISSUE TITLE
The package page is non functional

### ISSUE THREAD

**Issue by 1ShahidBashir** [apu52/Travel_Website#1442]
@apu52  The package page is not usable for the users.
The formatting incorrect and the page is not usable at all
![image](https://github.com/user-attachments/assets/6581867f-9c86-4e78-a9a6-1e90dc71425b)

**Comment by 1ShahidBashir** [comment]
@apu52 Assign this issue to me I can work this out really well.
also give the relevant labels of gssoc and hacktoberfest

**Comment by apu52** [comment]
@1ShahidBashir this issue has already been assigned in this repo 
Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.

Sorry to close this issue for now .
