### ISSUE TITLE
[Bug]: Image is not appearing 

### ISSUE THREAD

**Issue by PATILYASHH** [apu52/Travel_Website#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

the image of person is not visible 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d1998074-a43a-402d-beb3-b3c16bb8700b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by PATILYASHH** [comment]
please assign me for this issue

**Comment by BhavikaPachauri** [comment]
@PATILYASHH  i wolud like to solve this issue

**Comment by ChauhanAyush04** [comment]
@apu52  plz assign me this issue

**Comment by ayush786hack** [comment]
please assign me for this issue.

**Comment by apu52** [comment]
@PATILYASHH this issue has already been solved . sorry to close this issue . but u can still make new issues on which u want to work on
