### ISSUE TITLE
[Feature Request]: suggestions of places while entering locations 

### ISSUE THREAD

**Issue by rishika105** [apu52/Travel_Website#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When I want will write my location, it should show me valid locations and suggestions below as I write.

### Use Case

It will allow easier conduct and flow like other professional websites.

### Benefits

It will be easier to write locations that actually exists. Also avoiding entering random locations those are not present. It has alert though but still it will allow easier conduct and flow like other professional websites.

### Add ScreenShots

I am raising an issue on this.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aditi13y** [comment]
Hi there,please assign it to me.
