### ISSUE TITLE
Creation of Feedback page 

### ISSUE THREAD

**Issue by thesri** [apu52/Travel_Website#145]
While making websites that people are gonna use it highly recommended to have feedback pages which will help us to enhance our work.

A feedback page would solve this problem definitely 

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/98333833/6cab86d3-7105-4776-9c31-613fbb5cbf35)

***Are you contributing under any open-source program ?***

please assign me this issue under jwoc 2024

**Comment by thesri** [comment]
> @thesri really it's a good issue. Make it a workful page & also make a button in the contact us portion to redirect to the feedback page

Yes okay

**Comment by vermaanurag1532** [comment]
please Assign it to me
