### ISSUE TITLE
[Bug]: Responsive issue

### ISSUE THREAD

**Issue by Kiran511-git** [apu52/Travel_Website#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot 2024-10-07 073502](https://github.com/user-attachments/assets/d15c2fae-f462-48f1-a896-d95593fee027)
There is a issue in Contact Us page where the border of the email is not properly set.When we resize the page it is not responsive.
![Screenshot 2024-10-07 073557](https://github.com/user-attachments/assets/cf8fb7ec-e680-4ce3-9819-a42c65b49eb3)
Please allow me to fix the issue.

### Expected behavior

It should be responsive.Border layout should correctly aligned.

### Add ScreenShots

![Screenshot 2024-10-07 073502](https://github.com/user-attachments/assets/4443c5d1-b554-41bb-8221-fccd6fca307f)
![Screenshot 2024-10-07 073557](https://github.com/user-attachments/assets/d1abd498-100d-4cf8-9303-2bc681e6c833)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran511-git** [comment]
please assign me this issue.

**Comment by BhavikaPachauri** [comment]
@Kiran511-git   i wolud like to solve this issue

**Comment by Kiran511-git** [comment]
@BhavikaPachauri I raised the issue and I'm solving the issue.

**Comment by BhavikaPachauri** [comment]
okk

**Comment by Kiran511-git** [comment]
@apu52 please once check #1462

**Comment by apu52** [comment]
> @apu52 please once check #1462

I will check
