### ISSUE TITLE
The scroll-back button directly jumps to the top; it does not scroll smoothly to the top.

### ISSUE THREAD

**Issue by Raj-Aditya-27** [apu52/Travel_Website#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The scroll-back button is expected to smoothly scroll the page to the top when clicked. However, instead of performing a smooth scrolling action, it directly jumps to the top of the page. This abrupt transition negatively impacts user experience, making it feel less intuitive and polished.

### Expected behavior

When the scroll-back button is clicked, the page should smoothly scroll to the top over a specified duration, providing a visually pleasing and seamless transition.

### Add ScreenShots

Actual behaviour in website: https://apu52.github.io/Travel_Website/#

Expected behaviour:
You can refer to my previous project where I implemented a more user-friendly "Back to Top" functionality.
https://raj-aditya-27.github.io/SarvottamSamachar/

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Raj-Aditya-27 u are assigned

**Comment by Raj-Aditya-27** [comment]
@apu52 Thanks for assigning this issue.
I will do it as soon as possible.
