### ISSUE TITLE
[Feature Request]: Adding navbar  in about us page and fixing the broken link.

### ISSUE THREAD

**Issue by trahulprabhu38** [apu52/Travel_Website#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there is no return home feature in about us page and u will be stuck there , so i can either add a complete navbar or only home button.
then the bottom button has a broken link as well.

@apu52 assign me this task so i can fix it immediately.

### Use Case

<img width="746" alt="Screenshot 2024-10-07 at 6 26 14 PM" src="https://github.com/user-attachments/assets/6b732903-a4b7-42ab-851f-d88e7b667eaf">
<img width="988" alt="Screenshot 2024-10-07 at 6 26 19 PM" src="https://github.com/user-attachments/assets/7a338ff7-0c0f-4795-b7bd-7249a4bdd11b">
<img width="1462" alt="Screenshot 2024-10-07 at 6 26 22 PM" src="https://github.com/user-attachments/assets/675c8391-4492-437c-a7eb-d3a3c7bfb8dc">

### Priority
High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by T-Rahul-prabhu-38** [comment]
@apu52 please assign me this task.

**Comment by T-Rahul-prabhu-38** [comment]
<img width="1468" alt="Screenshot 2024-10-07 at 6 30 15 PM" src="https://github.com/user-attachments/assets/f66dde40-3ff2-4e92-a632-e717de1780da">
same issue with this page as well


<img width="744" alt="Screenshot 2024-10-07 at 6 30 48 PM" src="https://github.com/user-attachments/assets/81f21638-7c1c-4b84-9d3b-8e9c0437b89f">
here the UI is broken.

**Comment by apu52** [comment]
@T-Rahul-prabhu-38 the adding of navbar in the about page is already present as an issue in the repo . So just try to fix the broken button link & make a new page in the "STRAT JOURNEY" button

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
