### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by Jerusha547** [apu52/Travel_Website#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add scroll to top button

### Use Case

Scroll to top button will be helpful to go quickly to the top

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by shivin21** [comment]
hey @apu52 i want to work on this issue please assign me.

**Comment by apu52** [comment]
@Jerusha547 add to top button is already present in the project sorry to close this repo . But u can still make new issues on which u want to work on
