### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by divyasaahithya** [apu52/Travel_Website#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the view button present on top right corner of the web page is not visible

### Expected behavior

the entire web page must fit properly on any kind of desktop device

### Add ScreenShots

![image](https://github.com/user-attachments/assets/df874d93-bba3-493a-adf3-1ac4a21dd247)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush786hack** [comment]
Hi @divyasaahithya! Thanks for opening this issue. We appreciate your contribution to this open-source project.

**Comment by apu52** [comment]
@divyasaahithya u are assigned this time . but from next time please try to use the issue templates to raise your issues
