### ISSUE TITLE
[Bug]: some images are not displayed on your live website. 

### ISSUE THREAD

**Issue by Sadab-Hussain** [apu52/Travel_Website#1461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some images on the live website are not being displayed as expected. The images work correctly in development but fail to load when the site is live. This issue could be due to incorrect file paths, case sensitivity, broken image links, incorrect file formats, or file permission issues on the server.

This problem only affects certain images, while others load normally.

### Expected behavior

All images on the website should be displayed correctly when the site is live, just as they do during development. Each image should load seamlessly according to the specified file paths, showing the intended visuals without any missing or broken image icons.

### Add ScreenShots

You can check the attached screenshot here.( header, header  in hero page)

![image](https://github.com/user-attachments/assets/f2f492fb-d2cc-4f57-a523-f2d5b5a34bdc)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush786hack** [comment]
Hi @Sadab-Hussain! Thanks for opening this issue. We appreciate your contribution to this open-source project.

**Comment by apu52** [comment]
![image](https://github.com/user-attachments/assets/ffe0ff98-bddd-4a4e-b9bd-44c5d5b873b2)

all of the images are correctly showing in the live deployed link . so sorry to close this issue for now . But u can still make new issues on which u want to work on
