### ISSUE TITLE
[Bug]: Improvement needed for button appearance on home page

### ISSUE THREAD

**Issue by rakeshprogramer** [apu52/Travel_Website#1463]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

Problem: The three buttons on the home page do not look good, though the hover effect is perfect.

### Expected behavior

 Buttons should be visually appealing.

### Add ScreenShots

![Screenshot (274)](https://github.com/user-attachments/assets/b4a07aea-c0ba-42bd-b7c3-79accde8a848)
![Screenshot (275)](https://github.com/user-attachments/assets/f638cf16-54f5-4272-8f83-3b4fb5c60a7d)
![Screenshot (276)](https://github.com/user-attachments/assets/a5246606-0b9c-4240-89df-f3eac5717e44)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@ssyy21 i have assigned u , u can start working , please try to submit your PR within 11.30 pm otherwise i can't be able to review the PR & merge it
