### ISSUE TITLE
[Bug]:web page linked with View button not responding

### ISSUE THREAD

**Issue by rohit-debnath24** [apu52/Travel_Website#1464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The web page containing probably the google map location linked with the View [Button] in the front page top left (https://apu52.github.io/Travel_Website/) not loading putting up a error screen 

### Expected behavior

google map should have been poped out to pin a particular location

### Add ScreenShots

![webpage error](https://github.com/user-attachments/assets/4b39ef4a-3e3e-4cc8-b8d4-72fc66e5430c)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@rohit-debnath24 u are assigned . to integrate g maps with the project is really a great work to do . Carry on . If u face any problem feel free to reach out me
