### ISSUE TITLE
[Bug]: No redirection to home page via about us page

### ISSUE THREAD

**Issue by sindhuja184** [apu52/Travel_Website#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to me redirection from about us page to the home page is a mandatory feature that every user wants to see on our website.

### Expected behavior

A button or an hyperlink is to be established such that the page is redirected from the about us page to the home page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/641ff48b-c345-4ed3-b819-ef76b9059984)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Preethii-R** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.

**Comment by apu52** [comment]
@sindhuja184 this about us navbar or home page redirecting thing is already present & already been assigned to another previous  issue . So sorry to close this issue for now  But u can still make new issues on which u want to work on
