### ISSUE TITLE
[Bug]: Light/Dark Mode Toggle Button is Misaligned

### ISSUE THREAD

**Issue by ShrutiDesai7** [apu52/Travel_Website#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Light/Dark mode toggle button is currently positioned outside of the navbar on the website. This affects the user experience and layout.

### Expected behavior

I propose adjusting the CSS to ensure the toggle button stays within the navbar, regardless of screen size or layout changes.
I can work on fixing this by making sure it aligns properly in both desktop and mobile views.

Please assign to me.

### Add ScreenShots

![Screenshot 2024-10-08 184245](https://github.com/user-attachments/assets/7675f488-db15-43ed-a1d6-67c506a20249)

### On which device are you experiencing this bug?

windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by DarakshanSaara** [comment]
Can I work on this project? Could you assign this to me?

**Comment by Techbarsha** [comment]
Could you please assign to me the task? I believe it will improve the visual appeal of the project.

**Comment by apu52** [comment]
@ShrutiDesai7  this issue has already been raised as a n issue previously & already been assigned . sorry to close this issue . but u can still make new issues on which u want to work on
