### ISSUE TITLE
[Bug]: Navbar size is too big for small screens and all the buttons aren't showing up

### ISSUE THREAD

**Issue by ShaliniKashyap717** [apu52/Travel_Website#1468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my desktop, navbar size is showing too big. I feel like it should be in a certain ratio. that would be more appealing for the users if it doesnt take too much space. Also, the end buttons aren't even showing up in my screen. So I want to make it look alright for all screen sizes using my css skills.. furthermore, the 25000 guides, 20000 tours nd destinations block is with very less padding. I want to make this block look more elegant by adding proper margin and padding

### Expected behavior

I want to work on navbar so as to make it in an appropriate dimension (smaller than what it is right now for smaller screens like my desktop) and add padding to the blocks written by the names of guides, tours and destinations.

### Add ScreenShots

<img width="956" alt="tour_gui" src="https://github.com/user-attachments/assets/c156eb33-5d80-4ac4-bd46-4f16aaa9f4ba">

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Preethii-R** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.

**Comment by MD-IRFAN-RAJ** [comment]
Please assign this to me . @apu52

**Comment by ShaliniKashyap717** [comment]
please add level label too. i have started working on this issue

**Comment by apu52** [comment]
> please add level label too. @apu52 i have started working on this issue

@ShaliniKashyap717 u can start working . I will label the issues as per my review of the PR
