### ISSUE TITLE
[Bug]:  When I click on Google icon on login and registar page it's shows error 

### ISSUE THREAD

**Issue by ayushbhjh** [apu52/Travel_Website#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the login and registration pages, clicking the Google icon intended for third-party authentication triggers an error. This issue arises because the Google OAuth functionality has not been properly set up or linked to a valid authentication flow. As a result, the user is either redirected to a broken page or an error message is displayed, preventing them from signing in with Google. This issue is critical for users who rely on social login options.

### Expected behavior

When a user clicks on the Google icon on the login or registration page, they should be seamlessly redirected to the Google OAuth authentication flow. After successfully authenticating with their Google account, the user should be redirected back to the application, automatically logged in or registered, and granted access to the appropriate page (e.g., home or dashboard) without any errors. The social login process should be smooth and error-free

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-10-09 at 1 51 23 AM" src="https://github.com/user-attachments/assets/9f262064-d4e2-4b3e-8f5d-fdd2c317974a">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
