### ISSUE TITLE
Feature_Request : Attractive footer

### ISSUE THREAD

**Issue by vermaanurag1532** [apu52/Travel_Website#147]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by vermaanurag1532** [comment]
please assign it to me

**Comment by apu52** [comment]
what is this?? on which topic you want to work on???
There is no details
