### ISSUE TITLE
Add Redirect Functionality to Website Logo in membership page

### ISSUE THREAD

**Issue by misbahqadri** [apu52/Travel_Website#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I click on the logo in the header, it does not redirect me to the home page as expected. 
![image](https://github.com/user-attachments/assets/6dbb54f5-b754-4e2a-bc40-e63c37dfd97d)

### Expected behavior

Clicking on the logo should redirect the user to the home page.

### Add ScreenShots

Clicking on the logo does not result in any action.

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Preethii-R** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.

**Comment by misbahqadri** [comment]
@apu52  I’ve made the changes. Please add the 'Level' tag so I can push.
