### ISSUE TITLE
[Bug]: Dropdown Menu for Services Not Displaying Properly in Membership Page

### ISSUE THREAD

**Issue by misbahqadri** [apu52/Travel_Website#1473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I click on the "Services" menu, the dropdown does not display clearly, showing a white background that makes the text hard to display.
![image](https://github.com/user-attachments/assets/e9698ba9-567b-4f94-9d2e-0b8cd3bbcd4d)

### Expected behavior

The dropdown should have a contrasting background color to ensure the text is easily readable.

### Add ScreenShots

The dropdown menu appears with a white background, making it difficult to see the text.

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
