### ISSUE TITLE
Title Not Visible and Text of Contact Us

### ISSUE THREAD

**Issue by Kavish-Paraswar** [apu52/Travel_Website#1474]
The title in not visible  , alignment of the title should be changed .
![image](https://github.com/user-attachments/assets/0ffd876c-abec-4108-99d1-7a1475937269)

The contact us is not visible , adding that 
![image](https://github.com/user-attachments/assets/d59a59fd-b7fa-4cda-8867-d76354665153)

**Comment by JagritiChopra** [comment]
I will like to work for this issue under gssoc 2024 ext tag. 
Can you pls assign it to me?

**Comment by JagritiChopra** [comment]
I know how to fix this☺

**Comment by ayush786hack** [comment]
I will like to work for this issue under gssoc 2024 ext tag.
Can you pls assign it to me?

**Comment by apu52** [comment]
@Kavish-Paraswar I think u have made this issue in a wrong repo ,
As far as I can see this issue belongs to canvas-editor So try to make the issue in the canvas-editor repo 
Sorry to close this repo

**Comment by Kavish-Paraswar** [comment]
i am sorry for this mistake
