### ISSUE TITLE
[Feature Request]: Make text show up on hovering over a button

### ISSUE THREAD

**Issue by LNischala** [apu52/Travel_Website#1476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature allows text to appear when a user hovers over a button, providing additional information or context about the functionality of the button

### Use Case

Some of your website's buttons, such as the chat button, scroll up button, and dark to light theme switching buttons, can be accompanied by their respective text labels when hovering.

### Benefits

Improved user guidance
Engaging user experience

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [x] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.

**Comment by apu52** [comment]
@LNischala good issue
