### ISSUE TITLE
[Bug]: The package page not displaying the components properly

### ISSUE THREAD

**Issue by shivi13102** [apu52/Travel_Website#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After clicking on the "Package" menu on the home page, a new page opens, but the navbar is not configured properly, and the images are also not displayed.

### Expected behavior

I wanted it to display multiple packages like family package, solo trips package, etc with the pricing, and a proper navbar to go back to the home page.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/184acd78-8921-4805-a3ec-db29ad90dd09)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by shivi13102** [comment]
So I can start working on it, right?

**Comment by apu52** [comment]
@shivi13102  this issue is already present in the repo previously & already been assigned to another contributor  . sorry to close this issue . but u can still make new issues on which u want to work on
