### ISSUE TITLE
 Add Search Bar to Contributors Page

### ISSUE THREAD

**Issue by priyachau12** [apu52/Travel_Website#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature request is to add a search bar to the contributors page to make it easier for users to find specific contributors. It will improve usability by allowing users to quickly locate contributors by name or username without manually scrolling or changing the page through the entire list.

### Use Case

This feature will be particularly useful for large projects with many contributors. Users and contributors will be able to navigate and connect with specific members more efficiently, enhancing community interaction and engagement.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1dc89065-b236-4d0d-a41d-395d65a37c6b)

![image](https://github.com/user-attachments/assets/0bc49590-bcbd-437c-b5b4-9f6676d95ac1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by DARSHANITRIPATHI** [comment]
Please assign this issue to me
