### ISSUE TITLE
[Bug]: Missing Navigation Bar to About Us Page

### ISSUE THREAD

**Issue by DivyaJyothi9** [apu52/Travel_Website#1479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I noticed that the About Us page of the project currently lacks a navigation bar, while all other pages have one. Adding a navigation bar to the About Us page will enhance the user experience by providing consistent navigation throughout the site.

I would like to contribute. Kindly assign me this issue.

### Expected behavior

- Implement a navigation bar on the About Us page that matches the style and functionality of the existing navigation bars on other pages.
- Ensure that all links are functioning correctly and direct users to the appropriate sections.

### Add ScreenShots

![Screenshot (317)](https://github.com/user-attachments/assets/c14b59b4-29b2-4e4d-89d6-64b235179864)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by DivyaJyothi9** [comment]
@apu52 Kindly assign me under gssoc-extd, hactoberfest2024 and level.
Thank you ,ma'am!!

**Comment by apu52** [comment]
@DivyaJyothi9 this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
