### ISSUE TITLE
[Bug]: Improper display of some sections

### ISSUE THREAD

**Issue by Nivesh2003** [apu52/Travel_Website#1481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot 2024-10-09 210015](https://github.com/user-attachments/assets/880cf04f-e306-4fc9-af7c-9965e4c1d8e3)
The packaging list section is a bit cut from below , i am new to contributing so i was thinking maybe i can do something little like this 

### Expected behavior

It should display correctly without any cuts.
I am a beginner and want to contribute please guide me

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Nivesh2003** [comment]
Guys i am totally new so help me if you can

**Comment by apu52** [comment]
@Nivesh2003 I think there is no cut in the website , But Maybe it happens to you for maybe due to your screen width . 
But sorry to close this issue for now .
But as u are a beginner try to make new issues on which u want to work on & if u need any type of help , feel free to reach out me
