### ISSUE TITLE
[Bug]: Improvement of footer Section

### ISSUE THREAD

**Issue by coderajawat** [apu52/Travel_Website#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A few UI-related issues that could be improved in the footer section:

1. **Inconsistent Spacing:** Adjust margins/padding for even spacing between sections.
2. **Misaligned Select Language:** Align it better with other content.
3. **Map Overlap:** Resize or reposition the Google map to avoid overlapping with text/icons.
4. **Low Contrast Text:** Improve the visibility of the copyright text.
5. **Cluttered Social Media Icons:** Space them out or resize for a cleaner look.
6. **Oversized Visitor Box:** Reduce the size of the "VISITORS" box.
7. **Mismatch in language box design:** Style the language dropdown to match the footer’s theme.

### Expected behavior

The expected behavior would be:

1. **Consistent spacing:** Sections will look well-organized and easier to navigate.
2. **Aligned language dropdown:** The "Select Language" box will fit smoothly with other elements, creating a balanced design.
3. **No overlaps:** The map will be clear, with no elements overlapping each other.
4. **Readable text:** The copyright and other texts will be easier to read.
5. **Neatly arranged social icons:** Icons will have proper spacing for a cleaner look.
6. **Appropriately sized visitor box:** The visitor box will be smaller, fitting in with the rest of the layout.
7. **Styled language box:** The dropdown will match the overall theme, making the design cohesive.

### Add ScreenShots

![Screenshot 2024-10-10 112226](https://github.com/user-attachments/assets/41ac8613-d438-41de-839e-28b6f160368c)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by coderajawat** [comment]
Hi! I am GSSOC extended 2024 contributor. Please assign me this issue. I would love to work on it.

**Comment by CowTheGreat** [comment]
Hi! I am GSSOC extended 2024 contributor. Please assign me this issue @apu52 . I would love to work on it.

**Comment by swati-204** [comment]
Hi! I am a GSSOC extended 2024 contributor. Please assign me this issue @apu52. I want to work on it .

**Comment by ssyy21** [comment]
@apu52 please assign me this task under IEEE open source week.

**Comment by apu52** [comment]
@ssyy21 i have assigned you , now u can start working on this issue
