### ISSUE TITLE
[Feature Request]: Strong password recommendation

### ISSUE THREAD

**Issue by Ishika-Gupta06** [apu52/Travel_Website#1484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

User will be asked to create a strong password with some suggestions.

### Use Case

Better UX and enhance security

### Add ScreenShots

![Screenshot 2024-10-10 121736](https://github.com/user-attachments/assets/79fff15b-9bf6-41f8-af22-e6a9d9c51895)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Ishika-Gupta06** [comment]
@apu52 please assign me this under GSSOC-EXT, HACKTOBERFEST & LEVEL-1,2,3

**Comment by Preethii-R** [comment]
@apu52 Could you please assign me this under GSSOC-EXT, HACKTOBERFEST ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this task.
