### ISSUE TITLE
[Feature Request]: To check the format for gmail while registering

### ISSUE THREAD

**Issue by Ishika-Gupta06** [apu52/Travel_Website#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Avoid user the register with misspelling in gmail & even check the format of gmail

### Use Case

Better user experience 

### Add ScreenShots

![Screenshot 2024-10-10 122208](https://github.com/user-attachments/assets/11162fe6-12db-410e-aa1e-8a9b178171fd)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Ishika-Gupta06** [comment]
@apu52 **please assign me this under GSSOC-EXT, HACKTOBERFEST & LEVEL-1,2,3**

**Comment by Preethii-R** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.
