### ISSUE TITLE
[Bug]: The size of the navbar seems off, and the red line that appears when we click doesn’t quite fit the design.

### ISSUE THREAD

**Issue by jhuma20** [apu52/Travel_Website#1486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I noticed the navbar is showing up too big. It would look better if it followed a certain ratio. Also, the red line that appears when we click doesn't seem to fit well maybe we could try a different style

### Expected behavior

I would like to work on the navbar and make some adjustments. I’ll implement a proper size ratio and improve the design, including tweaking that red line when we click.

### Add ScreenShots

<img width="960" alt="contribution" src="https://github.com/user-attachments/assets/59ae65d4-c2bf-4b8f-a6d7-6204fc4e2e22">

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@jhuma20 I think the navbar size issue is already been assigned to another contributor previously . So u can just work on the red line & also maybe on some other design of the navbar

**Comment by jhuma20** [comment]
Thanks for the update! I'll focus on the red line issue and explore some design improvements for the navbar.
