### ISSUE TITLE
[Bug]: Lag in loading animation of the website causing delay

### ISSUE THREAD

**Issue by Aditi2k5** [apu52/Travel_Website#1488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On visiting link of website the loading animation has a lag present 

### Expected behavior

Preferably smoother loading animation

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
