### ISSUE TITLE
[Bug]: issue with packages 

### ISSUE THREAD

**Issue by Mehak-Parveen** [apu52/Travel_Website#1490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is an issue with packages in website

### Expected behavior

the elements should be inline

### Add ScreenShots

![Screenshot 2024-10-11 074858](https://github.com/user-attachments/assets/f14ddb49-fb79-4c50-bfb7-6fd5a41acc6d)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by nigam-divyanshi-dev** [comment]
please assign this to me under gssoc and hacktoberfest tag..so that i can contribute...

**Comment by apu52** [comment]
@Mehak-Parveen this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
