### ISSUE TITLE
[Feature Request]: Improving Topdeals page

### ISSUE THREAD

**Issue by nksmanya** [apu52/Travel_Website#1491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The topdeals page does not have favicon. nav bar nor the footer section. 
I would like to work on this issue. 
Please assign this issue to me @ap

### Use Case

This feature makes sure that the page follows the same structure as the other pages in the website.

### Benefits

Improving the Topdeals Page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c4915fb7-fde6-402c-9527-a994040955ea)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by avishek999** [comment]
hey, i would like to work on task please assign me this task i can add favicon. nav bar and footer section.
