### ISSUE TITLE
[Bug]: Missing logo on the nav bar

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [apu52/Travel_Website#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/8f463689-4f9c-4eb0-ba81-38d042168c85)
i would like to add logo on the nav bar also..
please assign me with the required labels as per gssoc'24 extended program

### Expected behavior

nav bar looks more neater

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Preethii-R** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.

**Comment by ayush786hack** [comment]
Could you please assign me this under GSSOC 2024 ? I am confident that I can provide a strong solution and would appreciate the opportunity to work on this issue.
