### ISSUE TITLE
[Feature Request]: Enhancing Plan a trip page

### ISSUE THREAD

**Issue by Arveti-likhitha** [apu52/Travel_Website#1493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The tabs in the nav bar do not direct to the respective pages. I would like to make changes to make sure they are navigating to the correct pages.
Also in the trip suggestion section the cards move even if there are no further cards containing information. Changing them such that navigation stops after it reaches the last suggestion card would look good.

### Use Case

Improves user experience and easy navigation through the application.

### Add ScreenShots

![Screenshot 2024-10-11 103537](https://github.com/user-attachments/assets/46ee3c72-f2aa-4b86-b192-09f669b0e817)
![Screenshot 2024-10-11 103942](https://github.com/user-attachments/assets/13907725-2c50-4eec-8daf-e88b3dd83933)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

Please add the tags: hacktoberfest-accepted, hacktoberfest, gssoc-ext

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
