### ISSUE TITLE
[Bug]: In Testimonials section, the photo of Broccoli is not laoding.

### ISSUE THREAD

**Issue by adiprem73** [apu52/Travel_Website#1494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Testimonials section, the profile photo for broccoli is not loading. I would like to request you to assign me to fix this issue.

### Expected behavior

There are three testimonials there and two of them are showing profile picture while on isnt.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e3669feb-b072-41bd-8545-5952f0e6a46e)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by shivisingh25** [comment]
@apu52 Hey there I would like to work on this issue, the solution involves addition of . in the image file path, creating a PR straightaway.

**Comment by himanshujainsanghai** [comment]
Hii ,  I am interested in contributing to this project, specifically to this part. However, after reviewing the provided code, I was unable to locate any file or folder related to Testimonials section. Could you kindly guide me on where I might find the relevant code or if this part is yet to be implemented!

**Comment by apu52** [comment]
@adiprem73 this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
