### ISSUE TITLE
[Bug]: Testimonial Third Card Image is not loading.

### ISSUE THREAD

**Issue by sneha056** [apu52/Travel_Website#1496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Website is having an issue while loading the Image for testimonial third card. I have checked and I have investigated and found the root cause behind this. And was able to fix the issue for my system. @apu52 please assign me this task. ( #1496 )
![Screenshot 2024-10-11 173840](https://github.com/user-attachments/assets/dc81d06e-a54a-4b51-bb67-5081986c8078)
![Screenshot 2024-10-11 174841](https://github.com/user-attachments/assets/c4ea5220-aab0-480c-8939-3a3467cb992f)

### Expected behavior

The Third Image for the testimonial should load as per the other two.

### Add ScreenShots

![Screenshot 2024-10-11 173840](https://github.com/user-attachments/assets/d37d9a50-d064-411e-9b99-7cb00d867815)
![Screenshot 2024-10-11 174841](https://github.com/user-attachments/assets/53fe281c-d7f2-4094-a907-18b3b9577978)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by MD-IRFAN-RAJ** [comment]
@apu52 please assign this issue (#1496) to me.

**Comment by apu52** [comment]
@sneha056  this issue has already been solved . sorry to close this issue . but u can still make new issues on which u want to work on
