### ISSUE TITLE
[Bug]: deal/ card proper UI is not maintained

### ISSUE THREAD

**Issue by sneha056** [apu52/Travel_Website#1497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In top deals page, bottom middle card UI is not matching with other cards. 
![Screenshot 2024-10-11 175756](https://github.com/user-attachments/assets/9517fc93-cfc1-4e2e-98c3-61d987712970)
Here's the attached screenshot. @apu52  kindly assign me task (#1497 ) so that I can start working on this.

### Expected behavior

All the cards image alignment should be in the proper format as in 1 row card.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.

**Comment by ssyy21** [comment]
@apu52 Kindly assign me this task under IEEE open source week, Thank You.

**Comment by apu52** [comment]
@ssyy21 I have assigned u , now u can start working on this issue.

**Comment by ssyy21** [comment]
@apu52 I think this issue is already solved as the UI of bottom card is matching with other cards on the website.

**Comment by apu52** [comment]
@ssyy21 okk then I am closing this issue
