### ISSUE TITLE
[Feature Request]: adding storage features to the 2 forms. and improving the UI

### ISSUE THREAD

**Issue by trahulprabhu38** [apu52/Travel_Website#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- improving UI for the feedback form,
- adding backend functionality to save the data in local storage.

@apu52 can you please assign me this task.

### Use Case

<img width="1190" alt="Screenshot 2024-10-12 at 12 21 01 AM" src="https://github.com/user-attachments/assets/006194a6-2b62-430b-bb77-674c90c09a4f">
<img width="796" alt="Screenshot 2024-10-12 at 12 21 07 AM" src="https://github.com/user-attachments/assets/f2c7af33-5ae3-4b10-a957-7654e18437e0">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@T-Rahul-prabhu-38 I think I have assigned u 3 issues ,so please try to work on the issues separately & one by one in separate PR

**Comment by T-Rahul-prabhu-38** [comment]
yes yes , ill be doing seperate PR's
