### ISSUE TITLE
Adding Hotels and places list in a trip

### ISSUE THREAD

**Issue by SaiSravanthiChandana** [apu52/Travel_Website#15]
By adding all the places to visit in that certain city by adding 3 4 cities as example and scrollable cities and the hotels available in that city

**Comment by DarshSohaliya** [comment]
I would like to contribute on this issue

**Comment by apu52** [comment]
@SaiSravanthiChandana Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
