### ISSUE TITLE
[Bug]: Forgot password is not working

### ISSUE THREAD

**Issue by DeeyaMeena** [apu52/Travel_Website#1500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when we are sign in our account in your tourguide incase we forgot our password and then we go to forgot password option and when we click on forgot password it is not returning anything it is not working

### Expected behavior

you provided tourguide a forgot password option but you didn't provided it's javascript code so i want you to provide it it's code so it can work properly 

### Add ScreenShots

![Screenshot 2024-10-12 095615](https://github.com/user-attachments/assets/b5e88b3e-af61-406e-b649-70bd35e7974b)
in this in login section in forgot password option

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by DeeyaMeena** [comment]
> Hi @DeeyaMeena! Thanks for opening this issue. We appreciate your contribution to this open-source project.

thanks alot

**Comment by ishivansmishra** [comment]
Hi, I'd like to work on fixing this issue. Could you please assign this issue to me?
