### ISSUE TITLE
[Bug]: Packages.html

### ISSUE THREAD

**Issue by GarvitaSapra** [apu52/Travel_Website#1501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Need to update the webpage for packages https://apu52.github.io/Travel_Website/packages.html

### Expected behavior

It should show images as shown in the layout instead of showing alt text and also need to fix the header

### Add ScreenShots

![{63BE3B65-88E5-416B-95FE-FCF7177B489F}](https://github.com/user-attachments/assets/d2cbbb7b-88e7-40a3-acad-dd6f99e14334)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by ishivansmishra** [comment]
Hey, I'd like to work on fixing this issue. It seems like optimizing the index.html load time or addressing the alignment problem on mobile devices could improve the user experience. Could you please assign this issue to me?

**Comment by GarvitaSapra** [comment]
> Hey, I'd like to work on fixing this issue. It seems like optimizing the index.html load time or addressing the alignment problem on mobile devices could improve the user experience. Could you please assign this issue to me?

Hey it seems like you have misunderstood the issue raised here , its not bout the loading time or alignment problem , its about the packages page which is not displaying the right content (pictures) as supposed to on any device . And About the devices , i havent mentioned any issue with responsiveness to be precise.

**Comment by apu52** [comment]
@GarvitaSapra this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
