### ISSUE TITLE
Adding more pictures to grab viewers attention(UI enhancement)

### ISSUE THREAD

**Issue by Diya-Saha2005** [apu52/Travel_Website#1502]
Hello admin @apu52 ! I would like to make improvement in the picture section here, adding more pictures , some more interactions like while the viewer is viewing the section more pictures automatically scroll to show various destinations. 
Please assign me the issue of improvement and an early reply from your side will be appreciated. 
![image](https://github.com/user-attachments/assets/d9b5a7eb-5daf-411d-ba38-45aeecdf816c)

**Comment by apu52** [comment]
@Diya-Saha2005 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.

Sorry to close this issue for now .
