### ISSUE TITLE
[Feature Request]: Add Home Logo for Redirection on TopDeals Page

### ISSUE THREAD

**Issue by misbahqadri** [apu52/Travel_Website#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to propose adding a new Home logo on the TopDeals page that redirects users back to the home page when clicked. This will improve navigation and enhance user experience.

### Use Case

**Scenario:** When users are browsing the TopDeals page, they often want to return to the home page to explore more products or categories. Currently, they might have to rely on the browser's back button or scroll back to find a link, which can disrupt their shopping experience.

**Enhancement:** By adding a Home logo that redirects users back to the home page, we streamline their navigation. Users can easily return to the home page with a single click, improving the overall usability of the site.

### Benefits

- Improved navigation for users.
- Enhanced visual appeal of the TopDeals page.
- Increased accessibility to the home page.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6077e173-254e-45c0-b06f-72a19bc243b6)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Akshit1507** [comment]
@misbahqadri I would like to work on this issue. Please assign the label of level 1 to this issue and assign it to me !

**Comment by apu52** [comment]
@misbahqadri this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
