### ISSUE TITLE
[Feature Request]:Improvement in Homepage

### ISSUE THREAD

**Issue by shambhavipathak24** [apu52/Travel_Website#1508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to work on homepage. I would like to enhance homepage look.

### Use Case

By making homepage interactive to user.

### Benefits

Increase User interaction.
Visibility.
Responsiveness.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shambhavipathak24 what are the UI changes u want to add in the homepage can u please describe with the help of some prototype or SS/ description??
