### ISSUE TITLE
BUG : New video

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#151]
**Describe the bug**

hello All, 
There was a video in the "Watch our story" section. but somehow it got removed.

**Expected behavior**

#126 refer to the PR & make the same changes in this issue & make a new PR making the changes

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**
### 
### Those who want to work on this issue comment down with JWOC mentioned on it .

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by vishal2005025** [comment]
Please assign it to me under JWOC'2024.

**Comment by apu52** [comment]
@vishal2005025 You are assigned now. 
Welcome to the repo.
You can submit your PR within 2-3 days.

**Comment by vishapraj** [comment]
pls assign me under "JWOC"

**Comment by vishal2005025** [comment]
I am still working on this issue.

**Comment by vishal2005025** [comment]
sir , I have created pr .
please check..

**Comment by vishal2005025** [comment]
sir , I have created pr.
please check..

**Comment by vishal2005025** [comment]
sir , please check pr.
