### ISSUE TITLE
[Bug]: lagging issue

### ISSUE THREAD

**Issue by Anushaburnwal** [apu52/Travel_Website#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the homepage is not opening fast it is taking too much of time to open

### Expected behavior

there should not be lagging on the website as it is happening on the home paghe the starting page when we are clicking the website link

### Add ScreenShots

![SS](https://github.com/user-attachments/assets/5dadc5df-7e24-412c-ad17-fdeacacbea68)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Anushaburnwal his issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
