### ISSUE TITLE
[style] The copyright right is not placed at the bottom 

### ISSUE THREAD

**Issue by hadifarousheen** [apu52/Travel_Website#1511]
The copyright section should be placed at the bottom. It is not placed at the correct position. I want to fix this issue.
![Uploading Screenshot_20241013-170927_Chrome.jpg…]()

**Comment by B-Ayushi** [comment]
please assign me in this issue @B-Ayushi

**Comment by apu52** [comment]
@hadifarousheen Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.

Sorry to close this issue for now .
