### ISSUE TITLE
No hover effect on 2nd button of home page ie. plan a trip

### ISSUE THREAD

**Issue by sneha056** [apu52/Travel_Website#1512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @apu52 please assign me this task (#1512) so that I can start working on this.
https://apu52.github.io/Travel_Website/
At home page out of 3 button on 2nd button their is no hover effect .

### Expected behavior

As every button is having hover effect then 2nd one should also has the same hover effect

### Add ScreenShots

https://github.com/user-attachments/assets/90016730-3173-4e48-a320-bc6c1ed3d9a1

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by vaibhavrajharsh** [comment]
I can fix that

**Comment by sneha056** [comment]
Hey @apu52, I have raised PR kindly review it, if possible could you please label this issue with some level.
