### ISSUE TITLE
[Bug]: Issue with Navigation Links on "Rate Us?" Page Opening New Tabs

### ISSUE THREAD

**Issue by Nitheesha33** [apu52/Travel_Website#1513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the "Rate Us?" page of the website, when I attempt to navigate to other features using the hyperlinks in the navigation bar, each link opens a new webpage instead of staying within the same tab. This leads to multiple tabs being opened unnecessarily, which is not consistent with the expected behavior of navigation.

### Expected behavior

When clicking on hyperlinks from the "Rate Us?" page, I expect the navigation bar links to load the respective pages within the same tab, maintaining a seamless browsing experience without opening new tabs for each feature.

@apu52 please assign me this issue. I would like to work on it

### Add ScreenShots

https://github.com/user-attachments/assets/a4d6102c-7145-44f9-9080-d922011cfca2

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Nitheesha33** [comment]
@apu52 Please add a label with the appropriate level

**Comment by apu52** [comment]
> @apu52 Please add a label with the appropriate level

u can start working . I will label the issues as per my review of the PR
