### ISSUE TITLE
Warning :- Regarding Unassigned Issues and Missing Labels on Merged PRs  (GSSoC Extd Core Team)

### ISSUE THREAD

**Issue by Meetjain1** [apu52/Travel_Website#1517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Hi @apu52 

I hope this message finds you well. We, the **GSSoC Extended Core Team**, have observed that certain issues in your project have been left **unassigned for more than a week**, and some of the **merged PRs are missing appropriate labels**. These actions are crucial to maintain transparency and ensure smooth collaboration among contributors.  

As per the guidelines, project admins are expected to:  
1. **Assign issues promptly** to interested contributors.  
2. **Label merged PRs** appropriately to reflect their status with their proper labels as specified in gssoc-ext guidelines.

correct labels:
- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

### Suggested Change

We request you to take the necessary steps immediately to avoid any further escalations.  

Thank you for your understanding and cooperation.  

Best regards,  
GSSoC Extended Core Team

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Meetjain1 Thanks for reminding me & Sorry for the delay . But from now I am still working actively on both of my repos

**Comment by Meetjain1** [comment]
> @Meetjain1 Thanks for reminding me & Sorry for the delay . But from now I am still working actively on both of my repos

Great @apu52 👍
