### ISSUE TITLE
[Feature Request]: Navbar UI and alignment

### ISSUE THREAD

**Issue by shriyadindi** [apu52/Travel_Website#1518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to make changes with the existing navbar by enhancing the alignment and design , kindly assign me the task

### Use Case

This feature would enhance the UI of the navbar for smooth navigation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shriyadindi what are the changes u want to make in our website ?? like in the navbar UI ?? u can also drop here the description/ss/prototype video of the features

**Comment by shriyadindi** [comment]
@apu52 I would like to realign the elements and  make every element visible and if required would add a drop down menu for some elements, and  improve the styling of the navbar
![Screenshot 2024-10-20 142452](https://github.com/user-attachments/assets/fb7e7a14-2fa5-4790-811e-4d2ec8de9730)

**Comment by apu52** [comment]
@shriyadindi go for it  , go ahead with your changes

**Comment by shriyadindi** [comment]
@apu52 Done!

**Comment by shriyadindi** [comment]
@apu52 I've completed the task, please go through it.
https://github.com/apu52/Travel_Website/pull/1578
