### ISSUE TITLE
[Bug]: Image not inserted and alignment

### ISSUE THREAD

**Issue by TanviGandhotra** [apu52/Travel_Website#1519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/abbe67ae-2094-4e83-80d6-334d6365cd5d)
Image of thailand is not inserted.
![image](https://github.com/user-attachments/assets/6387b02d-37df-446b-b7a7-3b5baab81497)
and in above not proper alignment
@apu52 plzz assign me so i could correct it.well i have also contributed in this repo earlier also.I added those place u want to visit.so happy by again seeing this wonderfull project here.

### Expected behavior

it should be crrcted

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by nigam-divyanshi-dev** [comment]
please assign this to me under gssoc and hacktoberfest tag..so that i can contribute...

**Comment by apu52** [comment]
@TanviGandhotra please try to insert the image only under this issue 
As like in the 2nd alignment issue u have proposed has already been assigned to another contributor in another issue
