### ISSUE TITLE
[Bug]: Navigation Bar Missing on "Top Deals" Page

### ISSUE THREAD

**Issue by Deepanshi0019** [apu52/Travel_Website#1522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The website's navigation experience is inconsistent due to the absence of the navigation bar on the "About" and "Top Deals" pages. When users click on these links, they are redirected to pages that lack a navigation bar, preventing them from easily accessing other sections of the website or returning to the homepage.

Steps to Reproduce:

1. Navigate to the homepage of the website.
2. Click on the "Top Deals" link in the navigation bar.
3. Observe that the navigation bar is missing on the "Top Deals" page.
4. Repeat the process for the "About" link.

### Expected behavior

All pages should include the navigation bar to allow users to navigate seamlessly between different sections of the website, ensuring a consistent and user-friendly experience.

### Add ScreenShots/Videos

![Screenshot from 2024-10-16 17-46-09](https://github.com/user-attachments/assets/e5ffe854-eece-46ba-bf9d-1b5dfaa45093)

### Record

- [x] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by KanishkRaj-RAKA** [comment]
Hi @Deepanshi0019 i'm kanihk raj, can you assign me this issue

**Comment by Deepanshi0019** [comment]
@KanishkRaj-RAKA I am also a contributer

**Comment by apu52** [comment]
@Deepanshi0019 this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
