### ISSUE TITLE
[Feature Request]: Improve UI/UX the Accessible page 

### ISSUE THREAD

**Issue by Himanshu-kumar025** [apu52/Travel_Website#1523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In current website the accessible page UI is not good enough .I would like to work on this issue please assign me under GSSOC"24 and Hacktofest'24.
Thank you

### Use Case

This feature Improve the UI of  this Accessible page.

### Add ScreenShots/Videos

![accessible travel](https://github.com/user-attachments/assets/7368d37f-6ea1-4485-a42d-3ff32e0b04bd)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Himanshu-kumar025** [comment]
@apu52 Please assign me this issue I like to work on this issue under Gssoc'24 and Hacktofest'24 .

**Comment by apu52** [comment]
@Himanshu-kumar025 what are the changes u want to enhance in the UI of the pages like some description / ss/ video prototypes
