### ISSUE TITLE
[Feature Request]: Adding feedback button option

### ISSUE THREAD

**Issue by Aditijainnn** [apu52/Travel_Website#1526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/f6d8325f-3aed-4da1-b8a5-bbe4ca799be7)
Adding feedback/rate-us option in footer or navbar

### Use Case

assign this to me under gssoc ext and jhacktoberfest

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by naitikhoriya1** [comment]
You may assign this task to me .

**Comment by apu52** [comment]
@Aditijainnn Thee feedback option is already present there in the contact us section , So i don't think that the feedback button is not needed in the footer section now .
So sorry to close the issue for now,
But u can still make new issues on which u want to work on
