### ISSUE TITLE
'Book now' button is not clearly visible 

### ISSUE THREAD

**Issue by biswa2005** [apu52/Travel_Website#1529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The book now button is not clearly visible at first glance

### Expected behavior

It should be a very attractive color or design to eye catch the audience

### Add ScreenShots/Videos

> ![Screenshot_2024-10-18-09-18-05-732_com android chrome](https://github.com/user-attachments/assets/34ead59a-8dc3-444c-89f3-290c774f4874)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by biswa2005** [comment]
Please assign me this issue

**Comment by jaygupta18** [comment]
Hey @biswa2005 may you assign me this issue

**Comment by biswa2005** [comment]
please merge my pull request.

**Comment by biswa2005** [comment]
Please merge my pull request.

**Comment by biswa2005** [comment]
Please merge this pull request I change book now btn style to look attractive
