### ISSUE TITLE
[Feature Request]: Developing a new page for packages

### ISSUE THREAD

**Issue by shivenyadavs** [apu52/Travel_Website#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will build a new page for packages where it will contain a all the booking mechanisms

### Use Case

this will ease the booking and travel guides to reach the customers easily.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by shivenyadavs** [comment]
@apu52 please assign this to me

**Comment by apu52** [comment]
@shivenyadavs what are the changes u want to enhance in the UI of the pages like some description / ss/ video prototypes???

**Comment by shivenyadavs** [comment]
https://github.com/user-attachments/assets/4405054d-24c4-428a-95f9-d44ed63cdd23

**Comment by shivenyadavs** [comment]
@apu52 please check and let me know

**Comment by apu52** [comment]
> Untitled.video.-.Made.with.Clipchamp.mp4

great design ...just add some design matching with the UI like a dark mode toggle in the page 
I am assigning u the issue . go ahead with the PR
