### ISSUE TITLE
[Bug]: Check mail format while register

### ISSUE THREAD

**Issue by Ishika-Gupta06** [apu52/Travel_Website#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When users try to register by entering their email, there is no validation or improper validation of the email format. As a result, users are able to enter incorrect or improperly formatted email addresses, causing issues with registration.

### Expected behavior

When users enter their email in the subscription form:

The email should follow the standard format, i.e., username@domain.com.
If the email format is incorrect, an error message should appear, prompting the user to enter a valid email.
The form should not be submitted until a properly formatted email is entered.

### Add ScreenShots/Videos

![Screenshot 2024-10-20 200603](https://github.com/user-attachments/assets/a4e003b1-863f-4317-9c4f-ee80c8f7413e)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Ishika-Gupta06** [comment]
@apu52 assign me under GSSOC-EXT, HACKTOBERFEST, LEVEL-1,2,3

**Comment by apu52** [comment]
@Ishika-Gupta06 i have assigned you , just try to make separate Pr SEPARATELY  for both if the issues
