### ISSUE TITLE
[Bug]: In home section underline hover effect on plan a trip button is not coming in dark mode.

### ISSUE THREAD

**Issue by Mayukh69-gif** [apu52/Travel_Website#1549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the adjacent two buttons, Hover effect is visible but on plan a trip button it is not.

### Expected behavior

There should be a hover effect on plan a trip button.

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by muskiagrwal** [comment]
hi can you assign me this issue
