### ISSUE TITLE
[Bug]: There is some issue with the packages section

### ISSUE THREAD

**Issue by Nivesh2003** [apu52/Travel_Website#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The packages tab when clicked leads to this page ->
![Screenshot 2024-10-20 135215](https://github.com/user-attachments/assets/ff90e5f7-04b7-417d-961f-eec5dbed6330)
Now the issue maybe CSS file not properly linked or something else 

I see two different packages files in the codebase , the problem may be the linking of these double files for the same section

![Screenshot 2024-10-20 135229](https://github.com/user-attachments/assets/1034a1a1-741f-4b46-9423-ff399660c49f)

### Expected behavior

A single file should be there for the packages . I can try to link those properly till the packages page itself don't get renewed.

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
