### ISSUE TITLE
BUG: Dark theme not working

### ISSUE THREAD

**Issue by gitgoap** [apu52/Travel_Website#156]
# **Description of  the bug**
The dark theme button provided on the home page, when clicked is not working.

## **Expected behaviour**
It should turn on the dark mode when the dark theme button is clicked.

## **Video (Mandatory)**

https://github.com/apu52/Travel_Website/assets/117789470/f3f7c1d9-9edf-41a0-9157-880e4aee8f96

***Are you contributing under any open-source program ?***
JWOC 2024

**Comment by gitgoap** [comment]
Please assign me this issue under JWOC 2024!
Thanks!

**Comment by apu52** [comment]
@gitgoap I will assign you . But as you have already assigned to an issue . I will assign you after the completion of the previous PR

**Comment by gitgoap** [comment]
@apu52 Assign it to somebody else, I am currently not taking up any issue.

**Comment by prakharsingh-74** [comment]
> > @apu52 i would like to contribute on this issue. Assign me under JWOC
> 
> This issue is in waiting. you can make a new issue on which you want to work on

@apu52 I have asked you first for this issue to contribute. so, now please assign it to me

**Comment by apu52** [comment]
> > > @apu52 i would like to contribute on this issue. Assign me under JWOC
> > 
> > 
> > This issue is in waiting. you can make a new issue on which you want to work on
> 
> @apu52 I have asked you first for this issue to contribute. so, now please assign it to me

#112 this issue is already present

**Comment by prakharsingh-74** [comment]
> > > > @apu52 i would like to contribute on this issue. Assign me under JWOC
> > > 
> > > 
> > > This issue is in waiting. you can make a new issue on which you want to work on
> > 
> > @apu52 I have asked you first for this issue to contribute. so, now please assign it to me
> 
> #112 this issue is already present

Assign this issue to me
