### ISSUE TITLE
[Bug]: About US page is not redirecting 

### ISSUE THREAD

**Issue by Zubaida0113** [apu52/Travel_Website#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (483)](https://github.com/user-attachments/assets/e04ed853-fc7a-4bbd-a868-b4707aa09a0d)
![image](https://github.com/user-attachments/assets/1ae38bc0-2d84-47c7-b0c3-2716c6004856)

In About US page, after clicking the button there is no redirection to the home page.
![image](https://github.com/user-attachments/assets/d059e29b-5908-4c4b-b638-f0d987afc151)
I would like to work on this issue.

### Expected behavior

After fixing it the 404 error will be removed.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by CreativitySayan** [comment]
I can solve the issue of not found in the about page and fix the errors found in this page. If I can get the project assigned to me.

**Comment by apu52** [comment]
@Zubaida0113 yes yess , u can work on this issue under this issue's pr

**Comment by Zubaida0113** [comment]
I have fixed the other issues(various broken links) I have mentioned above. Please assign me the issue in the new PR #1613 so that I can push branch.
