### ISSUE TITLE
[Documentation Update]: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [apu52/Travel_Website#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

### Suggested Change

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@milansamuel609 ACTUALLU I THINK THE CONTRIBUTING.MD file is well structures . so sorry i can 't assign u this issue . u can still make new issues on which u want to work on
