### ISSUE TITLE
[Feature Request]:  Creating Site Map Page

### ISSUE THREAD

**Issue by VidhanThakur09** [apu52/Travel_Website#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This issue proposes the creation of a site map page for the project. A site map is a visual representation of the website's structure, making it easier for users to navigate and find the information they need. It will act as a centralized hub, providing a clear overview of all the available pages and their relationships.

### Use Case

- **User Navigation:** The site map will serve as a valuable tool for users to quickly locate specific pages or sections within the website.
- **Search Engine Optimization (SEO):** A well-structured site map can improve the website's visibility in search engine results by providing a clear path for search engines to crawl and index content.
- **Accessibility:** The site map will enhance accessibility for users with disabilities, as it offers a visual representation of the website's structure.

### Benefits

- **Improved User Experience:** A site map enhances user experience by making it easier for users to find their desired information.
- **Better Search Engine Rankings:** A well-optimized site map can boost the website's search engine rankings.
- **Enhanced Accessibility:** The site map improves accessibility for users with disabilities.
- **Clearer Website Structure:** The site map provides a clear visual representation of the website's structure, making it easier to understand and maintain.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by VidhanThakur09** [comment]
@apu52 can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by VidhanThakur09** [comment]
@apu52 Can you add level so that i can start working on this issue.

**Comment by apu52** [comment]
> @apu52 Can you add level so that i can start working on this issue.

u can start working . I will label the issues as per my review of the PR

**Comment by VidhanThakur09** [comment]
Sure, I'll get started on it.
