### ISSUE TITLE
[Feature Request]: Back to Top Button

### ISSUE THREAD

**Issue by AyutheCoder** [apu52/Travel_Website#1571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding Back to Top button will enhance the website.

### Use Case

It will enhance the website features

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@AyutheCoder the back to top button is already present in this project . sorry to close this issue . but u can still make new issues on which u want to work on
