### ISSUE TITLE
[Bug]: Double scroll bar in the website

### ISSUE THREAD

**Issue by Shane-3** [apu52/Travel_Website#1572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A double scroll bar appears on the page due to overflow issues, likely caused by an extra layer or component setting an unintended scroll behavior. This creates a secondary scroll bar, which affects the overall UX by adding unnecessary space and redundant scrolling.

https://github.com/user-attachments/assets/487cf780-6a94-4ab5-9211-91c50cddae14

### Expected behavior

Only one scroll bar should appear, allowing users to scroll through the page without redundancy.

### Add ScreenShots/Videos

![image](https://github.com/user-attachments/assets/df78ac25-a769-45ce-afd1-b5ec0faaf901)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.

**Comment by Shane-3** [comment]
I have requested for PR. Kindly review it.

**Comment by Musaveershaik** [comment]
As per Rules i Requested first, please @Shane-3 try another one all the best
