### ISSUE TITLE
[Feature Request]:  Registration Page for Travel Website

### ISSUE THREAD

**Issue by Ananyashetty7** [apu52/Travel_Website#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a Registration Page to the Travel Website project using HTML, CSS, and JavaScript. This page will allow new users to create accounts on the website, offering a personalized experience by saving their information for future logins and preferences.

The registration page will include:

Input fields for Name, Email, Password, and Confirm Password
Optional fields for Travel Preferences (such as favorite destinations, types of travel, etc.)
A Submit button that saves the user data for future access

### Use Case

This feature will benefit the website by allowing users to register and save their details. For example:

New users can create profiles and save their favorite destinations.
Returning users can log in to see personalized recommendations based on their preferences.

### Benefits

Adding a registration page would:

Increase user engagement by personalizing the user experience.
Allow travelers to revisit the website and access stored preferences easily.
Provide a more professional and interactive interface for the travel website.

### Add ScreenShots/Videos

i will do it and add it directly

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Ananyashetty7** [comment]
Do i need to give the screen shots ?

**Comment by apu52** [comment]
@Ananyashetty7 a registration + login page is already present in the repo . So can u add some more features into it ??
if yes , then tell me what are the features u wan to add
Then I will assign u the issue

**Comment by apu52** [comment]
> Do i need to give the screen shots ?

@Ananyashetty7 yess that will be better
