### ISSUE TITLE
overall styling of the rating page as right now its very basic (Feature_Request)

### ISSUE THREAD

**Issue by Hansawani** [apu52/Travel_Website#159]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@Hansawani Please fill up the details properly what features you want to add. 
Otherwise I will be not able to assign this issue

**Comment by Hansawani** [comment]
The rate-us page is very basis and plain and it requires styling so that it is visually appealing to the users. I will add a background image to the page, modify the ratings box, style the feedback page a little and also add the navbar to the rate-us page too so that users can go from that page to others too.

**Comment by apu52** [comment]
> The rate-us page is very basis and plain and it requires styling so that it is visually appealing to the users. I will add a background image to the page, modify the ratings box, style the feedback page a little and also add the navbar to the rate-us page too so that users can go from that page to others too.

@Hansawani I have understood your issue. but from next time properly fill the issue templates

**Comment by apu52** [comment]
@Hansawani I have assigned you this time. you have 2-3 days to submit your PR

**Comment by Hansawani** [comment]
i have made a pr...please review the changes and give your feedback on whether anything more is to be done
