### ISSUE TITLE
login/signup page creation

### ISSUE THREAD

**Issue by Hansawani** [apu52/Travel_Website#16]
login/signup page for maintaining travel history and past bookings with the site. it can also store the personal info required if user makes a booking

**Comment by Sruti-sahini** [comment]
@apu52 Please assign me this issue.
I am from JWoC'24.

**Comment by apu52** [comment]
@Hansawani @Sruti-sahini Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
