### ISSUE TITLE
[Feature Request]: Consistent New Hover Effect on "Book Now" Buttons

### ISSUE THREAD

**Issue by shivam8112005** [apu52/Travel_Website#1611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature aims to introduce a consistent hover effect for all "Book Now" buttons throughout the application. Currently, the hover effects for these buttons vary across different pages, leading to a lack of uniformity and a potentially confusing user experience. A consistent hover effect will enhance the visual appeal and interactivity of the buttons, making them more engaging for users.

### Use Case

When a user browses the application and comes across a "Book Now" button, they expect a clear indication of interactivity. The current inconsistent hover effects may lead to confusion regarding whether the button is clickable. By applying a standardized hover effect, users will instantly recognize that they can interact with the button, leading to an improved booking experience.

For instance, if a user hovers over a "Book Now" button on the Packages page and notices the consistent hover effect that clearly highlights the button's interactivity, they are more likely to click on it and proceed with the booking.

### Benefits

Improved User Experience: A consistent hover effect enhances the usability of the "Book Now" buttons, making it clear to users that these buttons are interactive.

Increased Engagement: Users are more likely to click buttons that have clear visual feedback, potentially increasing booking conversions.

Brand Cohesion: A uniform hover effect across the application reinforces branding and creates a professional appearance, making the application feel polished and cohesive.

Enhanced Accessibility: By ensuring that hover effects are visually distinct and adhere to accessibility standards, we improve the overall usability for all users, including those with disabilities.

### Add ScreenShots/Videos

Before:

![Screenshot 2024-11-01 020146](https://github.com/user-attachments/assets/729e5012-1f8b-4de1-aa37-d02b1e60e70f)

After:
something like this

https://github.com/user-attachments/assets/99d3c0b5-31f5-4e9c-a4da-cccce61b9bb8

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@shivam8112005 I have assigned you both of the PR'S , PLEASE  try to complete this issues in both separate PR's

**Comment by shivam8112005** [comment]
ohkk i will complete both in different pr . by tomorrow
