### ISSUE TITLE
The issue with the other broken links in About Us page not being redirected 

### ISSUE THREAD

**Issue by Zubaida0113** [apu52/Travel_Website#1613]
The issue with the About Us page not being redirected to the home page has been solved but the services, testimonial and Contact Us page still can't be accessed from the About page. And from the Top deals subpage you can't be redirected to the About page, it shows an error. From the Rate Us subpage if you click on the About page you get redirected to the home page. Can I fix these above issues?

@apu52  I want to confirm can I move ahead working on this issue as discussed as a new PR.  

_Originally posted by @Zubaida0113 in https://github.com/apu52/Travel_Website/issues/1561#issuecomment-2449346828_

**Comment by apu52** [comment]
@Zubaida0113 I have assigned u the issue , but from next time please try to raise issue properly with the  issue templates from next time . anyways , all the best

**Comment by Zubaida0113** [comment]
@apu52 All the links on the navbar(home, about, services, testimonials, rate us, contact us, login/signup, view) are working fine, and the logo on the home page is now visible. I have also fixed the links to membership, plan a trip and the book now button on the home page with other buttons on the navbar. Please review this and let me know if there is anything you would like to mention.

**Comment by apu52** [comment]
@Zubaida0113 where is your PR??

**Comment by Zubaida0113** [comment]
@apu52 I have raised the issue; please check it.
