### ISSUE TITLE
[Documentation Update]: Want to add security policy 

### ISSUE THREAD

**Issue by Dipanita45** [apu52/Travel_Website#1615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Want to add security to protect the website against the harms 

### Suggested Change

Add security to the website 

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [ ] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Dipanita45 I have assigned you the issue .but can u please explain me what kind of Security u want to add in this repo like maybe with some of the examples
