### ISSUE TITLE
[Feature Request]: Pointer movement is not professional

### ISSUE THREAD

**Issue by skanarul8002** [apu52/Travel_Website#1617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i will make pointer movement as professional. So this is good for your website that enhance professional software development

### Use Case

Existing pointer movement is really agains with professional software development process.

### Benefits

Make website as professional website.

### Add ScreenShots/Videos

![image](https://github.com/user-attachments/assets/92af1e9a-a619-48ba-9e65-612602c97c81)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@skanarul8002 what kind of Cursor movement UI u want to add like can u give any example like with maybe some prototypes

**Comment by skanarul8002** [comment]
Ok sure @apu52. Basically standard Web applications follows a normal pointer movement there are no back dot blinking, no any things. That exists pointer movement is really different from other applications but your Web is good so need to make professional.
Also you see a snapshot, is this right? I think 🤔 this not good for applications.

So I want to make normal standard pointer that fit in your application.

**Comment by apu52** [comment]
Actually @skanarul8002 I understand your recommendations as a Cursor basic style , But as it's a totally open source project , i want to make it interactive & really don't want to make it a the basic cursor again.
So if u may have some other recommendations regarding this u can generally tell here

**Comment by skanarul8002** [comment]
@apu52 , if you will accept this task then i will give my best design and also look professional, design also.

**Comment by skanarul8002** [comment]
please mentor @apu52 , mention required levelno also. 
Thanks for accepting this issue.

**Comment by apu52** [comment]
@skanarul8002 I will add labels after reviewing your PR , don't worry about that , go ahead with the PR
