### ISSUE TITLE
Feature_Request: Add membership pricing table

### ISSUE THREAD

**Issue by Sneha6003** [apu52/Travel_Website#162]
**Is your feature request related to a problem? Please describe.**
Include membership pricing table

**Describe the solution you'd like**
I would like to add a pricing table for users to buy membership and avail offers. There will be three membership plans: basic, premium, ultimate.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/147996970/0467111e-00ac-44ff-b067-7b5fdf4838aa)

https://github.com/apu52/Travel_Website/assets/147996970/be16a058-1b6c-4135-8a06-c7d872ccaa62

***Are you contributing under any open-source program ?***

I would like to work on this issue under JWOC

**Comment by apu52** [comment]
@Sneha6003 Good issue make it functionable with a membership button in the home page . I want to say whenever user clicks The MEMBERSHIP button he will be redirected to the page

**Comment by Sneha6003** [comment]
@apu52 will do, Thank you!
