### ISSUE TITLE
[Bug]: Navbar styling is not consistent across all pages

### ISSUE THREAD

**Issue by shivam8112005** [apu52/Travel_Website#1626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar styling is not consistent across all pages. The font size, colors, and alignment of the navbar vary depending on the page, which creates a disjointed user experience. Some pages show different spacing or background colors in the navbar, making it appear unpolished.

### Expected behavior

The navbar should have a uniform style across all pages, with consistent font size, colors, alignment, and spacing. Users should experience a seamless transition when navigating from one page to another without any changes in the navbar's appearance.

### Add ScreenShots/Videos

![Screenshot 2024-11-05 005942](https://github.com/user-attachments/assets/ba357466-00d2-4374-a6ae-ee29f3747e2d)
![Screenshot 2024-11-05 010149](https://github.com/user-attachments/assets/b4a91f9a-c6f2-4b33-a0be-01820c3125d0)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by shivam8112005** [comment]
@apu52 should i work on this?

**Comment by apu52** [comment]
@shivam8112005 yess , u can work on this issue .

**Comment by jitendrasuthar1998** [comment]
@apu52 Hello Arpan, i would like to work on this issue as part of Kwoc. 
I have seen these issues related to navbar
1. Its content is not properly aligned.
2. On some pages, navbar options are different.
3. Light & dark theme toggle button not working or missing from some pages navbar.

@apu52 Can you assign me this issue and set a label for Kwoc? I will work on it, and resolve it one by one.

**Comment by apu52** [comment]
@shivam8112005 Thanks for figuring out this type  of issues in different pages , i am assigning u this issue , u can start working on it

**Comment by apu52** [comment]
@jitendrasuthar1998 u can continue with your pr
