### ISSUE TITLE
ADD A TRANSLATOR TOOL

### ISSUE THREAD

**Issue by Anchal-C09** [apu52/Travel_Website#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

A translator tool on a travel guide website enhances accessibility, improves user experience , and supports global reach by breaking down language barriers, offering instant translations, and making content more inclusive and culturally sensitive.

### Add ScreenShots/Videos

![translator image](https://github.com/user-attachments/assets/86f16e79-3b5b-45c7-8da3-275943ab836b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Anchal-C09 a google translator is already present in the website like u will find the translator in the footer option . So sorry to close this issue for now . But u can still make new issues on which u want to work on
