### ISSUE TITLE
[Bug]: Redirecting links of Services tab is not working, Logo not rendering on website and Light/Dark Mode inconsistency between Book Now page and website.

### ISSUE THREAD

**Issue by Zubaida0113** [apu52/Travel_Website#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Found a few Bugs:-

1. The logo of the website is not rendering on About Us, Topdeals, Rate Us, 
![Screenshot (533)](https://github.com/user-attachments/assets/3622482a-a3ba-4aa3-9785-0f5899e1b603)

2. Mismatch logo on Book now, plan a trip and membership page. Which one is the actual one - the logo with an orange background or the logo with blue earth? Please clarify.![Screenshot (523)](https://github.com/user-attachments/assets/c9210ea1-2302-4e81-9709-8cea3ec05102)
![Screenshot (534)](https://github.com/user-attachments/assets/6f447f22-9782-42df-92c0-cf2ab22f0650)

3. The Services tab section is not being redirected to their respective sub-services(Destinations, trip gallery, hotels and resorts, etc.) only. It is showing not found error because of the wrong file path.
![Screenshot (532)](https://github.com/user-attachments/assets/efd05fc6-ff1d-4f43-85b0-c247c3c1cb12)

4.  The light/dark mode of the Book Now page is not synchronized with the website(like if the home page is in dark mode, then the Book Now page remains in light mode).                                                                                                                                                                                        i
5. This is a feature bug:- The Login and view buttons on the navbar don't have the same design on different subpages. Like on the Home page, it looks like this:-
![Screenshot (534)](https://github.com/user-attachments/assets/337908db-9ac6-4704-8eca-4596b640379a)
But on other sections like About, packages etc it looks like this:-
![Screenshot (533)](https://github.com/user-attachments/assets/c346abe7-ea20-4b17-9f93-094cf64a9f11)

@apu52 So I want to work on the above issue. Please let me know your thoughts on this.

### Expected behavior

Here is the expected behaviour for each issue once fixed:

1. **Logo Rendering on Specific Pages:** The logo should appear consistently across all pages, including the About Us, Top Deals, and Rate Us pages. The logo should render correctly regardless of the page to provide a uniform look across the website
2.  **Logo Mismatch on Certain Pages**: Once clarified, either the orange background logo or the blue earth logo should be used consistently across all pages. The logo design should be identical on the Book Now, Plan a Trip, and Membership pages to avoid confusion and reinforce brand identity.
3. **Services Tab Redirection:** Each sub-service under the Services tab (such as Destinations, Trip Gallery, and Hotels and Resorts) should redirect to the correct page when clicked. The links should be updated to avoid "Not Found" errors, ensuring a smooth navigation experience for users.
4. **Light/Dark Mode Synchronization:** The Book Now page should synchronize its theme with the rest of the website. If the user is in dark mode on any page and navigates to Book Now, it should also display in dark mode, and vice versa. This synchronization should apply globally across all pages.
5. **Navbar Button Design Consistency:** The Login and View buttons should have a consistent design on all pages. The styling seen on the Home page should be applied across the About, Packages, and other sections, ensuring uniformity in button appearance across the website.

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by Zubaida0113** [comment]
Hey @apu52 there is an issue regarding the label request.
![image](https://github.com/user-attachments/assets/a6cff4cd-5deb-404d-b295-3c2020b3a557)
Can you check where the issue is? Because I have checked the guidelines for opening an issue, and there doesn't seem to be anything I missed. Did I?

**Comment by apu52** [comment]
@Zubaida0113 don't worry about the issue labels , I have already given that . this is a very good issue , try to fix it asap
