### ISSUE TITLE
[Feature Request]: add multilingual support to the website

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [apu52/Travel_Website#1632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add a multilingual dropdown box with multiple languages

### Use Case

increases scalability and reach of website

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@SanikaBhalerao1345 a google translator is already present in the website like u will find the translator in the footer option . So sorry to close this issue for now . But u can still make new issues on which u want to work on
