### ISSUE TITLE
[Bug]: FAQ dark-mode heading

### ISSUE THREAD

**Issue by saumyayadav25** [apu52/Travel_Website#1638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Title should be black or of darker color for better visibility

### Expected behavior

Title should be black or of darker color for better visibility

### Add ScreenShots/Videos

<img width="1434" alt="Screenshot 2024-11-12 at 5 06 50 PM" src="https://github.com/user-attachments/assets/29b7708e-8890-4133-987d-1df9de556a48">

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a  IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@saumyayadav25 i have assigned you . u can start working on it & submit a new pR
