### ISSUE TITLE
[Bug]: At feed.html page twitter logo update

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/Travel_Website#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in your website at Feedback page i have noticed that at the bottom the twitter logo should be updated one i want to update this .

### Expected behavior

twitter logo update 

### Add ScreenShots/Videos

![WhatsApp Image 2024-11-25 at 23 22 19_6bf531dd](https://github.com/user-attachments/assets/996de7b9-274e-40ef-a97e-86cd28486197)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a  IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by neeraj10122004** [comment]
@apu52 please assign this issue to me

**Comment by apu52** [comment]
@biswajit-sarkar-007 I have assigned you , u can start working on this issue .

**Comment by apu52** [comment]
> @apu52 I am interested in working on this issue

As this issue is already raised by another contributor , so I can't assign u this issue . But u can make new issues on which u want to work on
