### ISSUE TITLE
[Bug]: Navbar logo fix faq page  

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/Travel_Website#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

faq.html page  at Navbar logo img is showing error 

### Expected behavior

error img fix

### Add ScreenShots/Videos

![WhatsApp Image 2024-11-26 at 00 05 26_5c55e655](https://github.com/user-attachments/assets/a07fba21-9c6e-47c2-a220-493daabfa0a3)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a  IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by neeraj10122004** [comment]
@apu52 please assign this issue to me

**Comment by apu52** [comment]
@biswajit-sarkar-007 as u have already raised 2 issues , so sorry i have to close this issue for now

**Comment by apu52** [comment]
@neeraj10122004 welcome to the repo , As this issue will be closed , so please try to make new issues on which u want to work on so that it will be easier for me to assign u
