### ISSUE TITLE
[Feature Request]:  UI improve of trending.html page 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/Travel_Website#1651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in trending.html page i have seen that the UI is not good at all all the cards of this page there is lack of animation and hover effect i want to added some animation and hover effect to make this website more engagging.

### Use Case

make more engaging

### Benefits

make this website more engaging

### Add ScreenShots/Videos

https://github.com/user-attachments/assets/81e6d8ec-1f55-43f6-bf66-e94933d4ca6f

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a  IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@biswajit-sarkar-007 @biswajit-sarkar-007 as u have already raised 2 issues , so sorry i have to close this issue for now
