### ISSUE TITLE
[Feature Request]: To Add more locations in view page

### ISSUE THREAD

**Issue by neeraj10122004** [apu52/Travel_Website#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

currently there are only 3 locations in view page and i want to add more locations to it

### Use Case

it would be more informative to add more locations to map

### Benefits

better user experience

### Add ScreenShots/Videos

![image](https://github.com/user-attachments/assets/a6850c26-a7a4-437d-a13a-eef0c550d976)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a  KWOC 2024 contributor
- [X] I have starred the repository

**Comment by neeraj10122004** [comment]
@apu52 assign this issue to me under KWOC 2024

**Comment by apu52** [comment]
@neeraj10122004 u are assigned
