### ISSUE TITLE
[Bug]: spacing issue in navbar 

### ISSUE THREAD

**Issue by neeraj10122004** [apu52/Travel_Website#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

we can see a little spacing issue in navbar which appears when we hover over the Home it covers a part of the Tourguide title , it covers "." in the title

### Expected behavior

i think the spacing should be adjusted so that on hover over home it will not cover the "." in title

### Add ScreenShots/Videos

https://github.com/user-attachments/assets/27b6251b-139f-49f1-a0c4-e5509602a0c3

![image](https://github.com/user-attachments/assets/ee5d804f-ae2c-4f1f-898c-4ef4743bda92)
![image](https://github.com/user-attachments/assets/8e0ca107-895c-430d-b2ee-3cd2ff5decb9)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a  KWOC 2024 contributor
- [X] I have starred the repository

**Comment by neeraj10122004** [comment]
@apu52 assign this issue to me under KWOC 2024

**Comment by apu52** [comment]
@neeraj10122004 I have assigned 2 issues , Try to make 2 different PR's for both of the issues

**Comment by neeraj10122004** [comment]
ok @apu52 thank you
