### ISSUE TITLE
Not responsive for mobile devices.

### ISSUE THREAD

**Issue by Zenitssuu** [apu52/Travel_Website#166]
This website is not responsive for mobile devices, i want to make it responsive, align the web page to centre and make it's good looking with smooth transitions
![IMG_20240125_112103](https://github.com/apu52/Travel_Website/assets/154405878/a74f457f-215f-4279-a28e-194812b94311)

Please assign it to me under JWOC'24

**Comment by apu52** [comment]
Sorry @Zenitssuu this issue already exists in the repo. sorry to close your issue. But you can make any new issue
