### ISSUE TITLE
Too many BUG

### ISSUE THREAD

**Issue by tushargupta1504** [apu52/Travel_Website#167]
First of all the 
: the - top heading is not properly aligned the algnment is to be adj.
2. dark theme not working 
3. chat bot 
4. cantact image is not - loading in req. time

**Comment by apu52** [comment]
@tushargupta1504 The issues are really good . But some of them are already existed in the repo I will like to suggest you to use the Issue templates in the **"NEW ISSUE"** section to describe your issue. I am closing this issue. But you can make new issue on this topics

![image](https://github.com/apu52/Travel_Website/assets/114172928/47cdd4f1-3e19-443c-aab5-dcfbaadaa4da)
