### ISSUE TITLE
[Bug]: Subscribe Button Appearance is Disruptive

### ISSUE THREAD

**Issue by Atharvverma1234** [apu52/Travel_Website#1672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The appearance of the "Subscribe" button in the subscription section is not aligned with the rest of the design. The button looks disruptive and visually inconsistent.

### Expected behavior

The "Subscribe" button should be visually consistent with the design theme.
Have proper alignment and spacing.

### Add ScreenShots/Videos

![Screenshot 2024-12-28 175046](https://github.com/user-attachments/assets/a1a63987-d98e-421d-b544-0ad7daacf847)
![Screenshot 2024-12-28 175021](https://github.com/user-attachments/assets/8a2edccb-9b56-4803-8c32-5546837c9f25)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a  KWOC 2024 contributor
- [X] I have starred the repository

**Comment by Atharvverma1234** [comment]
Hello Sir, 
I would like to work upon this issue. Please assign it to me. Thank you

**Comment by apu52** [comment]
@Atharvverma1234 u are assigned , u can start working on this issue

**Comment by apu52** [comment]
@sanjeevnikumari as this issue has already been assigned to another contributor , so i can't assign u this issue , but u can still make new issues on which u want to work on
