### ISSUE TITLE
create/ enhance Review page

### ISSUE THREAD

**Issue by Sushwetabm** [apu52/Travel_Website#17]
Users can put their comments and reviews of  a particular place they have been to, or if they have purchased a particular package they can share their experience.

**Comment by prasukjain07** [comment]
Hey mentor, I am participation in JWoC and I want to contribute in this, please assign this issue to me.

**Comment by apu52** [comment]
@Sushwetabm @prasukjain07 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
