### ISSUE TITLE
Feature_Request : Add newsletter pop up box

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hello All,
I want to add some NEWSLETTER pop up box whenever any user opens the website 

**Describe alternatives you've considered**

 The news letter may contain 
- A logo with name "TOURGUIDE"
- A demo video/img
- some description about Tourguide
- A subscription button
- A Sell / discount offer (maybe hovering or attractive)

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/114172928/c4717725-6505-4ee8-874b-dfbf63f45f75)

Just a demo newsletter

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
### Those whoever comment first with JWOC mentioned in it  I will assign it to HER/HIM

**Comment by antilneeraj** [comment]
@apu52 Kindly assign it to me under JWOC.

**Comment by antilneeraj** [comment]
@apu52 just for clarification what do you mean by `A Sell / discount offer (maybe hovering or attractive)`
- The button ?  
- or The heading text ?

**Comment by apu52** [comment]
> @apu52 just for clarification what do you mean by `A Sell / discount offer (maybe hovering or attractive)`
> 
> * The button ?
> * or The heading text ?

a heading text

**Comment by apu52** [comment]
@antilneeraj You are assigned. you have 2-3 days to submit this issue's PR
