### ISSUE TITLE
BUG : Make the Website responsive in Desktop version

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#178]
**Describe the bug**

Hello All,
The webpage is not really responsive for all the Zoom portion in the webpage desktop version & also the color is not static in the background

**Expected behavior**

- I want to make the background in one static color or some animation design 
- & also make the website desktop responsive to all the zoom options
- & also make the background with some animation & maybe with some bgm music

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/114172928/f8d55496-a7e6-4bdc-984f-382e42b0e08c)
make the alignments ok

![image](https://github.com/apu52/Travel_Website/assets/114172928/8aecdf57-780d-41d8-a4be-f964941723c6)
Make the background well like this . it's a demo.

**Additional Context (Mandatory )**

### Those whoever want to work on this issue comments first with JWOC mentioned on it I will assign it to HER/HIM

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by SohanRC** [comment]
@apu52  I can try to make the website responsive. Please assign me under JWOC 2024.

**Comment by apu52** [comment]
@SohanRC You are assigned. You have 4 days to complete this issue properly
