### ISSUE TITLE
Currently, clicking 'Reviews' in the navbar redirects to the gallery section, but it should lead to a non-existing reviews section. I intend to create a dedicated reviews section for the redirection.

### ISSUE THREAD

**Issue by pranjal12-web** [apu52/Travel_Website#184]
**Is your feature request related to a problem? Please describe.**
When we click on reviews in the navbar, it redirected us to gallery section on the home page. Instead it should be redirected to reviews section which is not present. 

**Describe the solution you'd like**
So I would like to create a review section to which we can redirect on clicking reviews.

***Are you contributing under any open-source program ?***
Yes, under JWoC 24

**Comment by apu52** [comment]
@pranjal12-web That's a very good issue. I want to suggest you that make the REVIEW button in navbar as GALLERY & also make a separate page as REVIEW with some picture & interactive section

Nut we already have a feedback issue assigned. #145  So I am not closing this issue. if she fails to submit her PR , I will assign you this

**Comment by apu52** [comment]
@pranjal12-web you are assigned. there is already a feed back page there. make all of your changes there in your way make it interactive & also make the navbar changes as I have told you in the previous comment

**Comment by pranjal12-web** [comment]
Sure!!
