### ISSUE TITLE
BUG FIXING & ADDITION

### ISSUE THREAD

**Issue by ratnojitsaha** [apu52/Travel_Website#185]
1. SOMETHING WENT WRONG WITH THE HEADER AND FOOTER I ADDDED IN THE FIRST 3 PAGES NEED TO FIX THAT.
2. ALSO WANT TO ADD MORE 5-6 DESTINATIONS DEDICATEDD PAGES!

**Screenshots (Mandatory)**
![WhatsApp Image 2024-01-26 at 15 08 23_7d7d3b05](https://github.com/apu52/Travel_Website/assets/110903082/f3ab78df-7f85-43a7-8099-c5b1c92347f2)

![WhatsApp Image 2024-01-26 at 15 08 23_d344b82e](https://github.com/apu52/Travel_Website/assets/110903082/4a2169b1-c3e3-4184-b583-7ab38e2e94ee)

Please assign me under JWOC 2024

**Comment by apu52** [comment]
@ratnojitsaha Really good issue. Make "CHECK OUT" button also workful & also make all of the changes you have mentioned

**Comment by ratnojitsaha** [comment]
![Screenshot (516)](https://github.co/Travel_Website/assets/110903082/d630f7a8-d2b6-4098-97cf-6564e5e8c83b)
@apu52 It was working well enough after merge it seems messed up.
Should I work on making a complete different nav and footer or (look a like) , and not use the main styles.css sheet.
Please, Tell me what you think!

**Comment by apu52** [comment]
> ![Screenshot (516)](https://private-user-images.githubusercontent.com/110903082/300255989-ee4a32e5-2838-4514-a089-965666c2efdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzkxMjIsIm5iZiI6MTcwNjQzODgyMiwicGF0aCI6Ii8xMTA5MDMwODIvMzAwMjU1OTg5LWVlNGEzMmU1LTI4MzgtNDUxNC1hMDg5LTk2NTY2NmMyZWZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDkwNWVlNGM2NDU1Nzc4Yjg1ZGM4ZGVjZDg4MGNjYzNiYzZhZjYzZTYwODM1ZjdhN2ViY2Y2YjQ1MGRlYTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aPn-Llri6iGzrdjySFuVRiWv6CgJoHyM-SKwbe4uRLE)
> 
> @apu52 It was working well enough after merge it seems messed up. Should I work on making a complete different nav and footer or (look a like) , and not use the main styles.css sheet. Please, Tell me what you think!

yes you can do that . Just link it with the main file. I will suggest you to make a new issue on it so that it will be considered in the JWOC

**Comment by ratnojitsaha** [comment]
ok
