### ISSUE TITLE
I want to make the height of all pictures uniform for best trip package section.

### ISSUE THREAD

**Issue by saikatdey61** [apu52/Travel_Website#19]
![WhatsApp Image 2024-01-12 at 19 01 45_d96cc207](https://github.com/apu52/Travel_Website/assets/128217785/5d0fad0f-6d66-4585-8573-1350b41c8cb6)

**Comment by saikatdey61** [comment]
I want to work on this issue under jwoc 2024 , please assign me.

**Comment by saikatdey61** [comment]
<img width="942" alt="image" src="https://github.com/apu52/Travel_Website/assets/128217785/c9eefbe3-7b05-4262-b1a4-9693782b4d46">

**Comment by rahat2134** [comment]
This issue is a duplicate of #7.

**Comment by apu52** [comment]
@saikatdey61 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
