### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by tushargupta1504** [apu52/Travel_Website#199]
The contact page is not properly aligned it can have better spacing and have spaces
![image](https://github.com/apu52/Travel_Website/assets/138330699/7dbc762f-629a-4128-972a-bc3d44441705)

**Comment by apu52** [comment]
![image](https://github.com/apu52/Travel_Website/assets/114172928/1dc1024c-444b-48b4-b391-79ae52cc79ae)

@tushargupta1504 Please use the proper issue templates to raise your issue. I am closing this issue as #178 is already present there
