### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by tushargupta1504** [apu52/Travel_Website#200]
The switch is not looking nice
![image](https://github.com/apu52/Travel_Website/assets/138330699/ac01cc36-3c32-4a14-a7e1-073ee5b3dec8)
either the bg should same or not there

**Comment by apu52** [comment]
![image](https://github.com/apu52/Travel_Website/assets/114172928/6c39fde7-d2b7-4005-8bbf-c1868b660942)

@tushargupta1504 Please use the proper issue templates to raise your issue. I am closing this issue as #178 is already present there
