### ISSUE TITLE
Feature_Request : Add carousel

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#203]
**Is your feature request related to a problem? Please describe.**

add carousel in explore top destination

**Describe the solution you'd like**

dynamic carousel instead of static cards

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/110532770/910e7a55-6572-4091-9c3e-a556089a3bbb)

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
@PranavBarthwal #38 is already present there with the same issue. Sorry to close this issue. But you can make any new issue
