### ISSUE TITLE
BUG improper placement of button 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#204]
**Describe the bug**

Button of feedback is not need in contact us from we can add it in ratus page 
[ if any customer is comming first time then why he need to feedback ]

**Expected behavior**

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/125949765/147df847-f42e-40a5-b792-85f5986c173c)

we will add it in 

![image](https://github.com/apu52/Travel_Website/assets/125949765/f4a8bd19-68a6-4c52-8a1c-b890beeb7e3b)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by Asin-Junior-Honore** [comment]
@AftabMankapure  i can work on  these

**Comment by apu52** [comment]
@AftabMankapure there are two different pages in the website one is "Rate us" & the other is "feedback page" so they are not same . Sorry I think this repo can't be assigned
