### ISSUE TITLE
FEAT New style UI update

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#207]
update old UI to new 

Current style is :

https://github.com/apu52/Travel_Website/assets/125949765/b2e64a72-6d38-4150-96d8-046c28a6aad9

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

this is under devlopment
https://github.com/apu52/Travel_Website/assets/125949765/d475777d-e6f8-4499-a866-b17a549124b0

***Are you contributing under any open-source program
jwoc

**Comment by AftabMankapure** [comment]
bro pls watch video without audio 
sorry for that voice

**Comment by apu52** [comment]
> bro pls watch video without audio sorry for that voice

no problem

**Comment by apu52** [comment]
@AftabMankapure The new UI is really cool but if this UI is applied so the Theme change feature will be invalid & all other light theme features. So **I just want to suggest you one thing , make the new UI change in the DARK THEME portion So that the light theme potion will be as it is.**

**Comment by apu52** [comment]
@AftabMankapure You are assigned. You have 4 days to submit your PR

**Comment by AftabMankapure** [comment]
current dark mode is not working

**Comment by AftabMankapure** [comment]
if you want new style we will apply to that dark them

**Comment by apu52** [comment]
> current dark mode is not working

But current dark theme  is working properly

**Comment by apu52** [comment]
> if you want new style we will apply to that dark them

Yes. apply your UI & make the changes in the current dark theme

**Comment by AftabMankapure** [comment]
ok i will work on it 
pls check #221 
already make pr for this 
after pr merge for #221  it i will start work on this #207

**Comment by AftabMankapure** [comment]
what about background image in dark mode  (bubble background image)

https://github.com/apu52/Travel_Website/assets/125949765/76b8837d-69be-4fa1-b35c-a645dca2566c




i think it better to remove image and add color in background 


https://github.com/apu52/Travel_Website/assets/125949765/b3e0b1f5-7e69-4c97-a731-ec0369dcb479

**Comment by apu52** [comment]
ok @AftabMankapure Just remove the background bubble in the dark mode only , not in the light mode

**Comment by AftabMankapure** [comment]
https://github.com/apu52/Travel_Website/assets/125949765/bf66ed90-fbd8-485c-99ae-628fa7295357

i will make pr for this 
i unable to remove bubble effect in dark mode 
we can remove from both mode only 
i think it good to remove form both mode

**Comment by apu52** [comment]
@AftabMankapure I think there is no need to remove the bubble effect in dark mode. it looks good . you should make the PR with this changes now. It's LGTM

**Comment by AftabMankapure** [comment]
i will try to any way to remove bubble from dark mode only
