### ISSUE TITLE
Enhance the contact section

### ISSUE THREAD

**Issue by Aadhya-Sharma** [apu52/Travel_Website#211]
**Is your feature request related to a problem? Please describe.**

The contact section lacks visual appeal, hindering user engagement.

**Describe the solution you'd like**

I want to elevate the contact section with a modern design overhaul, enhancing visual appeal and user engagement.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-01-28 135806](https://github.com/apu52/Travel_Website/assets/121510222/7c95d988-8c77-4370-9bf2-868fc17fffee)

***Are you contributing under any open-source program ?***
I am contributing under JWOC 2024.

**Comment by Aadhya-Sharma** [comment]
I would like to work on this issue under JWOC.

**Comment by apu52** [comment]
@Aadhya-Sharma Welcome to the repo!!!!!!!
you are assigned.
you have 2-3 days to submit your issue
happy Coding!!!!!!!
