### ISSUE TITLE
[Feature_Request] COMPLETE NEW HEADER AND FOOTER FOR THE DESTINATIONS

### ISSUE THREAD

**Issue by ratnojitsaha** [apu52/Travel_Website#212]
The Header and footer seems messed after fixing multiple bugs!, and it may get messed on time-to-time new updates!,
I want to unlink the pages with the main styles.css and make a separate css files to prevent further bugs.

Please assign me under JWOC 2024

**Comment by apu52** [comment]
@ratnojitsaha Where is your PR, Please submit it within today , otherwise I have to unassign you

**Comment by Parth4git** [comment]
I want to work on this issue .kindly assign me this issue

**Comment by apu52** [comment]
> I want to work on this issue .kindly assign me this issue

Already @ratnojitsaha is assigned. I will assign you if he fails to submit his PR

**Comment by apu52** [comment]
> @ratnojitsaha Where is your PR, Please submit it within today , otherwise I have to unassign you

@ratnojitsaha Please submit your PR within tonight .

**Comment by ratnojitsaha** [comment]
@apu52 sorry for delays I'm extremely engaged with the ritual programs will  submit u with 2am

**Comment by apu52** [comment]
> @apu52 sorry for delays I'm extremely engaged with the ritual programs will submit u with 2am

I know . I understand . No problem . Try to submit it within tonight
