### ISSUE TITLE
Feature_Request : LOADING PAGE with LOGO 

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#214]
**Is your feature request related to a problem? Please describe.**

Yes . it's an Enhancement
**Describe the solution you'd like**

Hello all,
I want to add a loading page to our webpage  .

**Describe alternatives you've considered**

The loading page may have the name "TOURGUIDE" in blocks or maybe the logo with a loading sign . for better understanding go through the JWOC main website or look at the below SS

**Demo Video/Screenshot (Mandatory )**

![image](https://github.com/apu52/Travel_Website/assets/114172928/872af643-af4b-4a91-ad9b-9a26bcfbb1bc)
dsfsdfsdfdfdffff

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
### Who want to work on this issue Please comment with JWOC mentioned in it .

**Comment by daksh1210jain** [comment]
i would like to try
under JWOC

**Comment by SohanRC** [comment]
I want to work under this issue !! please assign me under JWOC 2024

**Comment by apu52** [comment]
@daksh1210jain You are assigned. you have 3 days to complete this issue

**Comment by daksh1210jain** [comment]
ok sir i will try my best

**Comment by prakharsingh-74** [comment]
@apu52 I would like to work on this issue now under JWOC as the number of days has been passed by the other contributor.

**Comment by apu52** [comment]
@daksh1210jain please submit your PR ASAP within 1 day

**Comment by prakharsingh-74** [comment]
> @daksh1210jain please submit your PR ASAP within 1 day

@apu52 As the 3 days have been passed now, kindly assigned this issue to me now.

**Comment by apu52** [comment]
> > @daksh1210jain please submit your PR ASAP within 1 day
> 
> @apu52 As the 3 days have been passed now, kindly assigned this issue to me now.

Ok you are assigned on this issue

**Comment by apu52** [comment]
@daksh1210jain As you have crossed the deadline, sorry to unassign you

**Comment by SohanRC** [comment]
> I want to work under this issue !! please assign me under JWOC 2024

Please assign me this issue if not completed !

**Comment by apu52** [comment]
> > I want to work under this issue !! please assign me under JWOC 2024
> 
> Please assign me this issue if not completed !

I have just assigned @prakharsingh-74 yesterday

**Comment by prakharsingh-74** [comment]
@apu52 sorry to give trouble you but please unassign me this issue due to my some other works that are on my priority first. i will not be able to contribute in this issue right now for a couple of days. Thank you for giving me the oppurtunity to work on your project.

**Comment by apu52** [comment]
> @apu52 sorry to give trouble you but please unassign me this issue due to my some other works that are on my priority first. i will not be able to contribute in this issue right now for a couple of days. Thank you for giving me the oppurtunity to work on your project.

okay . no problem

**Comment by apu52** [comment]
@SohanRC Do you want to work on this issue . As per rule you will get assigned to this issue

**Comment by SohanRC** [comment]
> @SohanRC Do you want to work on this issue . As per rule you will get assigned to this issue

Yes

**Comment by apu52** [comment]
@SohanRC You are assigned . you just have 2-3 days to submit your PR
