### ISSUE TITLE
Enhancing the dark mode toggle button

### ISSUE THREAD

**Issue by Aashi19234** [apu52/Travel_Website#218]
**Describe the bug**
Currently the dark-mode button is very basic, i would enhance it by adding some styling of switching between these two modes.

**Expected behavior**
I want it to make the dark mode toggle button to somewhat look like this.

![Screenshot 2023-10-18 215220](https://github.com/apu52/Travel_Website/assets/140010647/1b68b3de-127d-4511-aaf2-dcdfbe2402e8)

**Screenshots (Mandatory)**
Currently it is very basic and i would enhance it to make it attractive to user.

![Screenshot (77)](https://github.com/apu52/Travel_Website/assets/140010647/26e34875-a8a3-49fe-a353-6ad1d1ed45e6)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes under JWOC'24

**Comment by AftabMankapure** [comment]
@Aashi19234  can i work on it 
assign me under JWOC

**Comment by Aashi19234** [comment]
@AftabMankapure Currently i am working on it.

**Comment by AftabMankapure** [comment]
ok best luck
