### ISSUE TITLE
Feature_Request : 3 diff checkout page for memberships

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#220]
**Is your feature request related to a problem? Please describe.**

3 different checkout page for different membership tiers

**Describe alternatives you've considered**

link these membership options with 3 different checkout pages

**Demo Video/Screenshot (Mandatory )**
![Screenshot (90)](https://github.com/apu52/Travel_Website/assets/110532770/b62e49a2-25e3-4374-b3f1-82997e082c51)

***Are you contributing under any open-source program ?***

jwoc'24

**Comment by apu52** [comment]
@PranavBarthwal I will like to recommend to make all the deployment in one check out page which is already existing in the repo & make enhancements there. I think you have previously added the check out page . So , it's better you make the checkout page more functionable

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal I will like to recommend to make all the deployment in one check out page which is already existing in the repo & make enhancements there. I think you have previously added the check out page . So , it's better you make the checkout page more functionable

Sure, noted.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal I will like to recommend to make all the deployment in one check out page which is already existing in the repo & make enhancements there. I think you have previously added the check out page . So , it's better you make the checkout page more functionable

hey ! Its a request to increase the difficulty tag of this issue so that I can get extra time because for increasing the functionality of the existing checkout page, like you said, I need to explore some newer concepts like local storage and it'll take time. So it would be great if you could do so. thanks

**Comment by apu52** [comment]
> > @PranavBarthwal I will like to recommend to make all the deployment in one check out page which is already existing in the repo & make enhancements there. I think you have previously added the check out page . So , it's better you make the checkout page more functionable
> 
> hey ! Its a request to increase the difficulty tag of this issue so that I can get extra time because for increasing the functionality of the existing checkout page, like you said, I need to explore some newer concepts like local storage and it'll take time. So it would be great if you could do so. thanks

ok go for it. you have time
