### ISSUE TITLE
STYLE Navbar improvement 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#221]
**Describe the bug**
Updated navbar 

**Screenshots (Mandatory)**

Current navbar 
https://github.com/apu52/Travel_Website/assets/125949765/443116be-712e-4cdc-9ed7-af27be247e4c

Changes 
               1.order of navbar option 
               2. Change dark mode button 
New navbar 

https://github.com/apu52/Travel_Website/assets/125949765/1232cfc1-d5af-489b-abc6-e1eb43ab0c75

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure sorry but this issue can't be assigned as already #218 is assigned on the same navbar related issue. Sorry to close this issue. 
Hope to see u with more valuable contributions.
