### ISSUE TITLE
Login Page design Improve

### ISSUE THREAD

**Issue by soumik7063** [apu52/Travel_Website#224]
**Is your feature request related to a problem? Please describe.**
In login page there is no hover effect in buttons, and I think login button slight be responsive

**Describe the solution you'd like**
In hover buttons should be responsive

**Demo Video/Screenshot (Mandatory )**
![Screenshot (61)](https://github.com/apu52/Travel_Website/assets/145036560/65e79575-f40a-4a5d-99db-394b1a0e15ce)

***Are you contributing under any open-source program ?***
yes In JWOC 2024

**Comment by apu52** [comment]
@soumik7063 #223  is already present in the repo with same enhancement Thank you for your issue . But this issue can't be assigned.
Hope to see you with more contributions.
