### ISSUE TITLE
Enhance:Non-Functional "View All" Button for More Best Trip Packages

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#23]
![Uploading Screenshot 2024-01-13 at 9.23.26 PM.png…]()
Users visiting the Best Trip Packages section expect to have the option to view more than the initial 3 packages presented. However, the current state of the "View All" button prevents users from accessing additional packages. Our goal is to investigate and rectify this issue, ensuring users can seamlessly explore a comprehensive list of the best trip packages.

**Steps to Reproduce:**
Navigate to the homepage and locate the "Best Trip Packages" section.
Attempt to click on the "View All" button.
Currently, the button is non-functional, preventing access to additional trip packages.

**Problem:**
The "View All" button in the Best Trip Packages section is not currently functional, preventing users from accessing an extended list of trip packages. This impacts the user experience and limits the exploration of available offerings.

**Solution:**
Identify and resolve the issue causing the non-functionality of the "View All" button. Update its functionality to redirect users to a dedicated page showcasing an extensive list of the best trip packages.

**Comment by rahat2134** [comment]
@apu52 assign this to me.

**Comment by apu52** [comment]
@rahat2134 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
