### ISSUE TITLE
BUG navbar item arrangement is not per web content 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#234]
**Describe the bug**

navbar item arrangement is not per web content 

**Screenshots (Mandatory)**

current navbar 
### light mode
![nO](https://github.com/apu52/Travel_Website/assets/125949765/d1500cd5-1dcc-442e-8549-cf150e8a2008)

### Dark mode
![no1](https://github.com/apu52/Travel_Website/assets/125949765/769163b5-154f-456b-9bb2-230b3c5f2bc7)

**Expected behavior**

Changes :
   As per user interaction / current website flow
1.    T estimonials come after trip gallery
2. insted of adding button to "**contact us**" we can add button for "**Login**"
3. Dark mode button updation
4. Arrange navitem to left side 

New navbar
light mode

![nn1](https://github.com/apu52/Travel_Website/assets/125949765/9aba3d62-1438-4639-bb43-5b62e5491042)

Dark mode
![nn2](https://github.com/apu52/Travel_Website/assets/125949765/d6b99d6c-de4d-428c-8b16-349b17784c94)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@AftabMankapure Good issue
