### ISSUE TITLE
Feature_Request New btn style for both mode 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#235]
adding new btn style to both mode

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/125949765/2594970c-152c-4edb-8e31-516472c60565

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure Don't raise more than 1 issue. Work on one issue at a time. this is against the rules of JWOC as well as the rules of this repo

**Comment by AftabMankapure** [comment]
assign me under jwoc

**Comment by apu52** [comment]
> assign me under jwoc

@AftabMankapure You are assigned.

**Comment by apu52** [comment]
> pls check the pr
> 
> Bro it is not that much easy pls change label to hard

I have already changed the label
