### ISSUE TITLE
Feature_Request new sub title style for both mode

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#236]
New sub title style for both mode 

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/125949765/9ef54ba1-8861-4732-b954-0a4f519a550b

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure Don't raise more than 1 issue. Work on one issue at a time. this is against the rules of JWOC as well as the rules of this repo

**Comment by AftabMankapure** [comment]
Assign me under jwoc

**Comment by apu52** [comment]
@AftabMankapure Now you are assigned. You have 2-3 days to submit your PR

**Comment by AftabMankapure** [comment]
Can you make label medium to hard

**Comment by AftabMankapure** [comment]
pls check this
