### ISSUE TITLE
BUG : Unusual button in footer

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#238]
**Describe the bug**

unnecessary open chatbot button below the footer

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/110532770/6c5672c7-7775-4fa1-a700-5be65060bef5)

**Additional Context (Mandatory )**
will remove this

***Are you contributing under any open-source program ?***

jwoc'24

**Comment by apu52** [comment]
@PranavBarthwal good issue
