### ISSUE TITLE
BUG Style mismatch for contact form 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#239]
**Describe the bug**
Style is mismatch for contact form 

**Expected behavior**

we should remove the curve border 

**Screenshots (Mandatory)**

![c1](https://github.com/apu52/Travel_Website/assets/125949765/8e289589-4811-480c-81da-0dd56484c5f5)
border is curve

![c2](https://github.com/apu52/Travel_Website/assets/125949765/b7bcaf98-acb9-48fd-b17e-9b846e5fb647)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure Sorry to close this issue . You can raise this issue gain but only after the successful completion of the previous PR
