### ISSUE TITLE
Add "Go to Top" Button Feature

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#24]
The current version of the website lacks a "Go to Top" button, which can enhance user experience by providing a convenient way for visitors to quickly navigate back to the top of the page, especially on longer pages.

**Problems:**
User Navigation Difficulty:
Without a "Go to Top" button, users may find it inconvenient to manually scroll back to the top, especially on lengthy pages.

**Describe the solution you'd like**

**Solution:**
Adding a "Go to Top" button provides a simple and user-friendly solution for quick navigation to the top of the page.

**Demo Video/Screenshot (Mandatory )**
<img width="716" alt="Screenshot 2024-01-13 at 10 42 04 PM" src="https://github.com/apu52/Travel_Website/assets/136263179/0642a6b3-42ef-45ef-b1dd-74f92bb2995e">
<img width="689" alt="Screenshot 2024-01-13 at 10 42 33 PM" src="https://github.com/apu52/Travel_Website/assets/136263179/8a458327-3783-4feb-aeb0-122bad608a03">
<img width="716" alt="Screenshot 2024-01-13 at 10 42 04 PM" src="https://github.com/apu52/Travel_Website/assets/136263179/0642a6b3-42ef-45ef-b1dd-74f92bb2995e">

JWOC

**Comment by rahat2134** [comment]
@apu52 assign this issue to me.

**Comment by apu52** [comment]
@rahat2134 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts

**Comment by rahat2134** [comment]
@apu52 no problem, should i remind you to open the issue or i should raise the new issue with same info?

**Comment by apu52** [comment]
> @apu52 no problem, should i remind you to open the issue or i should raise the new issue with same info?

You can raise a new Issue
