### ISSUE TITLE
BUG navbar is not present on ratus us page

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#240]
**Describe the bug**
Navbar is not available on "RATE US " page

**Expected behavior**

**Screenshots (Mandatory)**

![ratus ju](https://github.com/apu52/Travel_Website/assets/125949765/e4fe1b4c-a635-4c64-840c-f78a3ce32c42)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure Sorry to close this issue . You can raise this issue gain but only after the successful completion of the previous PR
