### ISSUE TITLE
BUG absence of navbar in login page

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#241]
**Describe the bug**
Navbar is not present in login page 

**Expected behavior**
There should be a navbar to navigate

**Screenshots (Mandatory)**

![login](https://github.com/apu52/Travel_Website/assets/125949765/d9870a5b-7a96-49db-9c58-56e7b0f93bcb)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure Sorry to close this issue . You can raise this issue gain but only after the successful completion of the previous PR
