### ISSUE TITLE
BUG : remove footer from side in santorini page

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#247]
**Describe the bug**

 remove footer from side in santorini page

**Expected behavior**

Ill fix the page and will make the page look better

**Screenshots (Mandatory)**

![Screenshot (112)](https://github.com/apu52/Travel_Website/assets/110532770/4cf6a0b6-b778-4e09-a87f-c33098b76d4b)

***Are you contributing under any open-source program ?***

jwoc'24

**Comment by apu52** [comment]
@PranavBarthwal Can you please explain which footer you are talking about

**Comment by PranavBarthwal** [comment]
![IMG_20240202_094519.jpg](https://github.com/apu52/Travel_Website/assets/110532770/79100967-4d9b-4084-b232-c05fe661fdb6)

**Comment by apu52** [comment]
> ![IMG_20240202_094519.jpg](https://private-user-images.githubusercontent.com/110532770/301726470-79100967-4d9b-4084-b232-c05fe661fdb6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDc2NjMsIm5iZiI6MTcwNjg0NzM2MywicGF0aCI6Ii8xMTA1MzI3NzAvMzAxNzI2NDcwLTc5MTAwOTY3LTRkOWItNDA4NC1iMjMyLWMwNWZlNjYxZmRiNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNDE2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWQxNTY2ZWZlNmEyN2E3N2E2Njk0ZDIzY2NlNDkyN2ExN2Q2NTRiYzhiODk4NzRiNGQxNzE4MmEzZTVhZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w6yj_pkaiK0wznoaVW40BFlrDById7FrZ64rmOqHZBs)

ok
