### ISSUE TITLE
BUG : Fix machu pichu page

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#249]
**Describe the bug**

the whole page is distorted.

**Expected behavior**

I would like to fix this

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/110532770/33c45962-8317-49c3-98d8-47dc8c9b94d5)
![image](https://github.com/apu52/Travel_Website/assets/110532770/41044a81-ffcb-42cf-82f0-002b991f1a85)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
#212 someone is already working on this issue. Sorry to close this issue
