### ISSUE TITLE
Invisible Text in Footer on Dark Mode Switch

### ISSUE THREAD

**Issue by HappyLife2** [apu52/Travel_Website#253]
### Issue Description
Upon switching the website theme from light mode to dark mode, certain text elements in the footer become invisible, rendering them unreadable. The affected text is the footer section.

### Steps to Reproduce
1. Open the website in a browser.
2. Navigate to a page containing the footer.
3. Toggle the theme from light mode to dark mode.

### Expected Behavior
Text in the footer should remain visible and readable in both light and dark modes.

### Actual Behavior
In dark mode, the specified text elements become invisible, making it challenging for users to read the content.

### Before Fix
![Screenshot 2024-02-03 231015](https://github.com/apu52/Travel_Website/assets/130459769/5f00b15c-dea9-44ac-a8cc-fe09afb8ba89)

### After Fix
![Screenshot 2024-02-03 231033](https://github.com/apu52/Travel_Website/assets/130459769/1ab5ef67-9a1f-4977-bf1f-989e8cf0674d)

Kindly assign me on this issue so I can upload the file which will fix this issue.

**Comment by apu52** [comment]
@HappyLife2 Really good issue. You are assigned. 
Are you contributing under JWOC??

**Comment by HappyLife2** [comment]
sorry what does JWOC mean, I'm still new here.
and is it possible I add you on discord if possible?

**Comment by apu52** [comment]
> sorry what does JWOC mean, I'm still new here. and is it possible I add you on discord if possible?

OK no problem , actually this repo is under an ongoing open source contribution programme named JWOC
But you can still contribute in this repo . happy coding!!!!!!!!

**Comment by apu52** [comment]
> sorry what does JWOC mean, I'm still new here. and is it possible I add you on discord if possible?

Yes . you can add me on Discord
apuscorner ---- username
