### ISSUE TITLE
BUG : Padding between button

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#255]
**Describe the bug**

the story button and plan a trip button has no spacing

**Expected behavior**

add a little padding

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/110532770/70607c64-19a1-4ef2-965e-108f254837ee)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

JWoC'24

**Comment by kaif969** [comment]
this project assigned me

**Comment by apu52** [comment]
> this project assigned me

This issue is already assigned. You can work on any other issue or raise aby new issue
