### ISSUE TITLE
BUG: Invisible text in the pricing section on switching to dark mode

### ISSUE THREAD

**Issue by Aswinr24** [apu52/Travel_Website#259]
**The bug**
Text in the pricing section cards is invisible on switching to dark mode

**Expected behavior**
The text colour should remain the same

**Screenshot**
![Screenshot 2024-02-04 140208](https://github.com/apu52/Travel_Website/assets/135364633/0c276d24-e60c-44cd-ad5e-801167b3177a)

**Additional Context **
would like to get this bug cleared

***Are you contributing under any open-source program ?***
JWOC 2024

**Comment by apu52** [comment]
@Aswinr24 Welcome to the REPO.
I have assigned you. You just have 1 day to submit your PR .
Happy Coding!!!!!!!!!

**Comment by Aswinr24** [comment]
Sorry saw this message late..will make a PR by tonight
