### ISSUE TITLE
Feature_Request : Make a Different Login Page

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#26]
**Is your feature request related to a problem? Please describe.**

Hello All,
You can make a different login page in this project 

**Describe the solution you'd like**

It  will help the users to login with their
- mail
- facebook
- google account
& also made a button in the front pg as clickable to jump into that page

**Describe alternatives you've considered**

you can use JS or react to make this with added HTML& CSS.

**Demo Video/Screenshot (Mandatory )**

![image](https://github.com/apu52/Travel_Website/assets/114172928/f79250b1-2986-4afe-af0a-a54ad77edf97)

This is just a Demo. You can make it more fascinating & working

***Are you contributing under any open-source program ?***

JWOC 2k24

**Comment by apu52** [comment]
Whoever comments first , I will assign this issue , to her/him

**Comment by rahat2134** [comment]
@apu52 assign to me (JWOC).

**Comment by MalikAyush-55** [comment]
@apu52 Can You assign this issue to me?(Jwoc)

**Comment by SonaliKumari2** [comment]
@apu52 assign to me (JWOC).

**Comment by SonaliKumari2** [comment]
I want to work on this issue under JWOC.

**Comment by Sneha-Sonkar** [comment]
I would like to work on that issue under JWOC

**Comment by Sneha6003** [comment]
I would like to work on that issue under JWOC.

**Comment by SonaliKumari2** [comment]
I would like to work on that issue under JWOC.

**Comment by aksh1009** [comment]
I would like to work on the issue under JWOC

**Comment by ShreyaTiwari05** [comment]
Hii I am willing to work on this issue under JWoC'24

**Comment by apu52** [comment]
> I would like to work on that issue under JWOC.

@Sneha6003 I have assigned you . You can start working on this issue
Welcome to the repo!!!!!!!

**Comment by apu52** [comment]
@aksh1009 @SonaliKumari2 @ShreyaTiwari05 Welcome to the repo!!!!!

**Comment by sanjayh-2022** [comment]
I would like to work on that issue under JWOC.

**Comment by apu52** [comment]
> I would like to work on that issue under JWOC.

This issue is already assigned. You can raise any new issue you want to work on

**Comment by apu52** [comment]
@Sneha6003 You have to complete this issue within 2-3 days
