### ISSUE TITLE
BUG : unusual button below the footer in trip package page

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#260]
**Describe the bug**

unusual button below the footer in trip package page

**Expected behavior**

no button below footer

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/110532770/848b0125-45d1-402b-970b-6d4f02be75da)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

jwoc'24

**Comment by apu52** [comment]
@PranavBarthwal make a symbol for it(as in the home page) instead of "GO TO TOP" button
