### ISSUE TITLE
BUG: login page

### ISSUE THREAD

**Issue by Anushkabh** [apu52/Travel_Website#264]
**Describe the bug**

The login button in the top right of home page when clicked not showing expected behaviour.

**Expected behavior**

it should open up login page ... when i should click on login it should display email password .. but it is showing only for registration, even i am clicking on login button its showing the same thing

**Screenshots (Mandatory)**

![Screenshot (111)](https://github.com/apu52/Travel_Website/assets/99523033/58c1de34-25f8-48a1-bbc5-da8b1aa274d5)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
yes JWOC

**Comment by Anushkabh** [comment]
@apu52 kindly assign under JWOC

**Comment by Shubhra-Narang** [comment]
I can fix this issue, kindly assign it to me

**Comment by apu52** [comment]
@Anushkabh I can't exactly understand about your issue. can you please explain your issue as the login page is working well

**Comment by apu52** [comment]
@Anushkabh Are you still working on this issue or I will close this issue??

**Comment by apu52** [comment]
@Anushkabh You are assigned. you can start working on this issue

**Comment by apu52** [comment]
> @apu52 i would like to ask you what should be the expected behaviour here after clicking on register or login

By clicking on login it must redirect to the login page itself & clicking on register button it must redirect to a new registration page which is not ready till now

**Comment by hussain123sahil** [comment]
@apu52 thankyou for assigning me this issue. Will solve and revert back soon.

**Comment by SaiKishor66** [comment]
Can you pls assign me this issue?
