### ISSUE TITLE
Enhancement and Bug Fixes for Payment Gateway

### ISSUE THREAD

**Issue by Gowtham-S073** [apu52/Travel_Website#267]
**Describe the bug**

This issue is to track enhancements and bug fixes for the payment gateway module. The current implementation lacks proper validation for card details and requires enhancements to improve user experience and security.

**Expected behavior**

- Users should receive clear feedback when entering incorrect card details.
- The payment page should guide users to enter valid card information.
- Overall, the payment process should be smoother and more secure after implementing these changes.

**Proposed Changes**

- Implement validation for card number input field to ensure it follows the correct format.
- Validate expiry date of the card to prevent users from entering expired cards.
- Validate CVV input field to ensure it meets the required length and format.
- Enhance the user interface of the payment page to improve usability and clarity.

**Screenshots (Mandatory)**

https://github.com/apu52/Travel_Website/assets/127298215/b234d6f7-1916-4645-9032-7bdedbdd3325

**Comment by apu52** [comment]
@Gowtham-S073 Welcome to the repo!!!!!!!
You are assigned. you have 2-3 days to submit your issue.
Happy coding!!!!
