### ISSUE TITLE
BUG: social-icons on the login page

### ISSUE THREAD

**Issue by Shubhra-Narang** [apu52/Travel_Website#268]
**Describe the bug**
The social icons in the login and registration page are not working the way they supposed to.

**Expected behavior**
When the user clicks on the social icons for creating an account let suppose he clicks on Google, the page should open up for him to login with his Google account.

**Screenshots (Mandatory)**

<img width="1440" alt="Screenshot 2024-02-06 at 2 39 53 PM" src="https://github.com/apu52/Travel_Website/assets/143348689/67f857af-9b3a-4fa6-b517-1554d8c5b65c">

**Additional Context (Mandatory )**
The current site doesn’t perform the task of correctly linking it to the social platforms for making the login process a lot more easier and reloads the login page itself.

***Are you contributing under any open-source program ?***
Yes, JWOC

**Comment by apu52** [comment]
@Shubhra-Narang welcome to the repo!!!!!!!!
I have assigned you. You have 2-3 days to submit your issue.
Happy coding!!!!!!!!

**Comment by apu52** [comment]
@Shubhra-Narang  Where is your PR??

**Comment by Shubhra-Narang** [comment]
@apu52 working on it!, but authentication requires backend part too.

**Comment by shuhaki** [comment]
@apu52 i have very good experience in fronted part, i did some good projects related to fronted so, could you please assaign it to me i will do it

**Comment by Bhoomii2003** [comment]
I can fix this issue, please assign it to me!

**Comment by apu52** [comment]
> @apu52 i have very good experience in fronted part, i did some good projects related to fronted so, could you please assaign it to me i will do it

Okay. I am assigning you this issue under GSSOC'24 . Start Working on it.

**Comment by Ghanshyam89** [comment]
Hi @shuhaki , Are you still working on this issue as we can't see any PR yet.

**Comment by ananyag309** [comment]
Hey, I am looking forward to work on it. Please assign the issue to me.
