### ISSUE TITLE
I want to enhance the UI of the landing page as a contribution under JWOC'24

### ISSUE THREAD

**Issue by SuvayuN** [apu52/Travel_Website#269]
**Describe the bug**
I want to enhance the UI by adding a sidebar, putting some options of navbar to sidebar and giving the navbar a proper spacing. Also the go to top button and message buttons are in same side. I want to spread it to each side.

**Screenshots (Mandatory)**
![Screenshot 2024-02-07 122756](https://github.com/apu52/Travel_Website/assets/136915678/72fdaf75-a9b3-4810-93b0-5401e89462bf)

**Additional Context (Mandatory )**

The navbar is looking very congested now but I want to give it more spacing 

***Are you contributing under any open-source program ?***
I am contributing under JWOC'24

**Comment by apu52** [comment]
@SuvayuN welcome to the repo!!!!!!!!
I have assigned you. You have 2-3 days to submit your issue.
Happy coding!!!!!!!!

**Comment by apu52** [comment]
@SuvayuN Where is your PR??
