### ISSUE TITLE
Feature_Request : Make the Website Responsive

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#27]
**Is your feature request related to a problem? Please describe.**

Hello All , 
You can make the website responsive for all the devices.

**Describe the solution you'd like**

It will help all the users to use this website in any of their devices

**Describe alternatives you've considered**

You may use @keyframes or CSS preloader

**Demo Video/Screenshot (Mandatory )**

Attach the responsive photos in the comments

***Are you contributing under any open-source program ?***

JWOC 2k24

**Comment by apu52** [comment]
Whoever comments first , I will assign this issue , to her/him

**Comment by rahat2134** [comment]
@apu52 assign to me (JWOC)

**Comment by Surajit0573** [comment]
Please assign me this issue under JWOC 2024

**Comment by sanjayh-2022** [comment]
Please assign me this issue under JWOC 2024

**Comment by apu52** [comment]
> Please assign me this issue under JWOC 2024

@Surajit0573 Welcome to the repo.
I have assigned you . you can start working on this issue

**Comment by apu52** [comment]
@Surajit0573 You have 4 days to complete this issue

**Comment by apu52** [comment]
@Surajit0573 It's over 4 days & the deadline is crossed. Sorry , But I am unassigning you

**Comment by apu52** [comment]
### This issue is open to all now. Whoever comments first with properly mention JWOC in it , I will assign this issue to her/him

**Comment by SohanRC** [comment]
@apu52 I would try to make it responsive. Please assign me under JWOC 2024.

**Comment by vishal2005025** [comment]
I have read the issue and I want to work on it .
please assign it to me under JWOC'2024.

**Comment by Hacxmr** [comment]
Hey! @apu52 I would want to contribute to this issue. Kindly assign me this issue under JWOC'24.

**Comment by apu52** [comment]
@vishal2005025 Now you are assigned on this issue. you can start working. you just have 4 days to submit your PR

**Comment by Aashi19234** [comment]
@apu52 I would like to work on this issue if no one is working on it currently.

**Comment by vishal2005025** [comment]
I am still working on it..

**Comment by Aashi19234** [comment]
@vishal2005025 Okay no worries👍🏻

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by apu52** [comment]
> please Assign it to me

@vermaanurag1532 stop spamming in the ISSUES

**Comment by apu52** [comment]
> I am still working on it..

@vishal2005025 where is your PR. sorry to unassign you as you have crossed the timelimt

**Comment by apu52** [comment]
@Hacxmr Do you want to work on this issue. As per rule you will get the chance to work on this issue. 
If you are willing then I will assign you

**Comment by SohanRC** [comment]
Please assign me under JWOC 2024. I Would like to work here.

**Comment by Hacxmr** [comment]
> @Hacxmr Do you want to work on this issue. As per rule you will get the chance to work on this issue. If you are willing then I will assign you

Yes @apu52

**Comment by apu52** [comment]
> > @Hacxmr Do you want to work on this issue. As per rule you will get the chance to work on this issue. If you are willing then I will assign you
> 
> Yes @apu52

@Hacxmr You are assigned now. You have 4 days to submit you issue. Happy Coding!!

**Comment by apu52** [comment]
@Hacxmr Where is your PR . You just have 1 more day to submit your PR

**Comment by Aashi19234** [comment]
@apu52 please assign this issue to me if it is not yet solved.

**Comment by apu52** [comment]
@Aashi19234 Someone is already assigned. But you can wait.

**Comment by apu52** [comment]
@Hacxmr sorry to unassign you ....as it has already crossed the deadline

**Comment by apu52** [comment]
@Aashi19234 Do you want to work on this issue..

**Comment by Aashi19234** [comment]
Yes @apu52

**Comment by apu52** [comment]
Ok . I am assigning you . But I am making it clear the issue is related to make the website responsive in all the devices like specially in the mobile versions with using CSS preloader , keyframes or other stacks

**Comment by Aashi19234** [comment]
@apu52 Can i use media-queries to perform this task?

**Comment by apu52** [comment]
yes Obviously you can

**Comment by Aashi19234** [comment]
@apu52 can i please submit my PR till Friday as my college has started and am i getting little less time to complete this task.

**Comment by apu52** [comment]
> @apu52 can i please submit my PR till Friday as my college has started and i am getting little less time to complete this task.

@Aashi19234 Please submit your PR within 2 days

**Comment by apu52** [comment]
@Aashi19234  Where is your PR??

**Comment by Madanraj0519** [comment]
I m interested to work on this issue, can you please assign this to me

**Comment by apu52** [comment]
> I m interested to work on this issue, can you please assign this to me

Ok .I am assigning You . Happy Coding!!

**Comment by Guddu-kr** [comment]
I m interested to work on this issue, can you please assign this to me

**Comment by ivarcodes** [comment]
Hi sir , i would love to contribute on this issue and make the site responsive.

**Comment by Gokilp** [comment]
please assign to me  #gssoc24

**Comment by ritankarsaha** [comment]
Please assign this issue to me #gssoc'24. Thank You.

**Comment by Pujan-sarkar** [comment]
@apu52 is this issue is solved , i am working under GSSOC'24 . I want to contribute and solve this issue will you please assign this to me ?

**Comment by apu52** [comment]
Sorry everyone . But this issue is really old & complicated. So I am closing this issue.

**Comment by ritankarsaha** [comment]
> Sorry everyone . But this issue is really old & complicated. So I am closing this issue.

I get it it's complex but i have added the responsive nature successfully, you could have checked it once.
