### ISSUE TITLE
Feature_Request: Add Climate info of the place.

### ISSUE THREAD

**Issue by maadi7** [apu52/Travel_Website#270]
**Is your feature request related to a problem? Please describe.**
I want to add climate information of the place user are serching using API

**Describe the solution you'd like**
I will use API for this.

**Demo Video/Screenshot (Mandatory )**
Will add info in the blue marked place
![fly](https://github.com/apu52/Travel_Website/assets/95737654/b83f741c-09d8-4acf-a9cb-3bc361d3a24a)

***Are you contributing under any open-source program ?***
JWOC.

**Comment by apu52** [comment]
@maadi7 You are assigned.
Happy coding!!!!!!!!!!!!

**Comment by mandrita16** [comment]
Will use geospatial platforms for instance Google Earth Engine which offers the access to various datasets

**Comment by apu52** [comment]
@maadi7  Where is your PR??

**Comment by mandrita16** [comment]
Yaa I will

**Comment by maadi7** [comment]
hii @apu52, sorry for delay I was bit busy, but I will raise PR tommorow late night for sure.!!
