### ISSUE TITLE
Feature_Request   remove bubble background 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#280]
**Is your feature request related to a problem? Please describe.**

remove bubble background from website to **look good classic** 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Current home page 
![cr1](https://github.com/apu52/Travel_Website/assets/125949765/18ccdf14-f51f-45f0-8954-b96c5d335be3)

new 
![Screenshot 2024-02-16 150700](https://github.com/apu52/Travel_Website/assets/125949765/a9be6d3c-057f-44c4-a51a-0fcdbf69b7fb)

![rw1](https://github.com/apu52/Travel_Website/assets/125949765/f1a8e5a4-77f4-4c60-a8a2-8951015149fb)

![r3](https://github.com/apu52/Travel_Website/assets/125949765/f5a01620-f989-4ec5-846e-a64798cdfb34)

![Screenshot 2024-02-16 150807](https://github.com/apu52/Travel_Website/assets/125949765/dbedf37c-66e4-4704-9e59-070295cc9704)

***Are you contributing under any open-source program ?***

jwoc

**Comment by apu52** [comment]
@AftabMankapure Your proposal is good But Can you use a background theme maybe instead of the solid color can you use maybe  some animation or some image

**Comment by AftabMankapure** [comment]
https://github.com/apu52/Travel_Website/assets/125949765/5542e657-5700-463a-b0f6-7231da864007

it is ok

**Comment by AftabMankapure** [comment]
I think it it good 
pls change label medium to 
 ### **HARD**

**Comment by apu52** [comment]
> I think it it good pls change label medium to
> 
> ### **HARD**

OK please submit your PR .
