### ISSUE TITLE
Feature_Request: Add navbar on "Rate Us?" Page

### ISSUE THREAD

**Issue by Sanglap-Halder** [apu52/Travel_Website#283]
**Is your feature request related to a problem? Please describe.**
There is no navbar on "Rate Us?" Page 

**Describe the solution you'd like**
I want to add navbar on "Rate Us?" Page under JWoC 2024

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Before:
![Screenshot (128)](https://github.com/apu52/Travel_Website/assets/150362505/58041472-0f24-40ec-a167-880045bb822a)
After:
![Screenshot (129)](https://github.com/apu52/Travel_Website/assets/150362505/62197fec-4c04-49ab-a989-f3ef4d1c46cd)

***Are you contributing under any open-source program ?***
I am contributing under JWoC 2024
Please assign me this issue

**Comment by apu52** [comment]
@Sanglap-Halder I think there is no need to make a navbar in the rate us page as a return to home page is already present there .
Sorry this issue can't be assigned.

**Comment by Sanglap-Halder** [comment]
Ok
