### ISSUE TITLE
BUG  Highlight active section in navbar

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#286]
**Describe the bug**

Highlight active section in navbar

**Expected behavior**

When we scroll from one section to other it highlight in navbar 

**Screenshots (Mandatory)**

New 

![ac1](https://github.com/apu52/Travel_Website/assets/125949765/6abd0a0b-2eaa-4c56-aa27-f1dbf397fe8f)

![n1](https://github.com/apu52/Travel_Website/assets/125949765/eb164f90-3bcc-4940-b193-afd710155b2c)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

JWOC

**Comment by AftabMankapure** [comment]
@apu52  can you make label medium

**Comment by apu52** [comment]
> @apu52 can you make label medium

Ok. I will Go through the PR
