### ISSUE TITLE
Add Animations to the Pricing Page !

### ISSUE THREAD

**Issue by SohanRC** [apu52/Travel_Website#289]
**Is your feature request related to a problem? Please describe.**

On Clicking the view all button , the pricing page appears suddenly ! I think if we add animations to it , it will look much better ! I want to work in this issue ! Please assign me under JWOC 2024.

***Are you contributing under any open-source program ?***

Yes , under JWOC 2024.

**Comment by apu52** [comment]
@SohanRC I have assigned you. Just give me a preview here after your make your changes

**Comment by SohanRC** [comment]
> @SohanRC I have assigned you. Just give me a preview here after your make your changes

ok

**Comment by SohanRC** [comment]
> @SohanRC I have assigned you. Just give me a preview here after your make your changes

I have submitted a PR for this issue ! Please review it !
