### ISSUE TITLE
Add "Go to Top" Button Feature 

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#29]
The current version of the website lacks a "Go to Top" button, which can enhance user experience by providing a convenient way for visitors to quickly navigate back to the top of the page, especially on longer pages.

Problems:
User Navigation Difficulty:
Without a "Go to Top" button, users may find it inconvenient to manually scroll back to the top, especially on lengthy pages.

Describe the solution you'd like

Solution:
Adding a "Go to Top" button provides a simple and user-friendly solution for quick navigation to the top of the page.

Demo Video/Screenshot (Mandatory )
![image](https://github.com/apu52/Travel_Website/assets/136263179/5f4fd712-63ac-4645-8e49-89ef1051d607)
![image](https://github.com/apu52/Travel_Website/assets/136263179/e5c47e98-ee06-4d80-bc6a-586dee608b3b)

**Comment by rahat2134** [comment]
want to  work under JWOC

**Comment by rahat2134** [comment]
@apu52 Assign me

**Comment by rahat2134** [comment]
@apu52 assign this to me 🙂.

**Comment by sanjayh-2022** [comment]
assign me JWOC

**Comment by apu52** [comment]
@rahat2134 Welcome to the repo.
I have assigned you. you can start working on this issue

**Comment by rahat2134** [comment]
thank you

**Comment by rahat2134** [comment]
@apu52 please mention its difficulty label

**Comment by apu52** [comment]
@rahat2134 You have 2-3 days for the submission of your PR

**Comment by rahat2134** [comment]
Okay thats more than enough
