### ISSUE TITLE
BUG Contact us section is not properly display in light mode

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#293]
**Describe the bug**

BUG Contact us section is not properly display in light mode (Label or not display )

**Expected behavior**

**Screenshots (Mandatory)**

![Screenshot 2024-02-20 151141](https://github.com/apu52/Travel_Website/assets/125949765/29e8b8e3-435c-497c-acb7-02cf79b57045)

**Additional Context (Mandatory )**
JWOC
***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@AftabMankapure I will assign you this only after completion of the previous PR

**Comment by apu52** [comment]
@AftabMankapure this issue has already been solved . Sorry to close this issue
