### ISSUE TITLE
Title: Enhancement - Make Navbar Dynamic with HTML Bookmarks

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#3]
Issue Description
I would like to enhance the current navigation bar by making it dynamic using HTML bookmarks. The goal is to improve user experience and navigation within the website.
<img width="1002" alt="Screenshot 2024-01-10 at 11 58 57 PM" src="https://github.com/apu52/Travel_Website/assets/136263179/354e199a-a397-4e07-85b9-62a459e54d90">

Proposed Changes
Utilize HTML bookmarks to dynamically generate navigation links in the navbar.
Ensure that the navbar reflects the structure of the HTML document, allowing users to easily navigate to different sections.
Additional Information
Current navigation might be static and manual. This enhancement aims to automate the process and make it more user-friendly.
The implementation should consider the structure of the HTML document and generate links accordingly.

**Comment by rahat2134** [comment]
I can make it more engaging.Lets connect and discuss.

**Comment by zul132** [comment]
I would also like to work on this issue. @rahat2134 I noticed you've raised 4 issues under this project but as per JWoC rules, mentees can be allotted only 1 issue per project at a time.
So, @apu52 I would also like to be considered for this issue, just in case you decide to allot @rahat2134 to a different issue.

**Comment by apu52** [comment]
@rahat2134 Welcome to the repo.
Sorry to close this issue as it's invalid for JWOC
Make sure to open the issues after coding period starts
