### ISSUE TITLE
BUG Add navbar to feedback page

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#303]
**Describe the bug**

add navbar to feedback page

**Expected behavior**

navbar is required to feedback page 

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

JWOC

**Comment by AftabMankapure** [comment]
@apu52  pls assign me under JWOC

**Comment by apu52** [comment]
@AftabMankapure The over all feedback pg is not linked with CSS file maybe. try to fix that also.

**Comment by AftabMankapure** [comment]
@apu52 thank for you support see you again in any other Competition

**Comment by apu52** [comment]
> @apu52 thank for you support see you again in any other Competition

same to you. Thanks for all of your great contributions
