### ISSUE TITLE
Imporve the footer of the page

### ISSUE THREAD

**Issue by kairveeehh** [apu52/Travel_Website#308]
@apu52  the current footer is not interactive , doesnt has hover effects and needs a cleaner UI , I would like to fix these issues 
## please assign this issue to me
![Screenshot 2024-05-09 191721](https://github.com/apu52/Travel_Website/assets/145572028/739b9e38-fadc-4d26-9a08-1d2693cec356)

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by Prakhar-bansal1** [comment]
It will be my pleasure if you assign me for this issue. I'll try my best and give 100% to it..

**Comment by aditimishra0013** [comment]
Please do assign me this issue. I will surely solve this problem very effectively

**Comment by Swapnita06** [comment]
Please do assign this to me! I can work on it easily.

**Comment by DARSHANITRIPATHI** [comment]
please assign this to me

**Comment by StutiMittal** [comment]
@apu52 I am profiecient in HTML and CSS. I'm enthusiastic about taking charge of enhancing the website's footer to elevate user experience and project representation.

**Comment by PDurgaAnusha** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it. I'll solve this task

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by S-Siri** [comment]
hey I am interested in this issue, please assign me.
