### ISSUE TITLE
UI issue in your navbar 

### ISSUE THREAD

**Issue by negia7014** [apu52/Travel_Website#309]
There is an issue in navbar like  Login are misallignment  and  many more 
please assign this issue to me i have experience in fronted.

![image](https://github.com/apu52/Travel_Website/assets/111852535/09e9fe9b-bc81-4fa0-900c-941f74f9cf9c)

**Comment by negia7014** [comment]
could you assign this issue to me

**Comment by DARSHANITRIPATHI** [comment]
please assign this task to me

**Comment by Sathya-reddy1658** [comment]
i would like work on this issue , please assign me issue , i had long experience in dealing with headers and footers

**Comment by Aditya3426** [comment]
@apu52  @GSSoC'24 Sir I want to work on this project 
I have 2 years of experience in web technologies 
For more info you can visit my website  synthix.in

**Comment by Priyanshu2631** [comment]
Sir please assign this issue to me, I can try working on the header part

**Comment by anshmanitripathi** [comment]
i want to work on this assign this to me.

**Comment by Mohammed-790** [comment]
Sir please assign this issue to me i will give my best

**Comment by Godavarikadam** [comment]
navbar styling is not looking good and login button is appearing half hidden on laptop screen .So want to enhace nav section
GSSoC 2024

**Comment by ShivamPant1321** [comment]
Would like to contribute to solve this.
Please assign this to me.

**Comment by apu52** [comment]
@negia7014 WELCOME to TRAVEL_WEBSITE.
Please use the issue templates to raise the issues to make it clearer.

![image](https://github.com/apu52/Travel_Website/assets/114172928/e0abd555-9271-44ee-99eb-77c4540ea97a)
Use this templates to raise this issue again

Sorry to close this issue.
