### ISSUE TITLE
Bug - Asymmetric Design in Destination Section - Image Box Sizes

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#31]
Issue Description
There is a design inconsistency within the Destination section where image boxes vary in size, leading to an asymmetric layout. To enhance the visual appeal and maintain a cohesive design, we need to address this issue by making the image boxes symmetric in size.
![image](https://github.com/apu52/Travel_Website/assets/136263179/f29dccbd-d206-4f41-aab1-2793c6853272)Proposed Changes
Standardize the size of image boxes within the Destination section for a uniform and balanced layout.
Adjust the dimensions of images or containers to ensure a symmetric presentation.
Additional Information
A symmetric design contributes to a polished and professional look, improving the overall user experience.
Test the changes across different screen sizes to guarantee responsiveness.
Let's work together to create a visually pleasing and consistent layout within the Destination section by addressing this design asymmetry.

**Comment by rahat2134** [comment]
@apu52 want to work under JWOC, assign me this.

**Comment by apu52** [comment]
@rahat2134 I will assign you this issue only after the completion of the previous assigned issue's PR

**Comment by apu52** [comment]
@rahat2134 You are assigned on this issue. you can start working
You have 1 day to complete this issue
