### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by negia7014** [apu52/Travel_Website#310]
There is an issue in navbar like Login are misallignment and many more
please assign this issue to me i have experience in fronted.

![image](https://github.com/apu52/Travel_Website/assets/111852535/a85bebf8-b35a-4444-a249-6bff457a1639)

**Comment by MahawarHemlata** [comment]
I can fix it, can you please assign it to me under GSSOC'24

**Comment by yash-reddy01** [comment]
I can fix this with responsive behaviour please assign to me under GSSOC'24

**Comment by apu52** [comment]
@negia7014 
![image](https://github.com/apu52/Travel_Website/assets/114172928/3fe40d51-87f3-406d-875b-d2adda56fb89)
use this templates to raise the issues to make it clearer please
sorry to close this issue.
