### ISSUE TITLE
Improve the video player section

### ISSUE THREAD

**Issue by sujayx07** [apu52/Travel_Website#318]
Video player section is defaulted version of video player. It can be easily improved and styled it very proper way...

**It will be with good styling and good player buttons.**

![download](https://github.com/apu52/Travel_Website/assets/149602382/874661a2-fca6-4eaa-a77e-df4e2b2e801b)

**Very old and outdated style...**

***GSSOC***

**Comment by apu52** [comment]
@SujayDeyTMSL I have assigned you . start working on this issue.

**Comment by ananyag309** [comment]
Hey, I am looking forward to fix the issue. Please assign it to me under gssoc.

**Comment by itsekta** [comment]
Hey @ananyag309, you can start working on this issue
