### ISSUE TITLE
Improve the UI of the RATE US Page

### ISSUE THREAD

**Issue by rhea164** [apu52/Travel_Website#319]
The fonts and colours are not entirely appealing. The overall User Experience can be improved.

I would like to apply colour theory to propose a better page overall and use better font styles. The header can also be improved. Kindly assign this task to me so that I can work on it.

<img width="1420" alt="Screenshot 2024-05-10 at 10 03 06 AM" src="https://github.com/apu52/Travel_Website/assets/158840696/254b4f93-5c1a-4635-a378-d139dc438264">

**Comment by sinhaudita** [comment]
I am a frontend web developer and can design attractive UI designs. The rate us section seems to be not so appealing but I can make it catchy by implementing some good UI. So kindly assign this task to me as a part of GSSOC'24.

**Comment by ChandelAnish** [comment]
can you please label the issue

**Comment by HimanshiGoel10** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by shnwz-solves** [comment]
Hey PA, I would like to work on this issue. Please assign it to me. Thankyou!

**Comment by apu52** [comment]
@rhea164 I have assigned you . You can Start Working 
Welcome to the issue

**Comment by rhea164** [comment]
> @rhea164 I have assigned you . You can Start Working Welcome to the issue Are you contributing under GSSOC'24??

yes I am contributing under GSSOC'24. I will start working on the issue

**Comment by rhea164** [comment]
I have submitted a PR regarding this issue.
