### ISSUE TITLE
🚨⚠️NEW ISSUE WELCOME(JWOC 2k24) 🔔🌟

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#32]
### **Now , you all can make any NEW issues you want to work on this REPO** 
That maybe includes
- Bug fixing
- Enhancement
- Documentation

**Comment by 13AdityaDey** [comment]
I can make a toggle button , that will change the website theme from light to dark.

Before clicking the button:
![Screenshot 2024-01-15 231716](https://github.com/apu52/Travel_Website/assets/140962818/aee3546b-9298-4862-9bc2-bc4d26de72ef)

After clicking the button:
![Screenshot 2024-01-15 233015](https://github.com/apu52/Travel_Website/assets/140962818/702b905b-933b-4a55-8d48-266c5db22e80)
@JWOC 2024

**Comment by apu52** [comment]
> I can make a toggle button , that will change the website theme from light to dark.
> 
> Before clicking the button: ![Screenshot 2024-01-15 231716](https://private-user-images.githubusercontent.com/140962818/296834596-aee3546b-9298-4862-9bc2-bc4d26de72ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDgyMzQsIm5iZiI6MTcwNTM0NzkzNCwicGF0aCI6Ii8xNDA5NjI4MTgvMjk2ODM0NTk2LWFlZTM1NDZiLTkyOTgtNDg2Mi05YmMyLWJjNGQyNmRlNzJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxOTQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWIyMTA2NmYwNzI2YTczYTAzNzEzYWI0N2M0NjFmMWZkNDU3MjY3ZDIzNTgyY2U2Y2YwNDk2MGQxZjBlZmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAZyEERMGj-G5llQz7JzcfnX6Cb8uikZQRA345o2TWM)
> 
> After clicking the button: ![Screenshot 2024-01-15 233015](https://private-user-images.githubusercontent.com/140962818/296835073-702b905b-933b-4a55-8d48-266c5db22e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDgyMzQsIm5iZiI6MTcwNTM0NzkzNCwicGF0aCI6Ii8xNDA5NjI4MTgvMjk2ODM1MDczLTcwMmI5MDViLTkzM2ItNGE1NS04ZDQ4LTI2NmM1ZGIyMmU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxOTQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmRiMjk4Yjc0MGNhMTY4M2Q2MjAyMDg4NGVjNTc3NmFkOGRjNTM4YzE0MjVmNzQ3OGQxZjc1ZjZiNGEzMDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F4yxBEiVxEZPwMycVbOr-iKfczgXm7yKzS0nl49bHIA) @jWoc 2024
> 
> ASSIGN ME THIS ISSUE

Nice issue. Just make a proper new issue with all the details & all the SS using issue templates

**Comment by 13AdityaDey** [comment]
> > I can make a toggle button , that will change the website theme from light to dark.
> > Before clicking the button: ![Screenshot 2024-01-15 231716](https://private-user-images.githubusercontent.com/140962818/296834596-aee3546b-9298-4862-9bc2-bc4d26de72ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDgyMzQsIm5iZiI6MTcwNTM0NzkzNCwicGF0aCI6Ii8xNDA5NjI4MTgvMjk2ODM0NTk2LWFlZTM1NDZiLTkyOTgtNDg2Mi05YmMyLWJjNGQyNmRlNzJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxOTQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWIyMTA2NmYwNzI2YTczYTAzNzEzYWI0N2M0NjFmMWZkNDU3MjY3ZDIzNTgyY2U2Y2YwNDk2MGQxZjBlZmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAZyEERMGj-G5llQz7JzcfnX6Cb8uikZQRA345o2TWM)
> > After clicking the button: ![Screenshot 2024-01-15 233015](https://private-user-images.githubusercontent.com/140962818/296835073-702b905b-933b-4a55-8d48-266c5db22e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDgyMzQsIm5iZiI6MTcwNTM0NzkzNCwicGF0aCI6Ii8xNDA5NjI4MTgvMjk2ODM1MDczLTcwMmI5MDViLTkzM2ItNGE1NS04ZDQ4LTI2NmM1ZGIyMmU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxOTQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmRiMjk4Yjc0MGNhMTY4M2Q2MjAyMDg4NGVjNTc3NmFkOGRjNTM4YzE0MjVmNzQ3OGQxZjc1ZjZiNGEzMDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F4yxBEiVxEZPwMycVbOr-iKfczgXm7yKzS0nl49bHIA) @jWoc 2024
> > ASSIGN ME THIS ISSUE
> 
> Nice issue. Just make a proper new issue with all the details & with all the SS using issue templates

Sir i just created a new issue with all details and with the given template. Please find the attachment and confirm.
