### ISSUE TITLE
[BUG] Sidebar UI issue

### ISSUE THREAD

**Issue by Ankitapanda25** [apu52/Travel_Website#320]
The contents in the sidebar isnt aligned properly. 
and also the contents on hover, should have a change in its styling whereas the about link is already coloured

<img width="1079" alt="image" src="https://github.com/apu52/Travel_Website/assets/123666302/37951def-f5f3-4891-82a1-957eba21a7e2">

Please allow me to work on this issue and kindly assign me this under GSSOC'24

**Comment by MahawarHemlata** [comment]
@apu52 I can fix this issue, please assign it to me under GSSoC'24.

**Comment by Bhoomii2003** [comment]
I can fix this issue, please assign it to me under GSSoC'24.

**Comment by Neh2005** [comment]
Please assign this to me under GSSoC'24.

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by apu52** [comment]
@Ankitapanda25 Welcome to the issue.
I have assigned you . you can start working on this issue.
