### ISSUE TITLE
[Feature_Request] UI improvement in booking page

### ISSUE THREAD

**Issue by Ankitapanda25** [apu52/Travel_Website#321]
The UI in the booking page isnt interactive, both the design and the font and lacks responsiveness in mobile view.

<img width="187" alt="image" src="https://github.com/apu52/Travel_Website/assets/123666302/40d3b00f-0787-4200-b717-088b9362b9fc">

I have worked on UI on my personal projects. Please allow me to work on this issue and kindly assign me this under GSSOC'24

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project as a part of GSSOC 2024. I am a Frontend developer and I have worked on several projects and won hackathons as well. I can make ui improvements in the page. 

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by S-Siri** [comment]
Hey worked on many similar projects please assign me this task.

**Comment by apu52** [comment]
@Ankitapanda25 As I have already assigned you to another issue , as per the rule of the repo , I can't assign you this issue . Try to complete the already assigned issue.

**Comment by nakshatravyas** [comment]
> @nakshatravyas I am assigning you on this issue. Start working on this issue.

How can i contact you...just want to discuss a little bit more on the enhancement

**Comment by Ghanshyam89** [comment]
Hi @nakshatravyas 

What is the progress on this issue?

Regards
Project Mentor

**Comment by nakshatravyas** [comment]
> Hi @nakshatravyas
> 
> What is the progress on this issue?
> 
> Regards Project Mentor

Hey, i want to discuss about the issue with you. I want to contact you. I have also commented before but i got no reply

**Comment by Ghanshyam89** [comment]
@apu52 do you want to discuss?

**Comment by SaiKishor66** [comment]
Hi,
Can you please assign me this issue. I want to contribute to solve the issue under GSSOC 2024?

**Comment by apu52** [comment]
> @apu52 do you want to discuss?

yes .I will discuss

**Comment by apu52** [comment]
> > Hi @nakshatravyas
> > What is the progress on this issue?
> > Regards Project Mentor
> 
> Hey, i want to discuss about the issue with you. I want to contact you. I have also commented before but i got no reply

Sorry for the late reply . You can contact me through DISCORD if you need .
My Discord ID : apuscorner

DM me there on which you want to talk with me
