### ISSUE TITLE
[Feature_Request] A new Testimonial page

### ISSUE THREAD

**Issue by Ankitapanda25** [apu52/Travel_Website#322]
A new testimonial page is required

I have a few ideas for the ui of that page

Please assign me this under GSSOC'24

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project as a part of GSSOC 2024. I am a Frontend developer and I have worked on several projects and won hackathons as well. I can make the testimonial page. 

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a  full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!

**Comment by apu52** [comment]
@Ashutosh-0506 I have assigned you this issue. You can start working on this issue.

**Comment by Ashutosh-0506** [comment]
> @Ashutosh-0506 I have assigned you this issue. You can start working on this issue.

Thank You For assigning me this issue! I will begin right away.

**Comment by Ashutosh-0506** [comment]
@apu52  I've finished the task and submitted a PR on GitHub regarding the issue. Kindly review my work, please!

**Comment by Iamkg11** [comment]
I'd like to work on this issue. Please assign it under GSSOC
