### ISSUE TITLE
BUG: DARKMODE ENABLE

### ISSUE THREAD

**Issue by Manishak798** [apu52/Travel_Website#323]
**Describe the bug**
When I enabled the dark mode and refreshed the page it automatically converted to light mode, that leads to bad UX.

**Expected behavior**
When dark mode is enabled it should not automatically convert to light mode until unless user does this by themselves.

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
I am a **MENTOR** in **GSSOC'24** raising this issue for contributors to kickstart there contribution journey.

**Comment by MahawarHemlata** [comment]
@apu52 I can fix this issue, please assign it to me under GSSoC'24

**Comment by sinhaudita** [comment]
Kindly assign this to me under GSSoC'24, I can fix it.

**Comment by shivi028** [comment]
can you assign me this issue?

**Comment by Parishri07** [comment]
I can resolve this issue, please assign this task to me.

**Comment by krish-san** [comment]
hello, I'm confident about fixing this issue very soon. Please assign me this issue under GSSoc'24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by manassachdeva** [comment]
Hello I am Manas from PSIT Kanpur.
I can resolve this issue, please assign this task to me.

**Comment by apu52** [comment]
> **Describe the bug** When I enabled the dark mode and refreshed the page it automatically converted to light mode, that leads to bad UX.
> 
> **Expected behavior** When dark mode is enabled it should not automatically convert to light mode until unless user does this by themselves.
> 
> **Screenshots (Mandatory)**
> 
> **Additional Context (Mandatory )**
> 
> _**Are you contributing under any open-source program ?**_ I am a **MENTOR** in **GSSOC'24** raising this issue for contributors to kickstart there contribution journey.

@Manishak798 Thanks for raising this issue. thanks for the help
