### ISSUE TITLE
Feature_Request: ENABLE GITHUB ACTIONS to Greet Users and Comment on PR

### ISSUE THREAD

**Issue by Manishak798** [apu52/Travel_Website#324]
**Is your feature request related to a problem? Please describe.**
No.

***Are you contributing under any open-source program ?***
I am a **MENTOR** in **GSSOC'24** raising this issue for contributors.

**Comment by apu52** [comment]
### I am calling all the Contributors to Check out this ISSUE & comment first to get this issue Assigned to you.
The issue will be assigned on First come first serve basis.

**Comment by aindree-2005** [comment]
@apu52 can I work on this?

**Comment by apu52** [comment]
> @apu52 can I work on this?

Yes you can. Thanks for Commenting first . You are assigned. You can start working
