### ISSUE TITLE
Feature_Request : UI improvement for Destinations section

### ISSUE THREAD

**Issue by sinhaudita** [apu52/Travel_Website#326]
Title: Enhance the UI of Description section of this website

Solution:
I have got some ideas to make this section look enhanced and more attractive by implementing some unique designs using cards and some other stuffs.

![Screenshot 2024-05-10 140900](https://github.com/apu52/Travel_Website/assets/126314871/bb6c39ee-0501-4581-a946-81e838294424)
![Screenshot 2024-05-10 140918](https://github.com/apu52/Travel_Website/assets/126314871/1a2676f4-d598-4cb6-bee4-938b4422fe03)

 Kindly assign this task to me under GSSOC'24 for an attractive look for Description section.

**Comment by apu52** [comment]
@sinhaudita you are assigned. start working on the issues

**Comment by sinhaudita** [comment]
I have made a PR regarding the changes, please review it and let me know if there has to be any changes.
