### ISSUE TITLE
Better and optimal Organisation of the files in the Repo

### ISSUE THREAD

**Issue by nishantharkut** [apu52/Travel_Website#327]
**Is your feature request related to a problem? Please describe.**
The Files are not Organised Properly, it gets difficult for others to make changes and PRs/

**Describe the solution you'd like**
I will make Designated Folders for the Specified files

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/156298209/13d28b50-8ade-4b16-b2e2-8e92d6c5301d)

***Are you contributing under any open-source program ?***
Please Assign to me Under GSSoC'24

**Comment by apu52** [comment]
@nishantharkut I have assigned you . You can start working . just make sure no to hamper the DEPLOYMENT part & not any one's code

**Comment by itsekta** [comment]
Hey @nishantharkut, are you working on this issue?
