### ISSUE TITLE
Web-Responsiveness of the website, it is not displaying properly on all devices.

### ISSUE THREAD

**Issue by nishantharkut** [apu52/Travel_Website#328]
**Describe the bug**
The responsiveness of the website is extremely bad, it is not loading the elements properly on different devices.

**Expected behavior**
The Website should be apt and Responsive according to the device capability

**Screenshots (Mandatory)**
![WhatsApp Image 2024-05-10 at 14 24 08_1535c601](https://github.com/apu52/Travel_Website/assets/156298209/54de29be-e1a3-4268-bd31-6f7cb2302e23)
![WhatsApp Image 2024-05-10 at 14 24 08_2821029d](https://github.com/apu52/Travel_Website/assets/156298209/b9af2c8a-6dcc-4b70-b801-e765366e5017)

**Additional Context (Mandatory )**
All websites in today's world are responsive to the different devices, i will make the website responsive

***Are you contributing under any open-source program ?***

**Comment by maverickcodex18** [comment]
i can help you with this , i have experience in improving responsiveness .
I am Front End Developer , studying at NIT Raipur

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by apu52** [comment]
@nishantharkut Thanks for raising the issue. But as per the rule of this repo . You can get assigned 1 issue at a time. As you are already assigned I can't assign you this issue

**Comment by apu52** [comment]
@maverickcodex18 I am assigning you this issue . Start working on it

**Comment by Ghanshyam89** [comment]
Hi @maverickcodex18 

I am closiing this issue as you are taking more time as expected.
