### ISSUE TITLE
Font OverLapping

### ISSUE THREAD

**Issue by nishantharkut** [apu52/Travel_Website#329]
**Describe the bug**
The Font text in the ending section of the website is getting hidden.

**Expected behavior**
The Text should be clearly visible

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/156298209/d080cbcc-1cf0-4388-b1fc-46aef9ce8724)

**Additional Context (Mandatory )**
All the Texts in the website should be clearly visible for the easy use of the user.

***Are you contributing under any open-source program ?***
**### PLease Assign to me Under GSSoC'24**

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by apu52** [comment]
@nishantharkut Thanks for raising the issue. But as per the rule of this repo . You can get assigned 1 issue at a time. As you are already assigned I can't assign you this issue

**Comment by apu52** [comment]
@Abhishek-0899 You are assigned. start working on this issue

**Comment by apu52** [comment]
> hey @apu52
> 
> My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .
> 
> idea:- By incorporating div CSS and animations, I can make the font immersive
> 
> Please assign this task to me, GSSOC'24 .

this issue is already assigned. please raise new issues in which you want to work on
