### ISSUE TITLE
The Bubbles Animation not looking Good

### ISSUE THREAD

**Issue by nishantharkut** [apu52/Travel_Website#330]
**Describe the bug**
The bubbles animation in the whole website is not looking good

**Expected behavior**
A clear and Minimal UI that goes with your Website's theme will be Good

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/156298209/cecb0bf1-616f-41d4-ac1c-a623a304007c)

**Additional Context (Mandatory )**
The website Loading time gets longer due to the bubbles animation

***Are you contributing under any open-source program ?***
Please Assign to me Under GSSoC'24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by apu52** [comment]
@nishantharkut Thanks for raising the issue. But as per the rule of this repo . You can get assigned 1 issue at a time. As you are already assigned I can't assign you this issue

**Comment by apu52** [comment]
@nishantharkut As this is a really good issue . So I am assigning you this issue this time.. start working on both of the issues.
But from next time please don't raise more than 1 issue at a time so that everyone can get a chance to contribute
