### ISSUE TITLE
Updation in header

### ISSUE THREAD

**Issue by snehamalik09** [apu52/Travel_Website#332]
I'd like to address the appearance of the header section. The font size seems excessive and overall it appears messy. Could you please assign this issue to me so I can work on it as part of GSSOC 2024?

**Comment by PDurgaAnusha** [comment]
I want to solve this issue. please assign this task to me #gssoc contributor

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by apu52** [comment]
@snehamalik09  Welcome to TRAVEL _WEBSITE.
Thanks for raising the issue.
But I will like to recommend you to use the issue templates to make it clearer, more understanding.

![image](https://github.com/apu52/Travel_Website/assets/114172928/0f6ac618-0823-4621-ba5d-c3998f84d159)

Sorry to close this issue. 
But please use the issue templates
