### ISSUE TITLE
Personalization

### ISSUE THREAD

**Issue by mousumideyy** [apu52/Travel_Website#334]
I would like to add:
Personalized Recommendations: Offer personalized recommendations based on user preferences, past bookings, and browsing history, enhancing user experience and satisfaction

Please assign me under GSSoC'24

**Comment by apu52** [comment]
@mousumideyy @SujayDeyTMSL Welcome to TRAVEL _WEBSITE.
Thanks for raising the issue.
But I will like to recommend you to use the issue templates to make it clearer, more understanding.

![image](https://github.com/apu52/Travel_Website/assets/114172928/0f6ac618-0823-4621-ba5d-c3998f84d159)

Sorry to close this issue. 
But please use the issue templates
