### ISSUE TITLE
card hover effect 

### ISSUE THREAD

**Issue by sshivangi882** [apu52/Travel_Website#335]
**Describe the bug**

The card hover effects are not looking good it's taking too much time to hover and go back , the user may finds it iterating

**Expected behavior**

Decreasing the transition time in the card, so that it becomes smooth.

**Screenshots (Mandatory)**

![Screenshot (842)](https://github.com/apu52/Travel_Website/assets/122531720/36ced5c1-e105-4a06-a461-44a7408a3978)

**Additional Context (Mandatory )**
and the bubble effect is also not looking good. let me remove it
***Are you contributing under any open-source program ?***

GSSOC' 24

**Comment by parth3083** [comment]
Hello, I am a frontend developer and I make stunning and modern websites.
I completed an internship as a front-end developer.
I create the frontend in HTML, CSS, and react, and I use js libraries for animations and smooth scrolling.
The following are my works on the hover effect : 
https://ochi-clone-parth.netlify.app/
https://clone-sidcup-golf.netlify.app/

**Comment by PDurgaAnusha** [comment]
I want to work on this issue. Please assign this task to me . I'm an front end developer so that i'll be able to solve this issue

**Comment by themayank1729** [comment]
Good evening ma'am, I know how make it right and to change according to the user's perspective. Please assign this issue to me.
I have also registered for GSSOC 24.

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by sahithinandikula** [comment]
hey there! I would be solving the issue and willing to work on it . I would feel excited to contribute

**Comment by Dev-AyushTrivedi** [comment]
HEY there, could you please assign this issue to me i can resolve it , i have strong command in html, css and javascript, i can dolve this issue i am working as a contributor in GSSOC'24, could you please add labels for GSSOC'24 also

**Comment by harshbisht27** [comment]
Hello I am Harsh from GGSIPU University. I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by drashtigit** [comment]
@apu52 Can you please assign me this issue under GSSOC'24.

**Comment by apu52** [comment]
@sshivangi882 you are assigned

**Comment by Dev-AyushTrivedi** [comment]
@apu52 

HEY there, could you please assign this issue to me i can resolve it , i have strong command in html, css and javascript, i can solve this issue i am working as a contributor in GSSOC'24, could you please add labels for GSSOC'24 also
