### ISSUE TITLE
BUG: Card Hover Effect in Testimonials Section

### ISSUE THREAD

**Issue by aanchalpahuja18** [apu52/Travel_Website#336]
![image](https://github.com/apu52/Travel_Website/assets/136963878/9928094f-ad76-4ed5-bf27-ddcd6da70ca5)

**Comment by aanchalpahuja18** [comment]
@apu52 Kindly assign me this issue I will sort it out

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project as a part of GSSOC 2024. I am a Frontend developer and I have worked on several projects and won hackathons as well. I can make hover effect in the testimonial page. 

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a  full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!

**Comment by Parishri07** [comment]
I can resolve this issue of card hovering effect, please assign this task to me.

**Comment by apu52** [comment]
@aanchalpahuja18 @SujayDeyTMSL Welcome to TRAVEL _WEBSITE.
Thanks for raising the issue.
But I will like to recommend you to use the issue templates to make it clearer, more understanding.

![image](https://github.com/apu52/Travel_Website/assets/114172928/0f6ac618-0823-4621-ba5d-c3998f84d159)

Sorry to close this issue. 
But please use the issue templates
