### ISSUE TITLE
BUG in copyright

### ISSUE THREAD

**Issue by Meetjain1** [apu52/Travel_Website#337]
**Describe the bug**
 copyright is displaying website created year not the current year , i.e it is showing 2023 rather than 2024 

**Expected behavior**
It will display current year i.e 2024 till 31st dec 2024 , and in 2025 it will automatically display 2025

***Are you contributing under any open-source program ?***
I am contributing under gssoc24

@apu52 Please assign this issue to me I will fix it .

**Comment by richasriva** [comment]
Please assign this issue to me. I am contributing under gssoc24.

**Comment by StutiSingh04** [comment]
Please assign this issue to me.

**Comment by Meetjain1** [comment]
@apu52 sir, I have just created a pr #429 please have a look on it . Thankyou
