### ISSUE TITLE
Social media links Feature_Request

### ISSUE THREAD

**Issue by Meetjain1** [apu52/Travel_Website#338]
**Is your feature request related to a problem? Please describe.**
I think there should be some social media links that should present in footer section

**Describe the solution you'd like**
I will add social media links with icons in footer , contact us section

***Are you contributing under any open-source program ?***
I am working under gssoc24

please assign this issue to me I will work on it and fix this issue . Thankyou @apu52 sir

**Comment by StutiSingh04** [comment]
please assign this issue to me

**Comment by Meetjain1** [comment]
@apu52 sir can you tell me which social media platforms I have to add in footer and also provide the links of the same so that I can add , Thankyou .

**Comment by Meetjain1** [comment]
> @apu52 sir can you tell me which social media platforms I have to add in footer and also provide the links of the same so that I can add , Thankyou .

@apu52 sir ?

**Comment by Meetjain1** [comment]
> > @apu52 sir can you tell me which social media platforms I have to add in footer and also provide the links of the same so that I can add , Thankyou .
> 
> @apu52 sir ?

@apu52

**Comment by apu52** [comment]
> > @apu52 sir can you tell me which social media platforms I have to add in footer and also provide the links of the same so that I can add , Thankyou .
> 
> @apu52 sir ?

Sorry for the late reply. Extremely sorry .

You can add Instagram , mail , facebook , linkedin , twitter(X) social platform icons in the footer sections 

@Meetjain1

**Comment by Meetjain1** [comment]
> > > @apu52 sir can you tell me which social media platforms I have to add in footer and also provide the links of the same so that I can add , Thankyou .
> > 
> > 
> > @apu52 sir ?
> 
> Sorry for the late reply. Extremely sorry .
> 
> You can add Instagram , mail , facebook , linkedin , twitter(X) social platform icons in the footer sections
> 
> @Meetjain1

Can you provide the links of these social accounts

**Comment by apu52** [comment]
> > > > @apu52 sir can you tell me which social media platforms I have to add in footer and also provide the links of the same so that I can add , Thankyou .
> > > 
> > > 
> > > @apu52 sir ?
> > 
> > 
> > Sorry for the late reply. Extremely sorry .
> > You can add Instagram , mail , facebook , linkedin , twitter(X) social platform icons in the footer sections
> > @Meetjain1
> 
> Can you provide the links of these social accounts so that i can add it. @apu52

As for now , there is no official pages in any social media platform for this website , So Just add the icons now.
