### ISSUE TITLE
Google authentication in login page_BUG

### ISSUE THREAD

**Issue by Meetjain1** [apu52/Travel_Website#339]
**Describe the bug**
Google authentication is not working in login page 

**Expected behavior**
It should open google accounts on clicking sign in via a google account 

***Are you contributing under any open-source program ?***
I am working under gssoc24 , @apu52 sir please assign this issue to me , Thankyou

**Comment by ritankarsaha** [comment]
Please assign this issue to me #GSSOC'24. I would use NextAuth for efficient authentication

**Comment by apu52** [comment]
#268 Is already assigned . sorry to close this issue

**Comment by Meetjain1** [comment]
@apu52 no issue sir , Thank-you
