### ISSUE TITLE
FEATURE_REQUEST : Adding Animation to Our Trip Section

### ISSUE THREAD

**Issue by Prithwi32** [apu52/Travel_Website#34]
**Is your feature request related to a problem? Please describe.**
No it's actually not a problem, its aim is to give better user experience.

**Describe the solution you'd like**
I would like to add rotating image gallery to your 'Our Trip Gallery' Section. So that makes this website more attractive.

**Describe alternatives you've considered**
If you doesn't like to include rotating gallery feature, I can add any other framework components

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-01-15 014932](https://github.com/apu52/Travel_Website/assets/115262737/7e52025e-bf02-4ba2-bd85-87cc9683deb2)

***Are you contributing under any open-source program ?***

under JWOC 2024.

**Comment by Prithwi32** [comment]
@apu52  I want to work on that issue under JWOC 2024

**Comment by apu52** [comment]
@Prithwi32 Welcome to the repo!!!!!!!
Please fill up the issue with proper templates which is already given

![image](https://github.com/apu52/Travel_Website/assets/114172928/328030fd-d0e4-4519-a364-13d806f1a0d0)

**Comment by Prithwi32** [comment]
> @Prithwi32 Welcome to the repo!!!!!!! Please fill up the issue with proper templates which is already given
> 
> ![image](https://private-user-images.githubusercontent.com/114172928/296648421-328030fd-d0e4-4519-a364-13d806f1a0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTMxMzEsIm5iZiI6MTcwNTI5MjgzMSwicGF0aCI6Ii8xMTQxNzI5MjgvMjk2NjQ4NDIxLTMyODAzMGZkLWQwZTQtNDUxOS1hMzY0LTEzZDgwNmYxYTBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNDI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGMwM2E1YmU0YTUxMGQwMzM1MDUyYzMyMmExODY2MWY5YTkzZjczYjExZjM3NDE1Y2RlYTk0OThiNDNkMTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fd8SyC_rXwTPSHVemj0FwnzK_SSOEC3uw4iztSUGmsQ)

@apu52 sorry I didn't got it what you mean.. Please could you let me know what should be my next step...

**Comment by apu52** [comment]
> > @Prithwi32 Welcome to the repo!!!!!!! Please fill up the issue with proper templates which is already given
> > ![image](https://private-user-images.githubusercontent.com/114172928/296648421-328030fd-d0e4-4519-a364-13d806f1a0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTMxMzEsIm5iZiI6MTcwNTI5MjgzMSwicGF0aCI6Ii8xMTQxNzI5MjgvMjk2NjQ4NDIxLTMyODAzMGZkLWQwZTQtNDUxOS1hMzY0LTEzZDgwNmYxYTBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNDI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGMwM2E1YmU0YTUxMGQwMzM1MDUyYzMyMmExODY2MWY5YTkzZjczYjExZjM3NDE1Y2RlYTk0OThiNDNkMTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fd8SyC_rXwTPSHVemj0FwnzK_SSOEC3uw4iztSUGmsQ)
> 
> @apu52 sorry I didn't got it what you mean.. Please could you let me know what should be my next step...

please use the FEATURE_REQUEST template from the NEW ISSUE section to raise your issue

**Comment by Prithwi32** [comment]
> **Is your feature request related to a problem? Please describe.** No it's actually not a problem, its aim is to give better user experience.
> 
> **Describe the solution you'd like** I would like to add rotating image gallery to your 'Our Trip Gallery' Section. So that makes this website more attractive.
> 
> **Describe alternatives you've considered** If you doesn't like to include rotating gallery feature, I can add any other framework components
> 
> **Demo Video/Screenshot (Mandatory )** ![Screenshot 2024-01-15 014932](https://private-user-images.githubusercontent.com/115262737/296614724-7e52025e-bf02-4ba2-bd85-87cc9683deb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTI1NzksIm5iZiI6MTcwNTMxMjI3OSwicGF0aCI6Ii8xMTUyNjI3MzcvMjk2NjE0NzI0LTdlNTIwMjVlLWJmMDItNGJhMi1iZDg1LTg3Y2M5NjgzZGViMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwOTUxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjRjNjFmYWY5ZWIzZDVkODBkYjVhYmM2MWM5MWU1MTgyMGZmNmI2OGE4OTU3YTAyODczMWY2YjkxNjk1Y2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.728xoc3Mk9Rx8A2cAk00FYEVy8mTwl6g4OTRlhsGu14)
> 
> _**Are you contributing under any open-source program ?**_
> 
> under JWOC 2024.

@apu52  is this okay now?

**Comment by apu52** [comment]
@Prithwi32 I have assigned you . You can now start working on it.

**Comment by Prithwi32** [comment]
> @Prithwi32 I have assigned you . You can now start working on it.

Sure Sir..Thank You!

**Comment by apu52** [comment]
@Prithwi32 You have 2-3 days for submitting your PR.

**Comment by Prithwi32** [comment]
> @Prithwi32 You have 2-3 days for submitting your PR.

Okay I will complete asap..
