### ISSUE TITLE
Typography needs to be Improved

### ISSUE THREAD

**Issue by nishantharkut** [apu52/Travel_Website#340]
Typography is crucial in communication, enhancing readability, evoking emotions, and conveying messages effectively. It dictates tone, guides the eye, and influences perceptions. Through font choice, size, spacing, and alignment, typography shapes brand identity, user experience, and overall design aesthetics. It's the silent conductor of visual language, wielding immense power in expression.

**Comment by paridhi1509** [comment]
I would like to work on this issue.
Please assign it to me

**Comment by Deathnote45** [comment]
hi, I want to work on this issue under gssoc'24.
my profile: https://www.linkedin.com/in/shuvangi-de-369071236/

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by shruti110503** [comment]
I am interested in working on this issue. Please assign it to me

**Comment by apu52** [comment]
@nishantharkut  Welcome to TRAVEL _WEBSITE.
Thanks for raising the issue.
But I will like to recommend you to use the issue templates to make it clearer, more understanding.

![image](https://github.com/apu52/Travel_Website/assets/114172928/0f6ac618-0823-4621-ba5d-c3998f84d159)

Sorry to close this issue. 
But please use the issue templates
