### ISSUE TITLE
Website Not Responsive

### ISSUE THREAD

**Issue by nish1502** [apu52/Travel_Website#341]
**Describe the bug**
Website is not responsive
@apu52 

**Expected behavior**
website will become responsive

**Screenshots (Mandatory)**
![Screenshot 2024-05-10 at 7 04 02 PM](https://github.com/apu52/Travel_Website/assets/127622453/0141560b-dac3-4e32-bf58-29e82d9ac17c)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSoC '24

**Comment by PDurgaAnusha** [comment]
please label the issue

**Comment by HarshSDE0** [comment]
Hey there! I'm Harsh Abhishek from #GSSOC 2024. I'm a MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,java.
Sample Live project link: https://harshsde0.github.io/1-1personaltraining/
LinkedIn profile: https://www.linkedin.com/in/harsh-abhishek-463359222/

**Comment by Parishri07** [comment]
I can resolve this issue of making the website responsive. Please assign this task to me.

**Comment by maverickcodex18** [comment]
Hey there assign me the issue , i have experience in resolving this kind of issues.
I am a MERN Developer from NIT Raipur

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by gupta-ritik** [comment]
Please assign this task to me.

**Comment by shraddhalute** [comment]
I am prepared to work on resolving the issue with the website not being responsive. Kindly assign this task to me for resolution. Thank you.

**Comment by wilsonprodige** [comment]
Hey there, I am wilson zeugang a fullstack js developer, Making this page responsive will be a matter of hours, within which the results will really be appreciated please assign me the issue

**Comment by apu52** [comment]
#328 is already there on this same topic. Thanks for raising the issue but Sorry to close this issue
