### ISSUE TITLE
'Login' button not working on the Login Page

### ISSUE THREAD

**Issue by avanimathur** [apu52/Travel_Website#342]
Currently, on clicking the 'Login' Button, nothing happens.

Expected Behaviour:
After clicking on the Login button, the user should be led to the Home page. 

![Screenshot (208)](https://github.com/apu52/Travel_Website/assets/151984867/30444f2d-e281-469c-85e8-bbadbe652a67)

This is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign this issue to me.

**Comment by Neh2005** [comment]
Please assign this issue to me

**Comment by Muskansingh-19** [comment]
Please assign this issue to me

**Comment by sreehithaAdari** [comment]
I can resolve the issue , Assign this issue to me!

**Comment by gargimukherjee25** [comment]
Hello 
 I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by Diwakar124** [comment]
hello , 
I can resolve the issue , Assign this issue to me! i am working html, css.and js

**Comment by FatemaBaig** [comment]
Hello,
i would like to work on this part of project. Please assign it to me.

**Comment by richasriva** [comment]
Hello, Kindly assign this issue to me, I can fix this issue in less time.

**Comment by S-Siri** [comment]
Hello
I am Siri! I worked on such projects before. I'd appreciate being assigned this task for GSSoC 24.

**Comment by skrahmatullahgousi** [comment]
Hello 
sir can please assign this issue to me sir

**Comment by harikasayani** [comment]
Hi,
I am GSSOC'24 Contributor. Could you please assign this issue to me. I can handle it.

**Comment by vignesh-0512** [comment]
Hello @avanimathur i have good experience in html, css and Javascript also i have worked on projects so i would like to assign me this issue under Gssoc'24 i believe that i can able to fix this issue and raise a PR as soon as possible.

**Comment by gundellyvamshiyadav** [comment]
Hello! I'm a GSSOC'24 contributor and I'm interested in working on this issue. Could you please assign it to me?

**Comment by apu52** [comment]
#264 is already present there. on the same topic . Thanks for raising the issue . But sorry to close this issue
