### ISSUE TITLE
Issue with the registration on the Login page.

### ISSUE THREAD

**Issue by avanimathur** [apu52/Travel_Website#343]
**Describe the bug**
Currently, on clicking 'Register' button without entering any details, the page simply refreshes.
Name, Email and Password need to be a required field.

**Expected behavior**
It should display a message saying 'Please fill this field.'

**Screenshots**
[screen-capture.webm](https://github.com/apu52/Travel_Website/assets/151984867/db3565e3-0126-4193-9464-5710ef6be913)(video)
![Screenshot (208)](https://github.com/apu52/Travel_Website/assets/151984867/9402d8c2-4a73-4331-acda-d648fe23ffaa)

***Are you contributing under any open-source program ?***
This is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign it to me.

**Comment by Neh2005** [comment]
Please assign this to me

**Comment by aditi2805** [comment]
Please assign this to me, I'll try best to fix it

**Comment by sreehithaAdari** [comment]
Hey! I can resolve this issue in less time! Can you assign me?

**Comment by Debarunn1806** [comment]
Hello I am Debarun Chakrabortty and am contributing under GSSoC'24 , I would request you to assign this issue to me. Thankyou

**Comment by Yateeshapappala** [comment]
I want to work on this part of project please assign it to me under GSSOC-24

**Comment by Abhigna-arsam** [comment]
#343 Issue with the registration on the Login page
I want to contribute to the above issue ,can you please assign me this work because I can do it fast and efficient.

**Comment by harinisayani** [comment]
Hi,
I am contributing under GSSOC'24.I am having experience on developing web development projects and I can handle this issue. Could please assign it to me.

**Comment by apu52** [comment]
@avanimathur You are assigned . you can start working on this issue
