### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by NAVJOT-786** [apu52/Travel_Website#345]
**Describe the bug**
When navigating from the story.html page back to the index.html page's testimonial section by clicking on the testimonial link in the navigation bar, the user is not directed to the testimonial section as expected same issue for the other section trip gallery,about us
 

**Expected behavior**
Clicking on the testimonial link in the navigation bar on the story.html page should take the user back to the testimonial section on the index.html page. 

**Screenshots (Mandatory)**

<img width="1406" alt="Screenshot 2024-05-10 at 7 54 42 PM" src="https://github.com/apu52/Travel_Website/assets/109761760/1221e3da-70dd-4421-aca4-90ec77a33804">
<img width="819" alt="Screenshot 2024-05-10 at 7 55 25 PM" src="https://github.com/apu52/Travel_Website/assets/109761760/f6bf3540-e11a-4ab1-b5c9-d5579b54cf9e">
<img width="882" alt="Screenshot 2024-05-10 at 7 55 35 PM" src="https://github.com/apu52/Travel_Website/assets/109761760/b4042ef2-ca1d-4dbb-84b5-794a9ca193bc">

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

yes i am contributing under GSSoc24 open source Program .Please assign me this issue.

**Comment by paridhi1509** [comment]
I would like to work on this issue
Please assign it to me

**Comment by NAVJOT-786** [comment]
@apu52 please assign the issue

**Comment by apu52** [comment]
@NAVJOT-786 You are assigned . you can start working

**Comment by NAVJOT-786** [comment]
thanks @apu52
