### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by anushreemehta6** [apu52/Travel_Website#349]
**Is your feature request related to a problem? Please describe.**

i want to remove the bubble animation its not looking good , and i have some other formating to change .

**Describe the solution you'd like**

remove the bubble animation , change some lines in home page and many more css formating 

**Describe alternatives you've considered**

dh

**Demo Video/Screenshot (Mandatory )**
 
![Screenshot (411)](https://github.com/apu52/Travel_Website/assets/104919688/9fa2f8bb-5796-41a3-a54f-821c29bfa36e)

***Are you contributing under any open-source program ?***

Please Assign to me Under GSSoC'24

@apu52

**Comment by gargimukherjee25** [comment]
Hello @apu52  I am Gargi! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by apu52** [comment]
@anushreemehta6 thanks for raising the issue .
But this issue is already assigned #330 .
Sorry to close this issue. but you can start working on any other issues
