### ISSUE TITLE
Enhancement - Connect Contact Us Button to Admin's LinkedIn or Email 

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#35]
Issue Description
To improve the accessibility and responsiveness of the website, let's enhance the "Contact Us" button by connecting it directly to the admin's LinkedIn profile or email address. This will allow users to reach out to the administration more conveniently.
![image](https://github.com/apu52/Travel_Website/assets/136263179/35312cd7-17aa-44e7-9d7c-c224260547e3)

Proposed Changes
Implement a link in the "Contact Us" button that redirects users to the admin's LinkedIn profile or opens the default email client with the admin's email address pre-filled.
Ensure that the chosen method aligns with user preferences for communication.

Additional Information
A direct link to the admin's LinkedIn or email will streamline communication and enhance user experience.
Verify the admin's preferred contact method (LinkedIn or Email) before implementing the change.
Let's work together to make the "Contact Us" button more effective and user-friendly.

**Comment by rahat2134** [comment]
@apu52 assign me this under JWOC after my current issue

**Comment by Hacxmr** [comment]
Hey! @apu52 I am interested in working on this issue. Can you assign me this under JWOC?

**Comment by apu52** [comment]
@rahat2134 It's already stated in the CONTRIBUTING.md file , that don't raise multiple issues at a time.
It's against the rules of this repo

**Comment by apu52** [comment]
> Hey! @apu52 I am interested in working on this issue. Can you assign me this under JWOC?

I will suggest you to raise a new issue you want to work on

**Comment by rahat2134** [comment]
@apu52 assign this issue to me . I want to work under JWOC.

**Comment by SGCODEX** [comment]
I have already covered this under the issue #25

**Comment by apu52** [comment]
@rahat2134 Someone else is already working on the same issue . So sorry to close this issue. Refer : #28 
Happy coding!!!!!!!!!
