### ISSUE TITLE
Scrollbar Missing 

### ISSUE THREAD

**Issue by Hemav009** [apu52/Travel_Website#350]
**Describe the bug**

The content of the page exceeds the viewport height.

**Expected behavior**

Content on page will not  be visible to users completely.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/109607812/49c9f683-62f7-477b-aaa4-313700a27a9d)

**Additional Context (Mandatory )**

in above img the login page is going out of box. i would like work on this issue.please assign me .

Thank You!

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by Rohit153672** [comment]
hello i can work on this issue please assigned this for me it will be helpful

**Comment by sahithinandikula** [comment]
@apu52 I am interested in contributing for this issue

**Comment by harshbisht27** [comment]
Hello i am harsh from GGSIPU University. After carefully reviewing the issue description and requirements, I believe that my skills and experience make me well-suited to tackle this challenge. Allow me to outline why I am particularly excited about this opportunity.
