### ISSUE TITLE
Chatbot restart button is not working properly

### ISSUE THREAD

**Issue by Hemav009** [apu52/Travel_Website#351]
**Describe the bug**

on clicking chatbot restart button it is leading to page reload.

**Expected behavior**

Every time we click on the restart button page gets reloaded.

**Screenshots (Mandatory)**

https://github.com/apu52/Travel_Website/assets/109607812/e9623403-bcf2-4d9f-a220-ba6e51fbcde3

**Additional Context (Mandatory )**

I would like to solve this bug .please assign me ,
Thank YOU!

***Are you contributing under any open-source program ?***

**Comment by mdrehan369** [comment]
Yes I can solve this bug. Please assign this issue to me under GSSOC 2024.

**Comment by NitinSigilipelli** [comment]
please assign this issue to me

**Comment by n14rishitha** [comment]
I would like to work on this issue . so please assign this task to me and Can u please label the issue as GSSoC'24

**Comment by StutiSingh04** [comment]
please assign this issue to me

**Comment by apu52** [comment]
@Hemav009 you are assigned. good issue

**Comment by Tejarella** [comment]
I would like to fix this issue. So please assign this task to me . I am a contributor to GSSoC'24

**Comment by apu52** [comment]
@Hemav009 Where is your PR ??
As I have already assigned you this issue last week . Please try to submit your PR within 3 days

**Comment by Hemav009** [comment]
i will make a PR today.
