### ISSUE TITLE
UI Improvement for Login & Registration web pages

### ISSUE THREAD

**Issue by NitinSigilipelli** [apu52/Travel_Website#352]
**Login and Registration pages**
Login and Registration web pages doesn't match with the theme of landing page

**Assign this issue to me**
 Please assign this work to me I will Improve the UI of the login and registration webpages

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-05-11 020208](https://github.com/apu52/Travel_Website/assets/140246876/c6ec8b53-e55e-4192-a8df-2a6c7c350f95)

***Are you contributing under any open-source program ?***
 GSSOC 2024

**Comment by GAGGZ1** [comment]
hey @apu52 
I propose focusing on UI improvements for the Login & Registration web pages to enhance user experience and aesthetic appeal. With my background in front-end development and UI design, I'm eager to contribute by refining the layout, typography, and overall visual elements. Let's work together to create a more engaging and user-friendly interface.

Looking forward to collaborating on this exciting project!

**Comment by Devansh1508** [comment]
hi  Admin,
I want to contribute to this project. Please assign this work to me and add the GSSoC and level tag to it.

**Comment by vaishnavip27** [comment]
Hey @NitinSigilipelli I would love to work on this issue as i have worked as a designer and a developer both. Please assign me this issue. Looking forward for the approval

**Comment by apu52** [comment]
@NitinSigilipelli you are assigned. thanks for raising the issue . I just would like to request you to just change the overall UI maintaining the current features intact in the login pg

**Comment by anjana-18Singh** [comment]
hey @apu52 ,
 I would like to work on this issue and want to add my contribution to this . Please assign me this issue.Looking forward for your approval.

**Comment by anjana-18Singh** [comment]
hey @apu52 ,
I would like to work on this issue and want to add my contribution to this . Please assign me this issue.Looking forward for your approval.

**Comment by anjana-18Singh** [comment]
hey @NitinSigilipelli 
I would like to work on this issue and want to add my contribution to this . Please assign me this issue.Looking forward for your approval.

**Comment by apu52** [comment]
@anjana-18Singh this issue is already assigned .you can start working on any other issue .
