### ISSUE TITLE
Login using Google,Facebook,Github or Instagram dosen't work

### ISSUE THREAD

**Issue by Debarunn1806** [apu52/Travel_Website#353]
**Describe the bug**
On the login page clicking on any of the options other than email login takes the user back to the same login page again.

**Expected behavior**
It is expected to show options to log in using the chosen option or media(eg : Google login, Github login etc)

**Screenshots (Mandatory)**
![Screenshot 2024-05-11 023520](https://github.com/apu52/Travel_Website/assets/106834322/30810950-2a1b-4e0d-8208-f16ce63cd0b0)

https://github.com/apu52/Travel_Website/assets/106834322/73de8a47-2ae4-4b30-8df9-a1ec9fa12572

**Additional Context (Mandatory )**
There should be options for users to login to the website using preexsiting google or Github accounts instead they are forced to use only one medium of login that is through their email.

***Are you contributing under any open-source program ?***
Yes GSSoC'24

**Comment by dhruv8433** [comment]
i would like to work on this issue, can you please assign it to me...

**Comment by creativeadi** [comment]
Kindly assign me this issue, i would like to make this thing work

**Comment by Saumyatri** [comment]
Kindly Assign this issue to me

**Comment by shraddhalute** [comment]
I am ready to work on resolving the social media login issue. Please consider assigning this task to me. Thank you.

**Comment by MahadevprasadDL** [comment]
I am contributing under GSSOC'24. I am having good knowledge in web development projects. I think I can handle it. Could you please assign me this issue.

**Comment by apu52** [comment]
@Debarunn1806 Thanks for raising the issue . but #268 is already there. So I can't assign you this issue. But this is a really good issue. Thanks. 
Sorry to close this issue.
