### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CoderUzumaki** [apu52/Travel_Website#354]
**Is your Documentation related to a problem? Please describe.**
The problem with the text in the repository's README.md file lies in several grammatical and spelling errors, as well as a lack of clarity and conciseness. Specifically, there are errors such as "front-end Web Developement," "travelling," and missing punctuation marks.

**Describe the solution you'd like**
The message could be improved by making corrections like changing "travelling" to "travel", "Developement" to "Development", fixing capitalization and punctuation issues, and ensuring a consistent and professional tone throughout the text.

**Describe alternatives you've considered**
I am planning to include concise descriptions highlighting the various features of our project.
![image](https://github.com/apu52/Travel_Website/assets/149368945/0cccce33-7353-4a16-a8d1-a6e9012ef80d)

**Prototype Screenshot/Demo Video(Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/149368945/6f098479-eab0-4608-83a8-b88ddc4db6fa)
![image](https://github.com/apu52/Travel_Website/assets/149368945/22c0aa2e-a420-4e11-a3ac-feb2d0ac0b0e)

***Are you contributing under any open-source program ?***
I am contributing under GSSoC 2024 and look forward to contributing to the Travel_Website repository.

@apu52 I would like to request the assignment of this issue to me so that I can work on fixing the grammatical and spelling errors in the README.md file.

Thank you!

**Comment by anshika-gupta21** [comment]
Hello @apu52, I am a GSSoC'24 contributor. I would like to take up this issue and can fix this. Being a content writer, I believe I can take up this task and help you to improve the documentation.

**Comment by vaishali-sharma-20** [comment]
Hello, I'm excited to contribute to the Travel_Website repository as part of GSSoC 2024.

@apu52 To address the grammar and spelling mistakes in the README.md file, I would like to ask that this problem be assigned to me.

**Comment by apu52** [comment]
@CoderUzumaki you are assigned. start working on this issue.

**Comment by CoderUzumaki** [comment]
thanks @apu52
