### ISSUE TITLE
Inconsistent results upon clicking the cards in the about us section

### ISSUE THREAD

**Issue by Debarunn1806** [apu52/Travel_Website#355]
**Describe the bug**
In the about us section upon the clicking on the Destinations card the page simply refreshes while on clicking the other two it takes the user to a page where the story video is played

**Expected behavior**
Upon clicking the Destinations card it should also redirect the user to the story video.

**Screenshots (Mandatory)**
![Screenshot 2024-05-11 033345](https://github.com/apu52/Travel_Website/assets/106834322/6e361690-10c2-4f15-a4c5-a53dc7e8fcc6)

https://github.com/apu52/Travel_Website/assets/106834322/d64bd406-ce04-46c8-9958-a13f71eac9eb

**Additional Context (Mandatory )**
The onclick for the destinations card element need to be fixed so that upon clicking it the user would be redirected to the story video.

***Are you contributing under any open-source program ?***
Yes I am contributing under GSSoC'24

**Comment by Debarunn1806** [comment]
Do assign me this issue under GSSoC'24 , can fix it in less time.

**Comment by richasriva** [comment]
I can fix this issue. Kindly assign this task to me. #GSSOC24

**Comment by nagamukesh** [comment]
please assign this issue to me under gssoc 2024
i can fix this issue

**Comment by Adityagarg8384** [comment]
I have successfully solve the bug under GSSOC'24. Please assign it to me so that i can make a pull request/

**Comment by itsekta** [comment]
There is no need to redirect on the same page that the guide and tour pages are redirecting to as we don't have pages for tour and guide maybe added in future.
