### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by anushreemehta6** [apu52/Travel_Website#356]
**Is your feature request related to a problem? Please describe.**

Rate us page doesn't look good 

**Describe the solution you'd like**

want to change the rate us page 

**Describe alternatives you've considered**

will make it more readable and appealing 

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/104919688/11b5959b-b28c-4734-9688-224f1533216f)

***Are you contributing under any open-source program ?***

 @apu52  please assign me this under GSSOC'24

**Comment by Amitooo1** [comment]
@apu52 Could you please add GSSOC levels to each issue?

**Comment by anushreemehta6** [comment]
@apu52 can i please go ahead with this issue

**Comment by apu52** [comment]
@anushreemehta6 #319 This issue is already existing . So I can't assign you this issue.
But thanks for raising this issue.
Hope to see your new contribution very soon 
Thank you
