### ISSUE TITLE
Edit footer section

### ISSUE THREAD

**Issue by madhurima316** [apu52/Travel_Website#36]
I would like to add pointer cursor and hover effects to footer_col headings and would remove the hover effect of the description under Tourguide .
Please assign me this issue, under JWOC 2024

**Comment by apu52** [comment]
@madhurima316 Welcome to the repo 
I am suggesting you to please follow the issue templates to submit your issues.

![image](https://github.com/apu52/Travel_Website/assets/114172928/8add34d9-b9b9-4c98-bb64-7e0129294e86)

**Comment by shrutisk0405** [comment]
@apu52 I would like to work on this issue under JWOC. Please assign it to me

**Comment by apu52** [comment]
> @apu52 I would like to work on this issue under JWOC. Please assign it to me

@shrutisk0405 Try to raise another new issue properly as this issue is not up-to-date

**Comment by Jenis07** [comment]
I would like to work on this issue under JWOC. Please assign it to me

**Comment by apu52** [comment]
@madhurima316 Do you still working on this issue

**Comment by madhurima316** [comment]
I want to work on this issue but I am unable to understand which issue type would be suitable for this if not the one I have done. Can you please guide .

**Comment by apu52** [comment]
> I want to work on this issue but I am unable to understand which issue type would be suitable for this if not the one I have done. Can you please guide .

use the **FEATURE REQUEST** template

**Comment by apu52** [comment]
if u are not contributing I am going to close this issue @madhurima316

**Comment by madhurima316** [comment]
No, I would do it
