### ISSUE TITLE
Feedback page typography improvement

### ISSUE THREAD

**Issue by codershrutik** [apu52/Travel_Website#361]
The typography of the feedback page is not allowing easy access and viewing to the users. This makes it challenging to get feedback.

The typography needs a few changes in the CSS file to enhance its readability, as well as a change in the background image to bring the theme of the website together.

I would like to suggest changes such as those reflected in the image.
![Uploading Screenshot 2024-05-11 at 12.16.42 PM.png…]()

**Comment by juniorcoder02** [comment]
hi project admin @apu52  i'm participant in Gssoc'24 and i am thrilled to be contributing  after reviewing the open issues, i'm particularly interested in to add feedback page as it aligns well with my skills and interests.                                                                                                                                       Could you please assign this issue to me? I'm eager to dive in and make a meaningful contribution to the project.

**Comment by anveshadixit** [comment]
hi @apu52 i can work on this feedback page to make the user get attracted over it by customizing the style of this page kindly alot me to handle this issue

**Comment by apu52** [comment]
@codershrutik this issue is not clear to me . please use proper issue templates to raise a new issue .Sorry to close this issue

**Comment by codershrutik** [comment]
Hey @apu52 I raised the issue and created a pull request. I resolved the typography issue in my temp branch and sent a merge request. Please check it out if it is up to the mark, and accept the merge request. The image uploaded is my branch's result.
