### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by avanimathur** [apu52/Travel_Website#362]
Description:
Currently, the readme file consists of an old picture of the website

![image](https://github.com/apu52/Travel_Website/assets/151984867/b0ed77b6-6bc8-4801-bde1-8832a198596f)

Since we have new features in the navbar, we must update the readme with the latest screenshot from the website.
![image](https://github.com/apu52/Travel_Website/assets/151984867/7ecb29be-3e63-4c64-91af-fc4e78a67ca9)

This contribution is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign it to me 
Thanks.

**Comment by nagamukesh** [comment]
can you please assign this issue to me
I can fix it

**Comment by anveshadixit** [comment]
please assign this issue to me
I can fix it

**Comment by Dev-AyushTrivedi** [comment]
i am working as a contributor in GSSOC'24, i resolve your issued please assign it to me. and please label it for GSSOC'24
