### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by Devon-1984** [apu52/Travel_Website#364]
**Is your feature request related to a problem? Please describe.**
Currently clicking options leads to a new tab instead of changing the current tab cluttering the tabs bar making bad user experience.

**Describe the solution you'd like**
Improve the routing system and user experience by keeping users on the same tab

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/113367807/749f7c69-4211-44b0-af1d-95b441f57d0e)

***Are you contributing under any open-source program ?***
GSSoC

**Comment by Sooraj002** [comment]
I would like to fix this issue , I am a Gssoc Contributor

**Comment by apu52** [comment]
@Devon-1984 you are assigned
