### ISSUE TITLE
Beautify the UI Page

### ISSUE THREAD

**Issue by Saumyatri** [apu52/Travel_Website#366]
**Is your feature request related to a problem? Please describe.**
To create the box shadows for the buttons to beautify

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***
Yes GSSOC'24

**Comment by Saumyatri** [comment]
Kindly assign me this issue. I have created a pull request regarding this too. Please approve
![Uploading Screenshot 2024-05-11 143734.png…]()

**Comment by apu52** [comment]
@Saumyatri I can't under stand your issue. can you please explain ???
As the picture is still not loading

**Comment by Saumyatri** [comment]
The button can be beautified and make the UI look better.I'll try uploading the image again.
![Screenshot 2024-05-11 143734](https://github.com/apu52/Travel_Website/assets/111524502/00edc91f-850d-4081-add6-83387c5a4ed1).
I have made the changes in my branch and I have created a PR as well

**Comment by apu52** [comment]
@Saumyatri I have assigned you But I want to suggest you to close your previous PR & Submit your PR now

**Comment by Saumyatri** [comment]
Okay will do that Thankyou!!!

**Comment by ABDULRAZAQ79922** [comment]
Could you assign me this issue , i want to contribute it under gssoc24 and please add the lable also

**Comment by Saumyatri** [comment]
> @Saumyatri I have assigned you But I want to suggest you to close your previous PR & Submit your PR now

I have made the pull request kindly merge it.
