### ISSUE TITLE
updating information

### ISSUE THREAD

**Issue by Nihita123** [apu52/Travel_Website#368]
changing the destination name in london from gaint wheel to london eye and enhancing the ui

**Comment by wilsonprodige** [comment]
please Assign me the issue

**Comment by apu52** [comment]
@Nihita123  Welcome to TRAVEL _WEBSITE.
Thanks for raising the issue.
But I will like to recommend you to use the issue templates to make it clearer, more understanding.

![image](https://github.com/apu52/Travel_Website/assets/114172928/0f6ac618-0823-4621-ba5d-c3998f84d159)

Sorry to close this issue. 
But please use the issue templates
