### ISSUE TITLE
Feature_Request: Add a Trip Photo Gallary to the Travel Website

### ISSUE THREAD

**Issue by zul132** [apu52/Travel_Website#37]
**Is your feature request related to a problem? Please describe.**
I would like to enhance the Travel Website's user experience by introducing a captivating Photo Gallery page connected to the 'View All' button on the landing page. Currently, the 'View All' button in the Trip Gallery section is inactive, providing no avenue for visitors to explore potential travel destinations. As a result visitors of the site have no choice for exploring the places which they're interested in travelling to for their next destination. By implementing this change, users will have a visually appealing and informative gallery to browse, fostering engagement and assisting them in choosing their next destination."

**Describe the solution you'd like**
To enhance user engagement and inspire vacation bookings, I propose adding a visually appealing Trip Photo Gallery page accessed through the "View All" button on the Landing page. This new HTML page will feature a consistent Navbar and footer, displaying diverse trip photos in cards. The curated selection aligns with the website's theme, aiding users in discovering their Perfect Getaway and the World's Best-Kept Secrets. 
Another consideration is implementing a dynamic approach by randomly selecting photos from a curated collection for the Gallery. This would introduce an element of surprise and variety for users. Additionally, I propose incorporating a "Refresh" button in the Gallery, allowing users to shuffle and explore different sets of trip photos at their convenience.

**Describe alternatives you've considered**
Another solution considered was implementing a sliding carousel for the Photo Gallery, providing a visually appealing user experience. However, this alternative imposes limitations on the number of photos that can be displayed, which is not ideal for showcasing the desired diversity and range of trip destinations.

**Demo Video/Screenshot (Mandatory )**
This is the View All button which I intend to implement:
![issue1_photo_gallary](https://github.com/apu52/Travel_Website/assets/98112914/19736bf1-0e5f-4b52-868a-05db24b507e8)
The gallary would look something like this:
![issue1_photo_gallary2](https://github.com/apu52/Travel_Website/assets/98112914/f3d7aecd-4d98-4585-b9f0-8d09cf7ad5c6)

***Are you contributing under any open-source program ?***
I would like to contribute to this issue under JWOC.

**Comment by zul132** [comment]
@apu52 I would like to work on this issue under JWOC. Please assign it to me

**Comment by apu52** [comment]
@zul132 welcome to the repo
 But please follow the issue templates properly to fill up your ISSUE

**Comment by zul132** [comment]
@apu52 I have updated my ISSUE comment as per the issue template. Could you please check if it's alright now?

**Comment by apu52** [comment]
@zul132 I have assigned you . you can start working on this issue.

**Comment by apu52** [comment]
@zul132 you have 2-3 days for the submission of your PR.

**Comment by zul132** [comment]
@apu52 Another mentee @Prithwi32 was assigned a similar issue to mine and got her PR merged also. Now there's no point in me adding the photo gallery as the website now has the Animated gallery created by Prithwi32. My question is, why did you assign both of the us the same type of issue in the same day?

**Comment by apu52** [comment]
> @apu52 Another mentee @Prithwi32 was assigned a similar issue to mine and got her PR merged also. Now there's no point in me adding the photo gallery as the website now has the Animated gallery created by Prithwi32. My question is, why did you assign both of the us the same type of issue on the same day?

@zul132 sorry for any inconveniences. But you can instead make your changes in the gallery portion just beneath of the before merged animation gallery. That will also look good. If u can do so , It will be a great contribution

**Comment by zul132** [comment]
Okay I will do that

**Comment by zul132** [comment]
@apu52 Completed and created the PR #67
