### ISSUE TITLE
Adding icons in the navbar

### ISSUE THREAD

**Issue by harshmishra19** [apu52/Travel_Website#370]
**Is your feature request related to a problem? Please describe.**

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

**Describe the solution you'd like**

I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

**Describe alternatives you've considered**

One alternative could be redesigning the navbar layout or color scheme. However, adding icons is a more direct and effective solution to address the visual appeal and usability concerns of the navbar

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-05-11 080754](https://github.com/apu52/Travel_Website/assets/115486960/f3329f32-8e53-4f99-9b1f-8d8658eb98de)

***Are you contributing under any open-source program ?***

YES GSSOC'24

**Comment by swatikumari4312** [comment]
please assign me this issue .

**Comment by wilsonprodige** [comment]
please Assign me the issue

**Comment by harikasayani** [comment]
Hi, 
I am GSSOC'24 Contributor. Could you please assign this task to me. I will make the navbar more attractive by adding icons.

**Comment by harinisayani** [comment]
Hi,
I am contributing under GSSOC'24. I am having good knowledge in web development projects. I think I can handle it. Could you please assign me this issue.

**Comment by apu52** [comment]
@harshmishra19 You are assigned . You can start working on this issue
