### ISSUE TITLE
BUG: Inonsistency in fonts of headings

### ISSUE THREAD

**Issue by divyalaldinani** [apu52/Travel_Website#372]
**Describe the bug**

While other headings in index.html have font: Poppins and font-size: 32px, 'Contact Us' heading has font: Noto-Serif, font-size:44.8px

**Expected behavior**
All headings in the web-page must be consistent, i.e., must have same font-style and font-size

**Screenshots (Mandatory)**
Other headings: ![image](https://github.com/apu52/Travel_Website/assets/82147067/517f3d8e-6d1b-4bd4-828b-7399bb40fc4a)
Contact Us Heading: 
![image](https://github.com/apu52/Travel_Website/assets/82147067/069a3661-d009-4d97-83c5-51590596b0df)
Expected: 
![image](https://github.com/apu52/Travel_Website/assets/82147067/f2c6647e-511e-448e-bd51-5aaa4cf4b58b)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes, I am a contributor in GSSoC'24

**Comment by AnuragKr24** [comment]
please assign me this issue

**Comment by divyalaldinani** [comment]
can you check this out @apu52

**Comment by harinisayani** [comment]
Hi,
I am GSSOC'24 Contributor. Could you please assign me this issue. I am having experience in working with web development projects. I think I can handle it .

**Comment by DevNandini02** [comment]
i would like to work on it. please assign me this task under GSSoC'24.

**Comment by Charvithaaaa** [comment]
Assign me this issue

**Comment by apu52** [comment]
@divyalaldinani You are assigned. you can start working on this issue.

**Comment by vipinmishra0852** [comment]
@apu52  please assign me this issue
