### ISSUE TITLE
Nav bar toggle displays inappropriately on smaller screen sizes

### ISSUE THREAD

**Issue by wilsonprodige** [apu52/Travel_Website#373]
**Bug description**
On small screen sizes, the navbar shows a toggle icon(menu), so when that toggle is opened, the menu items(navbar items are not well aligned, and the hover effect on them does show appropriately

**Expected behavior**
In normal circumstances, this toggle should display the items in a well aligned manner and the hover effect on them should work perfectly

**Screenshots (Mandatory)**
<img width="1113" alt="Screen Shot 2024-05-11 at 14 52 37" src="https://github.com/apu52/Travel_Website/assets/83555554/c5d36f29-4fc2-4e23-ad0c-feb903077175">

**Additional Context (Mandatory )**
I am under GSSOC 2024 open source program

**Comment by wilsonprodige** [comment]
PLease kindly assign me the issue , GSSOC 2024

**Comment by aatmajajoshi** [comment]
Please assign this issue to me as i know pretty much front-end web technologies @wilsonprodige

**Comment by TejaKumar123** [comment]
Please assign me this issue.

**Comment by apu52** [comment]
@wilsonprodige #320 is already present & already assigned. So i can't assign you this issue . But it's really a good issue
You can work on any other issue you want to work on
Sorry to close this issue
