### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by darshan1328** [apu52/Travel_Website#374]
A new feature is adding top deals(hotels) and their prices.

**Describe the solution you'd like**

This attracts the customers inorder to browse more in the website.

**Describe alternatives you've considered**

Putting up a proper user friendly tablets to attract customers to the website.

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by darshan1328** [comment]
@sanjay-kv can you please assign me this particular

**Comment by darshan1328** [comment]
i am a gssoc contributor

**Comment by apu52** [comment]
@darshan1328 Can you please share some SS or pic of that features you want to add ??
So that I can assign you this issue

**Comment by apu52** [comment]
@darshan1328 are you still working on this issue or I will close this issue??

**Comment by DiwareNamrata23** [comment]
I'm interested to add top deals of hotels and their pricing section . I request @apu52 sir , kindly assign this issue to me

**Comment by helloanisha19** [comment]
I'm interested to make this site responsive . I request @apu52 sir , kindly assign this issue to me

**Comment by apu52** [comment]
@DiwareNamrata23 can u work on this issue now so that I can now work on this issue

**Comment by DiwareNamrata23** [comment]
Sure please assign

**Comment by DiwareNamrata23** [comment]
@apu52 can you please tell in top deals section what I need to add specifically?

**Comment by apu52** [comment]
> @apu52 can you please tell in top deals section what I need to add specifically?

According to u , what u best think which will be suitable for the website
