### ISSUE TITLE
Grammatical Corrections in README.md file

### ISSUE THREAD

**Issue by tempestanya** [apu52/Travel_Website#375]
**There are many grammatical errors in the README.md file**

**I would like to contribute by correcting those errors. I have added a screenshot after the corrections.**

![image](https://github.com/apu52/Travel_Website/assets/98050185/1f820695-352a-4db3-aaf2-615f35066242)

***I am contributing under GirScript Summer of Code program 2024***

**Comment by shiuli-19** [comment]
I am participating in GSSOC'24 and I would like to rectify this issue sir. Could you please assign it to me.

**Comment by shruti110503** [comment]
I am a contributor under GSSOC'24 and I would like to work on this issue. Please assign it to me.

**Comment by Techkunjan** [comment]
Can you please assign this task to me as I am a beginner in coding

**Comment by apu52** [comment]
@tempestanya this issue is already present in this issue.
#354 is already present there
Thanks for raising the issue But sorry ,I can't assign you this
