### ISSUE TITLE
beautify the web page Feature_Request

### ISSUE THREAD

**Issue by Vidhipawar20** [apu52/Travel_Website#376]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by AmrutaZagade** [comment]
I am participating in GSSOC'24 and I am interested in this issue, Could you please assign me.

**Comment by DevNandini02** [comment]
Please add the GSSoC label to this issue.
I can add more interactive features to this web pages. Please assign me this task under GSSoC'24.

**Comment by ishagothwad** [comment]
please add gsco label to this issue

**Comment by apu52** [comment]
no context present there
