### ISSUE TITLE
Adding animations to Navbar

### ISSUE THREAD

**Issue by Syed0206** [apu52/Travel_Website#377]
I would like to add animation effects to nabber @apu52 can you please assign me this issue under GSSOC'24

**Comment by Aradhya-005** [comment]
i would like to work on this . Please assign it to me under GSSoC'24

**Comment by parth3083** [comment]
I can add animations to the navbar.
I am a frontend developer and freelancer and i have good experience of the frontend development.
I will add the GSAP animations to the navbar and make it more attractive.

**Comment by apu52** [comment]
@Syed0206  Welcome to TRAVEL _WEBSITE.
Thanks for raising the issue.
But I will like to recommend you to use the issue templates to make it clearer, more understanding.

![image](https://github.com/apu52/Travel_Website/assets/114172928/0f6ac618-0823-4621-ba5d-c3998f84d159)

Sorry to close this issue. 
But please use the issue templates
