### ISSUE TITLE
dark and Light theme

### ISSUE THREAD

**Issue by Syed0206** [apu52/Travel_Website#378]
I would like to add Dark and Light theme to the website @apu52  can you please assign me this issue under GSSOC'24

**Comment by iim-amit** [comment]
hi,
I am GSSOC'24 Contributor. Could you please assign this task to me. I will add the Dark and Light theme to the website.

**Comment by shrashti2004** [comment]
I would like to add Dark and Light theme to the website @apu52 can you please assign me this issue under GSSOC'24

**Comment by Suvendu-UI** [comment]
i  would like to add dark and light theme, so plss assign me this issue under GSSOC 2024

**Comment by apu52** [comment]
@Syed0206 Theme change is already present in the website
