### ISSUE TITLE
Navbar Enhancement, Floating Balls Opacity, Footer Social Links Addition, and Login Page Fix

### ISSUE THREAD

**Issue by Ramu-chiluveru** [apu52/Travel_Website#379]
The current implementation of the website/application lacks several crucial elements, including enhancements to the navbar, adjustments to the opacity of floating balls, addition of social links in the footer section, and resolution of issues with the login page.

The navbar should be enhanced to improve navigation, responsiveness, and visual aesthetics, providing users with an intuitive and pleasant browsing experience.
Floating balls, if present, should have appropriate opacity levels that complement the design without distracting or obstructing content.
Social links should be added to the footer section, allowing users to easily connect with the website/application on various platforms.
The login page should function properly, allowing users to log in without encountering errors or issues.
<img width="960" alt="Screenshot 2024-05-12 071427" src="https://github.com/apu52/Travel_Website/assets/101164811/7706a4e9-8fe1-45d8-b7c3-77e46e949278">
<img width="960" alt="Screenshot 2024-05-12 071450" src="https://github.com/apu52/Travel_Website/assets/101164811/870436a4-2af0-4011-8eaa-aea614a621f3">
<img width="960" alt="Screenshot 2024-05-12 071501" src="https://github.com/apu52/Travel_Website/assets/101164811/96b6d134-a0f7-4be6-93ce-9fadd961bb8e">

GSsoc'24 contributor

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributor. I want to work on this issue. So, I request you to assign this to me
@apu52

**Comment by Aratrika-Gupta** [comment]
I would like to contribute on this issue as a GSSoC'24 contributor. I have some basic knowledge in designing. I request you to assign this to me.

**Comment by Ramu-chiluveru** [comment]
@apu52 i request you to assign me this issue

**Comment by apu52** [comment]
@Ramu-chiluveru Thanks for raising the issues & going through the bugs in the website properly.
But sorry the problems you have mentioned in this issue are already assigned to others in different issues.
So I can't assign you now .
