### ISSUE TITLE
Improve the UI/UX of rating page

### ISSUE THREAD

**Issue by dhanushsurendra** [apu52/Travel_Website#382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A more visually appealing Rate Us page. It does not blend with the other parts of the website.

**Describe alternatives you've considered**
It can be made visually appealing by improving the interface

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-05-12 120801](https://github.com/apu52/Travel_Website/assets/50047808/82940ea8-e786-41b0-b9b4-47d509f00a6c)

***Are you contributing under any open-source program ?***
Yes, GSSoc'24

**Comment by apu52** [comment]
@dhanushsurendra #319 is already present there with the same issue.
But this issue is really good. But Sorry I can't assign you this issue right now.
