### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by ishagothwad** [apu52/Travel_Website#386]
Just a few spelling errors:

1. "developement" should be "development" - In the line 3

2. "oftenly" should be "often"     &    "travelling" should be "traveling"  - In the overview section ,3rd line.

**Comment by Ankit389** [comment]
I have fixed this mistake
Please accept my request..

**Comment by Ankit389** [comment]
I have fixed this mistake
Please accept my request..  #386

**Comment by ishagothwad** [comment]
Hello [Maintainer],

I hope you're doing well! I've recently raised an issue #386 in [Travel_Website] and I'm eager to contribute to its resolution.
Please assign this issue to me.
