### ISSUE TITLE
BUG: Navbar Links are not aligned properly

### ISSUE THREAD

**Issue by Archiesachin** [apu52/Travel_Website#387]
**Describe the bug**
The Navbar is not styled properly. The navlinks are getting overflowed in the desktop as well as responsive view. 
Also adding the Navbar in the Rating and Login Page for better navigation around the website. 

**Expected behavior**
All the navlinks should be properly placed and be visible without getting overflown. 

**Screenshots (Mandatory)**

![Screenshot (980)](https://github.com/apu52/Travel_Website/assets/103347688/fba2e9f5-b9ae-434c-ba3b-165fb261bf61)

![Screenshot (979)](https://github.com/apu52/Travel_Website/assets/103347688/c6d4b1d5-6931-49f2-9485-a64909809edc)

![Screenshot (981)](https://github.com/apu52/Travel_Website/assets/103347688/b79837fe-1883-407a-a40e-fcbed3f53b84)

![Screenshot (982)](https://github.com/apu52/Travel_Website/assets/103347688/24f51317-8576-44c8-b34a-edbfeb56abda)

**Additional Context (Mandatory )**
This can be fixed by reducing the font size of navlinks and reducing the gap between them and the logo. For the responsive view, we need to remove the margin left from the navlink. 

***Are you contributing under any open-source program ?***
Yes, GSSOC'24

**Comment by Shristi613** [comment]
i want to resolve this issue .

**Comment by mohit2202solanki** [comment]
Hello @apu52 ,
Please assign this issue to me , I have worked on similar issues earlier so i love to do it .

You can visit my Github for reference :  https://github.com/mohit2202solanki

**Comment by apu52** [comment]
@Archiesachin You are assigned. you can start working on this issue

**Comment by apu52** [comment]
![Screenshot (979)](https://github.com/apu52/Travel_Website/assets/103347688/c6d4b1d5-6931-49f2-9485-a64909809edc)

@Archiesachin Just I want to request you not to fix this bug as this bug issue is already assigned to another contributor. O/w you can do all the other proposed changes

**Comment by SMARTHMALIK** [comment]
Hello  @apu52 .
Please assign this issue to me . I will try to resolve this in the best possible way .Thankyou

**Comment by Archiesachin** [comment]
> @Archiesachin You are assigned. you can start working on this issue

Okay will start working on this
