### ISSUE TITLE
Feature_Request:Implement a feature in the Contact Us section

### ISSUE THREAD

**Issue by GOKULGSECE** [apu52/Travel_Website#389]
**Problem:**
Users submitting queries or issues through the "Contact Us" form may not receive confirmation that their message has been received or know if it has been conveyed to management.

**Solution:**
Implement an automated email notification system to inform users that their message has been received and ensure that their query or issue is conveyed to the management's attention. Additionally, commit to responding to user inquiries within a specified timeframe.

**Proposed Implementation:**
1. **Email Confirmation:** Upon submission of the "Contact Us" form, users receive an automated email confirming receipt of their message. This email can include a reference number for tracking purposes.
   
2. **Management Notification:** Utilize an API to forward user messages directly to the management team's inbox or a designated email address. This ensures that user queries or issues are promptly brought to the attention of the relevant personnel.
   
3. **Response Commitment:** Establish a commitment to respond to user inquiries within a specified period, such as 24-48 hours. This ensures that users are kept informed and receive timely assistance.

**Considered Alternatives:**
- Implementing a manual confirmation process where support staff manually confirm receipt of each user message.
- Utilizing a ticketing system where users can track the status of their inquiries online.
- Integrating a chatbot or live chat feature for immediate assistance and confirmation.

**Demo:**
A demonstration video showcasing the implementation of the proposed features can be found [here](https://github.com/apu52/Travel_Website/assets/125350820/467e08d7-a3fd-44a9-81d9-e71ffbcb4ad3).

**Contribution Status:**
This contribution is not associated with any open-source program currently. However, I'm willing to take ownership of this feature request and implement it.

**Comment by GOKULGSECE** [comment]
Can I work on this feature under Gssoc'24 as a contributor

**Comment by apu52** [comment]
@GOKULGSECE This is really a very good issue. thanks for raising the issue . I am assigning you this issue. you can start working on this issue

**Comment by GOKULGSECE** [comment]
> @GOKULGSECE This is really a very good issue. thanks for raising the issue . I am assigning you this issue. you can start working on this issue

Thanks for assigning me @apu52

**Comment by GOKULGSECE** [comment]
@apu52 I need the official mail of the website for further improvement of this issue

**Comment by GOKULGSECE** [comment]
@apu52 As I need the mail id of the management of this project for proceeding my process

**Comment by GOKULGSECE** [comment]
It's oke thanks for replying @apu
by today i will be sending you the pull request
