### ISSUE TITLE
New community contibutors banner

### ISSUE THREAD

**Issue by shruti-sen2004** [apu52/Travel_Website#39]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
I want to present a new community contibutors banner for this repo

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/115914670/95c7ff30-545c-46a1-bb05-166a211e98fe

***Are you contributing under any open-source program ?***
no

**Comment by apu52** [comment]
@shruti-sen2004 You are assigned. you can start working on this issue.
