### ISSUE TITLE
BUG : Dark theme preference is not save

### ISSUE THREAD

**Issue by tat-tvam-asii** [apu52/Travel_Website#390]
**Describe the bug**
The dark theme preference is not saved. When i refresh the website after applying dark theme then the dark theme is gone . 

**Expected behavior**
Once selected the dark theme should remain until and unless light theme is selected

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
 I am contributing under GSSOC'24

**Comment by tat-tvam-asii** [comment]
@apu52 Please assign this to me under GSSOC'24

**Comment by apu52** [comment]
@tat-tvam-asii #323 issue on the same topic is already present there. So, Thanks for raising the issue but Sorry I can't assign you this issue
