### ISSUE TITLE
Documentation : Typo error

### ISSUE THREAD

**Issue by rugved0102** [apu52/Travel_Website#391]
There is a typo in the readme file 'development' is spelled as 'developement'. I am a contributor in GSSoC'24, I want to handle this issue plz could you assign it to me ?
![image](https://github.com/apu52/Travel_Website/assets/122914094/2762c3b7-dd20-41be-bd5b-d670a5855433)

**Comment by Suruchibharti** [comment]
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by rugved0102** [comment]
Hii Admin! I have raised this issue, Can you please assign it to me. I am a contributor in GSSoC'24. Thank You !

**Comment by apu52** [comment]
@rugved0102 #354 is already present there on the same issue. Thanks for raising the issue but I can't assign you this issue
