### ISSUE TITLE
WELCOME TO TRAVEL_WEBSITE🌟👋

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#392]
**Hello Everyone** ,
### Arpan here , The Project ADMIN of the repo , Welcoming you all to the **TRAVEL_WEBSITE ----TOURGUIDE**👋

**First Of all Congratulations , That You all are selected in **GSSOC'24**** 🎉🥳

### Let me Clear you the Rules of Contributing in this repo

1. You can also 

-     fix the Bugs or 

-     add features in the TRAVEL_WEBSITE website itself😊

2. **also you can Make some Documentation Update (e.g in the CONTRIBUTING.md , README.md)👨‍💻**

### 
For more detailed rules , Go through the CONTRIBUTING.md file Before Contributing 

**I am hoping guys that this 3 months will be a great journey for us
So , let's Code , Contribute & enjoy!!!!!!!!!
Happy Coding & all the best**  😊💻👨‍💻

**Comment by NeerajaGurram** [comment]
hi @apu52 ..can you please assign me this project so i would like to make a little changes in this

**Comment by anushreemehta6** [comment]
Hi!! I am Anushree mehta. @apu52 I would like to change the rate us page , it's not looking good. Please assign me this project under GSSOC'24 .

**Comment by kajal-panigrahi** [comment]
Hello,i am kajal , GSSOC'24.I would like to change and bring some modificatios in this page,please assign me the project.

**Comment by Kcode15** [comment]
Hi I am Khushi Mantri. I would like to contribute to this project and refine it, so please assign me this project under GSSOC'24.

**Comment by apu52** [comment]
@NeerajaGurram @anushreemehta6 @kajal-panigrahi @Kcode15 Thanks for your attention to this repo . The issues which are already raised are reviewed. I will like to suggest you all to raise new issues on which you want to work on

Very much excited to see all of your contributions. 
HAPPY CODING!!!!!!
& if you all face any problems feel free to reach out me

**Comment by Unknownmaster0** [comment]
Mark the GSSoC label
