### ISSUE TITLE
[Feature_Request]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [apu52/Travel_Website#394]
**Is your feature request related to a problem? Please describe.**
Currently, the issue template for this repo seems to be basic also it is less visually appealing.👇
![Screenshot from 2024-05-13 00-33-57](https://github.com/apu52/Travel_Website/assets/73957207/a50b3f6e-50e2-4eb6-881e-205f05bafc5f)

**Describe the solution you'd like**
I will make it look like this 👇

![image](https://github.com/apu52/Travel_Website/assets/73957207/9e1aec2d-4e58-4f93-b89f-66fe71f0fc61)

**Describe alternatives you've considered**
- Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/apu52/Travel_Website/assets/73957207/058456b8-beaf-4f4f-90c4-cd0101a53a52)

***Are you contributing under any open-source program ?***
- GSSOC'24

**Comment by TonyStark-47** [comment]
And I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by apu52** [comment]
@TonyStark-47 #311 is already present there in same topic , So I can't assign this issue right now. thanks for raising the issue
