### ISSUE TITLE
Improve the CSS and styling of pricing section and adding additional features.

### ISSUE THREAD

**Issue by nehavaishnav** [apu52/Travel_Website#395]
**Is your feature request related to a problem? Please describe.**
The pricing section has dull styling after clicking the specific place which deteriorates the user experience.

**Describe the solution you'd like**
I would like to improve its CSS and make the section more impressive. Additionally, I would like to add different options of flight, train and bus to reach the specific destination.

***Are you contributing under any open-source program ?***
I am contributing under GSSOC 2024. Kindly assign this issue to me.

**Comment by Sudharshana426** [comment]
I would love to work on this project..Assign me this task for better grid implementation and CSS styles for the issue...I have worked in multiple projects. Check out my LinkedIn Profile: https://www.linkedin.com/in/sudharshanab

**Comment by SHANMUGAPRIYA-1** [comment]
assign this task to me

**Comment by nehavaishnav** [comment]
I have completed it kindly check the PR
