### ISSUE TITLE
It is 2024. Update Your Footer

### ISSUE THREAD

**Issue by kashhisshh** [apu52/Travel_Website#396]
Change your static timestamp to an automatically updating copyright year or other dynamic timestamp.

**Comment by Suruchibharti** [comment]
hii @apu52 , please add level.
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by Ankit389** [comment]
Hello  i can fix this problem#396

**Comment by apu52** [comment]
> Change your static timestamp to an automatically updating copyright year or other dynamic timestamp.

@kashhisshh this issue has already been taken . thanks for raising this issue but I can't assign this to you right now. Sorry to close this issue
