### ISSUE TITLE
Your footer does not contain all the nessassry elements !

### ISSUE THREAD

**Issue by Helios-snd** [apu52/Travel_Website#397]
Let me design the footer for you

**Comment by revathishine** [comment]
Could you assign this task to me I had worked as a web developer at iitm reseach park.With my experinece i could do better.

**Comment by revathishine** [comment]
i just want to work on the document also in the title it has spelling mistake (nessasary )

**Comment by kartik100-svg** [comment]
i want to work this issue please assign this issue

**Comment by apu52** [comment]
@Helios-snd this issue is already taken in other issues. Sorry I can't assign you this issue
just I want to suggest you to raise your new issues next time with the help of issue templates already present there.
