### ISSUE TITLE
Feature_Request:Adding more details at footer

### ISSUE THREAD

**Issue by TanviGandhotra** [apu52/Travel_Website#398]
@apu52 
In the footer we can add more dteails like top countries,
unique places to stay and like honeymoon places ,it will be easy for user ![Screenshot (206)](https://github.com/apu52/Travel_Website/assets/142469729/930a3439-29c1-4b25-af82-52606ac5c1f3))
plzz assign this issue to me. i want to contribute in this.Through contributing here wanted to upskill myself..eagerly waiting for ur response

**Comment by apu52** [comment]
@TanviGandhotra I am assigning you this issue. just want to suggest you to add the links of the appropriate pages with the features you want to add?(e.g top countries, unique places)

**Comment by TanviGandhotra** [comment]
Thnku so much for assigning this and giving me this opportunity. And I will
surely add link to pages i want to add.
