### ISSUE TITLE
 Enhancement - Connect Contact Us Button to Admin's LinkedIn or Email

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#4]
Issue Description
To improve the accessibility and responsiveness of the website, let's enhance the "Contact Us" button by connecting it directly to the admin's LinkedIn profile or email address. This will allow users to reach out to the administration more conveniently.
<img width="319" alt="Screenshot 2024-01-11 at 12 03 41 AM" src="https://github.com/apu52/Travel_Website/assets/136263179/54a95a6c-f41c-4a48-ab39-693f3925eb32">

Proposed Changes
Implement a link in the "Contact Us" button that redirects users to the admin's LinkedIn profile or opens the default email client with the admin's email address pre-filled.
Ensure that the chosen method aligns with user preferences for communication.

Additional Information
A direct link to the admin's LinkedIn or email will streamline communication and enhance user experience.
Verify the admin's preferred contact method (LinkedIn or Email) before implementing the change.
Let's work together to make the "Contact Us" button more effective and user-friendly.

**Comment by rahat2134** [comment]
@apu52 assign this issue to me.

**Comment by zul132** [comment]
I would also like to work on this issue. @rahat2134 I noticed you've raised 4 issues under this project but as per JWoC rules, mentees can be allotted only 1 issue per project at a time.
So, @apu52 I would like to be considered for this issue, just in case you decide to allot @rahat2134 to a different issue.

**Comment by rahat2134** [comment]
@zul132 yup mentee can only work for 2 issues **Mentees are allowed to work only for a maximum of 2 issues at a time across all projects** I have raised 4 issues then i can solve them in 2 days(2 issue per day).🙂

**Comment by rahat2134** [comment]
JWOC`

**Comment by zul132** [comment]
Oh okay 😅

**Comment by DarshSohaliya** [comment]
I would like to work on this project

**Comment by apu52** [comment]
@rahat2134 @DarshSohaliya @zul132 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
