### ISSUE TITLE
Navigation Links Not Redirecting to Sections

### ISSUE THREAD

**Issue by yusra05** [apu52/Travel_Website#40]
**Describe the bug**
Clicking on the navigation links in the website header does not result in the expected redirection to the respective sections. The href attributes for the navigation links are currently set to "#", preventing proper navigation.

**Expected behavior**
Clicking on each navigation link should smoothly scroll to the corresponding section on the page.

**Screenshots **
![image](https://github.com/apu52/Travel_Website/assets/112852251/78dd0421-cf2d-418c-b66b-63a7be808975)
here even after clicking on 'Destination,' the page still does not redirect to the 'Destination' section.

**Additional Context **
I can resolve the navigation issue by updating the href attributes of the navigation links to match the IDs of the target sections. This adjustment will ensure proper redirection when users click on the links.

***Are you contributing under any open-source program ?***
I'm contributing under JWOC'24

**Comment by SGCODEX** [comment]
I am working on it under JWOC and in combination to issue #25

**Comment by apu52** [comment]
@yusra05 Welcome to the repo.
You can work raise any issue of your interest after looking into the already existing issues.
