### ISSUE TITLE
Search bar at the top right corner can be added

### ISSUE THREAD

**Issue by AyushShukla3466** [apu52/Travel_Website#400]
Search bar at the top right corner can be added for easy search and finds for the users

**Comment by vinuthnar** [comment]
hii @AyushShukla3466 @apu52 , please add level.
I'm GSSoC'24 contributor , I have experience in the designing animated search bars so, please assign this issue to me.

**Comment by Ipeeka** [comment]
I would like to work on this project.Please assign it to me.

**Comment by apu52** [comment]
@AyushShukla3466 this is a good issue. Just want to suggest you to raise your issues with the help of issue templates already present in the repo. Sorry to close this isssue
