### ISSUE TITLE
Move to the top scroll bar feature can be added

### ISSUE THREAD

**Issue by AyushShukla3466** [apu52/Travel_Website#401]
Move to the top scroll bar feature can be added

**Comment by Gokul-ram-j** [comment]
sir please assign me this issue  @AyushShukla3466  ,i can make it sir

**Comment by yushmitabisu018** [comment]
Sir, Please if possible assign me this issue, I will surely make it @AyushShukla3466

**Comment by apu52** [comment]
@AyushShukla3466 this is a good issue. Just want to suggest you to raise your issues with the help of issue templates already present in the repo. Sorry to close this isssue
