### ISSUE TITLE
Feature_Request: Checkout Page Missing

### ISSUE THREAD

**Issue by dhruv8433** [apu52/Travel_Website#402]
@apu52 
**Is your feature request related to a problem? Please describe.**

There is 404 page when user click on checkout button

**Describe the solution you'd like**

We can create a checkout page that take user card information for checkout and also we can integrate stripe for payment.

**Describe alternatives you've considered**

If user is not logged in than we redict it to login page

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/114583978/5e131c25-56db-4535-a691-24906a3f10d4)

***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@dhruv8433 you are assigned.

**Comment by dhruv8433** [comment]
@apu52 

Thank you for giving me opportunity. i will try my best
