### ISSUE TITLE
Feature_Request:Adding a logo for the website and make navbar concise.

### ISSUE THREAD

**Issue by aatmajajoshi** [apu52/Travel_Website#403]
**Is your feature request related to a problem? Please describe.**
- Incorporating a relevant logo that embodies the essence of the website.
- Enhancing the alignment of the navbar to improve user readability and navigation experience.
- Decreasing the prominence of the bubbles to ensure that website content remains easily readable and accessible for users.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Here's how I have implemented it:

https://github.com/apu52/Travel_Website/assets/78197261/552f0207-3b14-4cb6-a2b2-5672aae2c388

***Are you contributing under any open-source program ?***

**Comment by Sudharshana426** [comment]
I would love to work on this project..Assign me this task for better grid implementation and CSS styles for the issue...I have worked in multiple projects. Check out my LinkedIn Profile: https://www.linkedin.com/in/sudharshanab

**Comment by apu52** [comment]
@aatmajajoshi you are assigned. Now you can submit your PR
