### ISSUE TITLE
Enhance Navbar

### ISSUE THREAD

**Issue by varsha-saini02** [apu52/Travel_Website#404]
Hello,
Navbar's content is literally have a very large font and also login button at the right corner is not visible properly , the options like home,about us can be a bit leftward and small so that it looks pretty.

<img width="954" alt="image" src="https://github.com/apu52/Travel_Website/assets/114968675/53abb4ba-701a-4c93-a0b5-eacaca0dfa46">

So, if you find this issue relevant then please assign this to me under GSSOC'24. Thank you awaiting for your response.

**Comment by Adilkhan056** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Sudharshana426** [comment]
I would love to work on this project..Assign me this task for better grid implementation and CSS styles for the issue...I have worked in multiple projects. Check out my LinkedIn Profile: https://www.linkedin.com/in/sudharshanab

**Comment by SoumyajitPr** [comment]
Hi, I would like to contribute on this project. I can help to fix the issue of enhancing the navbar. Assign me this task, and I won't disappoint you. Thank you.

**Comment by apu52** [comment]
@varsha-saini02 THIS issue is already taken. Thanks for raising this issue. but I can't assign you this issue
