### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#406]
**Describe the bug**

The contact us page is not responsive.

**Expected behavior**

 Assign this task to me and I will make the page responsive.
**Screenshots (Mandatory)**

![Screenshot (410)](https://github.com/apu52/Travel_Website/assets/143121854/d010e905-55fe-45bc-a365-3123973a2a80)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes I am contributing under GGSOC'24

**Comment by apu52** [comment]
The contact us page is not any other page & responsiveness of the whole website ---this issue is already taken . So I can't assign you this issue. Sorry to close this issue.
