### ISSUE TITLE
BUG - misalignment in the navbar 

### ISSUE THREAD

**Issue by kairveeehh** [apu52/Travel_Website#407]
**Describe the bug**

there can be seen misalignment in the navbar of the home page 

**Expected behavior**

 better navbar
**Screenshots (Mandatory)**

[
![Screenshot 2024-05-13 191636](https://github.com/apu52/Travel_Website/assets/145572028/e108615c-93ae-4e03-928a-3620a8e52e95)
](url)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by rugved0102** [comment]
I am contributing under the GSSOC'24 program.

@apu52, could you please assign this issue to me? Thank you.

**Comment by Sowmyatiwari** [comment]
Hi @apu52 , I am contributing under the gssoc'24 program , can you please assign me this task , I can see the misalignment in the navbar , I will align it perfectly for better ui .

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24 @apu52 .

**Comment by apu52** [comment]
@kairveeehh this issue is already taken .sorry to close this issue
