### ISSUE TITLE
BUG - footer is not having a good ui/ux

### ISSUE THREAD

**Issue by kairveeehh** [apu52/Travel_Website#408]
**Describe the bug**
the footer lacks a clean ui and needs more features to make it interactive - social links are also missing as only email is there 

**Expected behavior**
a better footer with cleaner ui and more informative as well
**Screenshots (Mandatory)**

![Screenshot 2024-05-13 191744](https://github.com/apu52/Travel_Website/assets/145572028/0dd470cd-d17c-4a1a-8a3e-795fd76d6627)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
gssoc'24

**Comment by Karthikkariappa08** [comment]
Hi ,
I'm excited to tackle the task of adding more specialized menu items to the Menu webpage. With my experience in website development using HTML, CSS, and JavaScript.

i have a good knowledge in ux/ui designing

Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by rugved0102** [comment]
Hi Admin ! Please assign this task to me as I am a contributor in GSSoC'24. Excited to make the UI better ! Thank You.

**Comment by kgourab73** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by Sowmyatiwari** [comment]
Hi admin , could you please assign me this task ,I have an experience in ui , and also did projects in web development , I can solve this issue , I can see the footer is not properly aligned , I will create a better footer with cleaner ui , and informative as well.

**Comment by jinalraghwani18** [comment]
Could you please assign me this issue under GSSOC'24 and also add label of gssoc'24

**Comment by apu52** [comment]
@Karthikkariappa08 @rugved0102 @kgourab73 @Sowmyatiwari @jinalraghwani18 Please try to make new issues on the issues you want to work on. As the issue will be assigned as FCFS method

**Comment by ABDULRAZAQ79922** [comment]
Kindly assigned me this issue , I want to contribute assign me this issue under GSSOC'24 and also add label of gssoc'24

**Comment by apu52** [comment]
@ABDULRAZAQ79922 this issue is already assigned .you can raise any new issue on which you want to work.
