### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by NeerajaGurram** [apu52/Travel_Website#410]
watch our story in dark theme is not visible

auto sliding of top destinations might bring a good look to page

i would like to make changes in dark theme for visibility of watch our story
and make changes accordingly in html, js and css for auto sliding of images 

![image](https://github.com/apu52/Travel_Website/assets/152693538/9f25e841-43d8-4f19-9bbb-0e855c8f3ce4)
![image](https://github.com/apu52/Travel_Website/assets/152693538/a9b08dea-e9c4-4366-8852-87a569e66e90)

i'm contributing to gssoc 24 please label and assign it to me

**Comment by apu52** [comment]
@NeerajaGurram It's a good issue. You are assigned.

**Comment by prajna321** [comment]
I'm eager to work on these issues! @apu52  Could you please assign them to me?

**Comment by NeerajaGurram** [comment]
> @NeerajaGurram It's a good issue. You are assigned.

can you please give the issue an appropriate level label ?
