### ISSUE TITLE
Feature_Request :-  Enhancing the user interface of plantrip.html.

### ISSUE THREAD

**Issue by josum06** [apu52/Travel_Website#415]
1 **Responsive Navigation Bar**:  To make your navigation bar more responsive and user-friendly, consider implementing a design that adapts well to different screen sizes. This could involve using a responsive framework creating custom CSS media queries to adjust the layout of the navigation menu for various devices. Also, ensure that the navigation is intuitive and easy to use, with clear labels and organized menu items.
 
2. **Interactive Background Images**: Adding interactive background images can greatly enhance the visual appeal of your website.

3. **Social Media Links and Footer**: Incorporating social media links and a footer is essential for enhancing the accessibility and engagement of your website. 

<img width="872" alt="new git hub" src="https://github.com/apu52/Travel_Website/assets/136955127/24aa483a-0342-4f59-979a-31c52119854a">

**Comment by apu52** [comment]
@josum06 good issue. you are assigned. Start working on this issue.

**Comment by Shatakshi-gupta-ggits** [comment]
Can you assign this issue to me
