### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SDprogramer** [apu52/Travel_Website#418]
Website real time URL on GitHub not working from my laptop

I want to fix the code and deployment and I am under GSSOC 2024

![Screenshot 2024-05-14 164236](https://github.com/apu52/Travel_Website/assets/155221332/75f69ac9-97fe-44b2-b70c-dd3ad984cebd)

**Comment by apu52** [comment]
@SDprogramer actually it's because of processor problem & there is a file overloading problem in the website that slows the loading rate of website

**Comment by apu52** [comment]
So , Sorry to close this issue . But try to raise new issues on other things you want to work on

**Comment by apu52** [comment]
> @SDprogramer actually it's because of processor problem & there is a file overloading problem in the website that slows the loading rate of website

Can you solve this issue to make this page load faster???So that I can assign you

**Comment by SDprogramer** [comment]
Okay i am trying by night to do so

**Comment by SDprogramer** [comment]
Please add the gssoc labe
l

**Comment by Ghanshyam89** [comment]
Hi @SDprogramer ,

Is there any progress that you can solve this issue, please clarify ASAP so that I can assign this issue to you under gssoc.

Regards
Project Mentor

**Comment by SDprogramer** [comment]
No regarding this i have found the issue what it is, but i cannot able to find the file and fix it. Cannot understand on which file to work

**Comment by apu52** [comment]
> No regarding this i have found the issue what it is, but i cannot able to find the file and fix it. Cannot understand on which file to work

I can give you some tips @SDprogramer

**Comment by apu52** [comment]
I can give advice that   the HD , High Quality Images, Videos and other Static Assets are used  in this Website directly , try to omit/modify that . Either Compress it or Use SVG type of Images. You Can also Use Platforms like "Uploadthing", "MUX" to store images and Videos and then Use it in Your Website. Another Simple Solution is to use Links like Google Drive Links etc.

**Comment by SDprogramer** [comment]
Okay now i got the idea. Okay I will try to implement that surely

**Comment by apu52** [comment]
@SDprogramer are you still working on this issue??

**Comment by SDprogramer** [comment]
Sorry but i could not do anything so i am opting out of it. You can close this issue
