### ISSUE TITLE
Feature_Request Dialog box should be displayed properly in mobile

### ISSUE THREAD

**Issue by kapilG0** [apu52/Travel_Website#419]
**Is your feature request related to a problem? Please describe.**
Dialog box not displaying properly in mobile 

**Describe the solution you'd like**
Want to use media query 

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot_20240514_170243](https://github.com/apu52/Travel_Website/assets/59639410/8c93548d-bdea-424e-9453-c47282400866)

***Are you contributing under any open-source program ?***
Yes in gssoc

**Comment by kapilG0** [comment]
Hello @apu52 please assign this issue using gssoc

**Comment by apu52** [comment]
@kapilG0 you are assigned. Just make the dialogue box responsive

**Comment by kapilG0** [comment]
Hello @apu52 it is working fine in mobile it was my mistake . please close this issue . Thank you
