### ISSUE TITLE
Feature_Request Add responsive logos to navigation bar which will be adjustable to different screen sizes 

### ISSUE THREAD

**Issue by Shravani-Korde** [apu52/Travel_Website#42]
**Is your feature request related to a problem? Please describe.**
The existing website does not contain the navigation bar on reduced screen sizes i.e. mobile phones.

**Describe the solution you'd like**
- Add navigation bar that will be visible to reduced screen sizes i.e. for mobile phones as well.
- Also make the navigation bar responsive by adding logos instead of the contents when the screen size is reduced.

**Demo Video/Screenshot** 
The following screenshot describes the existing navigation bar on mobile phones:
![Image](https://github.com/apu52/Travel_Website/assets/149994109/f84d4961-4be8-47c0-8bce-e0f973609853)

**Are you contributing under any open-source program ?**
Yes under **JWOC** I am contributing as mentee.

**Comment by apu52** [comment]
@Shravani-Korde Already there is an issue present of responsiveness in the Issue section

**Comment by Shravani-Korde** [comment]
Ok, I have raised another issue please have a look.
