### ISSUE TITLE
BUG: The text is not visible for some parts in dark mode

### ISSUE THREAD

**Issue by Rakshit-gen** [apu52/Travel_Website#421]
**Describe the bug**
Text for the parts like watch our story etc isn't visible in dark mode.

**Expected behavior**
It should become brighter when shifting to dark mode

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/64471316/38bd2a87-967c-4903-9bbc-6c8ddfca83c0)

**Additional Context (Mandatory )**
I am contributing as a part of GSSoC '24.

Do assign me this issue I would like to solve it.

**Comment by apu52** [comment]
@Rakshit-gen this issue is already present in this repo & already assigned to another contributor. Sorry to close this issue.
But carry on your contribution
