### ISSUE TITLE
BUG - In contact us section

### ISSUE THREAD

**Issue by snehamalik09** [apu52/Travel_Website#422]
Certainly. The issue at hand involves the "Contact Us" section of a web page overflowing onto the right side, likely disrupting the layout and functionality of the page. This overflow could be due to various reasons, such as improperly sized or positioned elements, excessive content, or CSS styling issues.
Please assign me the task of resolving the overflow issue in the "Contact Us" section so I can address it as part of my contribution to GSSOC 2024.

![nnnnn](https://github.com/apu52/Travel_Website/assets/86192799/9be55377-bfae-4fda-a1a3-1346aad0bcc9)

**Comment by apu52** [comment]
@snehamalik09 thanks for raising the issue. but this issue is already present in the repo . Sorry to close this issue
