### ISSUE TITLE
BUG - Header section 

### ISSUE THREAD

**Issue by snehamalik09** [apu52/Travel_Website#423]
I'd like to address the appearance of the header section. The font size seems excessive and overall it appears messy. Could you please assign this issue to me so I can work on it as part of GSSOC 2024?

**Comment by Ankit389** [comment]
Can I complete  header section#423

**Comment by apu52** [comment]
@snehamalik09 I want to suggest you to raise new issue using the issue templates . So that the issue will be more clearer & more understanding . Sorry to close this issue,
