### ISSUE TITLE
Code-of-Conduct.md

### ISSUE THREAD

**Issue by n14rishitha** [apu52/Travel_Website#425]
**Is your Documentation related to a problem? Please describe.**
 the code of conduct takes effect (on issues and pull requests, or community activities like events?). Adopting, and enforcing, a code of conduct can help create a positive social atmosphere for your community. But there is no proper explanation to that.

**Describe the solution you'd like**
I would like to add  the proper explanation to it
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for everyone at the Event
Showing empathy towards others and Event Participants and etc.

![Screenshot 2024-05-14 205412](https://github.com/apu52/Travel_Website/assets/153157112/bfec227f-fee5-46bf-b2d2-81a82d15eb47)

***Are you contributing under any open-source program ?***
I am contributing under a open source program - GirlScript  summer of code (GSSoC'24)

**Comment by n14rishitha** [comment]
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by apu52** [comment]
@n14rishitha I have assigned you . you can start working on this issue
