### ISSUE TITLE
website taking much time to open and bad hovering effect

### ISSUE THREAD

**Issue by jinalraghwani18** [apu52/Travel_Website#430]
Website takes much time to load and the animation while loading the website is not good. secondly the hovering effect on cards can be done better the zoom-in effect is slower .

we can add any other text or animation or illustration while loading the website and change the timings of hovering effect

**Comment by apu52** [comment]
@jinalraghwani18 Can you please raise this issue using the issue templates So that the issue will be more clearer. Waiting for this issue
