### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RohithChitrada** [apu52/Travel_Website#433]
Bug Description: Slow Hover Transition Effect on Trip Cards
Issue Summary:
The hover effect on the trip cards is currently transitioning too slowly, resulting in a less responsive and less user-friendly experience. which makes the hover effect sluggish. Additionally, the cursor changes to a zoom-in style, but it would be more intuitive to change it to a pointer style to indicate interactivity.

Could you please assign this issue to me so I can work on it as part of GSSOC 2024?

**Comment by apu52** [comment]
@RohithChitrada you are assigned
