### ISSUE TITLE
BUG: In footer 

### ISSUE THREAD

**Issue by abhayvershwal** [apu52/Travel_Website#438]
**Describe the bug**
In the footer, only the Support section is highlighted in blue, while all other items are displayed in white.

**Expected behavior**
The expected behavior is for the Support section to also be displayed in white.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/93792490/5e614b44-612d-4aef-b034-ff637c8925d5)

Expected
![image](https://github.com/apu52/Travel_Website/assets/93792490/22b6a0bc-777b-4ac5-ba05-2acb104c94b1)

**Additional Context (Mandatory )**
The expected behavior is for the Support section to also be displayed in white, enhancing user experience and readability

***Are you contributing under any open-source program ?***
gssoc 2024

**Comment by abhayvershwal** [comment]
I have raised a PR for this issue #439

**Comment by AnshitaPawar** [comment]
I would like to work on this project. Please assign it to me .

**Comment by abhayvershwal** [comment]
@apu52 
I have raised a PR once again after you assigned me the issue. I apologize for raising the previous PR prematurely.
PR: #461

**Comment by izharisnia** [comment]
I would like to contribute on this project. Please assign it to me

**Comment by Sajiyasiddiqui** [comment]
I want to work on this .Please assign to me.

**Comment by itsekta** [comment]
Fixed in #461
