### ISSUE TITLE
[Feature] : Implement the Responsive site

### ISSUE THREAD

**Issue by sivaprasath2004** [apu52/Travel_Website#441]
**Is your feature request related to a problem? Please describe.**
- In every website users can use various devices but in this site doesn't `Responsive`.
- Please assign me i will fixed the issue..

**Describe the solution you'd like**
- `mobile` & `Tab` mode can be proper responsive site..
- In you will inspect the page and change to the mobile mode see the error.
- I will ready for work it the new feature... :rocket:

**Comment by apu52** [comment]
@sivaprasath2004 thanks for raising the issue . But this issue is already present in this issue & assigned. So sorry to close this issue
