### ISSUE TITLE
Favicon_BUG

### ISSUE THREAD

**Issue by Meetjain1** [apu52/Travel_Website#442]
**Describe the bug**
Currently the image is added in current website instead of the actual favicon.

**Expected behavior**
It should be a proper Favicon (created online)

**Additional Context **
Have a look on it , its looking ugly .

***Are you contributing under any open-source program ?***
Yes, I am working under gssoc24

**Comment by apu52** [comment]
can you give me the SS which favicon you are suggesting here??

**Comment by Meetjain1** [comment]
sure sir , 

![Favicon modified](https://github.com/apu52/Travel_Website/assets/133582566/7bb0b34c-1052-48db-b065-936ed94830df)

**Comment by Meetjain1** [comment]
@apu52 should I create a PR sir ? by adding this new favicon ?

**Comment by Meetjain1** [comment]
> @apu52 should I create a PR sir ? by adding this new favicon ?

if it so , then assign me this issue . Thankyou

**Comment by Ghanshyam89** [comment]
Hi @Meetjain1 

You can start working on it, and make sure to do this to each page of the website. 

Regards
Project Mentor

**Comment by Meetjain1** [comment]
> Hi @Meetjain1
> 
> You can start working on it, and make sure to do this to each page of the website.
> 
> Regards Project Mentor

Sure sir
