### ISSUE TITLE
Feature_Request : Design Enhancement on Bookings Page

### ISSUE THREAD

**Issue by m3kvt** [apu52/Travel_Website#443]
**Issue Details**
- Lack of Visual Hierarchy: The bookings page currently has a plain layout with minimal styling.
- Poor Readability: The text on the page lacks proper styling, such as line heights, and spacing, which affects readability.
- Unappealing Layout: The overall layout of the page is basic and does not make effective use of space.
**Proposed Solution:**

**Describe alternatives you've considered**
- Enhance Visual Hierarchy: Use CSS to style headings, subheadings, and important text elements with different font sizes, weights, and colors to create a clear visual hierarchy.
- Improve Readability: Use contrasting colors for text and background to enhance readability and accessibility.
- Enhance Buttons and Forms: Style buttons with colors, borders, and hover effects to make them stand out and appear interactive.

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-05-15 140010](https://github.com/apu52/Travel_Website/assets/98379619/cce6955e-b2ad-4be0-87a3-798a86be5b75)

**Comment by m3kvt** [comment]
Kindly add the gssoc labels and assign me this issue.

**Comment by Ghanshyam89** [comment]
Hi @m3kvt 

This is a duplicate issue, please have a look at available issues first before raising any issue.

Regards
Project Mentor
