### ISSUE TITLE
Feature :  Adding a logo to the Tour Guide website

### ISSUE THREAD

**Issue by AbhiJay1287** [apu52/Travel_Website#445]
There isn't a logo that enhances the look and brand of the website 

 I'm interested in contributing to this project by designing and adding a beautiful logo to it 

**Demo Video/Screenshot (Mandatory )**
![Screenshot (114)](https://github.com/apu52/Travel_Website/assets/105973197/5e966cc9-29e2-4f5d-9af1-821bd067eb26)

I'm very good at canva. Please assign this issue to me under GSSOC'24.

**Comment by AbhiJay1287** [comment]
@apu52 can you please take a look ?

**Comment by ChaitanyaLonarkar** [comment]
I want to add new logo to the website which looks more attractive and cool on this website. 
Assign this issue to me so that I can add new logo under GSSOC'24.

**Comment by Ghanshyam89** [comment]
Hi @AbhiJay1287 and @ChaitanyaLonarkar ,

This is a duplicate issue, please have a look at available issues first before raising any issue.

Regards
Project Mentor
