### ISSUE TITLE
BUG - Signup using google error

### ISSUE THREAD

**Issue by skshrinaya** [apu52/Travel_Website#448]
Hi , I'm a GSSOC'24 contributor . Your website is nice but while creating a new account using google , github etc. it is not working. it goes to the same page. I would like to contribute to this project. Please assign me this issue.

**Comment by Pardume-Sharma** [comment]
Hii @apu52, The issue of signup using all the social links like google, github, instagram are not working. Kindly assign me this issue with labels (gssoc).

**Comment by Akshitha-reddy-13** [comment]
Can you assign it to me? @apu52 
Isuue: #448
![Uploading Screenshot 2024-05-15 154920.png…]()

Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
Approach for this project: connecting third-part authentications firebase or google firebase to solve this error 
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

**Comment by Ghanshyam89** [comment]
Hi @skshrinaya 

This is a duplicate issue of #268 , please have a look at available issues first before raising any issue.

Regards
Project Mentor
