### ISSUE TITLE
BUG in responsiveness 

### ISSUE THREAD

**Issue by Pardume-Sharma** [apu52/Travel_Website#449]
The hero section, contact us section is not responsive to all the screens. kindly assign me this issue to resolve with label as gssoc @apu52.
 
![bug in responsiveness](https://github.com/apu52/Travel_Website/assets/122367467/6e0736f8-eef4-4a6c-b3d7-678b14dc7547)

**Comment by Ghanshyam89** [comment]
Hi @Pardume-Sharma 

This is a duplicate issue of #328 , please have a look at available issues first before raising any issue.

Regards
Project Mentor
