### ISSUE TITLE
BUG Url have space

### ISSUE THREAD

**Issue by dhruv8433** [apu52/Travel_Website#450]
**Describe the bug**

@apu52 

please check this img
![image](https://github.com/apu52/Travel_Website/assets/114583978/9702046f-4772-417a-967c-5694a4229d80)

it doesn't have slug and for search engin optimization we use slugify in url for better use experience

***Are you contributing under any open-source program ?***
GSSOC 24

**Comment by Ghanshyam89** [comment]
Hi @dhruv8433 

This is a good issue start working on it, try make it in 3-4 days.

**Comment by dhruv8433** [comment]
Thank you @Ghanshyam89
