### ISSUE TITLE
BUG - Login Page Error

### ISSUE THREAD

**Issue by Akshitha-reddy-13** [apu52/Travel_Website#451]
**Describe the bug**
Connecting third-part authentications firebase or google firebase to solve this error 

**Expected behavior**
When we use Google, GitHub, or our own credentials, it should redirect to the main page of the website with a successful login. 

**Screenshots (Mandatory)**
![Screenshot 2024-05-15 154920](https://github.com/apu52/Travel_Website/assets/122172211/b900ed35-6fce-4f2b-ad2f-e2178a3d767c)

**Additional Context (Mandatory )**
Please add the label of gssoc, project level  and There are some miner errors in the main page

***Are you contributing under any open-source program ?***
 GSSoC-2024 contributor

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the contributing.md file before contributing

**Comment by neeraj10122004** [comment]
please assign this task to me under gssoc 24

**Comment by Ghanshyam89** [comment]
Hi @Akshitha-reddy-13 

This is a duplicate issue #268 , please have a look at available issues first before raising any issue.

Regards
Project Mentor
