### ISSUE TITLE
BUG:Login option is not fully visible

### ISSUE THREAD

**Issue by K-Tikaraya** [apu52/Travel_Website#454]
**Describe the bug**
  in Navbar alignment of contents is not good and login option is also not properly visible which is most important

**Expected behavior**
 improving alignment and appearance of navbar contents and making login button clear and visible

**Screenshots (Mandatory)**

![Screenshot (222)](https://github.com/apu52/Travel_Website/assets/165303736/25dcafdf-55c8-4098-bb91-ff54e1ada8ec)

**Additional Context (Mandatory )**

Please label this issue and assign it to me @apu52 

***Are you contributing under any open-source program ?***

I am contributing in GSSOC@2024

**Comment by Ghanshyam89** [comment]
Hi @K-Tikaraya 

This is a duplicate issue, please have a look at available issues first before raising any issue.

Regards
Project Mentor
