### ISSUE TITLE
Add Arrow Button

### ISSUE THREAD

**Issue by Mrityunjya** [apu52/Travel_Website#456]
**Is your feature request related to a problem? Please describe.**
Yes, Navigation towards the top of the website

**Describe the solution you'd like**
I would like to create a arrow button which navigates to the top for users to easily navigate.

**Describe alternatives you've considered**
Creation of arrow button

***Are you contributing under any open-source program ?***
GSSOC 24 Contributor

**Comment by Sindhuja-Nigam** [comment]
I am experienced with this type of task. Please assign this issue to me.

**Comment by Ghanshyam89** [comment]
Hi @Mrityunjya 

It is a good issue, start working on it. Please make it in 3-4 days and post proper updates regularly.

**Comment by Mrityunjya** [comment]
Sure
