### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by Ramben0909** [apu52/Travel_Website#458]
the window section that appears at the beginning can be also closed by clicking outside of the window or clicking exit button

 I will add JavaScript functionalities so that this feature can be added to this site 

 I have good knowledge of JavaScript

![Screenshot 2024-05-15 184358](https://github.com/apu52/Travel_Website/assets/121795329/f74fdf8c-09cc-48fc-80b6-144dfdfc59be)
  
Hey @apu52 please add level to this issue and assign this to me as a GSSoC contributor

**Comment by Ghanshyam89** [comment]
Hi @Ramben0909 ,

I have assigned this issue to you, please start working on it and get it done in 2-3 days. 

Regards
Project Mentor
