### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by Ramben0909** [apu52/Travel_Website#459]
From the log in page I also can back to the main page using esc or exit button 

 I can  add JavaScript on click events to do so 

I have good knowledge of  JavaScript 

 
 
 
![Screenshot 2024-05-15 185237](https://github.com/apu52/Travel_Website/assets/121795329/e77ac4e1-6b3a-477a-8856-15ebd11eef27)

 Hey @apu52  please add the level and assign me this issue as a GSSoC contributor

**Comment by Ghanshyam89** [comment]
Hi @Ramben0909 ,

I have assigned you another issue and as per our contribution guidelines you can only work at one issue at a time. Please focus on that and complete it first.
