### ISSUE TITLE
Feature_Request Add animation to 'Best Trip Package' Section

### ISSUE THREAD

**Issue by Shravani-Korde** [apu52/Travel_Website#46]
**Is your feature request related to a problem? Please describe.**
It is not a problem. It will help to make the website more engaging and enhance the overall user experience.

**Describe the solution you'd like**

- Adding animation to the images present in 'Best Trip Package' section.
- Whenever user places the cursor on the image it will present highlighted animation giving a better visual appearance.
- Also making all the images of uniform size.

**Demo Video/Screenshot (Mandatory )**
![Image](https://github.com/apu52/Travel_Website/assets/149994109/b273608b-9791-4d89-bd7a-9859459aa06d)

***Are you contributing under any open-source program ?***
Yes I want to work on this issue under JWOC.

**Comment by apu52** [comment]
@Shravani-Korde You are assigned. Carry on!!!!!!

**Comment by apu52** [comment]
You have just 1 day to complete this issue
