### ISSUE TITLE
Typography needs to be improved

### ISSUE THREAD

**Issue by nishantharkut** [apu52/Travel_Website#462]
Typography is crucial in communication, enhancing readability, evoking emotions, and conveying messages effectively. It dictates tone, guides the eye, and influences perceptions. Through font choice, size, spacing, and alignment, typography shapes brand identity, user experience, and overall design aesthetics. It's the silent conductor of visual language, wielding immense power in expression.

***Are you contributing under any open-source program ?***
PLEASE ASSIGN TO ME UNDER GSSOC'24

**Comment by Ghanshyam89** [comment]
Hi @nishantharkut ,

Can you please show us some examples relating our pre-existing website to the thing you want to make before assigning this issue to you.

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @apu52  under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.

**Comment by DiwareNamrata23** [comment]
I'm interested to work on this issue .@apu52 Please assign this issue to me
