### ISSUE TITLE
Feature_Request: Add styling to the feedback page.

### ISSUE THREAD

**Issue by Saimanjari777** [apu52/Travel_Website#463]
**Is your feature request related to a problem? Please describe.**
The feedback form in the contact us section doesn't have any styling and it is not looking good.

**Describe the solution you'd like**
I want to add the styling to the feedback form and make it appealing to look.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/130165687/bc637e2f-4f89-49a0-9ec2-a1a965c8b97b)

***Are you contributing under any open-source program ?***
I am contributing under GSSoC'24.
Please assign this task to me @apu52

**Comment by Iamkg11** [comment]
Please assign this issue to me under Gssoc'24. I'm a contributor and I would like to work on this issue.

**Comment by SHANMUGAPRIYA-1** [comment]
Please do assign this task to me

**Comment by rounakdey6** [comment]
Please sir assign this work to me .I would love to work on this issue

**Comment by Bhoomii2003** [comment]
Please Assign this issue to me.

**Comment by Ghanshyam89** [comment]
Hi @Saimanjari777 

This is a duplicate issue of #493  . I would like to recommend you to raise any new issue. Please have a look at available issues first before raising any issue.

Regards
Project Mentor

**Comment by Ghanshyam89** [comment]
Yes @Saimanjari777 , So sorry for this unforeseen mistake. I have assigned this issue to you, please start working on it.

**Comment by Seejal03** [comment]
Please assign this issue to me.
