### ISSUE TITLE
Feature: Scroll to Top arrow button 

### ISSUE THREAD

**Issue by SalehaTabassum** [apu52/Travel_Website#464]
I have found that there is no scroll to top option in this website.It would make it more user friendly if we add this ,as it helps the user to easily navigate .
I have a good knowledge web development and have worked on making websites,so I think I can fix this issue easily 
 @apu52 so please assign this issue to me under GSSOC 2024 and add necessary labels to it

**Comment by prajna321** [comment]
A scroll-to-top option could greatly enhance user navigation. With my experience in web development, I believe I can quickly address this issue. @apu52, please assign this task to me under GSSOC 2024 and apply relevant labels. Thanks!

**Comment by tanishkaa08** [comment]
i would like to work on this issue. please assign me this issue.

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue

**Comment by Ghanshyam89** [comment]
Hi @SalehaTabassum ,

This is duplicate issue of #43 . I would like to recommend you to raise any new issue. Please have a look at available issues first before raising any issue.

Regards
Project Mentor
