### ISSUE TITLE
Feature_Request : Adding a remember me check box in the login page 

### ISSUE THREAD

**Issue by AnushkaSharma04** [apu52/Travel_Website#466]
# Issue to be resolved and solution :

For frequent travelers or users of the site providing an easy access will enhance the performance and give a bright impression. 

So I would like to add a remember me check box to the login page.

<img width="312" alt="login2" src="https://github.com/apu52/Travel_Website/assets/145102276/84727858-de50-4595-8ddf-cf2a48616c62">
This is the section to be targeted .

***Are you contributing under any open-source program ?**
I am a gssoc'24 contributor
I request you to kindly assign this issue to me under gssoc'24 label .

**Comment by AnushkaSharma04** [comment]
@apu52  Kindly add gssoc'24 label and assign this issue to me .

**Comment by Tejarella** [comment]
I would like to fix this issue. So please assign this task to me . I am a contributor to GSSoC'24

**Comment by Ghanshyam89** [comment]
Hi @AnushkaSharma04 ,

This is an amazing issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
