### ISSUE TITLE
Feature_Request:  Added missing Navbar on the feedback page

### ISSUE THREAD

**Issue by SadafKausar2025** [apu52/Travel_Website#469]
**Is your feature request related to a problem? Please describe.**

the Navbar was missing in the feedback section  and unable to navigate back so , itis important to add Navbar to feedback page also

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
before screenshot
![Screenshot (1692)](https://github.com/apu52/Travel_Website/assets/137484958/e1350a84-9443-406d-8186-c79b8351f167)

after updating

![Screenshot (1693)](https://github.com/apu52/Travel_Website/assets/137484958/56ebc7c0-f1a1-4b1b-887f-18714ea9cc27)

***Are you contributing under any open-source program ?***
yes girlscript summer of code (Gssoc'24)

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me #469

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by SadafKausar2025** [comment]
Hey @Ghanshyam89 

I have already done with PR #383 
can you please merge this PR?
