### ISSUE TITLE
[Feature_Request]The "Contact Us" link in the footer is currently unresponsive.

### ISSUE THREAD

**Issue by abhayvershwal** [apu52/Travel_Website#472]
**Is your feature request related to a problem? Please describe.**
When the "Contact Us" link is clicked, the website fails to redirect to the Contact Us page. This issue needs to be resolved so that the link properly redirects to the intended page.

**Describe the solution you'd like**
To address this issue, I propose adding a new link to the footer that redirects users to the Contact Us page. and also add same CSS to that so that it match other components in footer

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/93792490/0139f64c-69aa-4baa-bfcd-6c6d5ea0969c)

***Are you contributing under any open-source program ?***
GSSOC 2024

**Comment by abhayvershwal** [comment]
@apu52 
Please assign the task of updating the "Contact Us" link in the footer to redirect users to the appropriate page to me. I have successfully resolved this issue at my local, and now the link functions as intended, directing users to the Contact Us page of the website.

also mark label gssoc

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by abhayvershwal** [comment]
Hii @Mahimatestgithub 
You can clone the site locally in your system, run it, and identify any issues. Then, raise these issues on GitHub, and the repository owner will assign them to you.
