### ISSUE TITLE
BUG:LOGIN PAGE

### ISSUE THREAD

**Issue by IpsitaPrusty** [apu52/Travel_Website#476]
**Describe the bug**

We cannot have any proper details of users.

**Expected behavior**

There should be more boxes as an required information such as confirm password, first name ,last name.

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

No, I am not contributing under any open-source program except gssoc'24.

**Comment by ichitrang** [comment]
I hope this message finds you well. My name is Chitrang Jain, and I am a passionate developer with experience in web development and design. I am writing to express my interest in contributing to the "TourGuide" project, particularly by solving this bug comprehensive "Login" for the TourGuide website. To proceed, I kindly request access to the repository to begin working on this enhancement. I am open to feedback and keen on maintaining the project's coding standards and conventions.

**Comment by Ghanshyam89** [comment]
Hi ,

I am impressed with your issue. Please start working on this issue.

Regards
Project Mentor (GSSoC' 24)

**Comment by IpsitaPrusty** [comment]
@Ghanshyam89 sir what about the label??

**Comment by IpsitaPrusty** [comment]
@Ghanshyam89  Sir, also I am adding a page for login up for those who visit second time....so will that be included in bug level?
