### ISSUE TITLE
Adding social media icons in footer

### ISSUE THREAD

**Issue by Jagpreet153** [apu52/Travel_Website#477]
**Is your feature request related to a problem? Please describe.**
Yes , it would make user to connect with admin easily

**Describe the solution you'd like**
I would be adding 3-4 social media icons redirecting to the respective pages 

**Describe alternatives you've considered**
Using simple HTML , CSS 

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/119691733/9bee906f-a63f-4743-b49b-a7a5d14680be)

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by JagjeetChauhan** [comment]
Can you assign this problem to me? I am contributing to GSSoc'24.

**Comment by Sindhuja-Nigam** [comment]
I would like to work on it .Please assign this task to me .

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by TitikshyaChanda** [comment]
As a front end developer, I would love to work in this project.Kindly assign me this.

**Comment by satyendushukla** [comment]
I would like to work on it ,,please assign it to me ,i will surely do it

**Comment by Ghanshyam89** [comment]
Hi @Jagpreet153 ,

This is a duplicate issue, I would like to recommend you to raise any new issue you want to work on this repo and please have a look at available issues first before raising any issue.

Regards
Project Mentor
