### ISSUE TITLE
BUG: Add Styling to Feedback Form

### ISSUE THREAD

**Issue by Mansi-Narang** [apu52/Travel_Website#479]
**Describe the bug**
The feedback form looks like a pure html page, which doesn't looks good and attractive

**Expected behavior**
A clean UI for the feedback section must be provided to the User which may make them look approved by the feedback section.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/156189119/b4c3dccb-36c9-4b7a-8407-f470cc0de8c0)

**Additional Context (Mandatory )**
The User Interface makes user attracts the user towards itself and makes the user believe the correct behaviour of their experience over the website that they are at the right place.

***Are you contributing under any open-source program ?***
Yes I am contibuting under GSSOC

I want to work over this Issue

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by Rashi563** [comment]
Please assign me this issue under GSSOC'24.

**Comment by rounakdey6** [comment]
Sir I would like to work on this issue. Please assign this issue to me .

**Comment by Ghanshyam89** [comment]
Hi ,

This issue has been resolved already by someone.

Regards
Project Mentor (GSSoC' 24)
