### ISSUE TITLE
{Feature_Request}  Rating system using HTML CSS

### ISSUE THREAD

**Issue by daksh1210jain** [apu52/Travel_Website#48]
I want to add a rating system
**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Ss1](https://github.com/apu52/Travel_Website/assets/137384322/9b07b65b-cbfe-4a8d-8152-cd6a6ea4d78e)
![Ss2](https://github.com/apu52/Travel_Website/assets/137384322/a4457a6d-03d5-47f4-b7e5-036ceee3a72f)

Contributing under JWOC

**Comment by apu52** [comment]
can you please explain me more about this??
Like where you want to insert it?

**Comment by daksh1210jain** [comment]
sir basically i want to add an option at the top like given in the following page 
![ss_2](https://github.com/apu52/Travel_Website/assets/137384322/142ca151-5a57-4461-a39a-53bba3a76ee3)

**Comment by apu52** [comment]
> sir basically i want to add an option at the top like given in the following page ![ss_2](https://private-user-images.githubusercontent.com/137384322/296804838-142ca151-5a57-4461-a39a-53bba3a76ee3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzc5NDksIm5iZiI6MTcwNTMzNzY0OSwicGF0aCI6Ii8xMzczODQzMjIvMjk2ODA0ODM4LTE0MmNhMTUxLTVhNTctNDQ2MS1hMzlhLTUzYmJhM2E3NmVlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNjU0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTRlMWNhOTY1ZDI5ZjQzMjZmZWRjYTUwNDJkODk1MDlhN2JkMWJjNGJhMjEzZDc2NDdmMjUwOThjMTEzNTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.odwSTZUw6HiSkKIDX7e6vPr-q6loORkWnTFR9V8TnWA)

Is that will be responsive or static

**Comment by daksh1210jain** [comment]
i will try to make it responsive

**Comment by apu52** [comment]
@daksh1210jain I have assigned you . You have 2-3 days to submit your PR

**Comment by daksh1210jain** [comment]
Daksh jain is my name sir

**Comment by apu52** [comment]
ok
