### ISSUE TITLE
Feature : Imroving the Styling of the About us page

### ISSUE THREAD

**Issue by AbhiJay1287** [apu52/Travel_Website#480]
would like to improve the color theme of the about us main div and also make necessesary changes to it 

and improve the styling of the slider

![Screenshot (122)](https://github.com/apu52/Travel_Website/assets/105973197/c31301d7-c2aa-4431-8e7a-8b3a759a3c08)

I am a GSSOC'24 contributor can you please assign this to me ?

**Comment by BhumikaRahwani** [comment]
I would like to address on this issue
Plz, do assign it.

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by kishoranushka** [comment]
I would like to work on this issue can you please assign this to me?

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by harshcodesit** [comment]
hey @Ghanshyam89 

My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the About us page in an interactive manner, making it visually appealing.
make the footer immersive

Please assign this task to me, GSSOC'24 .

**Comment by ananyag309** [comment]
Hey, I am willing to work on the respective issue please assign it to me under gssoc'24.
