### ISSUE TITLE
adding a scroll back to top button

### ISSUE THREAD

**Issue by Soumya6Tiwari** [apu52/Travel_Website#481]
adding a scroll back to top button which will be placed at the bottom right of the page ,clicking on which will take the user back to the home page.
@apu52 kindly assign me this issue under gssoc'24

**Comment by anuragnegi000** [comment]
please assign this issue to me

**Comment by Soumya6Tiwari** [comment]
@apu52 kindly assign me this issue

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.

**Comment by Ghanshyam89** [comment]
Hi ,

This issue has been resolved already.

Regards
Project Mentor (GSSoC' 24)
