### ISSUE TITLE
About the newsletter section

### ISSUE THREAD

**Issue by Ajita369** [apu52/Travel_Website#483]
**Describe the bug**
There is "send" written on the option for user to submit their email.

**Expected behavior**
It should be either "submit" or "subscribe" in place of "send" as it is the right practice to use them.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/162597493/6c35b0aa-6e81-4960-a236-38e42523019c)

**Additional Context (Mandatory )**
I will like to work on this issue so please assign this issue to me under GSSOC'24.

***Are you contributing under any open-source program ?***
GSSOC'24

**Comment by Ankita248** [comment]
"Send" option is written instead of subscribe.
I will like to work on this issue so please assign this issue to me under GSSOC'24.@apu52
![Screenshot 2024-05-16 213357](https://github.com/apu52/Travel_Website/assets/102206335/32198579-6463-4a13-9bf4-83ea71aadf2c)

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
