### ISSUE TITLE
UI improvements, animation improvements, a bit unprofessional for a travel website, bugs in landing pages, bubbles seem to be overwhelming after a point

### ISSUE THREAD

**Issue by idkimbc** [apu52/Travel_Website#484]
## **Is your feature request related to a problem? Please describe.**
- The UI could be better. The page seems a bit less professional for a travel website. Overdone effects.
- The animations seem a bit long. The animations seem to keep going before the user moves the cursor away from the element.
- The pricing plan landing page doesn't seem to work properly. The contents don't load up until scrolled to a certain point
- The bubbles look okay at the start but as I scroll down, the bubbles seem to get in the way of a lot of things making it hard to look at the options. 
- The image in the first section of the landing page doesn't resize itself well when the resolution is reduced.

## **Describe the solution you'd like**
- For the UI part, I could design a new template for you to consider, if I'm assigned this project and then work on coding that up if you're up for it
- The animations can be taken care of as well. They can be optimised further and maybe unnecessary effects can be removed.
- The landing page problem can be dealt with by checking the scrolltrigger code again. Other changes might have to made as well
- The image resizing needs to be taken care of which can be done easily through some simple CSS enhancements

## **Describe alternatives you've considered**
- For the bubbles, maybe we can keep the bubbles restriced only to a particular section of the landing page and not let them float all over the website. This makes it harder for the user to keep looking at the website blocking the vision and also doesn't sit right in the brain psychologically. Might hamper their thinking and decision making.

## **Demo Video/Screenshot (Mandatory )**
The button/link redirects to the same video that is played on clicking on the above two buttons as well. As the name suggests 'location' it is more appropriate to maybe pinpoint the locations in the vicinity of the company. Or maybe produce a video that gives a brief about the same.
<img width="577" alt="Screenshot 2024-05-16 at 14 54 19" src="https://github.com/apu52/Travel_Website/assets/92934203/0c949256-ce32-4669-8d08-57ca7281784d">

### Issue with the 'View all' package options page.
The contents of the page don't seem to load until the scroller reaches a certain point.
The JS code needs to be looked into
<img width="1676" alt="Screenshot 2024-05-16 at 15 02 18" src="https://github.com/apu52/Travel_Website/assets/92934203/ecb66b84-39ef-46be-9f13-0cf735d30cef">

Improper alignment. All the three buttons should either be placed next to each other or on top of each other
<img width="241" alt="Screenshot 2024-05-16 at 15 11 55" src="https://github.com/apu52/Travel_Website/assets/92934203/fbff4ce8-d171-49d0-9257-125754bdb7d1">

Image resizing is not correct for lesser resolution devices.
<img width="499" alt="Screenshot 2024-05-16 at 15 13 29" src="https://github.com/apu52/Travel_Website/assets/92934203/1156a64d-b624-4036-8895-10bee9373230">

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by idkimbc** [comment]
I would like to contribute in helping adjust the errors and features that I have mentioned above so it'd be highly appreciated if you could assign me this task under GSSoC'24
Thank you for considering

**Comment by Rishitatripathi** [comment]
"I'd like to contribute by addressing the errors and implementing the suggested features. I would greatly appreciate being assigned this task for GSSoC'24. Thank you for considering my request."

**Comment by kishoranushka** [comment]
I would like to contribute in the GSSoC'24 by addressing the bubble overwhelming issue  and enhancing the UI part. Please assign this to me.

**Comment by Ghanshyam89** [comment]
Hi ,

I am very much impressed with your issue, please start working on this and focus on to reduce the loading time of website.

Regards
Project Mentor (GSSoC' 24)

**Comment by idkimbc** [comment]
yes I'll start working immediately

**Comment by kishoranushka** [comment]
Thank you so much for assigning the issue to me. I'll start working
immediately.
Regards
Anushka Kishor

**Comment by idkimbc** [comment]
He didn't assign it to you. Find your own issues on projects instead of taking up others'

**Comment by Ghanshyam89** [comment]
Yes @kishoranushka, I have assigned this issue to @idkimbc , as we follow FCFS rule. So sorry i forgot to mention the assignee.

**Comment by kishoranushka** [comment]
There was some confusion from my side. Thank you for the clarification.
