### ISSUE TITLE
Improvement in the feedback form

### ISSUE THREAD

**Issue by smritig26** [apu52/Travel_Website#485]
**Is your feature request related to a problem? Please describe.**

ui of the feedback form is not upto the mark

**Describe the solution you'd like**

improvement in the ui of the feedback form

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by MadMax1311** [comment]
@apu52  Please assign me this issue under GSSOC'24.

**Comment by Iamkg11** [comment]
Please assign this task to me under GssoC'24

**Comment by Ghanshyam89** [comment]
Hi ,

This issue has been already resolved.

Regards
Project Mentor (GSSoC' 24)
