### ISSUE TITLE
Hover effect on view all button in gallery

### ISSUE THREAD

**Issue by HimanshuGolyan01** [apu52/Travel_Website#486]
**Describe the bug**
The hover effect on view all button in gallery is not working as it is working in other sections.

**Expected behavior**
Slow hover on view all button in gallery

**Screenshots (Mandatory)**

https://github.com/apu52/Travel_Website/assets/165277909/14022c6a-98f4-45e4-88a0-eb9ef635f6d0

***Are you contributing under any open-source program ?***
GSSOC'24

**Comment by HimanshuGolyan01** [comment]
Please Assign this issue to me.

**Comment by Shatakshi-gupta-ggits** [comment]
Please Assign this issue to me.

**Comment by Bhoomii2003** [comment]
Please Assign this issue to me.

**Comment by Hanshika248** [comment]
Good Evening, It would be great if you would assign me this issue

**Comment by Tejarella** [comment]
I would like to fix this issue. So please assign this task to me. I am a contributor to GSSoC'24.

**Comment by Ghanshyam89** [comment]
Hi ,

This issue has been already resolved earlier only. Please raise a new meaningfull issue.

Regards
Project Mentor (GSSoC' 24)
