### ISSUE TITLE
Feature_Request: Add back to top Scroll button

### ISSUE THREAD

**Issue by Saimanjari777** [apu52/Travel_Website#487]
**Is your feature request related to a problem? Please describe.**
There is no back to top scroll button which we can add to make it look organized.

**Describe the solution you'd like**
I want to add the button on the bottom-right corner or in the middle according to the alignment.

***Are you contributing under any open-source program ?***
I am contributing under GSSoC'24
Please assign this issue to me @apu52

**Comment by TitikshyaChanda** [comment]
Please assign this issue to me @apu52

**Comment by Ghanshyam89** [comment]
Hi ,

This issue has been already resolved. Please raise a new issue that is meaningfull.

Regards
Project Mentor (GSSoC' 24)
