### ISSUE TITLE
Feature_Request: Top searches for best tour 

### ISSUE THREAD

**Issue by patelkiran185** [apu52/Travel_Website#488]
top searches for the best tour include the most frequent tours like top 10 visited, Agra tour, Delhi tour, Paris tour, Japan tour, etc.
top attraction worldwide, top destinations, top countries to visit, and top attraction categories

**Comment by Ghanshyam89** [comment]
Hi ,

We have a proper format for raising a issue so please raise a new issue with that template, for now closing this issue.

Regards
Project Mentor (GSSoC' 24)
