### ISSUE TITLE
Feature_Request :- Home Button on Plan Trip Page

### ISSUE THREAD

**Issue by Kcode15** [apu52/Travel_Website#489]
**Describe the bug**
There is no home button on "Plan a trip" Page

**Expected behavior**
A Home button on the Trip Planner page 

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/129003839/66d4fad4-c3de-484d-9cb9-ef866ddb03e2)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSoC 2024

**Comment by Kcode15** [comment]
Please assign me this issue. I am contributing under GSSoc'24

**Comment by somu545** [comment]
I would like to work on the issue . Assign this to me I am GSSoc 2024 contributor

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
