### ISSUE TITLE
BUG: Website auto refreshing after submitting contact us.

### ISSUE THREAD

**Issue by saketh-05** [apu52/Travel_Website#492]
In Contact Us section,

- After we fill details and press 'Send' button, website is refreshing without any reaction. Also any changes like "night mode ON" also reverting back to light mode.

- Also making email verification more accurate to prevent SQL injections.

-I can also work on issue with login page, which is not working correctly.

Please assign this issue to me under GSSoC'24
![Screenshot 2024-05-17 194323](https://github.com/apu52/Travel_Website/assets/134281589/8ce5b23b-35ab-4c0e-9fee-0f5700d3fbb0)

***Are you contributing under any open-source program ?***
GSSOC 2024

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this issue and just do first 2 points. 

Regards
Project Mentor (GSSoC' 24)
