### ISSUE TITLE
Styling for Feedback Form

### ISSUE THREAD

**Issue by HimakarC** [apu52/Travel_Website#493]
![Screenshot 2024-05-18 085649](https://github.com/apu52/Travel_Website/assets/116370824/d85d3d29-313b-4baa-8e08-394d9b2c3df0)

Adding styling to this form improves the attractiveness of this interface.

Please assign this Issue to me.

**Comment by Kavyasrikaki** [comment]
Please assign me this issue. I am contributing under GSSoc'24

**Comment by Ghanshyam89** [comment]
Hi @HimakarC  ,

I have assigned this issue to you, please start working on this issue and give proper updates with the progress regularly and follow color scheme and UI templates thoroughly.

Regards 
Ghanshyam Prajapati
Project Mentor

**Comment by Ghanshyam89** [comment]
Hi @HimakarC 

This is a duplicate issue of #463  . I would like to recommend you to raise any new issue. Please have a look at available issues first before raising any issue.

Regards
Project Mentor
