### ISSUE TITLE
improve destination page by reducing image size and text background,font

### ISSUE THREAD

**Issue by Prakrati1907** [apu52/Travel_Website#499]
The size of image is quite large with respect to window , moreover the font of country and place is not attractive with blur background like paris and eiffel tower.
please allow me to make changes to this, would assure you make it more better.
I am GSSOC'24 contributor and can fix this issue

![Screenshot 2024-05-18 204302](https://github.com/apu52/Travel_Website/assets/120261907/c4e3a803-9635-497b-9247-d43b6b1519ad)

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by ananyag309** [comment]
Hey, I am willing to work on the respective issue. Please assign it to me.

**Comment by Nikhilkumar111** [comment]
Hello, I  want to solve this issue  pls assign to me .
