### ISSUE TITLE
Creating Curved Corners for the Video

### ISSUE THREAD

**Issue by coderiksenthil** [apu52/Travel_Website#501]
**Is your feature request related to a problem? Please describe.**
The website currently looks plain and lacks visual appeal without any curvature in the video.

**Describe the solution you'd like**
Add a CSS property to make the video corners curved for a more attractive design,While seemingly minor, this issue can significantly impact the overall user experience, highlighting the importance of attention to detail in design.

Additionally, the code is already prepared and ready for implementation, I kindly request to be assigned to this task. 

**Describe alternatives you've considered**
Implementing curved corners to enhance the visual attractiveness of the video.

**Demo Video/Screenshot (Mandatory )**
Before Rounded Corners
<img width="960" alt="before_Rounded" src="https://github.com/apu52/Travel_Website/assets/66522620/82d0bcc4-da89-4126-a34f-c012ed0650be">
After Rounded Corners
<img width="960" alt="After Curve" src="https://github.com/apu52/Travel_Website/assets/66522620/f1c659b4-73a5-40ae-9587-0ece1f706bcf">

***Are you contributing under any open-source program ?***
I am a part of GSSoC 2024

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by coderiksenthil** [comment]
Thank You for assigning me this issue
