### ISSUE TITLE
BUG : There is a slight grammatical error on the login page.

### ISSUE THREAD

**Issue by karishmaaa101** [apu52/Travel_Website#502]
**Describe the bug**
This is how the login page looks:
![image](https://github.com/apu52/Travel_Website/assets/104766763/7fcab414-5dba-4cee-845c-150e5cd7b747)

**Expected behavior**
It should say :
_To stay connected with us,kindly login with your personal information_

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/104766763/13ef5c58-6bed-43b6-9572-f016dbad3411)

***Are you contributing under any open-source program ?***
I am contributing in the GirlScript Summer of Code 2024 as an open-source contributor.

**Comment by chakrabortydeep** [comment]
I can fix the errors. Please assign me the task.

**Comment by Tejarella** [comment]
I am ready to fix this issue . please assign me this task

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please come up with all such cases and change them not only in Login page but whole website.

Regards
Project Mentor (GSSoC' 24)

**Comment by ananyag309** [comment]
Hey, I am willing to work on the issue under gssoc. Please assign it to me.
