### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [apu52/Travel_Website#503]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by Ghanshyam89** [comment]
Hi ,

We already have such PR template please a have look into it and raise suggestion in that if any.

Regards
Project Mentor (GSSoC' 24)

**Comment by suhanipaliwal** [comment]
I would like to add a section in which contributor could select the type of issue solved like bug fixed or documentation issue or a feature addition. Also, I would like to organise this template in a better way. You can take reference from this link https://github.com/ashutosh-rath02/git-re/blob/main/.github/pull_request_template.md 
I added this pr template in this repository.

**Comment by apu52** [comment]
@suhanipaliwal this is a good issue .just want to let you know this repo already have a standard PR template . So without hampering / changing it so much you can add your features.

I am assigning you .you can start working

**Comment by apu52** [comment]
> @apu52 have a look into it

Thanks Sir for the reminder

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.
