### ISSUE TITLE
Auto typwriting text it home page is moving up and down..BUG

### ISSUE THREAD

**Issue by SuhainaFathimaM** [apu52/Travel_Website#504]
**Describe the bug**

The text cursor is moving up and down..

**Expected behavior**

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

I am Contributing under GSSoC'24

**Comment by SuhainaFathimaM** [comment]
@apu52Please assign me this issue

**Comment by apu52** [comment]
@SuhainaFathimaM can you please add some ss on which feature you want to add in this website (ex . the text cursor)

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me

**Comment by DiwareNamrata23** [comment]
hello @apu52 I'm interested to work on this issue . I request you to assign this issue to me

**Comment by apu52** [comment]
This issue is already been solved
