### ISSUE TITLE
BUG: Inconsistency in footer 

### ISSUE THREAD

**Issue by cxde-Sujal** [apu52/Travel_Website#505]
**Describe the bug**

messages on hover effect changes to color in a rough manner 
few messages are blue in color while others in white some change on hover some do not
 

**Expected behavior**

A smooth transition during hover and it remains consistent with other links and messages

**Screenshots (Mandatory)**

![Screenshot (156)](https://github.com/apu52/Travel_Website/assets/137087363/ec75c1ec-9ddb-4091-b76b-80693244741c)
![Screenshot (160)](https://github.com/apu52/Travel_Website/assets/137087363/211230d0-1556-4144-937c-2fba209fa7ab)
![Screenshot (159)](https://github.com/apu52/Travel_Website/assets/137087363/0d0e5c2a-66f8-492e-82eb-49540ae84c70)
![Screenshot (157)](https://github.com/apu52/Travel_Website/assets/137087363/f5025555-e7c8-4e51-984a-188bd655f029)
![Screenshot (158)](https://github.com/apu52/Travel_Website/assets/137087363/1079dc45-d96b-4824-95cc-ff77d3db6ce8)

**Additional Context (Mandatory )**
It will look better by fixing these issues

***Are you contributing under any open-source program ?***

GSSoC'24

**Comment by cxde-Sujal** [comment]
Please assign it to me for Gssoc @Ghanshyam89

**Comment by Ghanshyam89** [comment]
Hi @cxde-Sujal ,

This is a duplicate issue, please have a look at available issues first before raising any issue.

Regards
Project Mentor
