### ISSUE TITLE
Feature_Request Testimonial needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [apu52/Travel_Website#507]
**Is your feature request related to a problem? Please describe.**
Testimonials needs to be responsive 

**Describe the solution you'd like**
Will use media query for fixing that

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot_20240519_095206](https://github.com/apu52/Travel_Website/assets/59639410/36e9308e-3457-4b94-88b0-4a87d9c39a42)

***Are you contributing under any open-source program ?***
Gssoc 24

**Comment by kapilG0** [comment]
Hello @apu52 please assign this issue to me under gssoc 24

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
