### ISSUE TITLE
Feature_Request after click on book now on start.html page checkout need to be aligned 

### ISSUE THREAD

**Issue by kapilG0** [apu52/Travel_Website#508]
**Is your feature request related to a problem? Please describe.**
Request after click on book now on start html page checkout need to be aligned 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot_20240519_095514](https://github.com/apu52/Travel_Website/assets/59639410/128dd085-8cef-4668-aa1f-0eae36f64492)

***Are you contributing under any open-source program ?***
Gsoc 24

**Comment by kapilG0** [comment]
Hello @apu52 please assign this issue to me under gssoc 24

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.        under gssoc24

**Comment by apu52** [comment]
@kapilG0 you are assigned . you can start working

**Comment by kapilG0** [comment]
> @kapilG0 you are assigned . you can start working

Hello @apu52 i have raised pr https://github.com/apu52/Travel_Website/pull/631 for this issue please check
