### ISSUE TITLE
,Feature_Request After click on membership in mobile view it is not showing all and also not scrollable 

### ISSUE THREAD

**Issue by kapilG0** [apu52/Travel_Website#509]
**Is your feature request related to a problem? Please describe.**
Not able to see all membership in mobile view needs to be scrollable 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot_20240519_100511](https://github.com/apu52/Travel_Website/assets/59639410/ad0c5e74-db1a-4e59-98aa-c2bf1ea83dd2)

***Are you contributing under any open-source program ?***

**Comment by kapilG0** [comment]
Hello @apu52 please assign this issue to me under gssoc 24

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by kapilG0** [comment]
Hello @Ghanshyam89 I have raised pull request https://github.com/apu52/Travel_Website/pull/589 for this issue please check
