### ISSUE TITLE
We can add the opacity feature in the feedback page , so that after clicking the feedback button , they can add their information. It may look attractive and also engaging.

### ISSUE THREAD

**Issue by ANIRUDH130903** [apu52/Travel_Website#510]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by ANIRUDH130903** [comment]
we can also add the add the animation feature on this feedback , and the after clicking the button , the information page get open

**Comment by ANIRUDH130903** [comment]
@apu52 can you please assign me this task.

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue but can you please add some example screenshots what you want to do?

Regards
Project Mentor (GSSoC' 24)

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
