### ISSUE TITLE
In the payment form the Heading is not align properly , we can change the heading as well as make text more engaging and attractive . Also can change the background color.

### ISSUE THREAD

**Issue by ANIRUDH130903** [apu52/Travel_Website#511]
**Is your Documentation related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Prototype Screenshot/Demo Video(Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by ANIRUDH130903** [comment]
@apu52 can you pls assign me this issue.

**Comment by Ghanshyam89** [comment]
Hi ,

This might be a good issue but you need to follow issue template and describe your issue with proper screenshots. And at one time I can only assign one issue to you so work on one issue first then focus on another one.

Regards
Project Mentor (GSSoC' 24)

**Comment by ANIRUDH130903** [comment]
GOOD EVENING SIR ,
As you said i align the heading of the form(from h2 to h1) and also add the
background to the form section. If it's perfectly match with the demand ,
then please assign me the issue.
your sincerely
ANIRUDH SHARMA

**Comment by ANIRUDH130903** [comment]
![Screenshot 2024-05-29 230312](https://github.com/apu52/Travel_Website/assets/129547564/8d600b2d-eaba-4123-ad00-9422addf8c4d)

**Comment by ANIRUDH130903** [comment]
![Screenshot 2024-05-29 231717](https://github.com/apu52/Travel_Website/assets/129547564/552ec92d-00de-4c80-a6aa-51c8d6a7e33c)


@Ghanshyam89  @apu52 please assign me this issue.

**Comment by apu52** [comment]
the check out page is already well designed . So , I don't need any changes . Sorry to close this issue
