### ISSUE TITLE
On the login page we can add the confirm password column for validation , also we can add the only numbers feature in the phone contact column and making all the column compulsory to fill it up compulsory.

### ISSUE THREAD

**Issue by ANIRUDH130903** [apu52/Travel_Website#513]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by ANIRUDH130903** [comment]
@apu52 can you please assign me this task.

**Comment by Ghanshyam89** [comment]
Hi ,
 
This is a duplicate issue so closing this one. Please raise a new meeaningfull issue.

Regards
Project Mentor (GSSoC' 24)
