### ISSUE TITLE
BUG: Hero section not responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [apu52/Travel_Website#518]
**Describe the bug**

The hero section is not responsive for smaller screen sizes.

**Expected behavior**

Changing the style so that the section looks good in all types of devices.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/121669832/1a8e2fca-7220-4c94-b3c8-20bc7c0fd6c6)

**Additional Context (Mandatory )**
Please assign me this issue, I have relevant skills to solve this task.

***Are you contributing under any open-source program ?***

Yes, I am a GSSoC'24 contributor and I want to contribute to this project under it.

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
