### ISSUE TITLE
Navigation Bar CSS is not working properly.

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [apu52/Travel_Website#519]
**Is your feature request related to a problem? Please describe.**

While switching from page to other the navigation bar css should be updated. It is working properly.

**Describe the solution you'd like**

By configuring the issue, the user will find the smooth functioning of website.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

![image](https://github.com/apu52/Travel_Website/assets/125359008/d4ddf772-f4c1-429e-8903-4937d101611d)

**Comment by GnanariddhikaRavikumar** [comment]
The issue is to enhance the property of NavBar , so that it makes the user to use the website smoothly. The enhancement feature will improve the UI of the website. As I opened the issue please assign it to me 
@KrishnenduDG  @Ghanshyam89  @apu52 . Do consider this

**Comment by Ghanshyam89** [comment]
Hi @GnanariddhikaRavikumar ,

Could you please share some screenshots what chages you want to do?

**Comment by GnanariddhikaRavikumar** [comment]
**Navigation bar removing Bug**

Now we are in trip gallery but in navigation bar  but it is showing as we are in two tabs 

![image](https://github.com/apu52/Travel_Website/assets/125359008/cce9d5c4-9f63-44cc-8ae4-2b33c7738efa)

![image](https://github.com/apu52/Travel_Website/assets/125359008/8e106c7d-1b7a-4e7f-9f9c-881c30dadac9)

So It gets confuses. I can resolve this. Kindly assign me the issue with gssoc and level labels

**Comment by apu52** [comment]
@GnanariddhikaRavikumar you are assigned .you can start working on this issue.
