### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [apu52/Travel_Website#520]
**Describe the bug**
The login and signup button in home page is not responding. After registering the user is unable to login. The actions are not handled properly. There by defining the actions properly the user can experience the smooth functioning of app.

**Expected behavior**

 By defining the actions properly the user can experience the smooth functioning of app.

**Screenshots (Mandatory)**

![image](https://github.com/EternoSeeker/gameoflife/assets/125359008/013c1ab4-e3d4-45ac-9f5d-58fd32f6025b)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

@Ghanshyam89

**Comment by Ghanshyam89** [comment]
Hi @GnanariddhikaRavikumar ,

Can you please share some screenshots what you want to do?

**Comment by GnanariddhikaRavikumar** [comment]
### The login and signup button in home page is not responding. After registering the user is unable to login.

Here I am entering the details to register

![image](https://github.com/apu52/Travel_Website/assets/125359008/1768e4ba-fb2b-461b-bc18-cde4bf7687bf)

After registered with details , the user can't able to access login button

![image](https://github.com/apu52/Travel_Website/assets/125359008/b9ff5893-b32d-4587-8465-bc90868d9add)

**There is another login that also having same issue**

![image](https://github.com/apu52/Travel_Website/assets/125359008/5e3aaa98-7b03-4a51-8f32-f1717097a670)

After registering or loging in we can't move further. It is major drawback of our website

So I want to rectify the issue that after registering the user need to move to login page. I can rectify the bug Assign me the issue with Gssoc and level labels.

**Comment by apu52** [comment]
@GnanariddhikaRavikumar an issue is already assigned to you, Try to complete that issue at first , Then ping me here or the MENTORS regarding this issue.

**Comment by GnanariddhikaRavikumar** [comment]
@apu52 Ok..sure I will complete that  soon and let you know. Thank You

**Comment by GnanariddhikaRavikumar** [comment]
@apu52  @Ghanshyam89  I have completed the previously assigned issue(#519) and raised the Pull Request. So can I know the progress of this issue

**Comment by apu52** [comment]
this issue has already been solved . Sorry to close this issue.
