### ISSUE TITLE
BUG Create account using other social media applications are not working

### ISSUE THREAD

**Issue by Janani-m17** [apu52/Travel_Website#522]
**Describe the bug**

The four buttons below the create account that is google, github, instagram, facebook are not working. It is redirecting to the same page.

**Expected behavior**

By clicking the button such as icons of Google, github, facebook, instagram the user should be able to signup through that platform, which make the sign up process easier.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/124059957/97c774b5-46f5-4e93-bd44-4f5a0742b959)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

@Ghanshyam89 
@apu52

**Comment by Ghanshyam89** [comment]
Hi ,

This is a duplicate issue of #268 . Please raise a new issue.

Regards
Project Mentor (GSSoC' 24)
