### ISSUE TITLE
 End Date Can Be Set Earlier Than Start Date

### ISSUE THREAD

**Issue by Pranjalidhale0711** [apu52/Travel_Website#523]
There is an issue where the end date can be set to a date earlier than the start date. This should not be allowed, as it leads to logical inconsistencies in date selection.

Steps to Reproduce:

1]Go to the date selection feature.
2]Select a start date.
3]Select an end date that is earlier than the start date.

Expected Behavior:
The system should prevent the end date from being set to a date earlier than the start date, possibly with an error message or by disabling the invalid dates.

Actual Behavior:
The system allows the end date to be set earlier than the start date without any warning or error.

<img width="620" alt="Screenshot 2024-05-20 at 6 39 47 PM" src="https://github.com/apu52/Travel_Website/assets/123875758/92d0064d-278f-40ba-8481-f76fef689074">

**Comment by Pranjalidhale0711** [comment]
Please give me access to edit it

**Comment by Pranjalidhale0711** [comment]
I wanted to inform you that I've successfully addressed the date issue we discussed earlier, and I've submitted a pull request for your review

**Comment by apu52** [comment]
@Pranjalidhale0711 Now I have assigned you. Now you can submit your PR . happy contribution!!!!!!!!!

**Comment by Pranjalidhale0711** [comment]
Sir I've submitted a pull request for your review
