### ISSUE TITLE
Documentation : Adding the related tech in readme.md

### ISSUE THREAD

**Issue by sshivangi882** [apu52/Travel_Website#524]
**Is your Documentation related to a problem? Please describe.**

The tech stack in the readme.md are only html and CSS.

**Describe the solution you'd like**

I would like to add JavaScript, Bootstrap and, the related technologies

**Prototype Screenshot/Demo Video(Mandatory )**

![Screenshot (895)](https://github.com/apu52/Travel_Website/assets/122531720/6bb7cfdc-6fa7-4ddd-83ce-c8dbe2fd5f8f)

***Are you contributing under any open-source program ?***

GSSOC'24

**Comment by Yuvraj960** [comment]
@apu52 Please assign this issue to me under GSSoC24

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
