### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by anshupriya12** [apu52/Travel_Website#525]
I personally feel the bubbles coming on the screen continuously is creating disturbance to user interface .

 Instead we can keep our background in subtle pattern without changing the original background color. 

![Screenshot 2024-05-20 205103](https://github.com/apu52/Travel_Website/assets/141250419/eb88927a-42b0-4926-94b1-adca4866eaa0)

I want to contribute to this project. So, kindly assign me the task.

**Comment by Ghanshyam89** [comment]
Hi ,

This might a good issue but please use issue template and raise a fresh issue with proper details. 

Regards
Project Mentor (GSSoC' 24)
