### ISSUE TITLE
Add effect

### ISSUE THREAD

**Issue by Nikuunj** [apu52/Travel_Website#526]
**Type of Issue**
- [x] Bug 🐛
- [ ] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

Add a mouse effect when moving the mouse. The effect should be rendered.

@apu52 (Please assign me)

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by Nikuunj** [comment]
**Type of Issue**
- [x] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I'm interested in contributing to the feedback page.

@apu52 (Please assign me)
