### ISSUE TITLE
 Add Navbar to Checkout Page

### ISSUE THREAD

**Issue by grasyPatel** [apu52/Travel_Website#527]
**Is your feature request related to a problem? Please describe.**
The checkout page of our travel website currently lacks a navigation bar (navbar). This can disrupt the user experience, as it restricts easy access to other parts of the site. Adding a navbar will provide users with a consistent and seamless navigation experience across the website.
 

**Describe the solution you'd like**
Adding a navbar will provide users with a consistent and seamless navigation experience across the website.

Current Behavior:

The checkout page does not have a navbar.
Users must use the browser's back button or type in the URL manually to navigate to other sections of the site.
Proposed Behavior:

The checkout page should include a navbar similar to the one on the other pages of the website.
The navbar should contain links to key sections of the site, such as Home, Destinations, Bookings, and Contact Us.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/123757155/67b2e92b-5121-463e-8c9d-e3e13b483a8c)

***Are you contributing under any open-source program ?***
gssoc'24

**Request for Assignment:**
I would like to work on this issue. Could you please assign it to me?

**Comment by BhumikaRahwani** [comment]
Hi!! @grasyPatel I am Bhumika Rahwani, contributor in GSSoC , I would like to address this issue, plz do assign me.

**Comment by grasyPatel** [comment]
@BhumikaRahwani  Thank you for offering to help with this issue. Please feel free to proceed with your investigation and let me know if you need any additional information from me.

**Comment by grasyPatel** [comment]
@apu52 ,  kindly offer to look into this issue , assign to work on this issue.

**Comment by BhumikaRahwani** [comment]
@grasyPatel, plz do assign me this issue!!

**Comment by BhumikaRahwani** [comment]
![Screenshot 2024-05-23 130034](https://github.com/apu52/Travel_Website/assets/141950336/a98aac99-9543-4bb8-9ac2-d9b15536b738)
@grasyPatel , I have added navbar to checkout page, plz di go through it and plz do assign me this issue!!

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
