### ISSUE TITLE
BUG: LogIN screen's  login button doesn't work

### ISSUE THREAD

**Issue by Tasnuva12** [apu52/Travel_Website#528]
**Describe the bug**

Login page's login button doesn't work

**Expected behavior**

the pressing of Login Button will take you to a login page .

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/47001609/3cbc1557-33d3-4977-9cce-b54a79373934)

**Additional Context (Mandatory )**
the register portion also doesn't work
***Are you contributing under any open-source program ?***

GSOC24

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
