### ISSUE TITLE
Improve the testimonial Section

### ISSUE THREAD

**Issue by shrutigolwalk0109** [apu52/Travel_Website#529]
I think if the Testimonial section had a different background color so it would have better UI and also it is not aligned properly.I would also like to make it responsive.
Please Assign me this issue with the label of GSSOC.

Screenshot:- 

![image](https://github.com/apu52/Travel_Website/assets/132553685/ed7dd925-6bf1-492c-9be7-a4e6357a213a)

**Comment by Ghanshyam89** [comment]
Hi ,

This might be a good issue but you are supposed to wait to get it assigned to you before raising a PR.

Regards
Project Mentor (GSSoC' 24)

**Comment by apu52** [comment]
@shrutigolwalk0109 welcome to the repo . You are assigned now . Now you can submit your PR . but I am closing your previous PR as it violates our contribution guidelines.
But feel free to submit your PR now
