### ISSUE TITLE
[Feature_Request] Profile Page 

### ISSUE THREAD

**Issue by avanimathur** [apu52/Travel_Website#531]
**Is your feature request related to a problem? Please describe.**
Currently, the site does not show the user's profile.

**Describe the solution you'd like**
The user should be able to view their past payments , details of their past trips etc.

**Describe alternatives you've considered**
After Registration, the navigation bar shows an option/button of User Profile.
When the Profile page opens, user has option to view past payments, trip history etc. 

**Demo Video/Screenshot**
![WhatsApp Image 2024-05-21 at 18 50 18](https://github.com/apu52/Travel_Website/assets/151984867/242ebf14-6eca-44f4-869f-539457ab6748)

***Are you contributing under any open-source program ?***
This is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign it to me 
Thanks.

**Comment by Ghanshyam89** [comment]
Hi @avanimathur ,

This is a good issue, but I can't assign you multiple issues at a time. so I am assigning this issue to @kashi-verma .

Regards
Project Mentor (GSSoC' 24)

**Comment by kashi-verma** [comment]
Thanks for assigning  this issue .
