### ISSUE TITLE
adding destinations functionality

### ISSUE THREAD

**Issue by Srujitha-Raghava** [apu52/Travel_Website#535]
### Add Functionality to Display Best and Affordable Destinations

**Summary:**
Implement a feature that allows users to view a list of best and affordable destinations by clicking on the "10994 Destinations" element on the home page. This feature includes navigating to a new page that displays the destination details.

**Details:**
1. **Home Page Update:**
   - Modify the "10994 Destinations" clickable element to navigate to a new page.
   - The new page should be `destinations.html`.

2. **New Page Creation:**
   - Create a `destinations.html` page that displays a list of best and affordable destinations.
   - Each destination should include details such as name, price, and rating.

3. **Styling:**
   - Ensure that the new page is styled consistently with the existing website design.
   - Use the existing `styles.css` or update it to include styles for the destination items.

4. **JavaScript:**
   - Add JavaScript to handle the click event on the home page and navigate to the new page.
   - Populate the destination details dynamically on the new page using JavaScript.

5. **Navigation:**
   - Include a "Back to Home" button on the new page that navigates back to the home page.

**Acceptance Criteria:**
- Clicking the "10994 Destinations" element on the home page navigates to the `destinations.html` page.
- The `destinations.html` page displays a list of at least 5 best and affordable destinations.
- Each destination item includes the name, price, and rating.
- The "Back to Home" button returns the user to the home page.

**Attachments:**

![Screenshot 2024-05-22 172948](https://github.com/apu52/Travel_Website/assets/143430142/7eb9cc3c-2131-490e-bb8c-74534c8e4e60)

![Screenshot 2024-05-22 173934](https://github.com/apu52/Travel_Website/assets/143430142/58a9d672-e769-44c7-89f6-72e48de80896)

hey @apu52 i can add this functionality once you assign to me under gssoc.Thankyou!

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)

**Comment by Srujitha-Raghava** [comment]
hey @apu52 @Ghanshyam89 I have raised a PR.kindly,check that and please say if any changes required
