### ISSUE TITLE
Designing of login page

### ISSUE THREAD

**Issue by Srujitha-Raghava** [apu52/Travel_Website#536]
### Add Email Validation on Login Page

**Summary:**
The login page currently does not validate the email format entered by the user. Implement proper email validation to ensure that users enter a valid email address before submitting the login form.

**Details:**
1. **Current Behavior:**
   - The login form accepts any input in the email field without validating the email format.

2. **Desired Behavior:**
   - Implement client-side validation to ensure the email field only accepts valid email addresses.
   - Display an appropriate error message if the email format is invalid.

3. **Validation Criteria:**
   - The email should follow the standard format: `example@domain.com`.
   - Use HTML5 email validation and/or JavaScript to enforce the format.

4. **Error Messaging:**
   - If the user enters an invalid email, display an error message such as "Please enter a valid email address."

**Acceptance Criteria:**
- The email field should validate the input format as a proper email address.
- An error message should be displayed if the email format is incorrect.
- The form should not be submitted if the email is invalid.

kindly assign me this under gssoc,so that i can work on. @apu52

**Comment by NalinDalal** [comment]
can i be assigned this one?
maybe can do in 2 hours itself

**Comment by Ghanshyam89** [comment]
Hi @Srujitha-Raghava  ,

This is a good issue, but I can't assign you multiple issues at a time.

Regards
Project Mentor (GSSoC' 24)

**Comment by Srujitha-Raghava** [comment]
@Ghanshyam89 validation just takes 2 hours of time to add.kindly assign me this,I will make this as fast as i can

**Comment by Srujitha-Raghava** [comment]
@Ghanshyam89 @apu52 i have added the required validation,please assign me this under gssoc so that i can raise a PR.

![Screenshot 2024-05-24 104915](https://github.com/apu52/Travel_Website/assets/143430142/7fee142d-ec8a-4b7b-8b4a-24067d1af9b1)

**Comment by Srujitha-Raghava** [comment]
@apu52 @Ghanshyam89 sir,now i have no issues to work on. Kindly,please assign this to me

**Comment by apu52** [comment]
@Srujitha-Raghava you are assigned .Start working on it.

**Comment by Srujitha-Raghava** [comment]
@apu52 seems like #607 solved is this issue



instead can i work on the following issue! i.e; making the login button responsive and navigating to new page rather than staying in the same page
![Screenshot 2024-05-26 220746](https://github.com/apu52/Travel_Website/assets/143430142/fce03d06-eedf-4b0e-b692-6dc8091ba4ae)

**Comment by apu52** [comment]
> @apu52 seems like #607 solved is this issue
> 
> instead can i work on the following issue! i.e; making the login button responsive and navigating to new page rather than staying in the same page ![Screenshot 2024-05-26 220746](https://private-user-images.githubusercontent.com/143430142/333895310-fce03d06-eedf-4b0e-b692-6dc8091ba4ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDk1NTUsIm5iZiI6MTcxNjc0OTI1NSwicGF0aCI6Ii8xNDM0MzAxNDIvMzMzODk1MzEwLWZjZTAzZDA2LWVlZGYtNGIwZS1iNjkyLTZkYzgwOTFiYTRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxODQ3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQ2NWI5MDE0MmVlMDE5MDJmNDE5NDM5YzRmOTY1N2Q5MmYyNGU2Y2MzMTZmODIwNmUxODg3YTk5NmNmYzM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUsJklkn75Aps_xJWOiGceL-NFsS8JNHA1hg80nLHzo)

okay work on it
