### ISSUE TITLE
Carousel Slide Details Update

### ISSUE THREAD

**Issue by vyanky1227** [apu52/Travel_Website#537]
The changeSlide function attempts to update the slide details (title and subtitle) for all slides, not just the active slide. This can make incorrect titles and subtitles being displayed on inactive slides, causing a poor user experience.

Please assign me this issue @apu52 sir.

**Comment by Ghanshyam89** [comment]
Hi @vyanky1227  ,

I am closing this issue, raise a fresh issue using template to raise issue and explain your issue with all required details. 

Regards
Project Mentor (GSSoC' 24)
