### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by prasukjain07** [apu52/Travel_Website#539]
**Describe the bug**
Home page is not properly responsive

![image](https://github.com/apu52/Travel_Website/assets/115997785/e4e21bdf-af2e-4077-9b1e-63c8bce2dfa0)

Please assign this issue to me under GSSoC'24

**Comment by Ghanshyam89** [comment]
Hi ,

This is a duplicate issue of #518 , so cosing this issue, please raise a new issue.

Regards
Project Mentor (GSSoC' 24)
