### ISSUE TITLE
Feature_Request : Create Review/ Testimonials Section

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#54]
**Is your feature request related to a problem? Please describe.**

Website contains a review button in navbar. I want to rename it as testimonials and create a testimonials section linked to that button

**Describe the solution you'd like**

create a testimonials section

**Describe alternatives you've considered**

will make sure that it follows theme of the website

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-01-16 021202](https://github.com/apu52/Travel_Website/assets/110532770/d3a367ec-0b0a-4b00-b513-662f30904559)

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
@PranavBarthwal I want to suggest you instead of removing the "Review" button make another "Testimonial" button & work upon it

**Comment by apu52** [comment]
@PranavBarthwal you are assigned. you have 2-3 days to submit your PR
