### ISSUE TITLE
BUG : Contact Us Button Missing Link

### ISSUE THREAD

**Issue by Samridhi002** [apu52/Travel_Website#540]
**Description**
The "_Contact Us_" button in the footer section does not contain a link. As a result, users cannot easily reach out for support or inquiries.

**Steps** 
1. Navigate to the package page.
2. Scroll down to the footer section.
3. Observe the "_Contact Us_" button in the footer section.
4. Click the button, and notice that it does not link to any page or section.

**Expected Behavior**
The "_Contact Us_" button should link to a contact form, the admin's email, or the admin's LinkedIn profile to facilitate communication.

**Suggested Solution**
Add a link to the button that directs users to a contact form or the admin's preferred contact method.

**Attachment**
![Screenshot_23-5-2024_93735_apu52 github io](https://github.com/apu52/Travel_Website/assets/169380578/a767d074-37bf-468e-8665-445af707d7b4)

![Screenshot_23-5-2024_104555_apu52 github io](https://github.com/apu52/Travel_Website/assets/169380578/10c2e396-3ba9-4e94-8a79-ff36b1a08b1e)

hey, @apu52 I can solve this issue once you assign to me under GSSoC. Thank you!

**Comment by nimitagarwal26** [comment]
I can solve this issue and I would love that if you assign it to me under GSSoC. Thank you!

**Comment by Ghanshyam89** [comment]
Hi ,

This is a good issue, please start working on this.

Regards
Project Mentor (GSSoC' 24)
