### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [apu52/Travel_Website#541]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by apu52** [comment]
@suhanipaliwal this is a very good issue .But can you please elaborate so that I can understand & assign you this issue .
& please use ISSUE templates to raise new issues otherwise it will not be accepted

**Comment by suhanipaliwal** [comment]
I will be adding a YAML file in the .github directory to define this workflow of auto commenting on the trigger of a pull request being merged.

**Comment by apu52** [comment]
> I will be adding a YAML file in the .github directory to define this workflow of auto commenting on the trigger of a pull request being merged.

Ok go Ahead . I am assigning you .Start working

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.

**Comment by apu52** [comment]
> Please add the label of appropriate level as per gssoc guidelines on this issue.

I will add the labels after reviewing the PR , so Don't worry Just go ahead with your contributions.
