### ISSUE TITLE
BUG: Login Pages Alignment Issue and Misaligned Bold Sentence in Paragraph

### ISSUE THREAD

**Issue by driyash9881** [apu52/Travel_Website#542]
# Login Pages Alignment Issue and Misaligned Bold Sentence in Paragraph
## Problem Description

On the login pages of the website, there is an alignment issue, and a sentence written in bold within a paragraph is misaligned. This affects the visual consistency and readability of the login pages.
## Expected Behavior

The elements on the login pages should be properly aligned, and the bold sentence within the paragraph should be correctly aligned to ensure visual consistency and readability.

## Actual Behavior

The elements on the login pages are misaligned, and the bold sentence within a paragraph is not properly aligned, leading to a disorganized and less-readable appearance.
![image](https://github.com/apu52/Travel_Website/assets/118407844/45d3034a-c121-4e42-9971-50a0591147ea)
![image](https://github.com/apu52/Travel_Website/assets/118407844/cb1b909c-fa74-4bd8-8e03-749e2c681374)

**Comment by apu52** [comment]
@driyash9881 you are assigned .Start working on this issue .

**Comment by ananyag309** [comment]
Hey, I am willing to contribute to the respective issue. please assign it to me. 
thank you
