### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RohithChitrada** [apu52/Travel_Website#543]
**Describe the bug**
When navigating to a particular section of the website, the navbar elements do not show the hover effect. Additionally, clicking on the navbar elements causes the navbar to move or expand, which disrupts the layout and does not look visually appealing.

**Expected behavior**
Hovering over the navbar elements should highlight them to indicate that they are interactive.
Clicking on the navbar elements should not cause the navbar to move or expand. The navbar should remain static and maintain its layout.

**Screenshots (Mandatory)**
![Screenshot (39)](https://github.com/apu52/Travel_Website/assets/120176158/6cee39a7-ed90-41c9-a04f-780992ea1dbe)
![Screenshot (38)](https://github.com/apu52/Travel_Website/assets/120176158/a4f14b85-623b-48b3-ab9f-b7029095b63a)

***Are you contributing under any open-source program ?***
GSSOC'24

Could you please assign this issue to me so I can work on it as part of GSSOC 2024?

**Comment by KrishnenduDG** [comment]
@RohithChitrada got your point of the navbar moving or expanding but didn't get your second point of hover..

Since it's a moving effect, so can you just post a screencast for that or maybe provide some more detailed description over it so that we can move forward with it...

**Comment by RohithChitrada** [comment]
when i am in home section and about us section the navbar element is hovering but as for the remaining elements they are not hovering when we are in (or) when we move to that section

**Comment by apu52** [comment]
> when i am in home section and about us section the navbar element is hovering but as for the remaining elements they are not hovering when we are in (or) when we move to that section

@KrishnenduDG

**Comment by RohithChitrada** [comment]
Are You assigning this issue or not

**Comment by KrishnenduDG** [comment]
Good issue. Assigning it to you. Please follow the necessary guidelines for raising a PR and contribute accordingly. @RohithChitrada
