### ISSUE TITLE
Login buttom cursor add

### ISSUE THREAD

**Issue by HimangshuRanjan** [apu52/Travel_Website#547]
**Is your feature request related to a problem? Please describe.**
![WhatsApp Image 2024-05-23 at 14 50 20](https://github.com/apu52/Travel_Website/assets/146883557/3529c472-45a9-4f39-a644-fbf49aee4d3c)

**Describe the solution you'd like**
![WhatsApp Image 2024-05-23 at 14 50 23](https://github.com/apu52/Travel_Website/assets/146883557/f8c7a6f2-800d-4e4a-bfff-9f11c533c8fa)

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by HimangshuRanjan** [comment]
@apu52, I would like to fix this issue. Please do assign me this under GSSOC'24.

**Comment by zahidalam05** [comment]
I would like to fix this issue.

**Comment by sejal-sharma08** [comment]
Hello @apu52
It would be a great if you assign me this issue and I can fix this as I have created projects which includes thiis feaute

**Comment by apu52** [comment]
@HimangshuRanjan you are assigned.
