### ISSUE TITLE
Documentation Fix: Indentation, Whitespaces, Missing Information, etc

### ISSUE THREAD

**Issue by nimitagarwal26** [apu52/Travel_Website#551]
I noticed a few formatting issues in the documentation:
**Indentation:** There seems to be inconsistent indentation throughout the document.
**Whitespace:** There are extra spaces before periods and after commas. Additionally, some periods could benefit from a following space.
**Clarity:** The language used in the overview section could be improved for better clarity.

**Missing Information:**
**Technologies Used:** JavaScript is missing from the list of technologies used.
Additionally, consider including a waving hand GIF for a friendly touch.

The ideal solution would be a two-part update for the GitHub README file:

**Part 1: Addressing Formatting Issues:**
Consistent indentation applied.
Extra spaces removed.
Missing period spaces added.

**Part 2: Updating Content:**
JavaScript added to "Technologies Used" section.
Overview section reviewed for clarity.

**Prototype Screenshot**
![image](https://github.com/apu52/Travel_Website/assets/133317243/425529c4-b723-438b-8a09-a94a67e0d290)
![image](https://github.com/apu52/Travel_Website/assets/133317243/99703d5f-fe2b-4040-94cd-817f5e7e2873)

***I am contributing under GSSoC'24. Kindly assign me this issue under GSSoC'24.***

**Comment by nimitagarwal26** [comment]
I can do this documentation fix for you. Please assign it to me under GSSoC'24. Thank you!

**Comment by apu52** [comment]
@nimitagarwal26 I think JS is now already included there . So no need to add it now.
But other changes you have mentioned you can add those .
You are assigned. Start working

**Comment by nimitagarwal26** [comment]
Can you please assign level to this issue.

**Comment by apu52** [comment]
> Can you please assign level to this issue.

I already have added GSSOC label . the other labels I will add after reviewing your PR
