### ISSUE TITLE
Random text on navbar | Navbar responsiveness issue | Destination link not working on navbar | UI improvement for the Rate Us page

### ISSUE THREAD

**Issue by kishoranushka** [apu52/Travel_Website#557]
**Description of Bugs**
1) Navbar Responsiveness Issue
Description: The navbar does not adapt well to different screen sizes, causing layout issues on smaller or larger screens.

2) Random Text on Navbar
Description: There is some unexpected text appearing on the navbar that should not be there, potentially due to a misplaced element or a bug in the rendering logic.

3) Destination Link Not Working
Description: The destination link in the navbar does not navigate to the intended section on the page, likely due to incorrect URL or anchor link setup.

4) UI Improvement Needed for Rate Us Page
Description: The current background image on the Rate Us page is too overwhelming. It needs to be replaced with a simpler and cleaner image to improve the user experience.

**Expected Behavior**
1)Navbar Responsiveness
The navbar should properly adjust its layout and elements to fit any screen size, from mobile devices to desktops.

2)Removal of Random Text
The navbar should display only the intended navigation items without any extraneous text.

3)Functioning Destination Link
The destination link in the navbar should correctly navigate the user to the specified section of the page.

4)Improved Rate Us Page UI
The Rate Us page should have a simple and clean background image that does not distract from the content, enhancing the overall user experience.

**Screenshots (Mandatory)**
![OS1](https://github.com/apu52/Travel_Website/assets/111566100/01d5783e-6ad2-4e59-aeb1-f511a1909e87)
![OS2](https://github.com/apu52/Travel_Website/assets/111566100/9b2beb53-77ef-4f3b-a4a8-7036b2dd4a4b)
![OS3](https://github.com/apu52/Travel_Website/assets/111566100/09254994-38c2-4947-a650-2590c52779ab)
![OS4](https://github.com/apu52/Travel_Website/assets/111566100/b85eb1a2-e058-4f27-9ee5-c4387bc88087)

***Are you contributing under any open-source program ?***
I am contributing in this open source, Travel website project under Girl Script Summer of Code'2024.

**Comment by Sreeshvini03** [comment]
Please assign this issue to me under GSSoC'24

**Comment by TechSenseiX** [comment]
Kindly assigned this issue to me. I will fix this issue

**Comment by apu52** [comment]
@kishoranushka You are assigned . Start Working on it.

**Comment by kishoranushka** [comment]
Thank you for your response. I'll immediately start working on it.
