### ISSUE TITLE
[Feature_Request] issue with the footer 

### ISSUE THREAD

**Issue by abhayvershwal** [apu52/Travel_Website#559]
**Is your feature request related to a problem? Please describe.**
There is an issue with the footer: the FAQ and Terms & Conditions links are currently displayed on the same line. They need to be vertically aligned. Additionally, these links should have the same hover effect as the other elements in the footer.
**Describe the solution you'd like**

 The FAQ and Terms & Conditions links should be vertically aligned. Additionally, all elements in the footer should have a consistent hover effect.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/93792490/54b31663-004d-49c9-b32d-c4f887370491)

here the FAQ's and term and condition are two different links in same line 

solution:

https://github.com/apu52/Travel_Website/assets/93792490/4eec4508-edd5-458b-8ca2-f6bfd924b0fe

Event the contact us link is responsive and redirect the page to the contact us page 

***Are you contributing under any open-source program ?***
GSSOC 24

**Comment by apu52** [comment]
@abhayvershwal you are assigned.
