### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ratnojitsaha** [apu52/Travel_Website#56]
**Describe the bug**
<The contact us section of this page coincides with the nav section when visited through the contact us nav link/button, in 900px and above>

**Expected behavior**
<There should be some space in between the nav section and (contact us) body/elements>

**Screenshots (Mandatory)**
![Screenshot (477)](https://github.com/apu52/Travel_Website/assets/110903082/3d42f241-c359-4186-9099-5239375427a5)

**Additional Context (Mandatory )**
<The contact section is working fine in <900px but needs some adjustments in and above 900px>

***Are you contributing under any open-source program ?***
<No>

**Comment by apu52** [comment]
are you contributing under JWOC ??

**Comment by apu52** [comment]
@ratnojitsaha Welcome to the repo

**Comment by ratnojitsaha** [comment]
Yes, I am contributing under JWOC

**Comment by apu52** [comment]
@ratnojitsaha You are assigned. you just have 1 day to submit your PR
Welcome to the repo
& from next time please mention the JWOC part as it's mandatory

**Comment by ratnojitsaha** [comment]
Sure
