### ISSUE TITLE
BUG  Login and Sigup features in login.html is not working

### ISSUE THREAD

**Issue by Janani-m17** [apu52/Travel_Website#561]
**Describe the bug**

While running login.html i will land in page which contains login and signup features but it is not working. By clicking the tour guide button it will redirect to the official page of website where it contains another login and signup page it is working quite fine. So instead of that first login and sign up page It can be redesigned as Welcome page in which the features of website can be displayed and by clicking the tourguide button it will redirect to home page. User can login or signup in that page.

**Expected behavior**

An optimised design which contain a welcome page in which a button will redirect to home page which contains all necessary information like about page, contact, login sign up.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/124059957/cff7ff69-911f-45cd-a952-d8a77ca1a077)

**Additional Context (Mandatory )**
Please assign this issue to me sir.

***Are you contributing under any open-source program ?***

GSSoC'24

@apu52

**Comment by apu52** [comment]
@Janani-m17 thanks for raising the ISSUE .But I really don't want this kind of changes in the login page.
Sorry to close this issue for now.
Happy Coding !!!!!!!
Willing to see more of your contributions
