### ISSUE TITLE
Feature_Request | Optimize the functionality

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [apu52/Travel_Website#565]
**Is your feature request related to a problem? Please describe.**
After Submitting the rating and review the user needs to click the button to return to home page. Instead of Clicking the button we can enhance this feature dynamically.

**Describe the solution you'd like**

Instead of having two buttons we can combine this feature into one button and when the user clicks submit after successful submission it automatically moves to the home page

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/125359008/9eb04049-cba6-43f8-9000-036755ce801d)

***Are you contributing under any open-source program ?***
I am open source contributor in Gssoc 24

**Comment by apu52** [comment]
@GnanariddhikaRavikumar you are assigned.good issue.

**Comment by GnanariddhikaRavikumar** [comment]
Can I work on the same fork which was created before for the first issue a week ago @apu52

**Comment by apu52** [comment]
> Can I work on the same fork which was created before for the first issue a week ago @apu52

yes .you can work .Just make a new branch on the forked repo & Sync the fork (update the branch) so that it will not face any merge conflicts . Make all the changes in that branch & make a PR

**Comment by ApoorvSaxena08** [comment]
Hi @apu52 , I have reviewed the requirements for optimizing the functionality of the rating and review submission process. I would like to work on this enhancement. Please assign this issue to me. Thank you!

**Comment by Theboycut05** [comment]
Can you assign this to me
