### ISSUE TITLE
Contact Us section is not center aligned and can be made more better

### ISSUE THREAD

**Issue by Anou25** [apu52/Travel_Website#566]
The contact Us section is not center aligned and it can be made more appealing.

![Screenshot 2024-05-24 155616](https://github.com/apu52/Travel_Website/assets/136624807/a27fd553-96fd-4751-a99b-4ca099645aae)

I am contributiong under GSSoC'24.
I agree to the 

- [x] https://github.com/apu52/Travel_Website/blob/35f796a6bc350044dc2ee013433d986653843941/CONTRIBUTING.md
- [x] https://github.com/apu52/Travel_Website/blob/35f796a6bc350044dc2ee013433d986653843941/Code_of_conduct.md

@apu52 please assign this task to me

**Comment by sharmilapadhy23** [comment]
I would like to work on this project.Can you please assign me

**Comment by Anou25** [comment]
@apu52 please can u assign it to me

**Comment by apu52** [comment]
@Anou25 you are assigned.

**Comment by Anou25** [comment]
@apu52 Thank you, please can you also add the level.

**Comment by apu52** [comment]
> @apu52 Thank you, please can you also add the level.

I will add the labels(e.g level1,level2,level3) as per the review of the PR , so go ahead with your contribution , don't worry about the labels , it's my responsibility.

**Comment by Anou25** [comment]
Okay
