### ISSUE TITLE
Feature Request-- Add a clear button in the rate us section

### ISSUE THREAD

**Issue by mythri1010** [apu52/Travel_Website#569]
Add a "clear rating" button where users can undo their rates if done incorrectly.
this button clears all the existing rates done from the start. 
![image](https://github.com/apu52/Travel_Website/assets/142799652/3dc12925-ac9a-451e-9b8c-48c7ae6f8fea)
@apu52, I would like to add a similar button above the "submit" button. 
Pls assign me this issue under GSSOC'24. Thank You

**Comment by apu52** [comment]
@mythri1010 Please try to raise the issues with the help of the issue templates so that it will be more understandable & will be more clearer .Sorry to close this issue for now

**Comment by mythri1010** [comment]
Alright np
