### ISSUE TITLE
Enhancing Navbar

### ISSUE THREAD

**Issue by pranjal12-web** [apu52/Travel_Website#57]
**Is your feature request related to a problem? Please describe.**
Due to no background color for the navbar , when we scroll the website it is kinda not visible and so enhancement of navbar is required.

**Describe the solution you'd like**
Change background color of the navbar.

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-01-16 153844](https://github.com/apu52/Travel_Website/assets/67697534/490fa98e-081e-46d1-b3ef-605ef9a0a6df)

***Are you contributing under any open-source program ?***
I am contributing under JWoC 24

Please assign me this issue

**Comment by apu52** [comment]
@pranjal12-web Welcome to the repo. Please fill up your issue using proper templates which is already given in the NEW ISSUE ---> FEATURE REQUEST to submit your issue properly


![image](https://github.com/apu52/Travel_Website/assets/114172928/0d569e76-2e2b-47ed-a981-a68198866ea6)

**Comment by pranjal12-web** [comment]
I have updated the comment

**Comment by apu52** [comment]
@pranjal12-web You are assigned .you can start working on this issue. All the best
You just have 1 day to complete this issue
