### ISSUE TITLE
Navbar height increase after clicking on selected Navbar link again

### ISSUE THREAD

**Issue by Adityagarg8384** [apu52/Travel_Website#570]
**Describe the bug**

In the Navbar, when you click on the selected Navbar Link again, then the height of Navbar increases

**Expected behavior**

The height of Navbar should remain same when the selected Navbar Link is clicked again.

**Screenshots (Mandatory)**

![Screenshot (189)](https://github.com/apu52/Travel_Website/assets/124500889/b4281fff-bb83-41b8-91bf-018acc61968e)
![Screenshot (190)](https://github.com/apu52/Travel_Website/assets/124500889/05f68d1c-e1e7-494e-97e7-b438ad30ba72)

**Additional Context (Mandatory )**
Steps-1- Click on any Navbar Link.
2- Then again press the same Navbar Link. The height of Navbar changes.

@apu52 I can solve this issue once you assign to me under GSSoC. Thank you!

***Are you contributing under any open-source program ?***

gssoc

**Comment by apu52** [comment]
@Adityagarg8384 you are assigned.
