### ISSUE TITLE
Contact us Feature Enhancement

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [apu52/Travel_Website#571]
**Is your feature request related to a problem? Please describe.**
When we type the details and click on submit button there is no response whether the messa.ge is sent or not. So I thought of adding that  feature

**Describe the solution you'd like**
Displaying the alert box if message sent it should display message sent successfully or Some error occurred Like this. So that it avoids the confusion state of the user.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/125359008/90898042-5433-472f-be14-247f1aefca6c)

after clicking the send button also it display as same.

***Are you contributing under any open-source program ?***

I am a Open source contributor in GSSOC'24

**I can able to resolve this, so kindly assign me this issue under GSSOC with level labels @apu52**

**Comment by RahaneSayali** [comment]
assign this to me @GnanariddhikaRavikumar

**Comment by GnanariddhikaRavikumar** [comment]
@RahaneSayali I'm not the project admin or mentor. I too contributor

**Comment by apu52** [comment]
@GnanariddhikaRavikumar you are assigned. But I want to request you to complete the previously assigned issue first & then only complete this PR

**Comment by GnanariddhikaRavikumar** [comment]
ok @apu52.
