### ISSUE TITLE
Feature_Request Introducing google maps

### ISSUE THREAD

**Issue by Shivani756** [apu52/Travel_Website#572]
**Is your feature request related to a problem? Please describe.**
It is related to the better functionality of the website for the users

**Describe the solution you'd like**
This features introduces google maps in the website making it easier for tourists to locate places

**Describe alternatives you've considered**
![e52623cb8578d625_960](https://github.com/apu52/Travel_Website/assets/139329176/d923283c-2713-4dd4-ac14-c01b404da0f7)

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by Shivani756** [comment]
by when will i notified if I'm assigned this issue

**Comment by apu52** [comment]
@Shivani756 you are assigned.

**Comment by litesh1123** [comment]
@apu sir I would like to contribute in this issue, @Shivani756 we can collab in this issue

**Comment by Shivani756** [comment]
@apu52 sir..
I request you to assign this issue to @litesh1123 also so that we can work together

**Comment by apu52** [comment]
@Shivani756 @litesh1123 let me look at the rules of GSSOC'24 , then I will inform u

**Comment by litesh1123** [comment]
Ok sir two contributors can collab no issue with that actually in youtube video live they told

**Comment by apu52** [comment]
> Ok sir two contributors can collab no issue with that actually in youtube video live they told

okk then . I have also assigned you .Both of you can now work on this issue .Just one request please don't call me sir , As I am a student . Please try to make all the changes in one single pR & also please mention in the PR both oof your name so that I can assign the points to both of u

**Comment by litesh1123** [comment]
Thank you
