### ISSUE TITLE
Adding Logo beside title

### ISSUE THREAD

**Issue by harikasayani** [apu52/Travel_Website#573]
**Is your feature request related to a problem? Please describe.**
I observed that there is no logo beside title.

**Describe the solution you'd like**
I will add logo beside title

**Demo Video/Screenshot (Mandatory )**
![Screenshot (120)](https://github.com/apu52/Travel_Website/assets/143275265/6002face-b27f-499a-a808-8c8abf2e31e5)

***Are you contributing under any open-source program ?***
Yes under GSSOC'24
Please assign me this task.

**Comment by sejal-sharma08** [comment]
Hello @apu52 
I would like to contribute towards this issue. Please assign me this under gssoc as I have made such projects which includes the same functionality

**Comment by apu52** [comment]
@harikasayani you are assigned.
