### ISSUE TITLE
adding a search bar and filter in the pricing page 

### ISSUE THREAD

**Issue by bhavya-taneja** [apu52/Travel_Website#574]
**Is your feature request related to a problem? Please describe.**

I've observed that there isn't a search bar at the top of the pricing page. This means that if I have to search for a particular place, I have to scroll through everything, which hinders a smooth user interface. Also, if users have a particular budget in mind, they have to scroll through all the options to find a fit for their budget. This could be improved for a better user experience.

**Describe the solution you'd like**

A viable solution is adding a standard search bar at the top of the pricing page. This addition would allow users to quickly find specific destinations without having to scroll through the entire list. Along with this implementation of a "sort by" filter would provide users with the flexibility to sort options based on their preferences, such as price or star ratings of a particular place.

**Demo Video/Screenshot (Mandatory )**
This is a simple example of how a search bar and sort-by filter would look like 
![Screenshot 2024-05-24 210706](https://github.com/apu52/Travel_Website/assets/128042756/de8b2ab4-6edf-4579-a193-ca254990baed)
and this is where we could add it on the original page 
![Screenshot 2024-05-24 212253](https://github.com/apu52/Travel_Website/assets/128042756/cdba03a7-e6be-4e6e-9b03-8676d0b26a4c)

***Are you contributing under any open-source program ?***

Yes, i am a contributor at GSSoC.

Please, assign this task to me. 
And please assign appropriate labels to it.

**Comment by apu52** [comment]
@bhavya-taneja you are assigned. I want to suggest you one thing to add the search bar in the pricing page itself , not in the home page. That will be better

**Comment by bhavya-taneja** [comment]
thank you @apu52 for assigning it to me.
Noted the suggestion
