### ISSUE TITLE
Display Issue with the Index/Home Page.

### ISSUE THREAD

**Issue by Hunteringsoul** [apu52/Travel_Website#575]
**Describe the bug**
 1. On the ribbon where HOME/RATE US options are provided there seems to be some opaque letters visible next to the moon/sun icon   which is duplication of code according to me.
 2. The link which states Rate Us? can be changed to Rate Us which will look more neater/proper.
 3. There is no proper spacing which states Frequently Asked Questions and Testimonials.

**Expected behavior**
1. The code can be corrected by deleting the duplicated line of code.
2. The Rate Us can be corrected to Rate Us.
3. The proper spacing b/w FAQs and Testimonials can be corrected through the insertion of a <br> tag which makes it more neater and legible.

**Screenshots (Mandatory)**
![Screenshot 2024-05-24 220945](https://github.com/apu52/Travel_Website/assets/151203477/42b9db7f-afa8-4952-89a2-d4411e8ecdae)
![Screenshot 2024-05-24 220805](https://github.com/apu52/Travel_Website/assets/151203477/6fbaec6a-d132-4e80-8d43-0f7a3d555b9d)

**Additional Context (Mandatory )**
I hope this issue is assigned to me. 
Thank You.

***Are you contributing under any open-source program
<Cotributing for GSSOC>

**Comment by Hunteringsoul** [comment]
I hope that this issue is assigned to me. 
Thanks

**Comment by apu52** [comment]
@Hunteringsoul you are assigned
