### ISSUE TITLE
Adding a floating scroll to top button 

### ISSUE THREAD

**Issue by sharmi4590** [apu52/Travel_Website#576]
**Is your feature request related to a problem? Please describe.**

Yes , not user friendly

**Describe the solution you'd like**

A user friendly website always has a scroll to top button since it becomes easier for the user to come once again to the top of the page without scrolling and thus it is more user friendly.

**Demo Video/Screenshot (Mandatory )**
![333236918-015a40f6-d760-4971-b60a-11ba7c07499c](https://github.com/apu52/Travel_Website/assets/102676949/3aac8c7c-1fd7-47a4-afc3-1e8001292451)
![Screenshot_20240524-223006](https://github.com/apu52/Travel_Website/assets/102676949/2cfdec13-ecab-4fb4-b002-d02c29848b72)
Like this in the right bottom corner 
***Are you contributing under any open-source program ?***

GSSoC'24

**Comment by Prakhar-bansal1** [comment]
It will be my pleasure if you assign me for this issue. I'll try my best and give 100% to it..

**Comment by HK853** [comment]
Hi @apu52  , I would like to take on this issue .

**Proposed solution :** Add a scroll to top button (which is visible only after certain length has been crossed). On clicking the button it will take the user to the top of the page. I will make the desired changes by adding proper react component with styling corresponding to the theme.

**Comment by apu52** [comment]
@sharmi4590 you are assigned. we already have a "move to top" button , so I would like to suggest you to give some hovering effect & stylize the button as per your choice to complete this issue
