### ISSUE TITLE
BUG : Footer email and number is not working.

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [apu52/Travel_Website#577]
Hell PA,
Email and Number is not directing to mail and dialpad.

### Screenshot - 
![image](https://github.com/apu52/Travel_Website/assets/121503426/9b6bdbe4-f52e-45ea-81de-25e49724757d)

**Comment by apu52** [comment]
@SyedImtiyaz-1 the number & mail are just anonymous , it's not official . 
I am closing this issue .
& want to suggest you from next time please try to raise issues with the help of issue templates present in the repo.
