### ISSUE TITLE
Enhancing Contact us Page

### ISSUE THREAD

**Issue by harinisayani** [apu52/Travel_Website#579]
**Is your feature request related to a problem? Please describe.**
I want to enhance the contact us page

**Describe the solution you'd like**
I will add more CSS features in order to make it beautiful.

***Are you contributing under any open-source program ?***
I am GSSOC'24 Contributor.

**Comment by ananyag309** [comment]
Hey I am want to contribute to the issue under gssoc. please add label of gssoc to it and assign me. 

thank you

**Comment by apu52** [comment]
@harinisayani which features you want to add ?? can you give some of the examples or better SS/video prototype of those features??

**Comment by harinisayani** [comment]
I want to add icons and box shadow to make it look more attractive.

**Comment by apu52** [comment]
@harinisayani go ahead. you are assigned.

**Comment by AnshuRani7781** [comment]
Hey I would also like  to contribute to the issue under gssoc'24

**Comment by divyalaldinani** [comment]
> @harinisayani go ahead. you are assigned.

hey @apu52 , if there's no update on this issue, you can assign me this issue and i will raise a PR till tomorrow.
