### ISSUE TITLE
[STYLE] 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#58]
**Describe the bug**
Style of Button want to change 
Button is inside the textfield so we want to apply border-radius 

**Expected behavior**
Button should have curve form right side of it 

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/125949765/62e8b2fd-45de-468c-a88d-f899ce646e6f)

***Are you contributing under any open-source program ?***
JW0C'24

**Comment by apu52** [comment]
@AftabMankapure Welcome to the repo.
You are assigned.
You have just 1 day to submit your issue
