### ISSUE TITLE
BUG: Random text on navbar alongside login button

### ISSUE THREAD

**Issue by Astha-Raghuwanshi** [apu52/Travel_Website#580]
**Describe the bug**
Random text is there on navbar alongside login button

**Expected behaviour**
I would like to remove the text and realign the light and dark mode button accordingly

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/99084211/eca59de7-1dee-4f9d-873e-590ef7c55ab5)

**Comment by apu52** [comment]
@Astha-Raghuwanshi I can't see any of the random text present now in the repo . So I am closing this issue
