### ISSUE TITLE
BUG: height of the navbar is inconsistent

### ISSUE THREAD

**Issue by Astha-Raghuwanshi** [apu52/Travel_Website#581]
**Describe the bug**
height of the navbar is inconsistent. it changes upon alternate click on the navbar

**Expected behavior**
i would like to make changes so that height of the navbar remains fixed  

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/99084211/69028b3d-8d81-4eb2-ac87-7c9ce0ec3939)
upon clicking the navbar, its height changes 
![image](https://github.com/apu52/Travel_Website/assets/99084211/1f44dc15-0fc1-402e-952a-010d46f297c9)

**Comment by apu52** [comment]
@Astha-Raghuwanshi this issue is already present in the repo . Sorry to close the issue.
