### ISSUE TITLE
BUG: The UI of the ratings page is not consistent with the rest of the website

### ISSUE THREAD

**Issue by Astha-Raghuwanshi** [apu52/Travel_Website#582]
**Describe the bug**
The UI of the ratings page is not consistent with the rest of the website. It has a lot of non coherent components and colours.

**Expected behaviour**
I would like to redo the UI of the ratings page to make it more consistent with the UI of the rest of the website
 
**Screenshots (Mandatory)**
The page has too many components and colours that are not coherent
![image](https://github.com/apu52/Travel_Website/assets/99084211/34e7c226-0a11-4879-9af4-855617dbfc54)

**Comment by apu52** [comment]
@Astha-Raghuwanshi the UI of the page has already been improved.I am closing the issue
