### ISSUE TITLE
Navigation bar Issues

### ISSUE THREAD

**Issue by riya-rjha** [apu52/Travel_Website#584]
The navigation bar has issues like these where the unnecessary text is visible. Plus the text in the nav bar looks too cluttered. I would like to improvise the UI by changing the nav bar a bit & it's text. 

![Screenshot (49)](https://github.com/apu52/Travel_Website/assets/112813772/81d15923-a330-4194-8e28-795526cf74d6)

Kindly assign me this issue under the GSSOC label.

**Comment by DhruvJohri** [comment]
please assign this issue to me under gssoc24 @riya-rjha

**Comment by apu52** [comment]
@riya-rjha this issue has already been solved.ai am closing this issue.
