### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by manya975** [apu52/Travel_Website#585]
**Describe the bug**
The UI of book now page is not appropriate and payment page not accessible from checkout option.

**Expected behavior**
The navbar should be there and page should be more eye catching. The checkout page should direct to payment gateway.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/114555020/5771e930-abd3-4382-b8ca-a5c5fa9eae6b)

![image](https://github.com/apu52/Travel_Website/assets/114555020/abfb6115-0307-47e8-90e1-fdce2763a8c5)

***Are you contributing under any open-source program ?***
Contributing under GSSOC

Can you please assign me this issue under GSSOC'24

**Comment by KrishnenduDG** [comment]
@manya975 So if you could state the changes that you wanna make to the UI of checkout form..

**Comment by manya975** [comment]
@KrishnenduDG Like you can see there is no navbar in the aforementioned page. Moreover the page styling is not aligned with styling of other pages. So some CSS changes will be done by my side.

**Comment by KrishnenduDG** [comment]
Okk @manya975, assigned to you.. Try to complete the PR using the given Contribution Guidelines..

**Comment by manya975** [comment]
@KrishnenduDG It is happening that when I am opening the payment option for booking it is not going to the payment gateway page
