### ISSUE TITLE
BUG:No images in the "Explore Top Destination" section

### ISSUE THREAD

**Issue by nidhipai78** [apu52/Travel_Website#586]
**Describe the bug**

The pictures under each section for each of the top destinations are not added.

**Expected behaviour**
I would like to add the images to each of it .

**Screenshots**
<img width="950" alt="topdestinations" src="https://github.com/apu52/Travel_Website/assets/110184554/3d601502-b4f9-44ee-b306-1f532287d0f8">

***Are you contributing under any open-source program ?***
I am a GSSOC'24 Contributor

**Comment by apu52** [comment]
@nidhipai78 very good issue .try to fix this bug ASAP

**Comment by nidhipai78** [comment]
Hello,
 The issue #586 of the bug no images in explore top destinations has been
completed.

The issue is fixed by *#705*
The link is *https://github.com/apu52/Travel_Website/pull/705
<https://github.com/apu52/Travel_Website/pull/705>*
