### ISSUE TITLE
BUG: Underline in the logoname in the links of each destination of the "Best trip package"

### ISSUE THREAD

**Issue by nidhipai78** [apu52/Travel_Website#587]
**Describe the bug**
There is an underline in the logo name "tourguide." in each of the links to different destinations of the "Best trip package". 

**Expected behavior**
The underline is expected to be removed as it changes the display of the logoname.

**Screenshots**
<img width="911" alt="image" src="https://github.com/apu52/Travel_Website/assets/110184554/980e42b5-8fd9-441f-9722-ac308bd5b674">

***Are you contributing under any open-source program ?***
I am a GSSOC'24 Contributor

**Comment by apu52** [comment]
@nidhipai78 I have assigned you this issue. but first of al please try to complete the previously assigned issue

**Comment by nidhipai78** [comment]
Hello,
The issue #587 is showing that  *This branch has conflicts that must be
resolved. *The conflicting file is index.html. Can you please look into
this?

The link for the PR is *#759*

Thank You
