### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SDprogramer** [apu52/Travel_Website#588]
**Describe the bug**

**Expected behavior**

**Additional Context (Mandatory ) -> please add the issue under gssoc 24 and then i can make the pr after reviewing the issue.

***Are you contributing under any open-source program ?***

**Comment by KrishnenduDG** [comment]
Please describe the bug(with proper screenshots or some other contextual writings), otherwise we won't be able to move forward with the whole process.

**Comment by SDprogramer** [comment]
Please close this issue, it was not required, It was a mistake from my side
