### ISSUE TITLE
Enhancement of destinations

### ISSUE THREAD

**Issue by rupalimkrishnan** [apu52/Travel_Website#59]
I would like to add links to each destination to the places given explore top destination and enhance the book now button changing it's style

![Screenshot 2024-01-16 212536](https://github.com/apu52/Travel_Website/assets/153444802/3b4365c1-ab2c-450d-9c75-47c194718f6e)
Please assign me this issue under jwoc'24

**Comment by apu52** [comment]
@rupalimkrishnan Welcome to the repo. Please fill up your issue using proper templates which is already given in the NEW ISSUE ---> FEATURE REQUEST to submit your issue properly

![image](https://github.com/apu52/Travel_Website/assets/114172928/25cb20ed-c4c5-4ced-988b-5146ff4c671f)
