### ISSUE TITLE
Title:Carousel Slide Details Update Issue in changeSlide Function

### ISSUE THREAD

**Issue by vyanky1227** [apu52/Travel_Website#591]
Description:
The `changeSlide` function in the carousel component attempts to update the details (title and subtitle) for all slides, not just the active slide. This can lead to incorrect titles and subtitles being displayed on inactive slides, causing a poor user experience.

**Problematic Code:

slides.forEach((slide, index) => {
  if (!slide.querySelector(".destination__details")) {
    const detailsContainer = document.createElement("div");
    detailsContainer.className = "destination__details";
    slide.appendChild(detailsContainer);

    const titleElement = document.createElement("p");
    titleElement.className = "destination__title";
    detailsContainer.appendChild(titleElement);

    const subtitleElement = document.createElement("p");
    subtitleElement.className = "destination__subtitle";
    detailsContainer.appendChild(subtitleElement);
  }

  const titleElement = slide.querySelector(".destination__title");
  const subtitleElement = slide.querySelector(".destination__subtitle");
  titleElement.textContent = title;
  subtitleElement.textContent = subtitle;
});

**Steps to Reproduce:**
1. Navigate to the carousel component.
2. Observe the titles and subtitles displayed on all slides.
3. Change the active slide using the navigation arrows or dots.
4. Notice that the titles and subtitles on inactive slides are incorrect.

**Expected Behavior:**
Only the active slide's details (title and subtitle) should be updated.

**Proposed Solution:**
Update the code to modify only the active slide's details:

const activeSlideElement = slides[activeSlide];
if (!activeSlideElement.querySelector(".destination__details")) {
  const detailsContainer = document.createElement("div");
  detailsContainer.className = "destination__details";
  activeSlideElement.appendChild(detailsContainer);

  const titleElement = document.createElement("p");
  titleElement.className = "destination__title";
  detailsContainer.appendChild(titleElement);

  const subtitleElement = document.createElement("p");
  subtitleElement.className = "destination__subtitle";
  detailsContainer.appendChild(subtitleElement);
}

const titleElement = activeSlideElement.querySelector(".destination__title");
const subtitleElement = activeSlideElement.querySelector(".destination__subtitle");
titleElement.textContent = destinationTitles[activeSlide];
subtitleElement.textContent = destinationSubtitles[activeSlide];

**Additional Context:**
This issue affects the visual consistency of the carousel component, leading to a confusing user experience as slide titles and subtitles do not match the displayed images on inactive slides.

---
SCREENSHOT:

![Screenshot 2024-05-25 144838](https://github.com/apu52/Travel_Website/assets/132478275/89094adf-a420-4688-96ff-e9efaab0ad46)

PLEASE ASSIGN ME THIS ISSUE @apu52

**Comment by apu52** [comment]
@vyanky1227 you are assigned.

**Comment by vyanky1227** [comment]
> @vyanky1227 you are assigned.

resolved.
