### ISSUE TITLE
BUG : Nav bar not proper on Trip Gallery page in specific.

### ISSUE THREAD

**Issue by I-Saara** [apu52/Travel_Website#594]
**Describe the bug**
The nav bar is congested on the "Trip gallery" page. The dark mode switch is shrinked to the extreme corner.

**Expected behavior**
It should be displayed properly without any congestion. 
**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/146477775/d7195b4f-45cf-4a3f-bbdb-730af619aab3)

**Additional Context (Mandatory )**
Please assign me this so that I can work on it.

***Are you contributing under any open-source program ?***
Girlscript Summer of Code

**Comment by apu52** [comment]
@I-Saara you are assigned.

**Comment by helloanisha19** [comment]
@I-Saara are you still working on the issue?
