### ISSUE TITLE
BUG : The 'Destination' button in the nav bar is not functional.

### ISSUE THREAD

**Issue by I-Saara** [apu52/Travel_Website#595]
**Describe the bug**
There is a "Destination" button provided in the nav bar but there is no such section with that name to redirect. The section which refers to the destinations can be named as "destinations" and the button can be made functional with it. 

**Expected behavior**
The button should enable the user to move onto to "Destinations" section in the website as soon as it is pressed by the user.
**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/146477775/41f3d51c-e372-4aaf-9b34-720f6e53f613)
This is the section that has to be given a name.

***Are you contributing under any open-source program ?***
Gssoc'24

Please assign me this so that I can work on it.

**Comment by apu52** [comment]
![image](https://github.com/apu52/Travel_Website/assets/114172928/24c2ee2d-502f-4f04-89aa-fdb5fd061760)

there is an heading properly for this section , I want you to align this heading properly with the destination section So that will be helpful

**Comment by apu52** [comment]
@I-Saara but first complete the previously assigned issue.
