### ISSUE TITLE
BUG : Chatbot not able to recommend me places to visit. 

### ISSUE THREAD

**Issue by I-Saara** [apu52/Travel_Website#596]
**Describe the bug**
The chatbot isn't able to recommend destinations to help me plan a trip.

**Expected behavior**
It should suggest the destinations based on popularity or take input from the user about his preferences and then align to them to find out destinations for the user.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/146477775/9e2b54f9-380d-4c49-a7ba-9a2c8890f5ba)

Please assign me this so that I can work on it.

***Are you contributing under any open-source program ?***
GSSOC'24

**Comment by KrishnenduDG** [comment]
@I-Saara It is recommending.. Just click on that link which states "Click here to get familiar..." and it will redirect to a page where you can get suggestions..

Confirmed from my end. Just confirm it once from your end and then we can close the issue.

**Comment by I-Saara** [comment]
@KrishnenduDG Might be the case, but as I checked, It is showing error this time. 
![image](https://github.com/apu52/Travel_Website/assets/146477775/d336c853-4e1d-49d5-a449-1e94dee29a4d)

**Comment by KrishnenduDG** [comment]
Ok, so what will be your approach to solve this? Can you give a very brief overview? @I-Saara

**Comment by I-Saara** [comment]
I would be checking up on the chatbot and would be editing its functioning in such a manner that it does not have this bug again! @KrishnenduDG

**Comment by apu52** [comment]
@I-Saara I have assigned u .Start working on it. But please first update your forked branch at first
