### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Vikashchou-dhary** [apu52/Travel_Website#597]
**Describe the bug**
There is no picture of destination in the EXPLORE TOP DESTINATIONS section

**Screenshots (Mandatory)**
![destination places](https://github.com/apu52/Travel_Website/assets/158028747/7f846628-d5ad-44cb-90c1-7bc434d1a373)

**Additional Context (Mandatory )**
Yes I am contributing under gssoc'24 .
I can this issue please assign it to me

**Comment by apu52** [comment]
@Vikashchou-dhary good issue .  try to complete this PR within tomorrow

**Comment by Vikashchou-dhary** [comment]
sure sir

**Comment by apu52** [comment]
> sure sir

Don't call me sir Please , I am just a student .Just try to complete this issue within today .

**Comment by Vikashchou-dhary** [comment]
ok
