### ISSUE TITLE
to improve the UX of the TOP DESTINATION Page

### ISSUE THREAD

**Issue by Vikashchou-dhary** [apu52/Travel_Website#599]
**Is your feature request related to a problem? Please describe.**
In the page of BEST TRIP PACKAGE the destination cards are not align to the right which is not looking good as and all the left part are vacant.

**Describe the solution you'd like**
 i would align them evenly in the page which will improve the UX

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![not align2](https://github.com/apu52/Travel_Website/assets/158028747/68d318e9-0cff-40e4-b04a-787c8117d6f1)
![not align1](https://github.com/apu52/Travel_Website/assets/158028747/41f9833e-f11b-4774-a5c8-02a876046e21)

**Comment by Vikashchou-dhary** [comment]
@apu52 I can solve this ,Please assign it to me

**Comment by apu52** [comment]
@Vikashchou-dhary thanks for the issue .try to align the best trip package section as it was before .

& also try to align 
![image](https://github.com/apu52/Travel_Website/assets/114172928/151e7093-16fe-4b64-b60b-6aab57228cef)

the about us section at center

**Comment by apu52** [comment]
@Vikashchou-dhary try to complete this PR within tomorrow

**Comment by Vikashchou-dhary** [comment]
sure sir
