### ISSUE TITLE
Title: Enhancement - Connect "MyStory" Video Button to Relevant YouTube Video

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#6]
Issue Description
To enrich the user experience and provide engaging content, let's enhance the "MyStory" video button by connecting it to a relevant YouTube video that aligns with the current content. This will offer users an insightful and entertaining video related to the website's theme.
<img width="609" alt="Screenshot 2024-01-11 at 12 15 41 AM" src="https://github.com/apu52/Travel_Website/assets/136263179/84570f02-cbb2-40b5-b9d5-c4fd4b39e1ef">

Proposed Changes
Integrate a link in the "MyStory" video button that redirects users to a carefully chosen YouTube video matching the content of the website.
Ensure that the selected video provides value and complements the overall theme and purpose of the website.
Additional Information
A relevant and engaging video can captivate users and keep them connected to the website.
Consider updating the linked video periodically to keep the content fresh and interesting.
Let's collaborate to make the "MyStory" video button a compelling feature for users to explore and enjoy.

**Comment by rahat2134** [comment]
@apu52 assign it to me.

**Comment by apu52** [comment]
@rahat2134 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
