### ISSUE TITLE
Feature_Request: Create a login page for the website

### ISSUE THREAD

**Issue by Smritigit1202** [apu52/Travel_Website#60]
**Is your feature request related to a problem? Please describe.**
The travelers need to have a login ID and password for their track of Travel plans purchases
**Describe the solution you'd like**
Making a login and register page using HTML/CSS 
***Are you contributing under any open-source program ?***
JWOC

**Comment by apu52** [comment]
@Smritigit1202 Welcome to the repo.
Actually this issue is already present in the repo (#26 )
Sorry , this issue can't be assigned. Instead you van raise any other issue
Btw thanks for raising the issue.
