### ISSUE TITLE
Feat:- Adding  a blog section in the website .

### ISSUE THREAD

**Issue by mittal246** [apu52/Travel_Website#600]
@apu52  I am thinking of adding a blog section to the website which will provide high-quality informative content to the users about different places which will aid them to plan their trip efficiently. This section will help in engaging the visitors in a different way and make the website more credible.

I would love to work on this issue . Kindly assign me it under gssoc label.

Thank you.

**Comment by mittal246** [comment]
@apu52 kindly go through this issue and assign it to me.

**Comment by apu52** [comment]
@mittal246 please try to raise all the issues by using the issue templates present in the repo so that it will be more understandable & WILL BE MORE CLEARER.  
Closing this issue for now.
