### ISSUE TITLE
Bug in About Us Section

### ISSUE THREAD

**Issue by rudravashishtha** [apu52/Travel_Website#601]
As you can see, the text is not starting from the left of the box.

![image](https://github.com/apu52/Travel_Website/assets/91290891/37dd0222-bfd3-413f-915a-a45a1f90ebdc)

Text in the about us section is not aligned properly.

Creating this issue under GSSOC'24..

**Comment by apu52** [comment]
@Vikashchou-dhary good issue . try to complete this PR within tomorrow

**Comment by rudravashishtha** [comment]
Thanks @apu52. Sure, will do it till tomorrow.
