### ISSUE TITLE
BUG: Navbar is not responsive.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#608]
**Describe the bug**
The hamburger icon on the nav bar is not  visible in mobile view. 

**Expected behavior**
Assign this task to me and I will create a completely responsive navbar added with other styling.

**Screenshots (Mandatory)**
![Screenshot (448)](https://github.com/apu52/Travel_Website/assets/143121854/52860d20-a762-4a44-88a7-0708a65e68cf)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@meetarora10 you are assigned.
