### ISSUE TITLE
Feature_Request : Addition of 404 page

### ISSUE THREAD

**Issue by Jagpreet153** [apu52/Travel_Website#609]
**Is your feature request related to a problem? Please describe.**
Yes , when there is a request to fetch a page which is not present it shows 404 error page

**Describe the solution you'd like**
The 404 page will contain the svg animation along with proper invalid message

**Describe alternatives you've considered**
The page would be fully responsive 

**Demo Video/Screenshot (Mandatory )**
![Animation - 1716698448987](https://github.com/apu52/Travel_Website/assets/119691733/33c2bf03-d06a-4cbd-9a60-d3d3ee83cb46)

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by apu52** [comment]
@Jagpreet153 you are assigned.but just want to suggest you to please go through the website properly & then only work on this issue.

**Comment by Jagpreet153** [comment]
@apu52 Kindly add level label also

**Comment by apu52** [comment]
> @apu52 Kindly add level label also

Are you still working on this issue ?

**Comment by Jagpreet153** [comment]
> > @apu52 Kindly add level label also
> 
> Are you still working on this issue ?

Yes , will complete by tomorrow
