### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 13AdityaDey** [apu52/Travel_Website#61]
**Is your Documentation related to a problem? Please describe.**
No, my documentation is not solely related to a problem. It moreover an enhancement of the current project.

**Describe the solution you'd like**
Yes, I want to add a toggle switch, where on clicking on it, the entire website would change from light to dark theme and vice versa. The would also include change of font and button colors.

**Prototype Screenshot/Demo Video(Mandatory )**
Before clicking the toggle key :
![Screenshot 2024-01-15 231716](https://github.com/apu52/Travel_Website/assets/140962818/03dfe085-d7f2-4181-9281-fc5579ca5b61)

After clicking the toggle key :
![Screenshot 2024-01-15 233015](https://github.com/apu52/Travel_Website/assets/140962818/5610bb6f-3a4d-49a1-92af-10050ec2bf45)

Its just a dummy, this change would be applied to entire website.

***Are you contributing under any open-source program ?***
No, this is my first.

**Comment by apu52** [comment]
@13AdityaDey Welcome to the repo!!!!!You are assigned.
I just want to tell you just make the toggle button more stylized & appropriate with the design of the Website

**Comment by apu52** [comment]
you just have 1 day to complete this issue.

**Comment by 13AdityaDey** [comment]
> you just have 1 day to complete this issue.

Fine. Will try my best!!

**Comment by apu52** [comment]
@13AdityaDey Where is your PR . Please submit your PR within tonight

**Comment by 13AdityaDey** [comment]
> @13AdityaDey Where is your PR . Please submit your PR within tonight

job is completed. just facing problem to PR.

**Comment by 13AdityaDey** [comment]
> > > @13AdityaDey Where is your PR . Please submit your PR within tonight
> > 
> > 
> > job is completed. just facing problem to PR.
> 
> What problem?? if u need any kind of help you can reach out to me here or in discord

i downloaded the zip file in my local device and made all the changes.
now what to do to PR ?

**Comment by apu52** [comment]
> > > > @13AdityaDey Where is your PR . Please submit your PR within tonight
> > > 
> > > 
> > > job is completed. just facing problem to PR.
> > 
> > 
> > What problem?? if u need any kind of help you can reach out to me here or in discord
> 
> i downloaded the zip file in my local device and made all the changes. now what to do to PR ?

After making the changes in the local device. Then push your commits from VS code to the forked version of the repo making a branch

**Comment by 13AdityaDey** [comment]
> & then you can easily make your PR

what i did just now was copied my changed code and pasted it in to forked repo.
as i made change in html and css, it is showing patch1 and patch 2.

**Comment by 13AdityaDey** [comment]
> & then you can easily make your PR

sir i had made the pull request.

here is the screenshot
![Screenshot 2024-01-18 204057](https://github.com/apu52/Travel_Website/assets/140962818/df372b89-b811-4471-880f-3c2a0c92650d)

**Comment by apu52** [comment]
> > & then you can easily make your PR
> 
> sir i had made the pull request.
> 
> here is the screenshot ![Screenshot 2024-01-18 204057](https://private-user-images.githubusercontent.com/140962818/297787331-df372b89-b811-4471-880f-3c2a0c92650d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzY4MDYsIm5iZiI6MTcwNTYzNjUwNiwicGF0aCI6Ii8xNDA5NjI4MTgvMjk3Nzg3MzMxLWRmMzcyYjg5LWI4MTEtNDQ3MS04ODBmLTNjMmEwYzkyNjUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMzU1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjkxM2I3OTkzZjA0NTAwM2NiOTkwZjAzYWQzY2RmZWI1NjZlNjIxNTkxZjU4ZGFlNGVmNDUyOTU3NDY4YjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JJoSLXceIUPL5ef0okmXGymzCfoAMFwO2M-bwYUaA-s)
> 
> please check the PR and confirm

@13AdityaDey This PR can't me merged. please make  one single PR for one issue. Not multiple.
Sorry this PR can't be merged. Kindly make a new branch in your forked repo & make all the enhancement there & then submit your PR

**Comment by 13AdityaDey** [comment]
> > > & then you can easily make your PR
> > 
> > 
> > sir i had made the pull request.
> > here is the screenshot ![Screenshot 2024-01-18 204057](https://private-user-images.githubusercontent.com/140962818/297787331-df372b89-b811-4471-880f-3c2a0c92650d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzY4MDYsIm5iZiI6MTcwNTYzNjUwNiwicGF0aCI6Ii8xNDA5NjI4MTgvMjk3Nzg3MzMxLWRmMzcyYjg5LWI4MTEtNDQ3MS04ODBmLTNjMmEwYzkyNjUwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMzU1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjkxM2I3OTkzZjA0NTAwM2NiOTkwZjAzYWQzY2RmZWI1NjZlNjIxNTkxZjU4ZGFlNGVmNDUyOTU3NDY4YjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JJoSLXceIUPL5ef0okmXGymzCfoAMFwO2M-bwYUaA-s)
> > please check the PR and confirm
> 
> @13AdityaDey This PR can't me merged. please make one single PR for one issue. Not multiple. Sorry this PR can't be merged. Kindly make a new branch in your forked repo & make all the enhancement there & then submit your PR

Sir, i created a single PR. My changes are in the landing page folder. please check once and confirm.

**Comment by apu52** [comment]
@13AdityaDey Please make a new PR . your branch is outdated

**Comment by 13AdityaDey** [comment]
> @13AdityaDey Please make a new PR . your branch is outdated

Sorry, i think i made a mistake. i deleted the forked repo. and now it is showing the issue is closed.

**Comment by 13AdityaDey** [comment]
> > @13AdityaDey Please make a new PR . your branch is outdated
> 
> Sorry, i think i made a mistake. i deleted the forked repo. and now it is showing the issue is closed.

Can we do something about it?

**Comment by apu52** [comment]
> > > @13AdityaDey Please make a new PR . your branch is outdated
> > 
> > 
> > Sorry, i think i made a mistake. i deleted the forked repo. and now it is showing the issue is closed.
> 
> Can we do something about it?

This is your issue #61 . work on this . & Please submit your PR within tonight.
Make a new branch in your forked repo & then after properly syncing the branch only then make your desired changes & then submit your PR

**Comment by 13AdityaDey** [comment]
> > > > @13AdityaDey Please make a new PR . your branch is outdated
> > > 
> > > 
> > > Sorry, i think i made a mistake. i deleted the forked repo. and now it is showing the issue is closed.
> > 
> > 
> > Can we do something about it?
> 
> This is your issue #61 . work on this . & Please submit your PR within tonight. Make a new branch in your forked repo & then after properly syncing the branch only then make your desired changes & then submit your PR

I think it is perfect now. please check once.
