### ISSUE TITLE
BUG: Date validation for plan a trip page

### ISSUE THREAD

**Issue by nidhipai78** [apu52/Travel_Website#611]
**Describe the bug**
Date validation in Plan a trip page. The trip gets planned for an earlier date.

**Expected behaviour**
The trip is expected to be planned for a future date.The alert message should be popped up once the future date is selected.

**Screenshots**
<img width="563" alt="image" src="https://github.com/apu52/Travel_Website/assets/110184554/96261b3b-b762-4b40-8fba-1671c225ef37">

***Are you contributing under any open-source program ?***
I am a GSSOC'24 Contributor

**Comment by KrishnenduDG** [comment]
Good issue.. @nidhipai78
assigned to you. Plz follow the contribution guidelines for raising a PR. After contributing, please notify and link the PR here.

**Comment by nidhipai78** [comment]
Hello,
  The PR has been submitted for "Date Validation" in Plan a Trip for the
issue #611.

The link is  *https://github.com/apu52/Travel_Website/pull/677
<https://github.com/apu52/Travel_Website/pull/677>*

Thank You

**Comment by KrishnenduDG** [comment]
@apu52 check the PR plz..

**Comment by apu52** [comment]
> @apu52 check the PR plz..

Thanks for the reminder. Done
