### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by patelkiran185** [apu52/Travel_Website#612]
**Describe the bug**

When clicking the "Home" button in the navigation menu, the navigation box height increases unexpectedly. Additionally, the "Login" button and the toggle button are touching each other, causing a visual overlap.

**Expected behavior**

 The navigation box height should remain consistent regardless of clicking the "Home" button.
 The "Login" button and the toggle button should have sufficient spacing to avoid visual overlap.

**Screenshots (Mandatory)**

![Screenshot from 2024-05-26 11-37-53](https://github.com/apu52/Travel_Website/assets/138752385/3bef2657-eca9-489d-b73f-2ad0516cb491)

**Additional Context (Mandatory )**
The issue occurs on a travel website project created under the GSSoC '24 program.
***Are you contributing under any open-source program ?***

Yes, contributing under GSSoC '24 (GirlScript Summer of Code 2024).

**Comment by patelkiran185** [comment]
@apu52  please assign me this!!

**Comment by apu52** [comment]
@patelkiran185 you are assigned.

**Comment by thecloudcode** [comment]
Please assign me this issue under GSSoC'24, I can do this easily

**Comment by patelkiran185** [comment]
@apu52 Looks like #612 Bug has already been solved, but the navbar has two login buttons. https://apu52.github.io/Travel_Website/loginPage.html  and https://apu52.github.io/Travel_Website/login-modified.html.
The latter one is not visually appealing. Please assign me.
![Screenshot from 2024-06-03 22-31-42](https://github.com/apu52/Travel_Website/assets/138752385/b6023978-cba1-489d-9493-7492ed62191e)

**Comment by apu52** [comment]
> @apu52 Looks like #612 Bug has already been solved, but the navbar has two login buttons. https://apu52.github.io/Travel_Website/loginPage.html and https://apu52.github.io/Travel_Website/login-modified.html. The latter one is not visually appealing. Please assign me. ![Screenshot from 2024-06-03 22-31-42](https://private-user-images.githubusercontent.com/138752385/336161806-b6023978-cba1-489d-9493-7492ed62191e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODgxNDEsIm5iZiI6MTcxNzU4Nzg0MSwicGF0aCI6Ii8xMzg3NTIzODUvMzM2MTYxODA2LWI2MDIzOTc4LWNiYTEtNDg5ZC05NDkzLTc0OTJlZDYyMTkxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMTQ0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGI3NTg4OGY5MjVkMTNkMDQyZDFiODBmMzRlNGJiMDFkNDhkYzNmNTE5ODZkOTE3Mzg4YTRlM2Y2ZDk2ODI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2Nn2SUPN2EQIn9OhTK_sxvCypFMGyErG9ColJtCttro)

the issue you have suggested is already present . So I can 't assign you . I am closing this issue also as completed . You can still raise new issues on which you want to work on
