### ISSUE TITLE
Adding Strandard and Express Delivary options in the Payment 

### ISSUE THREAD

**Issue by coderiksenthil** [apu52/Travel_Website#613]
**Is your feature request related to a problem? Please describe.**

The current checkout page lacks a way to display and update shipping costs dynamically based on the selected shipping method. This could lead to confusion for users about the final total cost of their purchase.

**Describe the solution you'd like**

I have implemented a feature that dynamically updates the shipping cost in the "Your cart" section based on the user's selected shipping method. If "Standard Shipping" is selected, the cost is displayed as "Free". If "Express Shipping" is selected, the cost is displayed as "85 INR". The total cost is updated accordingly.

Additionally, the code is already prepared and ready for implementation, I kindly request to be assigned to this task.

**Describe alternatives you've considered**

An alternative could be to list the shipping costs in the "Billing address" section without updating the cart dynamically. However, this might not provide a clear and immediate update to the user about the total cost, leading to user confusion.

**Demo Video/Screenshot (Mandatory )**
Standard Delivery
![image](https://github.com/apu52/Travel_Website/assets/66522620/1c0dc00a-e9e4-484c-afa8-607dda244a72)
Express Delivery
![image](https://github.com/apu52/Travel_Website/assets/66522620/ea5e6fe8-c0db-4f85-a36a-bb0c8c4c7740)

***Are you contributing under any open-source program ?***

I am a part of GSSoC 2024

**Comment by coderiksenthil** [comment]
@aryan-1309  Thanks for your enthusiasm! It's awesome that you're eager to contribute. Just to clarify, I'm already on it and excited to tackle this issue and the code part is also ready. Let's collaborate on future tasks! 😊👍

**Comment by apu52** [comment]
@coderiksenthil u are assigned.

**Comment by coderiksenthil** [comment]
Thank You @apu52 for assigning me the task🙂
