### ISSUE TITLE
To add Images and modify the "EXPLORE TOP DESTINATIONS" section 

### ISSUE THREAD

**Issue by parkhibhandula** [apu52/Travel_Website#614]
**Describe the bug**
The "Explore top destinations" section images are not displaying and also, I want to change cards design.

**Expected behavior**
The images should be visible, and the cards need to be formatted. 

**Screenshots (Mandatory)**
![Screenshot 2024-05-26 124344](https://github.com/apu52/Travel_Website/assets/165069293/90e6e003-a53f-4d5e-8efe-da3548fca61e)

**Additional Context (Mandatory)**
This is my first open-source contribution.

***Are you contributing under any open-source program? ***
Yes, I am contributing under GSSOC 2024

**Comment by apu52** [comment]
@parkhibhandula this issue is already present in this repo . Sorry to close this issue .
