### ISSUE TITLE
To fix border of "CONTACT US" image section in Dark Mode

### ISSUE THREAD

**Issue by parkhibhandula** [apu52/Travel_Website#615]
**Describe the bug**
The contact us image section is having border-radius only from the 2 corners which is visible in the dark mode.

**Expected behavior**
The contact us image section should have border-radius from all the corners.

**Screenshots (Mandatory)**
![Screenshot 2024-05-26 124946](https://github.com/apu52/Travel_Website/assets/165069293/921910f6-9121-4afc-8745-99f596f66aef)

**Additional Context (Mandatory)**

***Are you contributing under any open-source program? ***
Yes, Iam contributing under GSSOC 2024.

**Comment by apu52** [comment]
@parkhibhandula you are assigned.

**Comment by parkhibhandula** [comment]
@apu52  I have done the task but getting error while pushing on github.
PS C:\GSSOC24\Travel_Website> git push origin main
remote: Permission to apu52/Travel_Website.git denied to parkhibhandula.
fatal: unable to access 'https://github.com/apu52/Travel_Website.git/': The requested URL returned error: 403

**Comment by parkhibhandula** [comment]
I made a separate branch as 'new' and trying to push it.
I will retry.
