### ISSUE TITLE
BUG: Destination section not working properly

### ISSUE THREAD

**Issue by Dilpreet0501** [apu52/Travel_Website#616]
Hello @apu52 , in destination section, images are not being displayed. Also on clicking destination in navbar, scroll is not working.

**Screenshots (Mandatory)**
![Screenshot 2024-05-26 133327](https://github.com/apu52/Travel_Website/assets/100590445/3f7615c7-e0e5-41c8-bdc4-0aceca9e8dc0)

**Additional Context (Mandatory )**
Kindly assign me this issue under GSSoC'24. I'll do my best.

***Are you contributing under any open-source program ?***
Yes, I am contributing under GSSoC'24.

**Comment by apu52** [comment]
@Dilpreet0501 this issue is already present in this repo & also assigned.
