### ISSUE TITLE
Feature: Login_popup page 

### ISSUE THREAD

**Issue by IpsitaPrusty** [apu52/Travel_Website#617]
**Is your feature request related to a problem? Please describe.**

Suppose if a user is visiting the website for the second time,then there should be a login page as well,why will the user will give all the informations again

**Describe the solution you'd like**

So when we tap on the login button then there should come a login popup page to login into the website.

**Demo Video/Screenshot (Mandatory )**

<img width="711" alt="image" src="https://github.com/apu52/Travel_Website/assets/145246053/4edcd4eb-7674-44f1-b6dc-1eb70e630b67">

***Are you contributing under any open-source program ?***
No, I am not contributing under any open-source program except GSSOC'24

@Ghanshyam89  please sir, assign this to me.

**Comment by apu52** [comment]
@IpsitaPrusty this  issue is really good .but now it's already present in the website. So I think there is no need for this issue now .thanks for the issue .but I have to close this issue for now.
