### ISSUE TITLE
Adding Social Media Icons

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#619]
To enhance the user experience of the About page by adding social media icons to the footer section.
This will provide users with easy access to our social media profiles and improve engagement.
Could you please assign this issue to me under GSSoC'24?

**Comment by somyagupta05** [comment]
can you pls assign me this issue.

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by KrishnenduDG** [comment]
Closing this issue cz no proper issue template has been followed. If you wanna contribute, first raise a issue using the proper Issue template provided and then we can proceed further.
