### ISSUE TITLE
Missing Login page

### ISSUE THREAD

**Issue by harsh02mishra** [apu52/Travel_Website#620]
On the web page login page is unavailable 
So I want to add the login page as attached below.
![LogIn](https://github.com/apu52/Travel_Website/assets/144336311/51ebb544-e860-4921-89ed-1cd4b9459acc)

@apu52, please assign this task to me.

This issue is underGSSoC'24.

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by apu52** [comment]
@harsh02mishra we already have a login page in the website . so no need of this issue now. I am closing this issue
