### ISSUE TITLE
Non-functioning links in the footer section of Story Page

### ISSUE THREAD

**Issue by Samridhi002** [apu52/Travel_Website#621]
### Description:

I have noticed that the footer links under the _"Support"_ section and the email address on the Story Page are not navigating to their respective pages. Here are the details:

**Support Links:**

- FAQs
- Terms & Conditions
- Privacy Policy
- Contact Us
- 

**Email Address:**

tour@tourguide.com

When I click on these links, nothing happens, and I am not redirected to the intended pages.

### Steps :

- Visit the Tourguide Website - Story Page.
- Scroll down to the footer section.
- Click on any link under the "Support" section or the email address.

### Expected Behavior:
Clicking on these links should navigate to the respective pages or open the email client for the email address.

### Actual Behavior:
Nothing happens when clicking on these links.

### Attachment
![Screenshot (14)](https://github.com/apu52/Travel_Website/assets/169380578/f0ca3259-a767-40c4-b6c5-78cf1e9cffb4)

***Are you contributing under any open-source program ?***
GSSoC'24

Hey @apu52 ,
I can solve this issue once you assign me under GSSoC. Thank You!

**Comment by apu52** [comment]
@Samridhi002 you are assigned.
