### ISSUE TITLE
[BUG] : Page not Responsing

### ISSUE THREAD

**Issue by sivaprasath2004** [apu52/Travel_Website#622]
**Describe the bug**
- In this project can be `payment.html` can be `404` cannot find the page Error. 

**Expected behavior**
- In `payment` page can be responsing in this project

**Screenshots (Mandatory)**

[Screencast from 2024-05-26 16-44-58.webm](https://github.com/apu52/Travel_Website/assets/121082414/299e066a-bb9a-4257-afeb-a08b352421d6)

***Are you contributing under any open-source program ?***
- GSSOC 24

**Comment by Ramanjangra158** [comment]
please add the label like gssoc and mention level number as well.

**Comment by apu52** [comment]
@sivaprasath2004 you are assigned.
