### ISSUE TITLE
Glowing Login Button: A User-Friendly Touch

### ISSUE THREAD

**Issue by sakshi261203** [apu52/Travel_Website#626]
**Is your feature request related to a problem? Please describe.**
No, the glowing login button feature request isn't directly related to a specific problem on the website. It's more about improving the user experience (UX) and design.

**Describe the solution you'd like**
Absolutely, adding a glowing button effect to the login button is a great way to enhance the user experience on the website. It can improve the button's visibility, especially for users with certain visual impairments, and add a touch of interactivity that can make the login process feel more engaging.
I'd like to propose adding a subtle glowing button effect to the login button. This could be implemented with pure CSS and would involve adding a hover effect that creates a glowing animation around the button when a user hovers their mouse over it.
I think_ this would be a great way to [ e.g. improve the button's visibility, make the login process more engaging] and I'm confident that I can implement this change using my skills in CSS. I've been working on similar effects recently, and I'm confident I can deliver a high-quality solution.

**Describe alternatives you've considered**
While a glowing button effect offers a nice touch,  here are some alternative approaches I've considered that might also achieve the desired goals:
1. **Increased Button Contrast**: A simple yet effective solution could be to increase the color contrast between the login button and its background. This can make it stand out more prominently without adding animation.
2. **Button Shadow**: A subtle drop shadow effect can also enhance the button's depth perception and make it appear more clickable
3. **Button Border Change**: On mouse hover, the button's border could change color or thickness to provide a visual cue for interaction.
4. **Button Animation (Non-Glowing)**: A different type of animation, like a slight button scale on hover, could also add interactivity without the glowing effect.

**Demo Video/Screenshot (Mandatory )**
![Screenshot (6891)](https://github.com/apu52/Travel_Website/assets/163162219/20382994-cf81-4b6a-8997-57896129fcdc)
![Screenshot (6892)](https://github.com/apu52/Travel_Website/assets/163162219/2b1a12ea-f5e8-44fd-a437-4c9cc6fb4957)

***Are you contributing under any open-source program ?***
No, I am not contributing under any open- source program till now.

**Comment by sakshi261203** [comment]
Hi Arpan Chowdhury, Please assign this issue to me..

**Comment by DiyaMittal02** [comment]
I want to contribute in this project. Please assign this issue to me

**Comment by apu52** [comment]
@sakshi261203 you are assigned.

**Comment by thecloudcode** [comment]
Please assign me this issue under GSSoC'24, I can do this easily

**Comment by apu52** [comment]
> Please assign me this issue under GSSoC'24, I can do this easily

This issue is already assigned . Please try to raise new issues on which you want to work on
