### ISSUE TITLE
Add a carasoul slider  after navabar .

### ISSUE THREAD

**Issue by MandeyMan** [apu52/Travel_Website#63]
![Screenshot 2024-01-16 233018](https://github.com/apu52/Travel_Website/assets/120216011/61fac827-52ae-47f6-9afe-eb980ae6222c)

I am writing to formally request a grant for the integration of a carousel slider , aimed at enhancing the user experience for travelers. The carousel slider will efficiently showcase travel destinations and information in a concise and visually appealing manner, promoting engagement and accessibility.

Please assign me this issue under jwoc 2024

**Comment by apu52** [comment]
@MandeyMan Welcome to the repo.
Actually this issue is already present in the repo (#38 )
Sorry , this issue can't be assigned. Instead you can raise any other issue
Btw thanks for raising the issue.
