### ISSUE TITLE
Feat: Adding styles/better UI in footer section 

### ISSUE THREAD

**Issue by Mubashir2611** [apu52/Travel_Website#637]
### Feature Request:
**The footer section area is not looks better, so i want to give a better UI in this section.**

### Solution
 **I want to give a better responsive UI in this section that is user friendly**

**I would like to work in this issue please assign me @apu52** 

![image](https://github.com/apu52/Travel_Website/assets/108177382/9b030951-8992-496e-bf68-c9043d8aba44)

***Are you contributing under any open-source program ?***
 **Yes**

**Comment by apu52** [comment]
@Mubashir2611 you are assigned.
