### ISSUE TITLE
BUG UI Enhancement of Image Gallery

### ISSUE THREAD

**Issue by sharmi4590** [apu52/Travel_Website#638]
**Describe the bug**

THE whole image gallery is not at all responsive and it is occupying a lot of space in the webpage and at the end the label is not visible.
And it is overlapping the testimonials.

**Expected behavior**

I will change it responsive and user friendly.

**Screenshots (Mandatory)**

![Screenshot (471)](https://github.com/apu52/Travel_Website/assets/102676949/c0d11d33-1778-4aa8-b086-2949c5cc7d6c)

![Screenshot (469)](https://github.com/apu52/Travel_Website/assets/102676949/5f33a38a-dcb2-4f13-89bc-399a28cd05e3)
![Screenshot (468)](https://github.com/apu52/Travel_Website/assets/102676949/c5a94e6c-1a64-458b-9a1d-b690da96153f)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by apu52** [comment]
@sharmi4590 this is really a very good issue . Try to design this trip gallery portion interesting . & I think there is some previously assigned issues you already have . So try to complete that at first

**Comment by Hanshika248** [comment]
please assign me this issue. I want to work on this issue

**Comment by apu52** [comment]
> please assign me this issue. I want to work on this issue

This issue is already assigned . Please try to raise new issues on which you want to work on
