### ISSUE TITLE
BUG FAQs

### ISSUE THREAD

**Issue by sharmi4590** [apu52/Travel_Website#639]
**Describe the bug**

FAQ test is very large and it is not matching with other texts in the website, as for a user friendly website the whole website should follow a pattern. Even it can be wriiten in one sentence instead of breaking it i.e enlarging its width (It will save the space).

**Expected behavior**

I will make sure the FAQs follow a pattern.

**Screenshots (Mandatory)**

![Screenshot (472)](https://github.com/apu52/Travel_Website/assets/102676949/d197de8f-7744-4434-be43-de73174ecf12)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

GSSoC'24

**Comment by apu52** [comment]
@sharmi4590 this is a good issue .but i am not assigning you this right now As you already been assigned previous 2 issues .try to complete those at first

**Comment by sharmi4590** [comment]
Hey @apu52 Since I completed the last two issues , could you assign me this.

**Comment by apu52** [comment]
@sharmi4590 u are assigned.
