### ISSUE TITLE
Grammatical errors in the "Best trip package" section of the website 

### ISSUE THREAD

**Issue by sandy-queen** [apu52/Travel_Website#640]
**Describe the bug**
There is a grammatical error in the above mentioned section. Since there are multiple trip packages being offered, it should be "Best Trip Packages". Also, the commas are misplaced. There is a space before the comma, but it should be after the comma. I think fixing these issues can improve the look of the website. 

**Screenshots (Mandatory)**
![issue travel website comma](https://github.com/apu52/Travel_Website/assets/147652780/3e198fa4-c061-4f02-a02f-94f45a69efff)

**Additional Context (Mandatory )**
I have highlighted the issues in the screenshot. 

***Are you contributing under any open-source program ?***

- [x] gssoc'24

**Kindly assign this issue to me, and please mark it under GSSoC tag**

**Comment by sandy-queen** [comment]
@apu52 please assign this issue to me. I can help in improving the look of the website.

**Comment by apu52** [comment]
@sandy-queen you are assigned.

**Comment by sandy-queen** [comment]
thank you. i'll get to it right away!
