### ISSUE TITLE
BUG: Misaligned and not properly Designed Purchase Button in Membership Section

### ISSUE THREAD

**Issue by techinaina** [apu52/Travel_Website#641]
**Describe the bug**

In the membership section of the website, the "Purchase" button is not aligned properly with other elements on the page, resulting in an inconsistent and unprofessional appearance. and also the design of all the three  purchase button are differing in appearance    This inconsistency can lead to a confusing and unprofessional user experience

**Expected behavior**

Align the purchase button -The "Purchase" button is properly aligned with other elements on the page to create a cohesive layout.
 All "Purchase" buttons should have the same design to maintain the same look consistent button design will improve the user experience and make the site look more professional.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/143960485/8dd20892-5336-41c5-b9c0-e1e1dfb4383d)
https://github.com/apu52/Travel_Website/assets/143960485/8dd20892-5336-41c5-b9c0-e1e1dfb4383d

**Additional Context (Mandatory )**
Please assign me this issue @apu52  . I would like to work on this issue  and contribute in  your project .

***Are you contributing under any open-source program ?***

yes in Gssoc

**Comment by techinaina** [comment]
@apu52 can you please assign me this issue . I am very happy to contribute in your project.

**Comment by apu52** [comment]
@techinaina you are assigned.
