### ISSUE TITLE
BUG Image on login page is not visible

### ISSUE THREAD

**Issue by Shreyaa173** [apu52/Travel_Website#642]
![Screenshot 2024-05-27 224905](https://github.com/apu52/Travel_Website/assets/144673309/49cddc9b-0da8-4137-92f1-4a7590d0534d)
I want to do this. Please assign me as a gssoc contributor.

**Comment by apu52** [comment]
@Shreyaa173 please don't raise issue without using the issue templates .please try to raise the issue with the help of the templates present in this repo .
sorry to close this issue.
