### ISSUE TITLE
Icons in the footer

### ISSUE THREAD

**Issue by Srujitha-Raghava** [apu52/Travel_Website#645]
**Is your feature request related to a problem? Please describe.**

Currently, our website footer lacks visual appeal and interactive elements. It only contains plain text links, making it less engaging for users. This can lead to lower user interaction and a less professional appearance. The absence of icons for social media links or other important sections makes it difficult for users to quickly identify and navigate to these links. Adding icons can significantly improve the user experience by providing visual cues and enhancing the overall aesthetic of the footer.

**Describe the solution you'd like**
instead of all the text want to replpace it with icons and proper navigations

**Describe alternatives you've considered**

By choosing to integrate an icon library such as Font Awesome, we ensure that the icons are scalable and simple to implement, providing professional look for the footer.

**Demo Video/Screenshot (Mandatory )**
FROM THIS
![Screenshot 2024-05-28 203816](https://github.com/apu52/Travel_Website/assets/143430142/76f97d77-81a7-4fff-b97e-63631fae992e)

TO THIS
![Screenshot 2024-05-28 203746](https://github.com/apu52/Travel_Website/assets/143430142/0aa1a785-2414-4106-bc4c-67cc7b938234)

***Are you contributing under any open-source program ?***
YES,I am contributing under GSSOC

**Comment by PrakarshSingh5** [comment]
Please assign this issue to me

**Comment by apu52** [comment]
@Srujitha-Raghava you are assigned.

**Comment by aryangaur380** [comment]
Dear @apu52 ,

I hope you're doing well. I would like to request this project assignment to contribute to. I'm eager to get involved and apply my skills to make a meaningful impact.

Looking forward to your response.

Best regards,  
Aryan Gaur
