### ISSUE TITLE
Fix feedback page

### ISSUE THREAD

**Issue by Nikuunj** [apu52/Travel_Website#647]
**Type of Issue**
- [x] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I would like to work on the feedback page.

previous issue number #526 

@apu52 (Please assign me)

**Comment by Nikuunj** [comment]
@apu52

**Comment by Nikuunj** [comment]
@apu52

**Comment by Shilpajha29** [comment]
please assign this task to me

**Comment by apu52** [comment]
@Nikuunj can you give me some of description/SS/video prototype that which of the features you want to add as feature in the feedback page??

**Comment by Nikuunj** [comment]
@apu52 Add a Dark Theme

**Comment by apu52** [comment]
Actually @Nikuunj I don't want a dark theme in the feedback page , So sorry to close this issue .
