### ISSUE TITLE
Feature_Request{ Add a new booking page}

### ISSUE THREAD

**Issue by rupalimkrishnan** [apu52/Travel_Website#65]
**Is your feature request related to a problem? Please describe.**
I would like to add a page for the book now button in the package trip section.

**Describe the solution you'd like**
In the page you get to enter your name number of people travelling and the destination that they want to travel to and other personal details.

**Describe alternatives you've considered**
Will make sure it gets all the personal details else we can add that to the contact us link.

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-01-17 07 54 46](https://github.com/apu52/Travel_Website/assets/153444802/ca5e1123-8ec4-4875-861c-1151362b3df3)

***Are you contributing under any open-source program ?***
Assign me under jwoc'24

**Comment by apu52** [comment]
@rupalimkrishnan Thank you for raising this issue. It's a very good issue
Make it more fascinating.

**Comment by apu52** [comment]
you have 4 days to complete your issue

**Comment by apu52** [comment]
@rupalimkrishnan you just have 1 more day to submit your PR

**Comment by apu52** [comment]
@rupalimkrishnan Where is your PR ??
Sorry to close this issue. As you have already crossed the deadline
