### ISSUE TITLE
Fix and enhance Feedback page 

### ISSUE THREAD

**Issue by tarushi29** [apu52/Travel_Website#650]
![Screenshot 2024-05-29 103425](https://github.com/apu52/Travel_Website/assets/128239884/74018bbf-9d19-41d5-a5f2-7bbe3b07dae6)
Provide space below Return to Home Page button.
Change the text style , font and color of the feedback page.

**Comment by MouliiiSharma** [comment]
assign me this issue under GSSOC'24

**Comment by apu52** [comment]
@tarushi29 please try to follow the issue templates present in the repo to raise your issue otherwise I can't assign you the issues.
