### ISSUE TITLE
BUG-FAQ SECTION

### ISSUE THREAD

**Issue by Dishaaa-T** [apu52/Travel_Website#651]
**Describe the bug**
The FAQ section starts right after the testimonials section box without any spacing which looks odd.

**Expected behavior**
There should be proper spacing before starting the FAQ section.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/169146901/d0bbd07e-1e47-4aeb-9fb2-5a4bb0db2690)

***Are you contributing under any open-source program ?***
I am contributing under GSSOC'24

please assign this issue to me under GSSOC'24

**Comment by apu52** [comment]
@Dishaaa-T you are assigned.
