### ISSUE TITLE
BUG:  Improving the membership section

### ISSUE THREAD

**Issue by DebapriyaJha** [apu52/Travel_Website#653]
**Describe the bug**
There is an alignment issue in the membership section of the project, where the layout of the content appears misaligned or inconsistent.

**Expected behavior**
The expected behavior is for the membership section to have a clean and consistent layout, with all elements properly aligned and spaced. The design should be visually appealing and easy to navigate.

**Screenshots (Mandatory)**
![pr1](https://github.com/apu52/Travel_Website/assets/111692420/4107769e-bac3-48ee-b60b-6d0f49fa0001)

**Additional Context (Mandatory )**
To improve the alignment and layout of the membership section, it is recommended to consider using modern CSS techniques and responsive design principles. One approach could be to utilize CSS Flexbox or CSS Grid for better control over the positioning and alignment of elements.

***Are you contributing under any open-source program ?***
Yes. I want to contribute in this project under the gssoc 2024 program

**Comment by apu52** [comment]
@DebapriyaJha this issue is already present in this repo & assigned to another contributor. So closing this issue.
