### ISSUE TITLE
BUG: Error in Destination section

### ISSUE THREAD

**Issue by DebapriyaJha** [apu52/Travel_Website#654]
**Describe the bug**
When clicking on the "Destination" option from the header navigation menu, the website is not scrolling or navigating to the intended destination section. Additionally, the images within the destination section are not loading correctly, even when scrolling down manually.

**Expected behavior**
The expected behavior is as follows:

1) When the "Destination" option is clicked in the header navigation menu, the website should smoothly scroll or navigate to the corresponding destination section on the same page.

2) Once the destination section is in view, either by clicking the navigation link or scrolling manually, the images within this section should load correctly and be displayed to the user.

**Screenshots (Mandatory)**
![pr2](https://github.com/apu52/Travel_Website/assets/111692420/a8616a70-d6f8-4334-a32e-14b55a296233)

**Additional Context (Mandatory )**
To resolve the issue with the header navigation link not targeting the destination section correctly, you may need to check the implementation of the click event handler or the logic that handles the scrolling/navigation functionality. Ensure that the correct target element or section is being identified and scrolled into view smoothly.
Additionally, for the images not loading correctly within the destination section, there could be several potential causes:

1) Incorrect image paths or URLs: Double-check that the image paths or URLs specified in the HTML or CSS are correct and pointing to the actual image files.
2)CSS issues: Inspect the CSS styles applied to the destination section and the image elements. Ensure that there are no conflicting styles or rules that might be causing the images to be hidden or not displayed correctly etc.

***Are you contributing under any open-source program ?***
Yes I want to contribute in this project under gssoc 2024 program

**Comment by PadmaSri08** [comment]
I want to work on this issue and make it the destination section work properly. Please assign this to me.

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by apu52** [comment]
@DebapriyaJha you are assigned & can work on the navigation work only as another contributor is already assigned to do the image part.

**Comment by DebapriyaJha** [comment]
Thank you @apu52 for assigning the task to me. Can You please assign an appropriate level label to this issue so that I can start working on it

**Comment by apu52** [comment]
@DebapriyaJha I will add the labels as per the review of the PR , u can start working....don't worry about the labels , it's my responsibility

**Comment by DebapriyaJha** [comment]
okay
