### ISSUE TITLE
BUG: Navbar is not proper in Contact Page

### ISSUE THREAD

**Issue by zalabhavy** [apu52/Travel_Website#655]
**Describe the bug**
In Contact page Navbar's height is very big and not align with login and logo of website.
**Expected behavior**
It should be properly align with other icons in Navbar.
**Screenshots (Mandatory)**
This is problem :
![image](https://github.com/apu52/Travel_Website/assets/126322584/80a922f3-c4e6-4bab-9344-1cc734ac8d9b)

***Are you contributing under any open-source program ?***

Please Assign this task me Under GSSOC'24

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by apu52** [comment]
@zalabhavy this issue is already present in the repo & already assigned to another contributor. Closing this issue.
