### ISSUE TITLE
Improvement in the login page image .

### ISSUE THREAD

**Issue by agrwal697** [apu52/Travel_Website#657]
**Describe the bug**
  The login page image is not visible ,so can I fix the issue.

**Expected behavior**
If the file name correct in the code, then the image will be visible in the login page and make an login page will be changed so that looks good and improves the UI of the website.

So please Assign me this issue with the GSSOC Label and level also , I would like to work on it.

**Screenshots (Mandatory)**
Before :
![image](https://github.com/apu52/Travel_Website/assets/128716726/ba97042a-1d7a-4ca3-b5ec-71706dab4e7f)

After: 
![Screenshot 2024-05-30 175606](https://github.com/apu52/Travel_Website/assets/128716726/655c0b3b-ad89-4f76-920f-b2beb4a75efc)

**Additional Context (Mandatory )**
If some additional changes happen with this picture, if can I change the width and height of the image . It looks good and improves the UI of the website.

***Are you contributing under any open-source program ?***
yes

**Comment by apu52** [comment]
@agrwal697 you are assigned.

**Comment by Hanshika248** [comment]
please assign me this issue
