### ISSUE TITLE
No Hover Effect on Subscribe Button and Theme Style Not Changing

### ISSUE THREAD

**Issue by adityas-github** [apu52/Travel_Website#659]
### Description:
- **Problem 1:** The subscribe button on the website lacks a hover effect.
- **Problem 2:** When toggling the theme of the page, the style of the subscribe button does not change accordingly.

### Expected Behavior:
- Hovering over the subscribe button should trigger a visual change indicating the hover state.
- Toggling the theme of the page should update the style of the subscribe button to match the new theme.

### Actual Behavior:
- The subscribe button does not exhibit any hover effect.
- The style of the subscribe button remains unchanged when toggling the theme.

### Possible Improvements:
- Ensure that the CSS for the subscribe button includes a rule for the hover state.
- Verify that the theme change logic updates the style of the subscribe button along with other elements on the page.

**Screenshots:** 

No Hover Effect
![image](https://github.com/apu52/Travel_Website/assets/98210910/ad1d40be-94bf-4274-88af-4854a1f3ed99)

Theme toggle
![image](https://github.com/apu52/Travel_Website/assets/98210910/bc36ccdc-1971-43e6-b13a-295ca4156472)

### Are you contributing under any open-source program?
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue
- [x]  I agree to follow this project's Code of Conduct

**Comment by nishthaaggarwal15** [comment]
Please assign me this issue.

**Comment by apu52** [comment]
@adityas-github you are assigned.
