### ISSUE TITLE
add a hover effect at email box

### ISSUE THREAD

**Issue by shuhaki** [apu52/Travel_Website#660]
**Is your Documentation related to a problem? Please describe.**
add a hover effect (hover on email border) at email box like that ....

**Describe the solution you'd like**

<img width="256" alt="Screenshot 2024-05-31 at 12 01 00 AM" src="https://github.com/apu52/Travel_Website/assets/145912232/1376096f-2007-4dd1-ad58-f77109626da5">
hover effect
<img width="268" alt="Screenshot 2024-05-31 at 12 01 29 AM" src="https://github.com/apu52/Travel_Website/assets/145912232/3b407b96-2d9a-486c-b9f9-75b3dd02462a">

**Prototype Screenshot/Demo Video(Mandatory )**

<img width="446" alt="Screenshot 2024-05-31 at 12 06 04 AM" src="https://github.com/apu52/Travel_Website/assets/145912232/ecd96574-0847-40e6-b095-5ab4648e7956">

***Are you contributing under any open-source program ?***
GSSOC'24

**Comment by nishthaaggarwal15** [comment]
@shuhaki Please assign me this issue.

**Comment by apu52** [comment]
@shuhaki you are assigned.

**Comment by ChauhanAyush04** [comment]
@apu52 plz assign me
