### ISSUE TITLE
Animation overpowering content visibility

### ISSUE THREAD

**Issue by diyaaa19** [apu52/Travel_Website#662]
The bubble animation looks good on the webapp but it's overpowering the actual content as we scroll down, I'd suggest that we move the animation to the back of the content, so that the content is clearly visible and the animation satisfies it's purpose too.
@apu52 Please assign me this issue under gssoc'24.
thanks

**Comment by apu52** [comment]
@diyaaa19 please try to raise the issues properly with the help of the issue templates present in the repo so that it will be more understandable .Sorry to close this issue for now.
