### ISSUE TITLE
The contact in footer is not linked with the contact section

### ISSUE THREAD

**Issue by ayush-848** [apu52/Travel_Website#664]
**Is your feature request related to a problem? Please describe.**
The footer contact has no function on clicking it

**Describe the solution you'd like**
On clicking it, we should be directed to the contact us page

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/126975547/479f061c-ccd9-4712-83b3-aee13d311171)

***Are you contributing under any open-source program ?***
Yes, GSSoC'24

**Comment by apu52** [comment]
@ayush-848 you are assigned.

**Comment by ayush-848** [comment]
@apu52 The preloading animation has been showing for a very long time. (as of 10:24 pm)
Please check your deployed website.
