### ISSUE TITLE
Enhanced Feedback Form

### ISSUE THREAD

**Issue by kashisharora9462** [apu52/Travel_Website#665]
**Is your feature request related to a problem? Please describe.**

Your website features an attractive design, enhanced by engaging animations and a cohesive color scheme. However, the feedback form does not match the overall aesthetic. It lacks visual appeal and fails to attract user interaction, which can negatively impact the overall user experience.

**Describe the solution you'd like**

I propose redesigning the feedback form to align with the modern and appealing design of the rest of the website. My approach will focus on creating a visually attractive, user-friendly interface that encourages users to provide feedback. This will include:

- Incorporating a clean, modern design that complements the existing website theme.
- Ensuring the form is easy to navigate and use, with clear instructions and intuitive layout.
- Adding interactive elements, such as hover effects  to make the form more engaging.

I am confident that my design will enhance user engagement and satisfaction. I would appreciate the opportunity to contribute to this project under GSSoC'24.

Recent feedback form made my me was-
![Screenshot 2024-05-26 073902](https://github.com/apu52/Travel_Website/assets/153215875/0d665a8c-ac8b-4f7e-80c0-749a9b6547a0)

**Comment by kashisharora9462** [comment]
> Hi @kashisharora9462! Thanks for opening this issue. We appreciate your contribution to this open-source project.

Please assign me under GSsoc'24

**Comment by apu52** [comment]
@kashisharora9462 you are assigned.
