### ISSUE TITLE
Login page UI

### ISSUE THREAD

**Issue by PriyanshSrivastava0305** [apu52/Travel_Website#666]
The login/signup page needs to be improved

I can do it pls allow me to improve this page 
![login page issue](https://github.com/apu52/Travel_Website/assets/124620152/928ed10f-34ab-4f4f-8a26-9c08cc833a67)

**Comment by PriyanshSrivastava0305** [comment]
@apu52

**Comment by MarishaShoeb** [comment]
Hey, I can work on this issue. Can you please assign this to me?

**Comment by PriyanshSrivastava0305** [comment]
@apu52 pls assign me

**Comment by KrishnenduDG** [comment]
First of all, this issue doesn't follow any of the guidelines and the Issue template and secondly, no proper implementation details or approach hasn't been specified. Closing this issue.

In case, any one of you want to contribute to this, just open a Proper issue with the issue template along with the necessary details  or the approach.
