### ISSUE TITLE
Adding Social Media Icons

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#672]
Is your feature request related to a problem? Please describe.
The current About page lacks social media icons in the footer, making it difficult for users to find and follow our social media profiles, which in turn limits our engagement and reach.

Describe the solution you'd like
Add social media icons to the footer section. These icons should link directly to our official social media profiles, providing users with easy access and encouraging them to follow and engage with us on these platforms.

Describe alternatives you've considered
Adding a separate section dedicated to social media links in the footer section of website.

Demo Video/Screenshot (Mandatory )
Social Media icons of facebook, instagram, twitter, github, etc can be add here
![image](https://github.com/apu52/Travel_Website/assets/168854094/eb81bb4a-2dff-4282-9960-c1d99696ecf1)

Are you contributing under any open-source program?
Yes, I would like to contribute this feature under GSSoC'24. Could you please assign this issue to me?

**Comment by Pratiksha1661** [comment]
Yes, I would like to contribute this feature under GSSoC'24. Could you please assign this issue to me?

**Comment by ananyag309** [comment]
Hey, i would like to contribute to the issue under gssoc. Can you please label it and assign it to me. Thank you

**Comment by apu52** [comment]
@TBorundia this issue is already present in the repo & already been assigned to another contributor . Sorry to close this issue .
