### ISSUE TITLE
Feature_Request adeed social media icon at footer

### ISSUE THREAD

**Issue by shuhaki** [apu52/Travel_Website#673]
**Is your feature request related to a problem? Please describe.**
<add social media that help to user follow your page.....  -->

**Describe the solution you'd like**

**Demo Video/Screenshot (Mandatory )**
<img width="197" alt="Screenshot 2024-06-01 at 2 59 19 PM" src="https://github.com/apu52/Travel_Website/assets/145912232/44689179-d1a8-449d-9ea0-46ec64a0688b">

***Are you contributing under any open-source program ?***
Gssoc'24

**Comment by apu52** [comment]
@shuhaki this issue is already present in this repo . Sorry to close this issue.
