### ISSUE TITLE
Feature_Request Addition of Preloader and Custom Cursor

### ISSUE THREAD

**Issue by Anjaliavv51** [apu52/Travel_Website#675]
**Is your feature request related to a problem? Please describe.**
No

**Describe Feature**
Preloader appears at time of loading and disapperas at Web start.
Custom Cursor more appearence in ointer.

**Demo Video/Screenshot (Mandatory )**

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/f4162b47-edcc-4869-9b68-0013f8898d37)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/e111595d-804c-4638-a2c9-02f1f4a33bab

***Are you contributing under any open-source program ?***
Yes
GSSOC

**Comment by apu52** [comment]
@Anjaliavv51 we already have a preloader & also have a custom cursor , so I am closing this issue .hope to see more of your contributions
