### ISSUE TITLE
BUG: Footer of the website

### ISSUE THREAD

**Issue by Ajita369** [apu52/Travel_Website#676]
**Describe the bug**
In the 'Support' section of the footer the 'Contact us' is looking different and it is also not directing us to contact us page. 

**Expected behavior**
They all should look same and it should direct to the page.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/162597493/c8f41638-c2f6-470a-bcbc-4fb8f6af13cd)

**Additional Context (Mandatory )**
I will like to work on this issue , please assign this to me.

***Are you contributing under any open-source program ?***
Yes, GSSOC'24

**Comment by PrakarshSingh5** [comment]
Please assign this issue to me

**Comment by abhisek2004** [comment]
Hey, I would like to contribute please allow me to work on this issue.
Thank you

**Comment by apu52** [comment]
@Ajita369 you are assigned.
