### ISSUE TITLE
Feature Request : in pricing page the footer support remove underline

### ISSUE THREAD

**Issue by jayanththalla** [apu52/Travel_Website#678]
the footer of the pricing the privacy  faqs remove the underline and hover it  

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/121346142/224a4ecb-5134-4a3d-895f-38bd61c27725)

***Are you contributing under any open-source program ?***

gssoc

**Comment by apu52** [comment]
@jayanththalla you are assigned.
