### ISSUE TITLE
Modifying the About Us section

### ISSUE THREAD

**Issue by Deepikaa20** [apu52/Travel_Website#679]
I'm Deepika.
I went through the Tourguide website. I must appreciate that it's so beautifully built. 
But to my concern the about us section not appearing too good.
Any user first goes through at some point is about the website but I figured out the padding is not proper in the section.
May be we can play with some background colors and even colors to the text to make it more attractive and making it blends with the webpage.
I hope you assign it to me @apu52 
Thank you. I'm looking forward to work with you.

**Comment by ananyag309** [comment]
Hello, @apu52 
I would really like to contribute to this issue please assign it to me and label it for gssoc. 
Thank you

**Comment by apu52** [comment]
@Deepikaa20 this issue is really good .Can you just raise this issue once again with the changes you want to make in the about us section by attaching some SS using the issue templates once again so that I can assign you this issue .
So , I am closing this issue & hope to see your new issue ASAP
