### ISSUE TITLE
Adding a google translate page

### ISSUE THREAD

**Issue by samarsajad** [apu52/Travel_Website#683]
**Is your feature request related to a problem? Please describe.**
Travel websites are usually accessed by people from different parts of the world, so a language barrier is  a common issue

**Describe the solution you'd like**
I would like to add a google translate option that can change the page language for the user

**Demo Video/Screenshot (Mandatory )**
The google translator option would look something like this
![Screenshot 2024-05-28 165535](https://github.com/apu52/Travel_Website/assets/142666229/0dd563bc-5269-49bd-b870-895aecbb8bd4)

***Are you contributing under any open-source program ?***
Yes GSSoC  24

**Comment by samarsajad** [comment]
Please assign this to me @apu52

**Comment by apu52** [comment]
@samarsajad this is really a good issue .you are assigned. start working
