### ISSUE TITLE
Unlimited rating and feedback can be given by one person

### ISSUE THREAD

**Issue by cecily-mee** [apu52/Travel_Website#684]
**Describe the bug**
A single person can give unlimited ratings and feedback on the website without logging in . This undermines the feedback system as some competitor company can anonymously give unlimited rating and feedback.

**Expected behavior**
A single feedback(or a finite number) can be given by a person after logging in . 

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSOC

**Comment by apu52** [comment]
@cecily-mee this is really good issue. You are assigned.

**Comment by cecily-mee** [comment]
@apu52 there are problems associated with the login page , as in not able to register and login because of which implementing this on existing login page is difficult. I see that u have given an open issue for creating a new login page . so should i wait until it is completed to start with this issue or create a login page by myself for this ?

**Comment by apu52** [comment]
> @apu52 there are problems associated with the login page , as in not able to register and login because of which implementing this issue on existing login page is difficult. I see that you have given an open issue for creating a new login page . So should i wait until that issue is completed to start with this issue ?

yes. The `Login page` issue is already assigned to another contributor , you should wait until he/she complete the issue , then u can start working on it.
