### ISSUE TITLE
BUG: NIGHT MODE does not work for the rating page 

### ISSUE THREAD

**Issue by cecily-mee** [apu52/Travel_Website#685]
**Describe the bug**
night/day mode does not work in the 'rate us' page of the website. Inspite of clicking night mode , the color of the page does not change as in the other pages.

**Expected behavior**
Expected color of the page to change in the 'rate us ' page on clicking the mode option

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/143897317/60415fe1-848c-4db1-b276-761278cadec5)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSOC

**Comment by apu52** [comment]
@cecily-mee you are assigned. But I want to recommend you to please complete the previously assigned PR.

**Comment by cecily-mee** [comment]
@apu52 okay, thanks . Will work on the previously assigned pr first .
