### ISSUE TITLE
BUG Same name for both login and register page

### ISSUE THREAD

**Issue by harinisayani** [apu52/Travel_Website#687]
**Describe the bug**
I observed that there is same name "login" for both login and register page.

**Screenshots (Mandatory)**
![Screenshot (154)](https://github.com/apu52/Travel_Website/assets/143276011/9b7f7655-8fbe-48f1-8bc0-2c928781795a)

**Additional Context (Mandatory )**
Please assign me this task.

***Are you contributing under any open-source program ?***
I am GSSOC'24 Contributor.

**Comment by apu52** [comment]
@harinisayani you are assigned.....Name the buttons differently That will be useful
