### ISSUE TITLE
Enhancing the Contact Page

### ISSUE THREAD

**Issue by ananyag309** [apu52/Travel_Website#690]
**Is your feature request related to a problem? Please describe.**
It is of contact us page. after the user submits the form successfully, they see an alert box with the message "Email sent successfully!" but the form is not reset

**Describe the solution you'd like**
after submission, the form will be reset, providing a better user experience.

***Are you contributing under any open-source program ?***
GirlScript Summer of Code GSSoC'24

**Comment by ananyag309** [comment]
please assign it to me under ggsoc'24

**Comment by apu52** [comment]
@ananyag309 Welcome to METAVERSE!!!!!!!!!
Thanks for raising the issue .
You are assigned. Start working on this issue.

**Comment by ananyag309** [comment]
@apu52 I have modified the code and pulled req, please have a check. Now the form gets reset after submission.
