### ISSUE TITLE
Closing or Back option is not available at feedback form

### ISSUE THREAD

**Issue by ananyag309** [apu52/Travel_Website#691]
Issue - Once opened the feedback form there is no option to go back or return.
Solution - I want to add that.
Contributing to - Gssoc'24

![issue](https://github.com/apu52/Travel_Website/assets/145869907/bcb42d02-1530-4353-9adc-d65e38035af0)

**Comment by ananyag309** [comment]
@apu52 please assign me this issue under gssoc'24

**Comment by apu52** [comment]
@ananyag309 please try to raise the issues using the issue templates & properly so that make it understandable attaching demo img or videos

**Comment by apu52** [comment]
sorry to close this issue
