### ISSUE TITLE
BUG : 

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#695]
**Describe the bug**

There are some alignment problem .I have described the problems here

**Expected behavior**

1. make the "Best trip package" heading at the center & also change it's color like the other color of the headings
2. Make suitable gap between these 3 buttons
3. make it a gap between about us make this as a heading of the slides "Explore Top Destinations"
4. Make the alignment as per instructed in the pic

**Screenshots (Mandatory)**

**1st problem :**
![image](https://github.com/apu52/Travel_Website/assets/114172928/b42a4033-1650-458f-9654-20a3636bf0e7)

**2nd problem :** 
![image](https://github.com/apu52/Travel_Website/assets/114172928/b0a491ec-ff43-46ba-bfb5-bbc052b5b5ce)

**3rd problem :**

![image](https://github.com/apu52/Travel_Website/assets/114172928/fc09f44d-aff2-4946-9323-54bb4148c23d)

**4th Problem :** 
![image](https://github.com/apu52/Travel_Website/assets/114172928/0efefa8f-6d7c-44c1-82c5-91005a03bda0)

**Additional Context (Mandatory )**

### It is a Open ISSUE , Whoever will comment first will get the issue assigned to HER/HIM.

***Are you contributing under any open-source program ?***

GSSOC'24

**Comment by Chelseasingla1** [comment]
> **Describe the bug**
> 
> There are some alignment problem .I have described the problems here
> 
> **Expected behavior**
> 
> 1. make the "Best trip package" heading at the center & also change it's color like the other color of the headings
> 2. Make suitable gap between these 3 buttons
> 3. make it a gap between about us make this as a heading of the slides "Explore Top Destinations"
> 4. Make the alignment as per instructed in the pic
> 
> **Screenshots (Mandatory)**
> 
> **1st problem :** ![image](https://private-user-images.githubusercontent.com/114172928/335896853-b42a4033-1650-458f-9654-20a3636bf0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODYxMTgsIm5iZiI6MTcxNzM4NTgxOCwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk2ODUzLWI0MmE0MDMzLTE2NTAtNDU4Zi05NjU0LTIwYTM2MzZiZjBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMzM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGRlNTlhNDRlNTVhN2RkZTE3Mjk3ZDdhYWEzYTI3Y2M2ODFjNjliM2M0MjY2MTVlYmNkZWUzZDA0MDUwMzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sfeWN3T29hAglO177mrK6ThxnSuT906qEy6vo7MJNWE)
> 
> **2nd problem :** ![image](https://private-user-images.githubusercontent.com/114172928/335896876-b0a491ec-ff43-46ba-bfb5-bbc052b5b5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODYxMTgsIm5iZiI6MTcxNzM4NTgxOCwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk2ODc2LWIwYTQ5MWVjLWZmNDMtNDZiYS1iZmI1LWJiYzA1MmI1YjVjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMzM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTU5OTgwOGY3ZWI0OWVmMzhhOWEwM2MwODAxMGViMTEzYmZjZThjNDU5ZmRhNmFmNWNhNjE5MGEyMzM4MmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IezRTQCd2MtZAppg_8C_dckv179JagEwMvmk--2QEdc)
> 
> **3rd problem :**
> 
> ![image](https://private-user-images.githubusercontent.com/114172928/335896907-fc09f44d-aff2-4946-9323-54bb4148c23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODYxMTgsIm5iZiI6MTcxNzM4NTgxOCwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk2OTA3LWZjMDlmNDRkLWFmZjItNDk0Ni05MzIzLTU0YmI0MTQ4YzIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMzM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2FkYTNmODc0ZTU1ODg3ZmY5OGJkNjM3YmI5NzE5YjA1MDg3NGYwMWExYzkxMzA4MzFjNTYzNmQyN2UyY2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DIsxd7MbSxUAxUn6phQKHiGguQu5hVVjdwlEZXxqwaI)
> 
> **4th Problem :** ![image](https://private-user-images.githubusercontent.com/114172928/335897115-0efefa8f-6d7c-44c1-82c5-91005a03bda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODYxMTgsIm5iZiI6MTcxNzM4NTgxOCwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk3MTE1LTBlZmVmYThmLTZkN2MtNDRjMS04MmM1LTkxMDA1YTAzYmRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMzM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2M2MWNmMjMyZGU1ODFmYzY2OGRkZTQxOGI1ODE4N2M1MjdjOTEwN2JlMzM3ZDczNjU1YzViY2E3NzM1ZmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0l1cGbS-2keL-_eLksCKfG-ZAPNHK3olFS72e7Yki6E)
> 
> **Additional Context (Mandatory )**
> 
> ### It is a Open ISSUE , Whoever will comment first will get the issue assigned to HER/HIM.
> _**Are you contributing under any open-source program ?**_
> 
> GSSOC'24

Hi please assign me this issue under GSSoC'24.

**Comment by Vasilistaxo** [comment]
> **Describe the bug**
> 
> There are some alignment problem .I have described the problems here
> 
> **Expected behavior**
> 
> 1. make the "Best trip package" heading at the center & also change it's color like the other color of the headings
> 2. Make suitable gap between these 3 buttons
> 3. make it a gap between about us make this as a heading of the slides "Explore Top Destinations"
> 4. Make the alignment as per instructed in the pic
> 
> **Screenshots (Mandatory)**
> 
> **1st problem :** ![image](https://private-user-images.githubusercontent.com/114172928/335896853-b42a4033-1650-458f-9654-20a3636bf0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTc4MjIsIm5iZiI6MTcxNzQxNzUyMiwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk2ODUzLWI0MmE0MDMzLTE2NTAtNDU4Zi05NjU0LTIwYTM2MzZiZjBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMjI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDBjMTIyZjA3MjgzYTliMzgwMWNhZDI4MDViYjRlYzg4ZmE3NzVlYjZlNDkwM2ViY2I1ZDliNjJhYmQ1ZTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihjE-U23X_6G0JapTtZCNWupJXhj5mOtD6DTuNjahdE)
> 
> **2nd problem :** ![image](https://private-user-images.githubusercontent.com/114172928/335896876-b0a491ec-ff43-46ba-bfb5-bbc052b5b5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTc4MjIsIm5iZiI6MTcxNzQxNzUyMiwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk2ODc2LWIwYTQ5MWVjLWZmNDMtNDZiYS1iZmI1LWJiYzA1MmI1YjVjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMjI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzY2ODA2OWY4MGU2OGZmYzZjZWVlOWQyZWFkMmVjNDZmZDk0ODllZDQ5NGE4ZTQ2NTRjZmI2YzIzOWRlMjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KqGT66wu82Lwmpboto5ZiJXPaVhKoEhm_BEeRPJJ-M8)
> 
> **3rd problem :**
> 
> ![image](https://private-user-images.githubusercontent.com/114172928/335896907-fc09f44d-aff2-4946-9323-54bb4148c23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTc4MjIsIm5iZiI6MTcxNzQxNzUyMiwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk2OTA3LWZjMDlmNDRkLWFmZjItNDk0Ni05MzIzLTU0YmI0MTQ4YzIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMjI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDdmZjU3NmIwZmQzNzBhNTkzYTE3NmI1ZWRhMGQ4MTI1YjljYWE0OTBiZWIxNTU4MGQzOWM5YzRlMTJhOWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yZsNFlRsCtn4UAuJVNpBs16BpfGU0GIU9gCG2Eubt8c)
> 
> **4th Problem :** ![image](https://private-user-images.githubusercontent.com/114172928/335897115-0efefa8f-6d7c-44c1-82c5-91005a03bda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTc4MjIsIm5iZiI6MTcxNzQxNzUyMiwicGF0aCI6Ii8xMTQxNzI5MjgvMzM1ODk3MTE1LTBlZmVmYThmLTZkN2MtNDRjMS04MmM1LTkxMDA1YTAzYmRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMjI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWFhMWNjNTUxNGVkYjllMmJlNDA0ZTYyMDQxYjhmYzRmN2JmM2UxMzgzMDUwNDc5Y2YxNmE4NGVkOGNlNDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r9ebrgnFK3fpU7WtuZxYVbqFTbC95rIbPyix6m-jS70)
> 
> **Additional Context (Mandatory )**
> 
> ### It is a Open ISSUE , Whoever will comment first will get the issue assigned to HER/HIM.
> _**Are you contributing under any open-source program ?**_
> 

Hello, i could fix this if you would assign me the issue. Thank you.

**Comment by thecloudcode** [comment]
Assign me this issue, I can handle this

**Comment by DiwareNamrata23** [comment]
I'm interested to fix this bug . @apu52 Please assign this issue to me .
thank you!

**Comment by abckhush** [comment]
Can you pls assign me this issue?

**Comment by apu52** [comment]
@Chelseasingla1 you are assigned .Start working on this issue & try to complete this issue within 2-3 days.

**Comment by apu52** [comment]
@Vasilistaxo @thecloudcode @DiwareNamrata23 @abckhush this  issue is already assigned following the FCFS rule . You can still raise new issues on which you want to work on.

**Comment by sauraabhh** [comment]
hey ! I am interested to fix this bug so please assign me this issue under GSSoC'24.

**Comment by pranavroy22** [comment]
I am interested to fix the bug so can you assign me the issue.
