### ISSUE TITLE
BUG : LOGIN PAGE

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#696]
**Describe the bug**

the 2nd "LOGIN"  button in the home page
![image](https://github.com/apu52/Travel_Website/assets/114172928/77ad144d-09bd-47ae-8f10-c22c13be6f59)
is totally messed up

**Expected behavior**

I want if any contributor can fix this bug & make the login page as it was previously or either you can make this login page from scratch . Give me your ideas in this issue's comments.

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/114172928/dbf52dc0-39ea-48ba-b958-96f53b0f8b04)

**Additional Context (Mandatory )**

**It is an open issue . Whoever will comment first with the best idea , I will assign it to HIM/HER**

***Are you contributing under any open-source program ?***

GSSOC'24

**Comment by ananyag309** [comment]
Please assign this issue to me under gssoc, i will fix the bug and will modify the login page accordingly.

**Comment by Vibe167** [comment]
Please assign me with this issue I will fix the bug

**Comment by DiwareNamrata23** [comment]
I  can fix this bug....
the idea is firstly to remove the second option of login and secondly making the to look good as the footer and navbar both are creating the mess on this page by adjusting navbar and footer also fixing the  login section can make this page to look beautiful also I will try to add animations to this page . I request @apu52 to assign this issue to me.
thank you!!

**Comment by apu52** [comment]
@DiwareNamrata23 I think you have got the best idea. so I have assigned you this issue. try to complete this issue within 2-3 days
