### ISSUE TITLE
Bug - Asymmetric Design in Destination Section - Image Box Sizes

### ISSUE THREAD

**Issue by rahat2134** [apu52/Travel_Website#7]
Issue Description
There is a design inconsistency within the Destination section where image boxes vary in size, leading to an asymmetric layout. To enhance the visual appeal and maintain a cohesive design, we need to address this issue by making the image boxes symmetric in size.
<img width="1307" alt="Screenshot 2024-01-11 at 12 21 57 AM" src="https://github.com/apu52/Travel_Website/assets/136263179/b5257a5b-6eb4-4dec-9a43-5598a31b9dc7">
Proposed Changes
Standardize the size of image boxes within the Destination section for a uniform and balanced layout.
Adjust the dimensions of images or containers to ensure a symmetric presentation.
Additional Information
A symmetric design contributes to a polished and professional look, improving the overall user experience.
Test the changes across different screen sizes to guarantee responsiveness.
Let's work together to create a visually pleasing and consistent layout within the Destination section by addressing this design asymmetry.

**Comment by rahat2134** [comment]
@apu52 assign this issue to me.

**Comment by apu52** [comment]
@rahat2134 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
