### ISSUE TITLE
BUG : Alignment Problems

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#70]
**Describe the bug**

_**Hello everyone,
I have noticed some Alignment problems in the website**_

**Expected behavior**

_I want to make it properly aligned to the website that will help users to use it_

**Screenshots (Mandatory)**

**Make this properly Right Aligned**
![image](https://github.com/apu52/Travel_Website/assets/114172928/ed215abb-70f8-4cc6-b734-0fa7cef05916)

**Make this properly left aligned**
![image](https://github.com/apu52/Travel_Website/assets/114172928/6636eae9-43d3-4247-851c-11aa7d334e57)

**Make it full screen as it's occupying very small padding in the website
(N.B: Don't make any change in other button codes)**
![image](https://github.com/apu52/Travel_Website/assets/114172928/77b3343e-2087-4baf-8bdd-b833735ebc0f)

**Make this properly left aligned**
![image](https://github.com/apu52/Travel_Website/assets/114172928/8fdd098d-c818-449c-9d61-7ffb0b1138a8)

**Additional Context (Mandatory )**

### Whoever will  comment  first on this issue with JWOC mentioned on it I will assign this issue to her/him

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by Prithwi32** [comment]
@apu52 I would Like to work on that issue under JWOC

**Comment by apu52** [comment]
@Prithwi32 You have 2-3 days to complete this issue

**Comment by Hacxmr** [comment]
@apu52 I would like to resolve this issue. Kindly assign me this task under JWOC.

**Comment by apu52** [comment]
> @apu52 I would like to resolve this issue. Kindly assign me this task under JWOC.

This issue is already assigned. you can wait or better raise another new issue you want to work on
