### ISSUE TITLE
 Moditification of About us section

### ISSUE THREAD

**Issue by Deepikaa20** [apu52/Travel_Website#704]
**Is your feature request related to a problem? Please describe.**

1.I went through the TourGuide website. It's actually amazing but the thing is About us section can be a lil bit different.

**Describe the solution you'd like**

2.I wanted to add a picture where the guide will be showing things to tourists it will be a illustration picture.
Then the information which is already there in the website comes beside the picture and the quote will be at the botton 

***Are you contributing under any open-source program ?***

3.Yes, I'm contributing under open-source program i.e., GSSOC'24.
Actually I raised this issue before you said to reopen it again with an ss of the modification.
So, I made an template and will be attaching to this comment.
Hope you assign it to me and I'm looking forward to work with you @apu52 
Thank you.

![Home](https://github.com/apu52/Travel_Website/assets/154827877/d3753c03-eb4d-4787-a551-4dc1f463d328)

**Comment by PrachiPaliwal1** [comment]
please assign the issue, i'll do my best in my first contribution , i am confident

**Comment by apu52** [comment]
@Deepikaa20 you are assigned . Just want to suggest you one thing there are 3 button just beneath the about us section (maybe like tours , guides etc.) don't make any type of change in those icons or cards .Otherwise you can go forward with your changes.

**Comment by Deepikaa20** [comment]
Ok, I will do that.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
