### ISSUE TITLE
Two login buttons in header

### ISSUE THREAD

**Issue by parkhibhandula** [apu52/Travel_Website#706]
**Describe the bug**
Two login buttons are displaying in the navbar.

**Expected behavior**
Only one login button should be there.

**Screenshots (Mandatory)**
![Screenshot 2024-06-03 122201](https://github.com/apu52/Travel_Website/assets/165069293/eb84717e-2a1e-45aa-ac56-6095075fc1e1)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
Yes I am contributing under GSSOC 2024

**Comment by maradadivyasree020** [comment]
can you please assign me this issue to fix it

**Comment by apu52** [comment]
@parkhibhandula already #696 is present there regarding this issue . So sorry to close this issue . But u can still raise new issues on which u want to work on.
