### ISSUE TITLE
Feature_Request : Pricing New Page

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#71]
**Is your feature request related to a problem? Please describe.**

**Hello all,
The pricing section of the website only have 3 cards . I want to make the VIEW ALL button to be working.**

**Describe the solution you'd like**

**I want contributors to make a separate page of the website. When any user clicks on the VIEW  ALL button they maybe redirected to a page which includes the TOUR PLACE CARDS as same as it is.**

**Describe alternatives you've considered**

The Pricing page might contain
- the same price cards
- With proper place name
- with a star review
- price 
- A book now button
- also include the same hovering effect to all the place-cards
**NB :Please include at least 10 place-cards to the website**

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/114172928/a2b7c64f-9a77-468a-892b-90db2753419c

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by apu52** [comment]
### Whoever will comment first on this issue with JWOC mentioned on it I will assign this issue to her/him

**Comment by PranavBarthwal** [comment]
@apu52 I want to work on this issue.

**Comment by apu52** [comment]
@PranavBarthwal You are assigned. You can start working on this issue.
You have 4 days to complete it
