### ISSUE TITLE
BUG: footer of the package.html page

### ISSUE THREAD

**Issue by Vasilistaxo** [apu52/Travel_Website#710]
**Describe the bug**
The footer in package.html page is shown verticaly.

**Expected behavior**
The footer should be displayed horizontaly as in the rest of the pages.

**Screenshots (Mandatory)**
![sc_package html_before](https://github.com/apu52/Travel_Website/assets/167290110/e09655ee-81af-4b1a-8a8c-169ce691e53d)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by Vasilistaxo** [comment]
I would like to fix this if you could assign me the issue. Thank you.

**Comment by apu52** [comment]
@Vasilistaxo this issue has already been fixed .thanks for raising this issue . But sorry I have to close it as completed. U can still raise new issues on which u want to work on.
