### ISSUE TITLE
Feature_Request: Enhance UI of Rate us section

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#711]
**Is your feature request related to a problem? Please describe.**
I would like to make the UI such that it matches the overall theme of the website

**Describe the solution you'd like**
make better CSS styles, match color themes, improve flex designs and make it responsive

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
Will add once assigned

***Are you contributing under any open-source program ?***

GSSOC'24

**Comment by Samik123Mit** [comment]
I wuld enhance the ui to make it more visually appealing,pls assign me the issue.

**Comment by apu52** [comment]
@sau-mili u are assigned . all the best

**Comment by sau-mili** [comment]
Thanks
