### ISSUE TITLE
[Feature] : Implement New Login & Sign Up form 

### ISSUE THREAD

**Issue by sivaprasath2004** [apu52/Travel_Website#713]
**Is your feature request related to a problem? Please describe.**
- In this project `login &  sign Up` form Ui is not perfect. So I suggest for the professional Ui

**Describe the solution you'd like**
- change `professional Login & sign Up form`

**Demo Video/Screenshot (Mandatory )**

[Screencast from 2024-05-23 08-03-02.webm](https://github.com/VanshKing30/FoodiesWeb/assets/121082414/72075675-b407-4dac-b1ed-7f288b405e72)

***Are you contributing under any open-source program ?***
- gssoc24 Contributer..

**Comment by apu52** [comment]
@sivaprasath2004 I am assigning you . Recently the login page UI have been changed in our website .please look into that , Then if u think u can do better UI work for the login page , then PING me with that idea here , I will assign you then

**Comment by sivaprasath2004** [comment]
@apu52  I'm ready to work.
- Assign me..

**Comment by sivaprasath2004** [comment]
@apu52 ,

[Screencast from 2024-05-23 08-03-02.webm](https://github.com/VanshKing30/FoodiesWeb/assets/121082414/72075675-b407-4dac-b1ed-7f288b405e72)

**Comment by apu52** [comment]
> @apu52 ,
> 
>  Screencast.from.2024-05-23.08-03-02.webm

okk. try to make it a full functional login page with all the functionalities & UI according to the theme of the website

**Comment by sivaprasath2004** [comment]
@apu52 ,sure
