### ISSUE TITLE
[Feat]:- Password Hide and Show button

### ISSUE THREAD

**Issue by SrinivasDevolper** [apu52/Travel_Website#715]
**Is your feature request related to a problem? Please describe.**

It has no show and Hide password input on the login and register pages.

**Describe the solution you'd like**

we need to add a show and hide button in the password input for user-friendly

**Demo Video/Screenshot (Mandatory )**
1. ![password2](https://github.com/apu52/Travel_Website/assets/121508628/81859088-0fbf-4e6c-8fd8-73e82ab21a61)
2. ![password1](https://github.com/apu52/Travel_Website/assets/121508628/ab18937f-a2aa-4ac0-b6c3-2fd29ae71e9b)

**which one you like**

***Are you contributing under any open-source program ?***

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

**Comment by abckhush** [comment]
Can you pls assign me this issue?

**Comment by apu52** [comment]
@SrinivasDevolper u are assigned . There are recent changes in the login page .So kindly update your branch before adding this feature . All the best

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.

**Comment by GuruLohithaNarala** [comment]
Hello @apu52  iam a contributor @GSsoc 2024 extnd  so i have worked on this project isuue . please assign me this issue under gssoc level 1 . 

iam providing the screen shots of the resolved issue please look into this and assign me this issue .

thank you,


 
![Screenshot 2024-10-03 151920](https://github.com/user-attachments/assets/9732dbdd-67c2-4a4b-85e6-e88822a69f46)
![Screenshot 2024-10-03 151946](https://github.com/user-attachments/assets/49da2aea-c8fc-4568-b15c-8c750d185988)

**Comment by Prithvi2004** [comment]
Hey @apu52 please assign me this task I  have much  experience in front end development
