### ISSUE TITLE
BUG : Pictures and Text not aligned properly in About Us Section

### ISSUE THREAD

**Issue by LakshmiMansi09** [apu52/Travel_Website#716]
**Describe the bug**
* Pictures and numbers related to guides, tours and locations in ABOUT US section are _**not aligned properly**_.
 
* The subheading 'location' is **_missing_** under number of locations visited.

**Expected behavior**
Pictures and Text related to guides, tours and locations to be aligned properly.
The tag 'locations' OR 'locations visited' to be added under the number of locations visited.
Overall UI of images in ABOUT US section can be improved.

**Screenshots (Mandatory)**
[]
![Screenshot (1707)](https://github.com/apu52/Travel_Website/assets/150318091/6a36ad98-cf65-4408-95f8-19fab7f3810a)

***Are you contributing under any open-source program ?***
GSSOC '24

**Comment by LakshmiMansi09** [comment]
Hello!
@apu52 please assign this issue to me under GSSOC '24

**Comment by Dhruvanshi29** [comment]
Hi @apu52  I can work on this issue easily and accurately. I m a contibutor under GSSoC'24 so can you please assign this issue to me?

**Comment by apu52** [comment]
@LakshmiMansi09 you are assigned . I would like to suggest u just to work on the bug only , as another contributor is already working on the overall UI change for the about us page
