### ISSUE TITLE
Updating the UI of login page

### ISSUE THREAD

**Issue by shraddhha** [apu52/Travel_Website#721]
The Ui of login page is good now, but it can be made more user friendly and attractive by structuring it properly. Please assign me the issue as I feel I would handle this issue very perfectly and make the login page more attractive.
@apu52 Please assign me this issue under gssoc

**Comment by abckhush** [comment]
Can you pls assign me this issue?

**Comment by Samik123Mit** [comment]
@apu52  pls assign me the issue. i will enhance the UI to give it a visually appealing look.

**Comment by apu52** [comment]
The ui of the login page is already been enhanced . & like to suggest u to please use proper issue templates to raise issues . Closing this issue as unplanned. @shraddhha
