### ISSUE TITLE
Feature_Request->Addition of Increasing Number Effect.

### ISSUE THREAD

**Issue by HishitaGupta** [apu52/Travel_Website#724]
Hello PA,
I propose to add an Increasing Number Effect on the following part of website to make it Look more interactive and appealing.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/159264060/200148d4-3ea0-47bd-bc5e-fafd7a9e9503)

***Are you contributing under any open-source program ?***
GSSoC

**Comment by apu52** [comment]
@HishitaGupta u are assigned.
