### ISSUE TITLE
BUG: navbar 

### ISSUE THREAD

**Issue by Vasilistaxo** [apu52/Travel_Website#725]
**Describe the bug**
When you press the any nav link it resizes the navbar , stretching it and then if you press any again it squeezes it in.

**Expected behavior**
It probably should not get resized when hitting any nav link.

**Screenshots (Mandatory)**
![navbar_stretched](https://github.com/apu52/Travel_Website/assets/167290110/d01f7c7f-9e16-496a-91ac-86ce690f40f6)
![navbar_squeezed](https://github.com/apu52/Travel_Website/assets/167290110/1d6510ce-6317-4a91-ba67-43997b212540)

**Additional Context (Mandatory )**
If you would like this behavior to change , please assign me the task. Thank you!
***Are you contributing under any open-source program ?***

**Comment by apu52** [comment]
@Vasilistaxo u are assigned .But please try to complete the previously assigned PR's at first

**Comment by Vasilistaxo** [comment]
@apu52 this issue #725 looks like its already settled. At least for the index.html page and all the conected sections. 
I noticed theres is a mispositioning of the navbar in the feedback.html page. 

![navbar](https://github.com/apu52/Travel_Website/assets/167290110/7732aa07-c164-4dd7-8e1c-179dca620492)

**Comment by apu52** [comment]
> @apu52 this issue #725 looks like its already settled. At least for the index.html page and all the conected sections. I noticed theres is a mispositioning of the navbar in the feedback.html page.
> 
> ![navbar](https://private-user-images.githubusercontent.com/167290110/337775314-7732aa07-c164-4dd7-8e1c-179dca620492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjM3NzEsIm5iZiI6MTcxNzgyMzQ3MSwicGF0aCI6Ii8xNjcyOTAxMTAvMzM3Nzc1MzE0LTc3MzJhYTA3LWMxNjQtNGRkNy04ZTFjLTE3OWRjYTYyMDQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNTExMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDY1MDAzN2M2ZjBlODFjYjU5NzFiNjdmNWNiNmFhZTVkMzNkYzc1YmRlYmUzMDRjMzQ2ZTk0ZjllMDQ3M2NhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D0uR5jZPTLx9OBbvErvG53ggFzsQ5-JjJNjQ7Gu-fyU)

ok u can work on this.

**Comment by Nikhilkumar111** [comment]
@apu52 Plz Assign to me this issue . I want to work on it.
