### ISSUE TITLE
BUG-> Image Carousel Slider not working Properly

### ISSUE THREAD

**Issue by HishitaGupta** [apu52/Travel_Website#726]
**Describe the bug**
 Image Carousel Slider not working Properly

**Expected behavior**
-Display of Relevant images
-User should be able to use the Image Slider.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/159264060/1dba8f8d-5bd1-492b-a6bd-39ffc1c28a31)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
-GSSoC'24

**Comment by apu52** [comment]
@HishitaGupta this issue has already been solved
