### ISSUE TITLE
Enhancing the checkout page.

### ISSUE THREAD

**Issue by shilpalatiyare** [apu52/Travel_Website#727]
**Is your feature request related to a problem? Please describe.**
In the checkout page, 
1.  The option to choose state is unorganised.
2. Some states are missing (e.g. Goa which can be a great destination for travelling in India).

**Describe the solution you'd like**
1. We can arrange the name of states in alphabetical order in checkout page . This will improve user experience .This improvement ensures that users can easily find and select their desired locations without having to sift through a unorganised list.
2. We can add missing states in the list. 

**Demo Video/Screenshot (Mandatory )**

<img width="1435" alt="Screenshot 2024-06-03 at 10 20 11 PM" src="https://github.com/apu52/Travel_Website/assets/100855418/7530b14a-369b-442d-8e88-5367fd6993d1">

***Are you contributing under any open-source program ?***
Yes , I am contributing under GSSOC'24.

**Comment by shilpalatiyare** [comment]
@apu52 Please assign this issue to me under GSSOC, I will fix this issue.

**Comment by Samik123Mit** [comment]
@apu52  I would enhance the ui ,pls assign me the issue.

**Comment by SohaFarhana** [comment]
I would like to work on this issue as GSSOC'24 contributor

**Comment by apu52** [comment]
@shilpalatiyare u are assigned.

**Comment by shilpalatiyare** [comment]
@apu52 I have resolved the issue , please have a look.
