### ISSUE TITLE
Feature_Request->Addition Of 3d Parallax Tilt Effect on Cards

### ISSUE THREAD

**Issue by HishitaGupta** [apu52/Travel_Website#728]
Hello PA,
I propose to add a tilty effect on cards in the website using tilt.js to make it look more appealing.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/159264060/8f051437-c843-43c8-8320-8a47a2977744)

***Are you contributing under any open-source program ?***
-GSSoC'24

**Comment by apu52** [comment]
@HishitaGupta u are assigned .But at first please try to complete previously assigned issues.
