### ISSUE TITLE
BUG : Gallery page destination

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#73]
**Describe the bug**

**Hello All,
I have noticed a bug in the website that there is a issue between the gallery/Reviews part & the contact us par**t

**Expected behavior**

**After clicking on the VIEW ALL button in the REVIEW/ GALLERY section the picture revolver & the gallery opens after the contact us portion .** 
- I want that it will be on the top of the contact us page , not beneath it.
- & also make the picture revolver center aligned

 

**Screenshots (Mandatory)**

https://github.com/apu52/Travel_Website/assets/114172928/b2d08ba1-b8e4-4458-b800-51a80bad84ea

**Additional Context (Mandatory )**

### Whoever will comment first on this issue with JWOC mentioned on it I will assign this issue to her/him

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by Lavanya-Sathya** [comment]
Hey @apu52, I would like to contribute to this issue. Please assign this to me.

**Comment by apu52** [comment]
@Lavanya-Sathya You are assigned. you can start working on this issue.
You have 2-3 days to complete this issue.

**Comment by clanang** [comment]
If @Lavanya-Sathya is unable to tackle this, I'd like to. Thank you!

**Comment by apu52** [comment]
> @apu52 if @Lavanya-Sathya is unable to tackle this, I'd like to. Thank you!

ok Are you contributing under JWOC??

**Comment by clanang** [comment]
> > @apu52 if @Lavanya-Sathya is unable to tackle this, I'd like to. Thank you!
> 
> ok Are you contributing under JWOC??

Hi @apu52 I'm currently studying web dev and would like to contribute under JWOC. I see this issue is closed, but can I contribute to others on this project?

**Comment by apu52** [comment]
> > > @apu52 if @Lavanya-Sathya is unable to tackle this, I'd like to. Thank you!
> > 
> > 
> > ok Are you contributing under JWOC??
> 
> Hi @apu52 I'm currently studying web dev and would like to contribute under JWOC. I see this issue is closed, but can I contribute to others on this project?

This issue is already completed. You can raise any new issue you want to work on
NB : please look at already closed/existing issues before that
