### ISSUE TITLE
BUG 🐞: Dark mode gets turned off on refeshing a page

### ISSUE THREAD

**Issue by aslams2020** [apu52/Travel_Website#732]
Hey @apu52,
Here is the issue i encountered - 
The dark mode preference does not persist across page refreshes. Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

**To Reproduce**
1. Go to the website.
2. Toggle the dark mode switch to change the theme.
3. Refresh the page.
4. Observe that the theme reverts to the default mode instead of retaining the selected mode.

**Expected behavior**
The selected dark or light mode should persist across page refreshes.
If a user selects dark mode, the page should remain in dark mode even after refreshing.

**Screenshots (Mandatory)**
Before refreshing the page looks like(currently in dark mode) :
![image](https://github.com/apu52/Travel_Website/assets/131389695/1413dfec-55ed-4fb8-b202-98d20c2401bf)

After refreshing the page :

![image](https://github.com/apu52/Travel_Website/assets/131389695/984e9c28-9c86-44db-9454-2c76e09e5d8d)

***Are you contributing under any open-source program ?***
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by aslams2020** [comment]
Hey @apu52 ,
Could you please review the issue?

**Comment by apu52** [comment]
@aslams2020 u are assigned.

**Comment by aslams2020** [comment]
@apu52

**Comment by aslams2020** [comment]
@apu52
