### ISSUE TITLE
BUG: Scroll To Top Button Visibility

### ISSUE THREAD

**Issue by pani2004** [apu52/Travel_Website#734]
The scroll to top button is visible even when we are at  the top of the page

**Expected behavior**
The button should be only visible when the user scrolls down the page

***Are you contributing under any open-source program ?***
GSSOC'24
![Screenshot (44)](https://github.com/apu52/Travel_Website/assets/154724111/e41a4067-cd0d-4e90-9c28-b50700282872)

**Comment by pani2004** [comment]
@apu52 Pls assign me this!!

**Comment by Samik123Mit** [comment]
please assign me the issue ,i will  make the scrollbar functionable.

**Comment by apu52** [comment]
@pani2004 u are assigned.

**Comment by pani2004** [comment]
@apu52 Pls add the level tag
