### ISSUE TITLE
BUG : Background of Contact Us is not properly visible 

### ISSUE THREAD

**Issue by adityas-github** [apu52/Travel_Website#736]
**Describe the bug**
When toggling to dark mode on the website, the "Contact Us" page has a background issue where elements become poorly visible due to the background color blending with the content. This significantly impacts readability and user experience.

**Expected behavior**
The background and text colors should contrast properly in dark mode, ensuring all elements on the "Contact Us" page are easily readable.

**Suggested Fix:**
To enhance readability in dark mode, we can add a bright shadow to the text and other critical elements on the "Contact Us" page. This would create a contrast between the elements and the background, ensuring they stand out more clearly.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/98210910/853805f9-d999-4e9e-b90a-406ced06c6bd)

***Are you contributing under any open-source program ?***
Yes it is GSSoC 2024

**Comment by rohir1132yadav** [comment]
i want to work on this project . please assign me

**Comment by apu52** [comment]
@adityas-github u are assigned.

**Comment by adityas-github** [comment]
@apu52 
kindly please check this and merge it.
