### ISSUE TITLE
BUG : Destinations in navbar

### ISSUE THREAD

**Issue by aswini-14** [apu52/Travel_Website#737]
when we are clicking on the destinations in the navbar we are navigating to the pictures directly.

but actually we need to navigate to the title "Explore our top destinations".

So ,I would like to correct this.

I would like to contribute under GSSOC 2024.

![Screenshot (137)](https://github.com/apu52/Travel_Website/assets/127423807/7474bd83-4163-4527-9ccf-2b813d1d8689)

**Comment by apu52** [comment]
@aswini-14 u are assigned.
