### ISSUE TITLE
BUG: Href links in the login page aren't looking good and fitting in the UI

### ISSUE THREAD

**Issue by mehrun171** [apu52/Travel_Website#738]
Links placed in the login page to go to home , about us, pricing aren't appropriate i.e they don't fit properly in the login window and are scrolling and getting on top of other elements when we scroll the page...so they need to be redesigned and set them according to the UI of the webpage and also their font color can be changed and hover effects can also be improved...so please assign me this task..i would do the best @apu52 
![Screenshot 2024-06-04 185334](https://github.com/apu52/Travel_Website/assets/116735695/66202407-b6b4-4b61-bf22-965fef5bb9e4)

**Comment by Samik123Mit** [comment]
@apu52  pls assign me the issue. i will fix the text to fit the UI and would enhance it.

**Comment by mehrun171** [comment]
Please assign me this issue @apu52

**Comment by apu52** [comment]
@mehrun171 this issue has already been solved now.

**Comment by mehrun171** [comment]
U didnt assign me this issue :(
