### ISSUE TITLE
adding X button at feedback form 

### ISSUE THREAD

**Issue by mehrun171** [apu52/Travel_Website#739]
we can add X button in the feedback form as when user wants to explore more about the website and then they want to give feedback.. there may be need of going back therefore X (cross) button is highly needed ...Please assign this task to me
![Screenshot 2024-06-04 190243](https://github.com/apu52/Travel_Website/assets/116735695/e1d59fb0-e6bd-4134-ae11-8f282df67f21)

**Comment by kushagrasaxena061** [comment]
@mehrun171 Please assign this issue to me

 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by apu52** [comment]
@mehrun171 this issue is good . But I have to close this  issue as it does not follow the proper issue template , I would like to recommend you to please use proper issue templates to raise the issue again so that I can assign you this issue .
