### ISSUE TITLE
Feature_Request  Define the one proper color to navbar and footer 

### ISSUE THREAD

**Issue by AftabMankapure** [apu52/Travel_Website#74]
Define the one proper color to navbar and footer 

**Describe the solution you'd like**

Maintain the one color 

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/125949765/4871933a-7b14-47c1-846a-c9128c1a870c)

***Are you contributing under any open-source program ?***

JWOC

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by apu52** [comment]
@AftabMankapure You just have 1 day to submit your issue

**Comment by AftabMankapure** [comment]
![image](https://github.com/apu52/Travel_Website/assets/125949765/000983cd-489d-491a-9466-76c0f28ac667)

Navbar hover 

![Screenshot 2024-01-18 084714](https://github.com/apu52/Travel_Website/assets/125949765/7765e52d-d95b-4bbe-8ef2-9f5c8ac7be9d)

footer hover 

![Screenshot 2024-01-18 084824](https://github.com/apu52/Travel_Website/assets/125949765/2cecf2c0-8255-455d-8c4e-41e34faa6eeb)


It it ok or change to any another color

**Comment by apu52** [comment]
@AftabMankapure Make the red hovering color to Sky blue maybe that will be more appropriate (CSS : #87CEEB)

**Comment by AftabMankapure** [comment]
instead of making sky blue we can make button like 

see hire me button  after hover which ever color are choose for button same color is applied to the footer section text
which ever you say i will apply this 

![image](https://github.com/apu52/Travel_Website/assets/125949765/2b74a18f-ee4b-43a0-aa70-c2ef9d8493cd)

after hover effect 

![Screenshot 2024-01-18 123930](https://github.com/apu52/Travel_Website/assets/125949765/86db0b09-e520-42b3-ac16-50f7cf93ca42)

i think it look better  

sky blue look like 

![Screenshot 2024-01-18 124217](https://github.com/apu52/Travel_Website/assets/125949765/4f97215d-9365-4086-91e7-6d11dc383dd3)


![Screenshot 2024-01-18 124639](https://github.com/apu52/Travel_Website/assets/125949765/7a12de04-05fa-4d94-bacd-4ec1d1e7d95e)
#FFD700

![Screenshot 2024-01-18 124809](https://github.com/apu52/Travel_Website/assets/125949765/f5f0874e-c3b0-4cda-a807-b77fcd7997ae)
#006400


added screenshot is form my project

**Comment by apu52** [comment]
![image](https://github.com/apu52/Travel_Website/assets/114172928/c7db5b34-4709-4782-a1b7-ed15859b1e85)

Make it this

**Comment by AftabMankapure** [comment]
i make the PR 
and for button  i can raise issue again and make the seperate PR

**Comment by apu52** [comment]
> i make the PR and for button i can raise issue again and make the seperate PR

No, make all the changes  in the same PR

**Comment by AftabMankapure** [comment]
![image](https://github.com/apu52/Travel_Website/assets/125949765/3b904f7d-b268-435d-a2e7-9e1723d4c8cf)

Hover on contact us
![Screenshot 2024-01-18 182936](https://github.com/apu52/Travel_Website/assets/125949765/dabda8a9-73b5-410f-9b21-dc7a1cc0ba96)


 
![Screenshot 2024-01-18 190304](https://github.com/apu52/Travel_Website/assets/125949765/7574f815-4ce2-4082-842b-a3dc1e212981)

**Comment by apu52** [comment]
ok

**Comment by AftabMankapure** [comment]
change label easy to medium i make the PR

**Comment by apu52** [comment]
> ok change label easy to medium

I will assign the label as per my review. Don't worry

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by AftabMankapure** [comment]
@vermaanurag1532  bro already done this issue just conflicts are there I solved this waiting for tomake PR
