### ISSUE TITLE
BUG: Texts are not allign properly in the navbar of the home page .

### ISSUE THREAD

**Issue by ayushrskiaa** [apu52/Travel_Website#741]
**Describe the bug**

Texts are not allign properly in the navbar of the home page .

**Expected behavior**

Texts should be allign properly.

**Screenshots (Mandatory)**

BEFORE: 
![Screenshot from 2024-06-04 19-17-13](https://github.com/apu52/Travel_Website/assets/130389607/51816d78-34ae-4c27-98c3-d614e1019772)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

GirlScript summer of code 2024.

**Comment by ayushrskiaa** [comment]
@apu52  Please assign this issue to me. I would like to work on it.
Thank you.

**Comment by Samik123Mit** [comment]
@apu52 pls pls assign me the issue. i would fix the bug and align the text properly.

**Comment by apu52** [comment]
@ayushrskiaa I think this issue is solved  now & I found the navbar working & looking well .
