### ISSUE TITLE
Feature_Request: Testimonial section into infinite Marquee

### ISSUE THREAD

**Issue by Archiesachin** [apu52/Travel_Website#743]
**Is your feature request related to a problem? Please describe.**
1. The testimonials take up a lot of space and looks very static. 

2. The footer of the website should have flex-direction as column and not row

3. Removing the 2 login buttons in the home page

**Describe the solution you'd like**
Adding a marquee/carousel for the testimonals section. 

Changing the footer flex orientation. 

**Describe alternatives you've considered**

**Demo Video/Screenshot **

![Screenshot (1049)](https://github.com/apu52/Travel_Website/assets/103347688/b230b1ce-41c2-49f9-b631-63f816446df3)
atory )

![Screenshot (1048)](https://github.com/apu52/Travel_Website/assets/103347688/75b0cc8a-1fe5-48b2-92de-41eaae3279a4)

GSSOC'24

**Comment by apu52** [comment]
@Archiesachin assigned .just want to suggest you that to work on the testimonial section only as the other 2 issues has already been completed.

**Comment by Archiesachin** [comment]
Okay
