### ISSUE TITLE
add social media links, symbols and update footer

### ISSUE THREAD

**Issue by dnyandeepchute** [apu52/Travel_Website#744]
social media links and symbols are not present which is a really important part and all the content in footer is adjust vertically, it will look better if it is horizontal.

**Comment by dnyandeepchute** [comment]
hey @apu52, please assign this to me, thank you.

**Comment by AnjaliUp** [comment]
@apu52 Please assign this issue to me

**Comment by ZnbKhan** [comment]
@dnyandeepchute assign this to me

**Comment by apu52** [comment]
@dnyandeepchute this issue has already been assigned to another contributor previously . & want to suggest you to pls use proper issue templates to raise the issues.
