### ISSUE TITLE
Accepts zero star ratings

### ISSUE THREAD

**Issue by NidhiTornekar** [apu52/Travel_Website#745]
**Describe the bug**
In the "Rate our Service" page, although there is validation for the feedback, there is no validation for the ratings. That is to say even if the user tries to give a zero star rating, it is being accepted.

**Expected behavior**
User should be alerted in case of submission of 0-star ratings and prevent default submission.

**Screenshots**
![ss4](https://github.com/apu52/Travel_Website/assets/121748841/a4c40c70-7126-4be9-a866-103977cdf11c)
![ss3](https://github.com/apu52/Travel_Website/assets/121748841/c5b6cd59-f158-4487-a1af-9109cbff04bc)

***Are you contributing under any open-source program ?***
Please assign me this issue under gssoc 2024.

**Comment by apu52** [comment]
@NidhiTornekar u are assigned.
