### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by nirajsingh015** [apu52/Travel_Website#747]
**Is your feature request related to a problem? Please describe.**
Yes, the current website lacks clear navigation and easy access to our social media profiles, which can hinder user engagement and connectivity.

**Describe the solution you'd like**
I propose enhancing the gooter for better interaction and adding social media links to increase user engagement and connectivity. This will involve reorganizing the footer for more intuitive access and integrating interactive social media icons in the footer.

**Describe alternatives you've considered**
Alternatives considered include placing social media links in the header or within the main content area, but adding them to the footer ensures consistent visibility across all pages without cluttering the main navigation area

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/115022991/3cb475d7-58d8-4f43-b5e0-e8b8202609e7)

***Are you contributing under any open-source program ?***
gssoc

**Comment by apu52** [comment]
@nirajsingh015 this same issue is already existing in this repo & already been assigned to another contributor.
