### ISSUE TITLE
Footer section alignment issue

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#750]
**Describe the bug**
The alignment in the footer section is not proper in some pages of website such as  home page , trip packages , etc. The text and links are not aligned correctly, resulting in an uneven appearance.

**Expected behavior**
The text and links in the footer section should be properly aligned, ensuring a clean and professional look.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/168854094/41f5f382-a63c-4c70-bb4c-b5a7082efc3f)

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by apu52** [comment]
@TBorundia this issue has already been solved.
