### ISSUE TITLE
UI improvement for feedback form to match website theme

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#751]
**Is your feature request related to a problem? Please describe.**
The current feedback form does not align with the overall theme of the website, resulting in a disjointed user experience.

**Describe the solution you'd like**
Redesign the feedback form to match the website's theme. This includes:
1.Updating the color scheme to match the website's primary colors.
2.Using consistent font styles and sizes.
3.Ensuring the form elements (input fields, buttons, labels) have a similar look and feel as the rest of the site.

**Describe alternatives you've considered**
To add a custom design that ensure better integration and consistency.

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/168854094/8696be19-5f79-484b-82f3-bd87e6204a35)

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by vaishnavip27** [comment]
hey @apu52 Can you assign me this issue? I can make the form look more appealing and attractive
