### ISSUE TITLE
Repetitive tagline in destination, trip package, and gallery sections

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#752]
**Describe the bug**
The line "Explore your suitable and dream places around the world. Here you can find your right destination." is repeated in the destination, trip package, and gallery sections. This repetition affects the uniqueness and professionalism of the website.

**Expected behavior**
Each section should have a unique and relevant tagline that enhances the user experience and provides clear, distinct information about each section.

**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/168854094/1f199b12-98fa-432d-87bd-2f1ee1ea3044)
![image](https://github.com/apu52/Travel_Website/assets/168854094/fa71a811-f9e3-439e-ad6c-11a547f5d9de)

***Are you contributing under any open-source program ?***
GSSoC'24

**Comment by apu52** [comment]
@TBorundia u are assigned .
