### ISSUE TITLE
Feature 🌟: "Scroll to Top" Button and "Web Chat-Bot" Are Overlapping.

### ISSUE THREAD

**Issue by Tejashri-Taral** [apu52/Travel_Website#754]
Hi @apu52,

I noticed that the "Scroll to Top" button and the Webchat bot are overlapping on the website.
This overlap affects the usability and accessibility of both features, making it difficult for users to effectively interact with the WebChat bot and the scroll top button.

**Steps to See the Issue:** 

Scroll down the page until the "Scroll to Top" button appears.
Observe the overlap between the "Scroll to Top" button and the WebChat bot.
The Expected Behavior for this is -
The "Scroll to Top" button and the WebChat bot should not overlap. Both elements should be easily accessible without interfering with each other.
Screenshots

So, Before Opening the Chatbot
![Screenshot 2024-06-05 170012](https://github.com/apu52/Travel_Website/assets/160386036/1ff9603a-e8ed-45af-ad6e-49c44dbee08e)

And This is when the issue is generated after clicking on the chatbot.
![image](https://github.com/apu52/Travel_Website/assets/160386036/1f382c0c-4222-4695-a9a2-152db679c6ee)

# The Solution:
I would like to contribute by adjusting the positioning or z-index of the elements to ensure they do not overlap. This can be done by modifying the CSS styles for these components.

@apu52 Could you please assign me this issue under gssoc'24 ?

Are you contributing under any open-source program ?
GSSOC'24

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
