### ISSUE TITLE
Feature_Request :  I want to add show/hide password feature in the login page.

### ISSUE THREAD

**Issue by agrwal697** [apu52/Travel_Website#756]
I think, If we add show/hide password feature in the login page. It will change the looks of the website and improves the UI of the website.

So please Assign me this issue with the GSSOC Label and level also , I would like to work on it.

screenshot : 

before : 
![image](https://github.com/apu52/Travel_Website/assets/128716726/6e613442-b149-49f7-8675-41055a3c7280)

after:
![image](https://github.com/apu52/Travel_Website/assets/128716726/02bfa855-6b06-4a60-9b53-8eca13cfcb3b)

***Are you contributing under any open-source program ?***
yes

**Comment by kushagrasaxena061** [comment]
@agrwal697  Please assign this issue to me

 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by apu52** [comment]
@agrwal697 this issue is already existing in the repo . Sorry to close this issue.
