### ISSUE TITLE
Log in button redirects to log in page

### ISSUE THREAD

**Issue by samarsajad** [apu52/Travel_Website#764]
**Describe the bug**
The user is redirected to the log in page after logging in

**Expected behavior**
User should be redirected to the home page

**Screenshots (Mandatory)**

https://github.com/apu52/Travel_Website/assets/142666229/0419844c-2462-4b46-8863-ae6301b00f9d

**Additional Context (Mandatory )**

GSSoC'24

**Comment by samarsajad** [comment]
Please assign this to me @apu52

**Comment by apu52** [comment]
@samarsajad now the total ui of the login page has been changed , Check out the new Login page & then if u found the same issue with that page , ping me here & then I will assign u this issue.

**Comment by samarsajad** [comment]
Now the buttons are not even functional.
https://github.com/apu52/Travel_Website/assets/142666229/cacbdd1a-5ed6-473c-9eb6-9a496ef5b340
