### ISSUE TITLE
BUG: Font size of questions > font size of heading in FAQ

### ISSUE THREAD

**Issue by divyalaldinani** [apu52/Travel_Website#765]
**Describe the bug**
As you can see, the font size of questions is large and should be lesser and thus looks weird wrt other contents
![image](https://github.com/apu52/Travel_Website/assets/82147067/a89636a8-1c22-4156-b2c2-0403c577c81c)

**Expected behavior**
Font size of questions should be less.

**Screenshots (Mandatory)**

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by divyalaldinani** [comment]
@apu52

**Comment by apu52** [comment]
@divyalaldinani u are assigned.
