### ISSUE TITLE
BUG: Font size of subscribe button is very large

### ISSUE THREAD

**Issue by divyalaldinani** [apu52/Travel_Website#767]
**Describe the bug**
The font size of subscribe button is much larger wrt the placeholder text 'email address' and should be 2/3px larger than the placeholder text, and can be made bold, to emphasise on the button.
![image](https://github.com/apu52/Travel_Website/assets/82147067/e6e473fe-711d-4c94-a172-bed3b09fb230)

**Expected behavior**
mentioned above.
**Screenshots (Mandatory)**
![image](https://github.com/apu52/Travel_Website/assets/82147067/ee9b09f5-8224-438c-89ff-905547fdb874)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

**Comment by HritikaPh** [comment]
Please assign this to me @apu52  under gssoc.

**Comment by apu52** [comment]
@divyalaldinani I have assigned u .but at first please try to complete the previously assigned issues.

**Comment by Meghana-n10** [comment]
Please assign me this issue. I really want to start my first contribution under ggsoc.
