### ISSUE TITLE
Dynamic Display of Local Events on "View Local Events" Button Click

### ISSUE THREAD

**Issue by coderiksenthil** [apu52/Travel_Website#770]
**Is your feature request related to a problem? Please describe.**

Currently, there isn't a feature to display local events when users click on the "View Local Events" button. This limits users' ability to discover and engage with local events, potentially leading to a less engaging user experience.

**Describe the solution you'd like**

I would like to propose a feature where clicking on the "View Local Events" button triggers a display of local events relevant to the user's location or specified area. These events could include concerts, festivals, workshops, and other activities happening nearby.

**Additionally, the code is already prepared and ready for implementation, I kindly request to be assign me to the issue**

**Describe alternatives you've considered**

One alternative solution could be to manually list local events on a separate page or section of the website. However, this approach may require frequent updates and may not provide the most relevant or up-to-date information to users.

**Demo Video/Screenshot (Mandatory )**
View Local Event Button
![image](https://github.com/apu52/Travel_Website/assets/66522620/891f0363-9820-4e1e-80d3-d11498a33491)
After Clicking on the button 
![image](https://github.com/apu52/Travel_Website/assets/66522620/fbc244fd-8965-4bbe-a765-c00667ba560b)

***Are you contributing under any open-source program ?***

I am a part of GSSoC 2024

**Comment by apu52** [comment]
@coderiksenthil u are assigned. really good feature

**Comment by coderiksenthil** [comment]
Thank you, @apu52, for assigning me this task. I'm currently working on it, and I expect to have it completed within the next two days.

**Comment by coderiksenthil** [comment]
@apu52 Will soon raise a PR

**Comment by apu52** [comment]
> @apu52 Will soon raise a PR

yess. please try to submit your PR ASAP . As u are assigned over 1 month on this issue

**Comment by coderiksenthil** [comment]
Sure @apu52
