### ISSUE TITLE
Feature_Request: Custom cursor

### ISSUE THREAD

**Issue by chaanakyaaM** [apu52/Travel_Website#772]
**Is your feature request related to a problem? Please describe.**

The website looks awesome, but it can be even more attractive and professional if there is a custom cursor which syncs to the website design.

**Describe the solution you'd like**

I would like to add the custom cursor with not only syncs with the website design but also with the motion after cursor movement effect.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

***Are you contributing under any open-source program ?***

GSSOC'24

**Comment by apu52** [comment]
@chaanakyaaM u are assigned .Can you please share some SS/.png file like which type of design u want to add in the website?

**Comment by chaanakyaaM** [comment]
https://github.com/apu52/Travel_Website/assets/131477601/b87523ad-62d5-469c-8bfb-0580fa011be9

If you want i will remove the cursor, so it looks like the black dot is the cursor(as per your requirements).

**Comment by apu52** [comment]
> custom.cursor.mp4 
> If you want i will remove the cursor, so it looks like the black dot is the cursor(as per your requirements).

Don't make it a black , try to find other alternatives for the UI of custom cursor

**Comment by chaanakyaaM** [comment]
I think this color is good, this color also syncs with the blue bubble mouse trail effect

![image](https://github.com/apu52/Travel_Website/assets/131477601/a99c1108-ab43-490e-bc1e-0c0bdeb22adb)


Would you suggest any color?

**Comment by chaanakyaaM** [comment]
??

**Comment by techieadi4703** [comment]
@apu52 @chaanakyaaM can u please assign me to resolve this bug?
