### ISSUE TITLE
BUG  Page not responsive 

### ISSUE THREAD

**Issue by agastya3636** [apu52/Travel_Website#775]
**Describe the bug**

https://apu52.github.io/Travel_Website/dedicated-destinations/santorini-aegean-sea/start.html   page is not responsive

**Expected behavior**

it should be responsive

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/124435030/d7a98526-9a1e-4e1a-a72d-7628597a9259)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes under gssoc24

**Comment by apu52** [comment]
@agastya3636 u are assigned.

**Comment by Meghana-n10** [comment]
Can you please assign this to me under ggsoc level 1. PLEASE
