### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by AbheetHacker4278** [apu52/Travel_Website#777]
![Screenshot 2024-06-06 182941](https://github.com/apu52/Travel_Website/assets/114290748/9689b6e8-b927-4c00-865e-172c8353d10d)

This page is very simple and less attractive for users , I can do much better than this.

Can you please assign me this work?

**Comment by apu52** [comment]
@AbheetHacker4278 this is really good issue . But please try to raise the issues with the help of the Issue templates so that it will be more understandable .
Eagerly waiting for your new issues
