### ISSUE TITLE
Change of color  in welcome to tour guide from green to the matching color available in page.

### ISSUE THREAD

**Issue by somyagupta05** [apu52/Travel_Website#779]
![Screenshot 2024-06-06 205442](https://github.com/apu52/Travel_Website/assets/115712949/b497790e-063b-4227-b9e8-6148df2a2812)
pls assign me this issue.

**Comment by somyagupta05** [comment]
pls assign me the issue.

**Comment by apu52** [comment]
@somyagupta05 please try to raise issues with the help of the issue templates so that it will be more understandable
