### ISSUE TITLE
Feature_Request: Footer section enhancement

### ISSUE THREAD

**Issue by shreya-paul-17** [apu52/Travel_Website#780]
**Is your feature request related to a problem? Please describe.**
The links of the footer section is placed one after the other. I would like to fix this issue.

**Describe the solution you'd like**
I want the links to be placed sidewise like we normally see in the footers of other websites. In this way the footer section length can be reduced

**Describe alternatives you've considered**
N/A

**Demo Video/Screenshot (Mandatory )**
Current condition:
![travel-web](https://github.com/apu52/Travel_Website/assets/135226069/d5885ed2-285e-47d8-979f-c7a8ff74b1f1)

***Are you contributing under any open-source program ?***
Currently I'm contributing in GSSoC 2024

Kindly assign me this issue

**Comment by apu52** [comment]
@shreya-paul-17 this issue has already been solved
