### ISSUE TITLE
BUG: Total amount remains same irrespective of the package selected

### ISSUE THREAD

**Issue by techy4shri** [apu52/Travel_Website#781]
**Describe the bug**
The total amount for package purchase remains ₹14000 in the checkout, irrespective of the price of the selected package. This should not happen. 

**Expected behavior**
After selection of package and applying PROMO Code of 1000, the total should be displayed accordingly in the checkout by deducting the ₹1000 from the package price.

**Screenshots (Mandatory)**
![Screenshot 2024-06-06 210844](https://github.com/apu52/Travel_Website/assets/141991095/4a11499f-c52f-4d13-8f89-21aac314f428)
![Screenshot 2024-06-06 210857](https://github.com/apu52/Travel_Website/assets/141991095/f9084f93-31bf-408a-a876-415f597572a0)
![image](https://github.com/apu52/Travel_Website/assets/141991095/b2225815-2208-4651-896a-b8bbe8b185d2)

**Additional Context (Mandatory )**
The price is pre-selected and is not calculated as per the selected package, which needs to be changed.
***Are you contributing under any open-source program ?***
Yes, I am contributing under GSSoC 2024

**Comment by apu52** [comment]
@techy4shri u are assigned . Start working on the issue.
