### ISSUE TITLE
Fixing 404 error for Rate-Us Page

### ISSUE THREAD

**Issue by itssarvani394** [apu52/Travel_Website#782]
**Describe the bug**
Clicking on the 'Rate-Us' Page from the 2nd time redirects to a 404 Page, would like to fix that 

**Expected behavior**
I would like to fix it as to redirecting it to the 'Rate-Us' Page no matter how many times clicked

**Screenshots (Mandatory)**
![Screenshot 2024-06-06 214842](https://github.com/apu52/Travel_Website/assets/129776752/25331ce0-b3e6-4ecf-a03b-ee453e72d938)

***Are you contributing under any open-source program ?***
GSSoC

**Comment by apu52** [comment]
@itssarvani394 u are assigned.
