### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Hunteringsoul** [apu52/Travel_Website#783]
**Describe the bug**
1. There is allignment error in the code in the explore top dextinations section.
2. "Rate Us?" can be changed to "Rate Us"
3. Spacing between testimonials and Faqs can be done by using br tag.

**Expected behavior**
1.Allignment can be made to center to resolve this.
2. Simple editing can be done.
3. Insert <br>tag.

**Screenshots (Mandatory)**

![Screenshot 2024-06-06 225245](https://github.com/apu52/Travel_Website/assets/151203477/97cb40e2-b066-47ec-b843-a7bc665ff147)
![Screenshot 2024-06-06 225300](https://github.com/apu52/Travel_Website/assets/151203477/ac9033ea-e0df-4c81-9f11-9817a1636750)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
<YES GSSOC>

**Comment by Hunteringsoul** [comment]
I request u to assign this to me.

**Comment by apu52** [comment]
@Hunteringsoul this issue is already existing in the repo & already been assigned.

**Comment by Hunteringsoul** [comment]
I'm new to open source, sorry for the mistake.
I just wanted to know that I ll give the push request in the previous issue
I had raised?
