### ISSUE TITLE
The book now page under destination tab needs design change

### ISSUE THREAD

**Issue by Anshravicode89** [apu52/Travel_Website#785]
The book now page under destination tab needs design change. It feels basic and needs the design elements of the overall website. Please assign me this under GSSOC'24. I have experience in UI designing and CSS. Here is a screenshot of the following.
![image](https://github.com/apu52/Travel_Website/assets/166092579/3f697242-52f7-419c-9fa5-4bda14e6c3eb)

**Comment by apu52** [comment]
@Anshravicode89 please try to raise issues with the help of the issue templates properly so that it will be more understandable
