### ISSUE TITLE
Feature_Request: Adding an eye in the password field

### ISSUE THREAD

**Issue by pani2004** [apu52/Travel_Website#788]
I can add a eye in the password filed in the login page 
![Screenshot (54)](https://github.com/apu52/Travel_Website/assets/154724111/07147b7e-60cc-4926-a15e-82ddface20a5)

**Comment by pani2004** [comment]
@apu52 Can I work on this?

**Comment by apu52** [comment]
@pani2004 the total UI of the login page has already been changed .take a look at the new UI of the login page & then try to raise new issue on this topic using the proper issue templates.
