### ISSUE TITLE
BUG fixing css of home page in mobile view 

### ISSUE THREAD

**Issue by dhairyagothi** [apu52/Travel_Website#790]
**Describe the bug**

Css of home page in mobile view is not working properly 

**Expected behavior**

Making home page responsive 

**Screenshots (Mandatory)**

![Screenshot_20240607_162553.jpg](https://github.com/apu52/Travel_Website/assets/142989448/38b1eab5-e689-4b32-9e35-ffd4a556a7cb)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes gssoc and ssoc

**Comment by apu52** [comment]
@dhairyagothi u are assigned.
