### ISSUE TITLE
BUG: SyntaxError

### ISSUE THREAD

**Issue by patelkiran185** [apu52/Travel_Website#793]
**Describe the bug**

The error message "Uncaught SyntaxError:
 redeclaration of let activeSlide" indicates you're trying to declare a variable with the name activeSlide twice using the let keyword.

**Expected behavior**

check for re declaration.
**Screenshots (Mandatory)**

![Screenshot from 2024-06-07 18-53-33](https://github.com/apu52/Travel_Website/assets/138752385/35908b71-433c-4e98-aa6a-548bbc879723)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

I am contributing in GSSOC'24

**Comment by apu52** [comment]
@patelkiran185 u are assigned.
