### ISSUE TITLE
[Feature_Request] Adding instructions before checkout

### ISSUE THREAD

**Issue by avanimathur** [apu52/Travel_Website#794]
**Is your feature request related to a problem? Please describe.**
When a user clicks on 'Book Trip' , they are directly taken to the payment page.
If instructions are provided to the user, it would streamline the checkout process.

**Describe the solution you'd like**
In order to simplify the checkout process, we can provide proper instructions to the user.
The instructions include informing the user about 
i) The information needed
ii) available methods of payment
iii) shipping methods

**Demo Video/Screenshot (Mandatory )**
Before filling the details, we may add the instructions.

![Screenshot (252)](https://github.com/apu52/Travel_Website/assets/151984867/06b6a38c-165d-4778-983f-fb5a9076c3f3)

***Are you contributing under any open-source program ?***
This is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign it to me
Thanks.

**Comment by apu52** [comment]
@avanimathur u are assigned.
