### ISSUE TITLE
style: Feature_Request

### ISSUE THREAD

**Issue by divyansh-2005** [apu52/Travel_Website#795]
**Is your feature request related to a problem? Please describe.**

Background change of feedback page

**Describe the solution you'd like**

I will change the background of feedback page to a more travel related background

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/118552563/00584f13-649d-45a9-9434-34e076568ab0)

***Are you contributing under any open-source program ?***

Gssoc'24

**Comment by apu52** [comment]
@divyansh-2005 u are assigned.

**Comment by divyansh-2005** [comment]
pull request #804 closes this issue
