### ISSUE TITLE
BUG: Destination section 

### ISSUE THREAD

**Issue by Praneeth-2602** [apu52/Travel_Website#796]
**Describe the bug**

When using the carousel component, the background image is displayed twice, resulting in double images. This issue affects the visual presentation and user experience.

**Expected behavior**

Remove the extra image and add reveal on click animation to the info so that it enhances the user experience

**Screenshots (Mandatory)**

Before:

https://github.com/apu52/Travel_Website/assets/137754636/9433f4ba-0de0-4be2-9c03-b9369866063b

After:

https://github.com/apu52/Travel_Website/assets/137754636/f6172e04-4594-4459-a56e-60265519c6e8

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

I would like to work on this issue under GSSOC'24

**Comment by apu52** [comment]
@Praneeth-2602 u are assigned
