### ISSUE TITLE
Feature_Request : X can be added at feedback form

### ISSUE THREAD

**Issue by mehrun171** [apu52/Travel_Website#798]
**Is your feature request related to a problem? Please describe.**
Feedback form doesn't have the option of going back to the homepage or exiting the form

**Describe the solution you'd like**
Therefore a X button can be added in the feedback form to exit the feedback form if needed by the user as there may be scenarios where user do not want to give feedback at that moment...so X button will redirect him back to home page

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-06-04 190243](https://github.com/apu52/Travel_Website/assets/116735695/26dfa4b8-f053-4dbf-9282-36e49666662b)

***Are you contributing under any open-source program ?***

I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

**Comment by mehrun171** [comment]
Please assign me this task @apu52

**Comment by mehrun171** [comment]
please respond @apu52

**Comment by apu52** [comment]
@mehrun171 u are assigned.

**Comment by mehrun171** [comment]
Ok vl update once i complete the task
