### ISSUE TITLE
Edit footer section

### ISSUE THREAD

**Issue by madhurima316** [apu52/Travel_Website#8]
I would like to add pointer cursor and hover effects to footer_col headings and would remove the hover effect of the description under Tourguide .
Please assign me this issue.

**Comment by DarshSohaliya** [comment]
I would like to work on this  
issue

**Comment by apu52** [comment]
@madhurima316 @DarshSohaliya Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
