### ISSUE TITLE
Feature_Request : Checkout page for tour packages

### ISSUE THREAD

**Issue by PranavBarthwal** [apu52/Travel_Website#80]
**Is your feature request related to a problem? Please describe.**

the book now button of the destination card are not linked to any checkout page.

**Describe the solution you'd like**

I would like to build a dummy checkout page (non functional, as of now), which will be linked to the book now button.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
inspiration
![Screenshot 2024-01-18 150145](https://github.com/apu52/Travel_Website/assets/110532770/4d34a661-61ed-41bc-8bba-5d950d60f1bd)

***Are you contributing under any open-source program ?***

JWoC'24

**Comment by apu52** [comment]
@PranavBarthwal Already someone else is assigned with the same issue (#65)
But , I am not closing this issue. you can work on this issue. If he fails to submit his PR , I will assign this issue to you.
Happy coding!!!!!!!

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal Already someone else is assigned with the same issue (#65) But , I am not closing this issue. you can work on this issue. If he fails to submit his PR , I will assign this issue to you. Happy coding!!!!!!!

@apu52  whats the status of issue #65 ? Is it still under progress or should I start working on it?

**Comment by apu52** [comment]
> > @PranavBarthwal Already someone else is assigned with the same issue (#65) But , I am not closing this issue. you can work on this issue. If he fails to submit his PR , I will assign this issue to you. Happy coding!!!!!!!
> 
> @apu52 whats the status of issue #65 ? Is it still under progress or should I start working on it?

He haven't submitted his PR but it hasn't crossed the timeline. I want to suggest you to please submit your assigned issue .

**Comment by apu52** [comment]
@PranavBarthwal you are assigned now. on this issue
