### ISSUE TITLE
BUG : Text Alignment in Page headings and Description 

### ISSUE THREAD

**Issue by yeolesanskruti** [apu52/Travel_Website#801]
**Describe the bug**
"About Us" Page heading and its description is aligned in the center while other pages have inappropriate alignment.

**Expected behavior**

There should be a proper center alignment of text for other pages heading as well.

**Screenshots (Mandatory)**
ABOUT US -
![Screenshot 2024-06-07 215911](https://github.com/apu52/Travel_Website/assets/129084275/30519eb7-e4ea-4420-9427-861458c2007a)

OTHERS -
![Screenshot 2024-06-07 215801](https://github.com/apu52/Travel_Website/assets/129084275/b5fd7f38-20cc-44c4-8e9b-17d65e4433de)
![Screenshot 2024-06-07 215818](https://github.com/apu52/Travel_Website/assets/129084275/ec730931-ce37-4713-9d1a-5619f33feb76)
![Screenshot 2024-06-07 215843](https://github.com/apu52/Travel_Website/assets/129084275/7b31921d-9372-4e1c-b9c7-6fc7b095a6eb)
![Screenshot 2024-06-07 215857](https://github.com/apu52/Travel_Website/assets/129084275/e5ee43b6-630b-4c59-8bde-baa3285bb96d)

**Additional Context (Mandatory )**
I want to align and make the website's alignment and view look nice.

***Are you contributing under any open-source program ?***

GSSoC'24

**Comment by apu52** [comment]
@yeolesanskruti u are assigned
