### ISSUE TITLE
BUG : login page is missing styling  

### ISSUE THREAD

**Issue by divyansh-2005** [apu52/Travel_Website#805]
**Describe the bug**

The login page has wrong css file path only html is visible

**Expected behavior**

The styling of the login page must be linked with html

**Screenshots (Mandatory)**

Before
![image](https://github.com/apu52/Travel_Website/assets/118552563/39af2d61-e92e-4b43-8c22-f923e2521404)

After: 
![image](https://github.com/apu52/Travel_Website/assets/118552563/fca0969a-c321-4783-add7-1a73cf332047)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

yes, GSSOC'24

**Comment by DiwareNamrata23** [comment]
@divyansh-2005    In newLogin.html on line no 269 the path for css is this <link rel="stylesheet" href="/login/login.css"> can you please corect it to <link rel="stylesheet" href="login/login.css"> . I don't know why this glitch has happened @apu52 so sorry for this🥲

**Comment by divyansh-2005** [comment]
@apu52 please assign me this issue.

**Comment by apu52** [comment]
@divyansh-2005 you are assigned

**Comment by apu52** [comment]
> @divyansh-2005 In newLogin.html on line no 269 the path for css is this can you please corect it to . I don't know why this glitch has happened @apu52 so sorry for this🥲

No matter @DiwareNamrata23 . Thanks for your contribution in the login page . There maybe some glitch in the file path name . @divyansh-2005 will fix it.

**Comment by Niku28-05-2004** [comment]
I would like to Work on this Project. Please assign it to me . I want work on Login page is missing styling

**Comment by divyansh-2005** [comment]
Issue is already solved.
With #821 pull request
