### ISSUE TITLE
[BUG]: Nav bar issue fix.

### ISSUE THREAD

**Issue by Ashutosh104** [apu52/Travel_Website#81]
**Describe the bug**
On hovering on the nav bar options like Destinations , pricing and Testimonials the other options gets pushed sideways.

**Expected behavior**
after hovering the other options should remain at the same place. 

**Screenshots (Mandatory)**
before hovering
![Screenshot 2024-01-18 190504](https://github.com/apu52/Travel_Website/assets/143163927/3d0b2f39-77ae-43c5-ad52-aca38855a00b)
after hovering
![Screenshot 2024-01-18 190520](https://github.com/apu52/Travel_Website/assets/143163927/87da697c-36f7-4108-9826-b777b1630617)

JWOC,2024.

**Comment by ramith-kulal** [comment]
i can work on this, can i get assigned

**Comment by ramith-kulal** [comment]
i want to work under jwoc,
do i have to wait untill i get assigned or can i just take up the issue

**Comment by apu52** [comment]
@Ashutosh104 You are assigned. You just have 1 day to complete this issue
