### ISSUE TITLE
BUG: Navbar in rate us page. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [apu52/Travel_Website#812]
**Describe the bug**
The navbar is differently aligned in the rate us page. Also the theme toggle button is not there. I wish to make those look same.

**Expected behavior**
I wish to make the navbar looks the same in all the pages. 

**Screenshots (Mandatory)**

in the normal page :

![Screenshot 2024-06-08 015051](https://github.com/apu52/Travel_Website/assets/123104247/35d18162-4af3-44be-97f7-fbc831b78194)

in the rate us page :

![Screenshot 2024-06-08 015100](https://github.com/apu52/Travel_Website/assets/123104247/90a81a01-1a1f-45c4-b25e-98cba5d46168)

***Are you contributing under any open-source program ?***

I am a GSSOC'24 contributor.

**Comment by apu52** [comment]
@ParnaRoyChowdhury777 u are assigned
