### ISSUE TITLE
Feature_Request : Automatic Movement of images 

### ISSUE THREAD

**Issue by namandude** [apu52/Travel_Website#814]
Hey !! I would like to add on one more feature in your already good looking website the images in the swiper should auto moves and stop  on hovering it add the next level addition on user experience 
![Screenshot 2024-06-08 021134](https://github.com/apu52/Travel_Website/assets/118013565/adf3b1ae-20b0-4ad3-b6e7-2b217b0c1957)
Tho images were there but user need to self move them to next one which is not ease, so i would like to add on automatic movement in some seconds in these images .

Please assign me this under Gssoc so that i can start working on it immediately.

**Comment by apu52** [comment]
@namandude I have assigned you .u can start working on it. But from next time please raise your issues using the issue templates which are already present in the repo
