### ISSUE TITLE
BUG : Open new tab on clicking on navbar links in rating section

### ISSUE THREAD

**Issue by namandude** [apu52/Travel_Website#815]
Hey I observed the bug in the rating section when i click on any other links in the navbar from the rating section it get opens up in the new tab which is so unease , i wanted to  fix it .

See there were many freshly new tabs were open rather than particular page i want :
![Screenshot 2024-06-08 021835](https://github.com/apu52/Travel_Website/assets/118013565/c5ecb107-f764-41b8-806c-b4143076072d)

It should stay up in  one page only and redirect to correct location .

Please assign this me under Gssoc  i want to resolve this issue  and help you out.

**Comment by satyabharathi19** [comment]
I would like to work on this issue.Please assign the task to me

**Comment by apu52** [comment]
@namandude please raise your issues using the issue templates which are already given in the "NEW ISSUE" section . Otherwise I can't assign u
