### ISSUE TITLE
Feature_Request : Add swiper and new destination 

### ISSUE THREAD

**Issue by namandude** [apu52/Travel_Website#816]
Hey while surfing the website i think there should be more places in the popular destination and there should be the automatic swiper added so that user themself dont need to swipe and saw it automatically swipes in few seconds which give website good appearance and user good experience .
![Screenshot 2024-06-08 021042](https://github.com/apu52/Travel_Website/assets/118013565/0bb3f8d5-7ffb-4765-be7b-f77c0c567c35)

Please assign this me under Gssoc  i would like to contribute in this . 
Thank You!!

**Comment by apu52** [comment]
@namandude please raise your issues using the issue templates which are already given in the "NEW ISSUE" section . Otherwise I can't assign u
