### ISSUE TITLE
BUG : Rating Page 

### ISSUE THREAD

**Issue by namandude** [apu52/Travel_Website#817]
Hey !! 
I feel the issue in the rating section there is bit of overlaping of stars and the background , also the color of the button are not so good it should be improved .
![Screenshot 2024-06-08 022609](https://github.com/apu52/Travel_Website/assets/118013565/1063f727-97cf-4cd7-98ef-effe5910d612)
I would to decrease the background opacity or changes the background to something good so that i looks more good and change the button also .

Please assign me this under Gssoc , i want to contribute in this .
Thank You!!

**Comment by apu52** [comment]
@namandude please raise your issues using the issue templates which are already given in the "NEW ISSUE" section . Otherwise I can't assign u

**Comment by apu52** [comment]
@namandude please don't raise multiple issues at a time . Otherwise it will violate the rules mentioned in the CONTRIBUTING.md file
