### ISSUE TITLE
Can improve the about section of this repo

### ISSUE THREAD

**Issue by bheemajayashreee** [apu52/Travel_Website#827]
There are a few grammatical and vocabulary errors that are to be fixed.
Here's the modified version.
Welcome 🌈

This repository has been officially accepted for GSSOC '24. 🌟 It contains my project on a travel website ✈️ using HTML and CSS. The project includes the landing page of a travel tour company website. If you have any frontend projects related to this, or if you can add new features to the project, you are welcome to contribute to this open-source repository.

If this is a proper issue to be raised, please assign this to me

**Comment by bheemajayashreee** [comment]
Please assign this issue to me!

**Comment by SohaFarhana** [comment]
Hi 
Can u assign this issue to me under GSSOC label

**Comment by apu52** [comment]
@bheemajayashreee  please raise your issues using the issue templates which are already given in the "NEW ISSUE" section . Otherwise I can't assign u
