### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by bheemajayashreee** [apu52/Travel_Website#828]
The feedback is getting submitted even if I am entering single character.

The feedback can never be of single character length.

![image](https://github.com/apu52/Travel_Website/assets/112753765/0d9949aa-141c-4b73-97e7-37e973b31751)

Contributing under GSSOC'2K24

I would like to solve this issue by modifying increasing the length of the input in feedback.

Please assign this issue to me.

**Comment by apu52** [comment]
@bheemajayashreee I am assigning you this time . But from next time please try to raise the issues with the help of the issue templates mentioned in "NEW ISSUE" section

**Comment by Nikhilkumar111** [comment]
Hello , Plz Assign to me this issue.
