### ISSUE TITLE
Alignment of destination section!!!!

### ISSUE THREAD

**Issue by Lifewithmuskan** [apu52/Travel_Website#83]
Describe the bug

So ,on the destination section  heading and its describing paragraph aligned in left. 

Expected behavior
But this destination section should aligned in the center.

Screenshots 

AFTER
<img width="643" alt="Screenshot 2024-01-18 200850" src="https://github.com/apu52/Travel_Website/assets/96696286/d5311fce-d8b0-4caf-a106-78e14e20fd27">
 
BEFORE
<img width="650" alt="image" src="https://github.com/apu52/Travel_Website/assets/96696286/ac18704a-685f-4b20-8145-ad2c7b11acdd">

JWOC,2024.

**Comment by vishal2005025** [comment]
Name : vishal malyan
I have read the issue and go through the code and i have some idea to solve the problem. 
I eagerly want to work on it . 
please assign it to me under jwoc'2024...

**Comment by vishal2005025** [comment]
Name : vishal malyan
I have read the issue and go through the code , I have an idea to solve the problem.
I eagerly want to work on it .
 please assign it to me under jwoc'2024...

**Comment by apu52** [comment]
@Lifewithmuskan Already someone is assigned with the same issue #70 .
Sorry to close this issue

**Comment by apu52** [comment]
> Name : vishal malyan I have read the issue and go through the code , I have an idea to solve the problem. I eagerly want to work on it . please assign it to me under jwoc'2024...

This issue is already present. You can make any other new issue on which you want to work on
