### ISSUE TITLE
Text not fully visible in membership page

### ISSUE THREAD

**Issue by ankiiitagupta** [apu52/Travel_Website#831]
**Describe the bug**
In membership page, the INR text is out of the box and is partly visible.

**Expected behavior**
This text must be inside the box and fully visible to the user. 

**Screenshots (Mandatory)**
![Screenshot 2024-06-08 205902](https://github.com/apu52/Travel_Website/assets/108889476/d65d56be-2d69-4558-bd31-40a8355fb851)

**Additional Context (Mandatory )**
I can place this text inside the box and make it fully visible to the user. Kindly, assign this issue to me under GSSOC'24.

***Are you contributing under any open-source program ?***
GSSOC'24

**Comment by apu52** [comment]
@ankiiitagupta u are assigned
