### ISSUE TITLE
BUG: Footer section improvement

### ISSUE THREAD

**Issue by Siddhipogakwar123** [apu52/Travel_Website#837]
**Describe the bug**
In the footer section, google image height is small and select language dropdown can be enhanced.

**Expected behavior**
Google image height can be increased and dropdown can be given few properties to look attractive.

**Screenshots (Mandatory)**
![Screenshot 2024-06-09 150107](https://github.com/apu52/Travel_Website/assets/159463193/9a9b4a9e-81f8-4ec2-9558-e69880f1b243)

**Additional Context (Mandatory )**
The google image in footer section should have a considerable height.

***Are you contributing under any open-source program ?***
gssoc 2024

**Comment by Siddhipogakwar123** [comment]
@apu52 sir please assign this issue to me under gssoc

**Comment by apu52** [comment]
@Siddhipogakwar123 u are assigned

**Comment by ssyy21** [comment]
@apu52 please assign me this task.

**Comment by apu52** [comment]
@ssyy21 I think this issue is not relevant now , this issue has now already been solved , so sorry to close this issue
