### ISSUE TITLE
BUG ["Navbar Resizing Issue"]

### ISSUE THREAD

**Issue by ramith-kulal** [apu52/Travel_Website#84]
**Describe the bug**

The navbar in the project allows users to resize, The expected behavior is that the navbar should not be resizable and should function as intended.

**Expected behavior**

The navbar should not be resizable and should function in a normal and expected manner.

**Screenshots (Mandatory)**

![Screenshot 2024-01-18 200725](https://github.com/apu52/Travel_Website/assets/142984776/d11ea480-22ef-4f9c-947d-bde366959b79)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

Contribution under JWoC'24

**Comment by apu52** [comment]
@ramith-kulal Now you are assigned. You can start working on this issue. You just have 1 day to submit your PR
