### ISSUE TITLE
Feature_Request

### ISSUE THREAD

**Issue by DaniaZehra** [apu52/Travel_Website#841]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![image](https://github.com/apu52/Travel_Website/assets/130988913/8225befa-b6ac-4563-89d4-6d85101d6760)

***Are you contributing under any open-source program ?***

Girls Script Summer of Code

**Comment by apu52** [comment]
@DaniaZehra I can't get any information from the issue .I am closing this issue as unplanned
