### ISSUE TITLE
[Feature_Request] : Replacing name with logo in the navbar

### ISSUE THREAD

**Issue by Gultreen** [apu52/Travel_Website#844]
I will add logo option for the website "Tourguide".

The Logo i have made for the website is -

![tourguidelogo](https://github.com/apu52/Travel_Website/assets/145576858/62d21843-e9ed-49e9-a68d-1b97c9eea1cb)

Kindly **_@apu52_**  assign me this task under GSSoC Contributor'24.

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by apu52** [comment]
@Gultreen I am assigning you this time . But from next time please try to raise the issues with the help of the issue templates mentioned in "NEW ISSUE" section
