### ISSUE TITLE
Uneven card size

### ISSUE THREAD

**Issue by root-0101** [apu52/Travel_Website#846]
The size of the cards under "Trip gallery" section are not same

![Screenshot 2024-06-10 161132](https://github.com/apu52/Travel_Website/assets/142779809/d5e4bbeb-edc6-4360-ad8d-38896785667e)

**Comment by Picodes10** [comment]
Hi, I want to be assigned this issue.

**Comment by Pavitra2128** [comment]
hi, I want to be assigned to this issue

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by apu52** [comment]
@root-0101  I can't get any information from the issue .I am closing this issue as unplanned. please try to raise the issues with the help of the issue templates mentioned in "NEW ISSUE" section
