### ISSUE TITLE
Feature_Request : Enhancing our trip gallery page

### ISSUE THREAD

**Issue by DiwareNamrata23** [apu52/Travel_Website#847]
**Is your feature request related to a problem? Please describe.**

this page styling can be enhanced to completely good styling using different animations

**Describe the solution you'd like**

good styling
**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
<img width="377" alt="Screenshot 2024-06-10 at 6 27 46 PM" src="https://github.com/apu52/Travel_Website/assets/142529986/de070145-ef46-43d3-a7dd-6e23430cd1ec">

***Are you contributing under any open-source program ?***

Gssoc'24

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by helloanisha19** [comment]
I'm interested to improve the alignment of this page and enhance its style. I request @apu52 sir , kindly assign this issue to me.

**Comment by apu52** [comment]
@DiwareNamrata23 I have assigned you .but Can u please give me some glimpse of the animations u want to add

**Comment by DiwareNamrata23** [comment]
Yes . For heading I will add aos so that it could slight right in a ease manner , next thing I will try to design  the paragraph  in more clean way ofcourse the width I will try to increase of paragraph and heading . Can you also suggest me the changes which I should do ?

**Comment by apu52** [comment]
> Yes . For heading I will add aos so that it could slight right in a ease manner , next thing I will try to design the paragraph in more clean way ofcourse the width I will try to increase of paragraph and heading . Can you also suggest me the changes which I should do ?

no these changes are enough
