### ISSUE TITLE
Enhancing  the checkin/checkout page

### ISSUE THREAD

**Issue by AlapanSen** [apu52/Travel_Website#848]
The check-in ,check-out page can be enhanced to improve the user experience.

Heres a rough idea of the changes i want to make->
a)Image Gallery
b)flight,train and bus buttons(The icons are only displaying text,no visible images)
c)check-in and check-out box

A demo of the change i want in the image element
![Screenshot 2024-06-10 213854](https://github.com/apu52/Travel_Website/assets/94228448/2aa56095-b95d-4893-9ae4-91806a0d4e71)

the changes visible are
a)image gallery
b)check-in and check-out buttons

###Are you contributing under any open-source program ?
Yes, I am contributing under GSSoC 2024

**Comment by apu52** [comment]
@AlapanSen I have assigned u .But from next time please use the Issue templates to raise the issues
