### ISSUE TITLE
BUG: 'Contact Us' Link Issues in Footer and Header section!

### ISSUE THREAD

**Issue by Samridhi002** [apu52/Travel_Website#850]
# Describe the bug

There are two issues with the navigation links on the website:

The "Contact Us" link in the footer section of Package page is not navigating to the appropriate section on the home Page.
The "Contact Us" link in the header on the feedback page is not navigating to the correct section on the home page.

Additionally, the phone number and email address in the footer of Package page should be clickable links that open the default email client and calling app, respectively.

# Steps to Reproduce

1. Open the website.
2. Scroll down to the footer section of Package Page.
3. Click on the "Contact Us" link.
4. Observe that it does not navigate to the contact section on the home tab.
5. Try clicking on the phone number and email address.

# Expected Behavior

- The "Contact Us" link in the footer of Package Page should navigate to the appropriate contact section on the home tab.
-  The "Contact Us" link in the header of Feedback Page should navigate to the appropriate contact section on the home tab.
- The phone number should be a clickable link that opens the default calling app.
- The email address should be a clickable link that opens the default email client.

# Attachments
 _**(Package Page)**_

![Screenshot (48)](https://github.com/apu52/Travel_Website/assets/169380578/2265fefe-d1a2-4d8d-a137-5c9aaf9c07ab)

_**(Feedback Page)**_

![Screenshot (49)](https://github.com/apu52/Travel_Website/assets/169380578/dcab792c-3909-4184-8f2a-2bbbe2903345)

***Are you contributing under any open-source program ?***

GSSoC'24

@apu52 
Please assign me this issue. Thank You!

**Comment by basundhara-070** [comment]
Please assign me this issue.

**Comment by apu52** [comment]
@Samridhi002 u are assigned
