### ISSUE TITLE
BUG:  Poor image of google at translate

### ISSUE THREAD

**Issue by GAVINESHWAR** [apu52/Travel_Website#851]
**Describe the bug**
**issue : #851**

**The google image was very thin and unable to view clearly , padding of elements  can be updated better**

**Expected behavior**

**The size of the google image can be changed as per website , the distance between the below and above should updated to view clearly , the drop down menu can be added border to look clear**

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/124431955/079a7f0c-0813-4006-9a34-1b8a9f1f3bf1)

**Additional Context (Mandatory )**
Assign me this issue @apu52   to work over it 

***Are you contributing under any open-source program ?***

I am contributing under the GSSOC24
I am following all the terms and conditions of the GSSOC and Projects

**Comment by basundhara-070** [comment]
Please assign me this issue.

**Comment by apu52** [comment]
@GAVINESHWAR this issue has already been assigned & already existing in this repo .So I am closing this issue.
