### ISSUE TITLE
Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [apu52/Travel_Website#853]
**Is your feature request related to a problem? Please describe.**

The current website does not display the number of visitors it has received, which could be useful for tracking engagement and performance metrics.

**Describe the solution you'd like**

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

**Describe alternatives you've considered**

An alternative could be using a third-party service like Google Analytics for more detailed visitor statistics, but it does not provide a simple, on-page visitor count.

**Demo Video/Screenshot (Mandatory )**
Preview of proposed Website Visitor widget:

![Screenshot 2024-06-12 143634](https://github.com/apu52/Travel_Website/assets/113301503/dbb3e2d4-361c-407b-8a60-f2e59ef4caa0)

***Are you contributing under any open-source program ?***

**Please assign this issue to me under the gssoc label**

**Comment by apu52** [comment]
@rohitinu6 u are assigned
