### ISSUE TITLE
Feature_Request: improve about us page

### ISSUE THREAD

**Issue by Prakrati1907** [apu52/Travel_Website#857]
enhancing about us page by making it more readable and attractive.
@apu52 
![Screenshot 2024-06-12 230238](https://github.com/apu52/Travel_Website/assets/120261907/5f8bc99f-6e37-48d0-8db4-a51a8153c4e2)
please assign this issue to me.

**Comment by apu52** [comment]
@Prakrati1907 I can't get any information from the issue .I am closing this issue as unplanned. Please try to raise issues using the ISSUE templates in the "NEW ISSUE" section

**Comment by shambhavipathak24** [comment]
I would like to improve about page by making more interactive to user. Please assign this to me @apu52.
