### ISSUE TITLE
Feature_Request : Interactive Drifting Bubbles

### ISSUE THREAD

**Issue by piyansusahoo** [apu52/Travel_Website#858]
**Is your feature request related to a problem? Please describe.**
The bubbles in the screen are somewhat obstructive towards the content a user is interested in or the target button the user is going for. The user might find this unsettling.

**Describe the solution you'd like**
Interactive Drifting Bubbles. The bubbles on the screen will drift away when the cursor is brought close to them. Upon clicking, the bubbles will move farther away from the point of the click in a faster way.

Purpose:
•	Enhances User Engagement: Captures attention and encourages exploration.
•	Improves User Experience: Dynamic, playful, and intuitive design.
•	Visual Appeal: Makes the website more attractive and memorable.
•	Guides Navigation: Subtly directs users to key content.
•	Differentiates Website: Unique feature that stands out from competitors.
•	Showcases Technical Skills: Demonstrates our proficiency and creativity.
•	Modern Design: Aligns with current web design trends, reinforcing brand identity.

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/130382676/e56a5ef5-fa0f-4f69-88a3-ba00e903bff4

**Bubbles will be moving** in the actual implementation this is just a demo on how the bubbles will drift away upon interaction with the cursor.

***Are you contributing under any open-source program ?***
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

@viki2211 Is also contributing to this issue so please assign her as well.

**Comment by piyansusahoo** [comment]
@itsekta Can you please tag the level of the mentioned issue?

**Comment by vaishnavi-jais** [comment]
It seems our bubbles are having a bit of a party—unfortunately, they’re crashing the content and target buttons that users are trying to focus on! These lively bubbles might be causing some unintentional distractions and making the experience less enjoyable.

I’m eager to step in and adjust these bubbles so they add to the user experience without overshadowing the important elements. Could you please assign me this task for GSoC '24? I’m ready to help refine our design and ensure our content gets the spotlight it deserves!

Thanks for considering my request!

**Comment by apu52** [comment]
> It seems our bubbles are having a bit of a party—unfortunately, they’re crashing the content and target buttons that users are trying to focus on! These lively bubbles might be causing some unintentional distractions and making the experience less enjoyable.
> 
> I’m eager to step in and adjust these bubbles so they add to the user experience without overshadowing the important elements. Could you please assign me this task for GSoC '24? I’m ready to help refine our design and ensure our content gets the spotlight it deserves!
> 
> Thanks for considering my request!

Actually the website does not include the bubble effect now , so it's not necessary now.
