### ISSUE TITLE
Email text modification

### ISSUE THREAD

**Issue by Shashanktriathi1703** [apu52/Travel_Website#859]
# Problem
### * The email text is not properly positioned like other text.
![image](https://github.com/apu52/Travel_Website/assets/105815482/7cf7eea8-5f01-4b35-99c9-6e2d33b3c0fc)
### * I marked the problem with a green marker.

- [X] I am contributing to an open-source program in **`GSSOC'24`**.

**Comment by Salma-Mamdoh** [comment]
@Shashanktriathi1703 please assign this issue to me under gssoc

**Comment by apu52** [comment]
@Shashanktriathi1703 I have assigned u this time .But please from next time try to raise the issues using the issue templates in the "NEW ISSUE" section
