### ISSUE TITLE
BUG: The Divs in the FAQ Section getting flickering due to improper hover effect and sizing

### ISSUE THREAD

**Issue by SumithThota** [apu52/Travel_Website#861]
**Describe the bug**

BUG: The Divs in the FAQ Section getting flickering due to improper hover effect.
when a client mouse over on the divs at Frequently Asked Questions Section are getting flickering due to improper sizing of divs and hovering. 
Let me Fix this issue as a gssoc24 contributor

**Expected behavior**
The hover should be there but there should not be any overlapping with other divs(flickering should be removed)

**Screenshots (Mandatory)**
This issue is present with all the three div in these section
![Screenshot 2024-06-13 160107](https://github.com/apu52/Travel_Website/assets/108344062/b12e0fae-b40c-4fda-94e1-d3da3c5f8e77)

Watch this Video for more info:

https://github.com/apu52/Travel_Website/assets/108344062/30d51f25-957b-4769-8794-a819bf3e2a13

**Comment by basundhara-070** [comment]
Please assign me this issue.

**Comment by apu52** [comment]
@SumithThota I have assigned u but under which contribution programme u are contributing?? GSSOC/VSOC

**Comment by SumithThota** [comment]
Hi @apu52, I am GSSOC contributor

**Comment by itsekta** [comment]
Hey @SumithThota, are you still working on this?

**Comment by SumithThota** [comment]
yes @itsekta I am in

**Comment by SumithThota** [comment]
@apu52 I have fixed this issue #934 
Please check it once and add apprpriate labels to it
