### ISSUE TITLE
Feature_Request : Adding CSS for Login and Sign Up page

### ISSUE THREAD

**Issue by GAVINESHWAR** [apu52/Travel_Website#866]
**Is your feature request related to a problem? Please describe.**

When Login or signUp page clicks  login page appear with no CSS I would like to add attractive css for the login and sign up page.

**Describe the solution you'd like**

I will add attractive css for the register and sign up page make the page attractive and user friendly , i thought leaving it as it is not recommend , so I would like to work on it 

**Describe alternatives you've considered**

**Demo Video/Screenshot (Mandatory )**
![Screenshot 2024-06-15 092015](https://github.com/apu52/Travel_Website/assets/124431955/2da0ad60-e931-4c27-a468-6112abd2c579)
Here there is no styles were added to the page

***Are you contributing under any open-source program ?***

I am Contributing Under the GSSOC 24 

Assign me this issue @apu52  to make contribution this project sir 
Thank you

**Comment by Kish-an-gupta** [comment]
I want to work on this for improving CSS properties of login page making it more better. 
I am working under GSSOC  2024 . Allow me to do this work. Right now no almost none CSS properties used and i can use them to make the page look better and attractive.

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by Kish-an-gupta** [comment]
@Riyasharma1311   are you contributing or contributed on any other project also?

**Comment by Riyasharma1311** [comment]
No, I am not.

**Comment by basundhara-070** [comment]
Please assign me this issue.

**Comment by narmadhajs** [comment]
I can help to enhance the look with css..kindly assign me this issue

**Comment by BhavithaReddyy** [comment]
@apu52 I want to work on this issue, kindly assign this issue.

**Comment by apu52** [comment]
@GAVINESHWAR this issue has already been solved. Sorry to close this issue
