### ISSUE TITLE
[Feature Request]: Mobile view of the app

### ISSUE THREAD

**Issue by Shivani756** [apu52/Travel_Website#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the website is only supported in the pc view on minimizing the screen the half part of the website becomes hidden 

### Use Case

on addition of this feature the website will adjust itself according to the height and width of the device making it user compatible

### Benefits

will allow users to use the website on any kinds of devices

### Add ScreenShots

_![Screenshot_2024-06-16-10-09-55-645_com.android.chrome.jpg](https://github.com/apu52/Travel_Website/assets/139329176/a92fdd1c-c7f6-4e26-a6b2-74bd990f5666)

the website doesn't aligned itself with the device's dimensions..after this feature it will be able to do so

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by litesh1123** [comment]
@Shivani756 can we collab in it , @apu52  please assign this issue to both of us

**Comment by Shivani756** [comment]
@apu52 
we @Shivani756 and @litesh1123 would like to collaborate.Please assigned this issue to both of us

**Comment by apu52** [comment]
@Shivani756 @litesh1123 I have assigned u both .Please use co-authored so that u both will get points for this pR

**Comment by litesh1123** [comment]
@apu52 thank you for assigning
