### ISSUE TITLE
Add Favicon to the login page 

### ISSUE THREAD

**Issue by CoderGirl2844** [apu52/Travel_Website#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of Favicon to the login/sign-up Page

### Use Case

Favicon would enhance the look of website

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@CoderGirl2844 u are assigned

**Comment by CoderGirl2844** [comment]
@apu52 please add the level label

**Comment by apu52** [comment]
> @apu52 please add the level label

I will add the label after the review of the PR

**Comment by CoderGirl2844** [comment]
created a new pull request as suggest..please merge it now @apu52

**Comment by apu52** [comment]
> created a new pull request as suggested . please merge it now @apu52

I have to close your repo as it has so may commits around it , please try to make a complete new PR pushing only your changes there & after updating your branch
