### ISSUE TITLE
[Bug]: View button in Nav bar

### ISSUE THREAD

**Issue by CoderGirl2844** [apu52/Travel_Website#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

on clicking the View button in nav bar it shows a blank white screen

### Expected behavior

we can it with google maps like it is done in the footer section

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by CoderGirl2844** [comment]
https://github.com/apu52/Travel_Website/assets/155231566/83f32516-b402-4e40-be34-f9406b7953fd

we can link this page to google maps

**Comment by apu52** [comment]
@CoderGirl2844 I have already assigned u a previous issue .please try to complete that issue at first .then After completing the previous PR ping me in this issue .then I will assign u

**Comment by CoderGirl2844** [comment]
@apu52 I have solved the previous issue please assign me this issue

**Comment by apu52** [comment]
> @apu52 I have solved the previous issue please assign me this issue

Actually the VIEW button already have codes which need credits to activate it . I will try to work on it after the completion of this programme. So I think this Issue has no need . But u can still make new issues on which u want to work on
