### ISSUE TITLE
[Feature Request]: Keyboard Arrow Key Control for Image Slideshow

### ISSUE THREAD

**Issue by KartikLutimath** [apu52/Travel_Website#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature enables users to navigate through the image gallery using the left and right arrow keys on their keyboard. 
In addition to clicking the **Prev** and **Next** buttons, users can now use the arrow keys for a more seamless browsing experience.

### Use Case

A user can now navigate through the image gallery using the left and right arrow keys, providing a more seamless and accessible browsing experience.

### Benefits

- This feature improves accessibility by enabling users with mobility impairments to navigate the gallery using the keyboard. 
- It also enhances the overall user experience by providing a more intuitive and efficient way to browse images.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@KartikLutimath are u contribution under GSSOC'24 or VSOC'24 , I can't assign you points under both of the competitions so choose wisely.
