### ISSUE TITLE
Can Make Login and Sign Up Page More Attractive and Appealing

### ISSUE THREAD

**Issue by AkshatPandey-2004** [apu52/Travel_Website#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I Can Add Flip Card Animation in Login and SignUp Page and i can add cool image Transistion.

### Use Case

Make it Look More Appealing and Attractive

### Add ScreenShots

![kokok](https://github.com/apu52/Travel_Website/assets/114497044/cee60b5b-d08c-43d7-9eb6-f4b2b73d8754)
I Can Make it your login page look like it

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by rohir1132yadav** [comment]
i want to work on this project . please assign me.

**Comment by apu52** [comment]
@AkshatPandey-2004 u are assigned .Start working on this issue.
