### ISSUE TITLE
[Feature Request]: Fixing of the chatbot

### ISSUE THREAD

**Issue by Broken-Kaddu** [apu52/Travel_Website#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The chatbot is unresponsive, along with that it has the chatbase.io watermark, also it takes a text prompt as input at the start Also the chatbot is not working on custom text input prompts, can fix that.

### Use Case

The chatbot is unresponsive, along with that it has the chatbase.io watermark, also it takes a text prompt as input at the start we can fix it by giving user multiple choice options to choose from and then take custom text inputs, like what do you want to chat about and then provide the user with options which would then continue furthur etc. Also the chatbot is not working on custom text input prompts, can fix that.

### Benefits

Users will have more friendly and easy experience with the chatbot which would in turn help them to understand along with that they would be able to have options on the chat bot such that it would help them interact with the website well and they would have a more customized experience on the website, also for customer support and hospitality

### Add ScreenShots

![chatbot_travel](https://github.com/apu52/Travel_Website/assets/166910220/4f41cfee-dfa1-4ad5-9012-ecfc97d26d87)
![chatbot_travel_website](https://github.com/apu52/Travel_Website/assets/166910220/85cb6bc0-8bb5-46d0-9bcc-1645d320ddfa)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Broken-Kaddu are u still working on this issue?? As it already been over a week that u are assigned .please try to submit your issue ASAP

**Comment by apu52** [comment]
@Broken-Kaddu as the VSOC programme is over , I am closing this issue
