### ISSUE TITLE
The navigation bar and login/sign up page layout [Bug]: 

### ISSUE THREAD

**Issue by yashvisharma1204** [apu52/Travel_Website#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. The navigation bar looks too much and compacted
2. The layout and UI of of login is lacking
3. Not responsible website

### Expected behavior

1.  The navigation bar would look smoothless and seemless and not compacted
2. The website will responsible
3. Login page will look better

### On which device are you experiencing this bug?

Android, iPhone, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@yashvisharma1204 u are assigned

**Comment by apu52** [comment]
@yashvisharma1204 are u still working on this issue?? As it already been over a week that u are assigned .please try to submit your issue ASAP
