### ISSUE TITLE
[Feature Request]: improving UI of  trip planner page

### ISSUE THREAD

**Issue by techinaina** [apu52/Travel_Website#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The trip planner page is very simple and less attractive so i will enhance its UI  to make it look more user friendly and attractive

### Use Case

it will make the trip planner page look more attractive to the user and they will find it easy to use 

### Benefits

the project will look more attractive to users 

### Add ScreenShots

![image](https://github.com/apu52/Travel_Website/assets/143960485/65e8f657-c2da-4f87-bd94-f6cd9dfc4282)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@techinaina u are assigned
