### ISSUE TITLE
[Feature Request]: Adding social  media links in the footer

### ISSUE THREAD

**Issue by Saipradyumnagoud** [apu52/Travel_Website#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer there are no social media links 

### Use Case

When the user try to contact owner they dont see the quick links 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
PR #893, will fix this issue
