### ISSUE TITLE
[Bug]: Improve the login/signup page.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Current login/signup page do not have proper styling and no proper alignment, due to which the page is not much attractive.

### Expected behavior

Assign this task to me and I can add styling on this page to make it attractive.

### Add ScreenShots

![Screenshot (498)](https://github.com/apu52/Travel_Website/assets/143121854/058f0ddb-1a07-4337-8026-da040495f338)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by itsekta** [comment]
Hey @meetarora10, can you please checkout the page again cause I am seeing a proper page with a good UI


![image](https://github.com/apu52/Travel_Website/assets/60789158/8807d189-1047-45ec-b0e6-38fa19842de8)

**Comment by meetarora10** [comment]
Yes thank you for commenting @itsekta
