### ISSUE TITLE
New feature: Add a Trip Photo Gallary to the Travel Website and Connect the page to "View All" button

### ISSUE THREAD

**Issue by zul132** [apu52/Travel_Website#9]
I would like to make the Travel Website more informative and engaging by adding a Beautiful new Photo Gallary page linked to the "View All" button on the landing page:
![issue1_photo_gallary](https://github.com/apu52/Travel_Website/assets/98112914/1c4a91c3-0b75-48aa-be8f-e8467975c48f)

Objective of this Issue:
I belive that providing a beautiful and diverse Gallary of Trip photos would significantly enhance the User experience and inspire Potential holiday goers to book a vacation to any suitable destination and also help users decide the right destination for their next trip.

Proposed Changes:
I propose adding a new HTML page to the project folder which could be accessed from the Landing page via the "View All" button. This page would contain a Navbar similar to the one in the landing page (or even the same one) along with the same footer. For the gallary I would use cards to display vibrant photos from various trips to different parts of the world. Care should be taken to ensure that selection of Trip photos is diverse and reflects the Website's theme of finding one's Perfect Getaway and Discovering the World's Best Kept Secrets.
It would also be good if the set of photos are changes routinely as it would keep the webpage Fresh and Interesting.

**Comment by apu52** [comment]
@zul132 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts
