### ISSUE TITLE
Improve the layout the Testimonials

### ISSUE THREAD

**Issue by Shu12388y** [apu52/Travel_Website#90]
**Describe the bug**

The testimonials section design can be improve

**Expected behavior**

**Screenshots (Mandatory)**

![Screenshot (127)](https://github.com/apu52/Travel_Website/assets/91714143/4d3c9bfb-8a8a-49c6-97bc-01495ed3e5b3)

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***

JWOC

**Comment by apu52** [comment]
How can you improve it?? 
Can you give some points @Shu12388y

**Comment by Shu12388y** [comment]
@apu52  the image for stretch for x axis by add right image size it will be perfect

**Comment by apu52** [comment]
@Shu12388y Just make the testimonial section more stylized with the repo
Now You are assigned . you can start working on this issue

**Comment by antilneeraj** [comment]
@apu52 As the assignee passed the 4 day limit and hasn't pushed any Pull Request. 
Can you assign this issue to me under JWOC.

I'll make the testimonials look more stylized
(reference)
![image](https://github.com/apu52/Travel_Website/assets/98269887/9786b5e3-0f31-4425-821b-a3c1a8b088d5)

**Comment by apu52** [comment]
@Shu12388y This issue has already crossed the deadline. So Sorry to unassigning you

**Comment by apu52** [comment]
@antilneeraj Thank you for your concern. you are assigned now. You have to submit your PR within 2-3 days
