### ISSUE TITLE
[Bug]:  Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [apu52/Travel_Website#902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- In this project cannot proper `Responsive`.

[Screencast from 2024-06-25 08-31-18.webm](https://github.com/apu52/Travel_Website/assets/121082414/f5979c59-1aa8-4bda-a4e6-0bf735c31064)

### Expected behavior

- 

### Add ScreenShots

- 

### On which device are you experiencing this bug?

Linux, Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by dewang002** [comment]
Are you still working on this issue?

**Comment by dewang002** [comment]
if yes I would like to help.

**Comment by sivaprasath2004** [comment]
@dewang002 , I will fix that Issue
