### ISSUE TITLE
[Bug]: Footer Section alignment issue

### ISSUE THREAD

**Issue by TBorundia** [apu52/Travel_Website#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Elements of footer section are not aligned properly.
Social Media icons are overlapping.
Twitter's old logo has been displayed.
Contact details is displaying in multiple line, that the number must be in 1 line.

### Expected behavior

Enhancement in footer section in required.

### Add ScreenShots

![image](https://github.com/apu52/Travel_Website/assets/168854094/fc0809d6-44e5-46c1-82da-00ccc35b826a)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by TBorundia** [comment]
@apu52 @itsekta , please assign this issue to me under GSSoC'24.
Thank You!

**Comment by Aryan681** [comment]
Hey ! have solved the issue , plz review and merge my PR ..

**Comment by apu52** [comment]
> Hey ! @apu52 @itsekta , i have solved the issue , plz review and merge my PR ..

@Aryan681 I want to inform u that u are not assigned in this issue . First raise an issue properly , then after only when u get assigned , u can submit your PR . I am closing your PR
