### ISSUE TITLE
[Feature Request]: Improve the FAQ page

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The faq now is not well alligned and has irregular size issue

### Use Case

Very important part of a travel website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sau-mili** [comment]
@apu52 please assign me this

**Comment by mrunal1309** [comment]
@apu52 Can you please assign me this issue ?
