### ISSUE TITLE
Feature_Request : Add Customized Scrollbar to Website

### ISSUE THREAD

**Issue by ramith-kulal** [apu52/Travel_Website#91]
**Is your feature request related to a problem? Please describe.**

The current scrollbar on our website is basic and doesn't align with the overall design aesthetic of the website.
**Describe the solution you'd like**

I would like to request the addition of a customized scrollbar for our website. The ideal scrollbar should be visually appealing.

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/142984776/6678de51-579f-45a1-bb64-440be313acbd

***Are you contributing under any open-source program ?***

**Working under JWoC'24**

**Comment by apu52** [comment]
@ramith-kulal I have assigned you . Made the color gradients of the scrollbar with the similarity of the webpage
