### ISSUE TITLE
[Bug]: On click pf the hamburger icon on the Rate Us page nothing happens.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On clicking of the hamburger icon on the navbar of the rate us page, no action takes place.

### Expected behavior

Assign this task to me and I can fix this issue.

### Add ScreenShots

![Screenshot (536)](https://github.com/apu52/Travel_Website/assets/143121854/8220930f-b128-4a3d-991d-2fb4d65b22cf)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 I have already assigned u an issue .please try to complete that issue at first & then ping me here or the mentors so that we will assign u this issue.

**Comment by meetarora10** [comment]
@apu52 okay thanku

**Comment by meetarora10** [comment]
@apu52 now you can assign me this issue.

**Comment by meetarora10** [comment]
Hi @apu52  assign me this issue.

**Comment by apu52** [comment]
@meetarora10 u are assigned
