### ISSUE TITLE
[Feature Request]: Trip Gallery Changes

### ISSUE THREAD

**Issue by AbheetHacker4278** [apu52/Travel_Website#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add ScreenShots

![Screenshot 2024-06-27 230043](https://github.com/apu52/Travel_Website/assets/114290748/53acc9a0-1a6a-40c5-bc75-b674ecd1cb8e)

@apu52 please assign this to me under GSSOC24

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by AbheetHacker4278** [comment]
@itsekta  please assign to me

**Comment by apu52** [comment]
@AbheetHacker4278 u are assigned
