### ISSUE TITLE
Remove the bubbles animation from the landing page[Bug]: 

### ISSUE THREAD

**Issue by itsekta** [apu52/Travel_Website#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The **bubbles** on the landing page are not good for user experience. Remove these and keep it in separate file if needed can be added later to another section

![image](https://github.com/apu52/Travel_Website/assets/60789158/c482cb47-2d7a-43b5-9f24-3ebbadbe2dee)

### Expected behavior

The landing page will look more nice without these bubble animations.

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Aryan681** [comment]
hey @itsekta , can u assign me this issue..?

**Comment by Aryan681** [comment]
hey @itsekta ,I have a question, can u tell how I can live the site locally on my machine.

**Comment by itsekta** [comment]
You can check it on locally, there is no need to make it live

**Comment by Aryan681** [comment]
Hey! @apu52  @itsekta ,I have fixed the issue review my PR #932 and merge it .

**Comment by Aryan681** [comment]
Hey @apu52  , i am waiting ...

**Comment by apu52** [comment]
@Aryan681 please wait I will review it very soon

**Comment by techieadi4703** [comment]
hey @apu52  @itsekta can u please assign me to resolve this issue?

**Comment by Vibhuti270** [comment]
Please assign this issue to me.

**Comment by Aryan681** [comment]
Hey @apu52 @itsekta , it's been 2 days...

**Comment by itsekta** [comment]
Hello @Aryan681, please be patience your branch will be merged.

**Comment by itsekta** [comment]
Fixed in #932
