### ISSUE TITLE
[Bug]: The blue line on the right of website doesn't look good

### ISSUE THREAD

**Issue by techieadi4703** [apu52/Travel_Website#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the blue gradient line on the right side of the website does not really looks good. If that is removed the website will become more attractive.

### Expected behavior

I only want to remove that line, only this will enhance the beauty of the website.

### Add ScreenShots

![image](https://github.com/apu52/Travel_Website/assets/154405757/0dcd17fb-f9e2-43aa-ad4c-6c79548fa8b6)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
you are assigned .just want to request you not to delete the scrollbar , just remove the blue line

**Comment by apu52** [comment]
> @sanjay-kv @mukeshtestgit @NaveenChandraAdhikari please label the issue

I think u have tagged the wrong persons .From next time please try to tag the PA & the mentor only
