### ISSUE TITLE
[Documentation Update]: Social footer is not aligned

### ISSUE THREAD

**Issue by adityasingh-0803** [apu52/Travel_Website#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot (43)](https://github.com/apu52/Travel_Website/assets/155234975/ca867724-6e62-45a4-9e80-90a84d3f2533)
see here social platforms are not segregated they are  mixed up please assign me under gssoc

### Suggested Change

see here social platforms are not segregated they are  mixed up please assign me under gssoc

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@adityasingh-0803 u are assigned.
