### ISSUE TITLE
[Bug]: On the "Rate Us?" page, clicking on nav__logo doesn't send you back to #Home

### ISSUE THREAD

**Issue by luiznasc** [apu52/Travel_Website#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking on the nav__logo "Tourguide." on the NavBar nothing happens.

### Expected behavior

 The behavior should be to send you back to "/index.html#Home" or "/index.html".

### Add ScreenShots

Before clicking:
![ss1](https://github.com/apu52/Travel_Website/assets/20481489/b7f41dcc-4325-4a2f-a664-f77820d74354)

After clicking:
![ss2](https://github.com/apu52/Travel_Website/assets/20481489/744e2f4f-95a7-4092-abb7-6ce2f030691a)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by luiznasc** [comment]
Let me know if I can fix it.

**Comment by apu52** [comment]
@luiznasc under which open -source programme , u are contributing

**Comment by luiznasc** [comment]
I'm not on an open source program.

**Comment by apu52** [comment]
> I'm not on an open source program.

ok .u are assigned
