### ISSUE TITLE
Feature_Request : Dark Mode/Light Mode Toggle Button in Navbar

### ISSUE THREAD

**Issue by ramith-kulal** [apu52/Travel_Website#94]
**Is your feature request related to a problem? Please describe.**

The current user interface lacks a dark mode/light mode toggle.

**Describe the solution you'd like**

I would like to propos e the addition of a dark mode/light mode toggle button in the navbar. This button will allow users to switch between dark and light modes based on their preference.

**Demo Video/Screenshot (Mandatory )**
Thinking of adding a toggle button in the marked part any suggestions are welcomed.
![Screenshot 2024-01-19 181448](https://github.com/apu52/Travel_Website/assets/142984776/f660665f-3a37-411e-adf3-4fcf975d1ed6)

***Are you contributing under any open-source program ?***

**Working under JWoC'24**

**Comment by apu52** [comment]
@ramith-kulal This issue is already assigned to another contributor. #61 
So , I will be not able to assign you this issue.
Sorry to close this issue
