### ISSUE TITLE
[Bug]: On the "Rate Us?" page, clicking yet again on the "Rate Us?" link in the NavBar sends you to a stray route.

### ISSUE THREAD

**Issue by luiznasc** [apu52/Travel_Website#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking on "Rate Us?" on the NavBar while already on the "Rate Us?" route sends you to "/index.htmlfeedback.html", which is not a valid route.

### Expected behavior

Opening another "Rate Us?" page.

### Add ScreenShots

![image](https://github.com/apu52/Travel_Website/assets/20481489/e612be2e-a45b-48d6-962a-38aeb3acf74f)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by luiznasc** [comment]
Please, let me know if I can fix it.

**Comment by apu52** [comment]
@luiznasc can you please mention under which open-source programme u are contributing??

**Comment by apu52** [comment]
@luiznasc u are assigned
