### ISSUE TITLE
Feature 🌟: Add "Licensing Page" Reflecting "MIT Licence"

### ISSUE THREAD

**Issue by Tejashri-Taral** [apu52/Travel_Website#941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu ,
Here is the feature request i want to implement -

To provide clear information about the licensing of the website's content and code, we need to add a dedicated "Licensing Page" that reflects the use of the MIT License.
This page will help users understand the terms under which they can use, modify, and distribute the website's resources.

### Use Case

- Clarity and Transparency
- Legal Compliance
- Documentation and Standardization

### Add ScreenShots

Like this:

![image](https://github.com/apu52/Travel_Website/assets/160386036/80e824cd-6f59-4604-baa6-657aa6aa3d7d)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Tejashri-Taral  under which open-source programme , u are contributing???

**Comment by apu52** [comment]
@Tejashri-Taral this is a really good issue .but under which particular open source programme u are contributing??? otherwise I can't assign u

**Comment by Tejashri-Taral** [comment]
I'm a contributor in GSSoC'24.
Please assign to me

**Comment by Tejashri-Taral** [comment]
@apu52 , I'm a contributor in GSSoc'24.
Please assign to me
