### ISSUE TITLE
[Feature Request]: Styling the "Terms and conditions" and "Privacy policy" pages 

### ISSUE THREAD

**Issue by aslams2020** [apu52/Travel_Website#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 ,
I want to suggest this feature so as to improve the visual enhancement of the website.

I **want to style** the current "terms and condtions" & "privacy policy" pages so that **they can match the color theme** of the Website,

**Currently,** 
the terms and condtions page look like this -

![image](https://github.com/apu52/Travel_Website/assets/131389695/0dffde54-7f49-42be-ad57-0a720ded4d70)

and privacy policy page look like this -

![image](https://github.com/apu52/Travel_Website/assets/131389695/038fa9dd-5ddf-415c-8986-39d7571a6b5c)

 

### Use Case

As a user, When i tend to open the terms and condition or privacy policy page...for us, it should enhance the visuality of it..And that can happen only when these pages follows the same color theme as the website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by aslams2020** [comment]
@apu52

**Comment by aslams2020** [comment]
Hey @apu52 , Please assign me this issue

**Comment by aslams2020** [comment]
Hey @apu52 , Please assign me this issue

**Comment by apu52** [comment]
@aslams2020 u are assigned

**Comment by aslams2020** [comment]
@apu52
