### ISSUE TITLE
[Feature Request]: Automatically add label to issues

### ISSUE THREAD

**Issue by avanimathur** [apu52/Travel_Website#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When a user creates a new issue, 
based on the user selecting "I'm a GSSOC'24 contributor" or "I'm a VSOC'24 contributor" , 
automatically "gssoc" or "VSoC'24" label is added respectively .

### Use Case

This reduces the work of the project owners and maintainers by automatically adding labels based on what the user has selected.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@avanimathur this is a real good issue that will be very helpful to the mentors. thanks a lot

**Comment by avanimathur** [comment]
Thank You!
I'll start working on it.
