### ISSUE TITLE
[Feature Request]: Adding a eye button in password field

### ISSUE THREAD

**Issue by pani2004** [apu52/Travel_Website#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the login page a eye button should be there in the password field for toggling visibility

### Use Case

Password visibility

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by pani2004** [comment]
@apu52 Can I work on this?

**Comment by honey7733** [comment]
I would like to work on this project or issue. Kindly assign it to me.

**Comment by IshaanXCoder** [comment]
@apu52 pls assign me with this issue, you'll definitely like my work!

**Comment by apu52** [comment]
@pani2004 now in the website (in the login page) the eye button already exists . so sorry to close this issue for now . but u can still make new issues on which u want to work on
