### ISSUE TITLE
[BUG] Contact Us Not Responsive 

### ISSUE THREAD

**Issue by thatguywhocode** [apu52/Travel_Website#96]
Description: The contact us in navbar is not funtioning.

Expected Behaviour: On clicking the button, the page should scroll down to contact section.

Please assign me this issue under JWOC.

**Comment by apu52** [comment]
@thatguywhocode Please raise/update  your issue with proper ISSUE template by filling all the details in the issue which is already given in the NEW ISSUE section

**Comment by apu52** [comment]
@thatguywhocode Are you still working on this issue

**Comment by thatguywhocode** [comment]
There was some glitch but now its working fine.

**Comment by apu52** [comment]
> There was some glitch but now its working fine.

Raise a new proper issue on this topic

**Comment by apu52** [comment]
I am closing this issue. Please make a new issue properly on this topic
