### ISSUE TITLE
[Feature Request]: Make proper alignment in mentioned section

### ISSUE THREAD

**Issue by Rajput-xv** [apu52/Travel_Website#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The sections mentioned below is not properly aligned with the current website these should be aligned in center to look more visually attractive.

![image](https://github.com/apu52/Travel_Website/assets/114978813/0e29893e-85b3-4e79-a911-05ad0039ed14)

another section needs the alignment.

![image](https://github.com/apu52/Travel_Website/assets/114978813/2bedda85-e346-44d9-8d48-bacfdf493e88)

in this also

![image](https://github.com/apu52/Travel_Website/assets/114978813/de02dc6e-d2e9-4775-b453-8edb8cc4e6f2)

 

### Use Case

this section should be appealing according to the website standards.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Rajput-xv now this alignment problem has already been solved . Sorry to close this issue for now . but u can still make new issues on which u want to work on
