### ISSUE TITLE
[Feature Request]: add effect on mentioned section

### ISSUE THREAD

**Issue by Rajput-xv** [apu52/Travel_Website#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/apu52/Travel_Website/assets/114978813/37e2ad63-3169-4e91-9edc-af479f334f50)

in above section when the image is clicked its width is increased but not when it is hovered.

### Use Case

i would like to add the effect to preview an image which will be easier for user to decide if he/she want to click on it or not. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Rajput-xv u are assigned .but there is some recent changes in the image slider now . so please update your branch before contributing.
