### ISSUE TITLE
Adding Dockerfile/docker-compose to run project  easily

### ISSUE THREAD

**Issue by mayank-0407** [apu52/Travel_Website#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding Docker file to Deploy or to setup locally.

### Use Case

This is a feature that helps the contributors setup this project easily on their pc. It will also help to deploy the project with great ease.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@mayank-0407 are u still working on this issue ??
