### ISSUE TITLE
[Bug]: View in Navbar

### ISSUE THREAD

**Issue by me-nilakshi** [apu52/Travel_Website#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![travel](https://github.com/apu52/Travel_Website/assets/101091762/759150e2-d8c5-45eb-b29a-19d4b7633bae)
The view in Navbar is showing error.

### Expected behavior

Once you click on view on navbar, it must open to google maps helping user to navigate through the map

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@me-nilakshi actually to solve this issue ,it needs to buy some google credits ...can u fic this in that manner?? If yes, ping me here , then I will assign u

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me

**Comment by Nikhilkumar111** [comment]
Hello  sir , plz Assign to me this issue .
