### ISSUE TITLE
[Bug]: Login and Register Page

### ISSUE THREAD

**Issue by me-nilakshi** [apu52/Travel_Website#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Travel0](https://github.com/apu52/Travel_Website/assets/101091762/9821979e-9f50-4d6f-a00d-acd2f07c0dfa)
![travel00](https://github.com/apu52/Travel_Website/assets/101091762/7f74843d-de6d-4b2a-bc9f-16c66a602841)
Both the pages are working fine even when details are not filled, i.e. user navigate further without typing their details.

### Expected behavior

The fields for both the pages must indicate required. It shows error when all fields are not filled on either page. Once the details are filled, the user navigates further.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@me-nilakshi u are assigned

**Comment by me-nilakshi** [comment]
Hey [apu52](https://github.com/apu52)
Please delete the unnecessary files in your repo. I'm facing difficulty in cloning the repo. I've troubleshoot from my end. But since the file size is large and unorganised, it showing error.
Kindly look into this.

**Comment by apu52** [comment]
> Hey [apu52](https://github.com/apu52) Please delete the unnecessary files in your repo. I'm facing difficulty in cloning the repo. I've troubleshoot from my end. But since the file size is large and unorganised, it showing error. Kindly look into this.

Please try to fork & clone this repo again. & I also think this issue has already been solved

**Comment by VAMPIREGIRLVG** [comment]
i am ready for solve the problem

**Comment by Theboycut05** [comment]
I can do it better can you assign me
