### ISSUE TITLE
CREATE DEDICATED PAGES FOR 3 DESTINATIONS OF TRIP PACKAGES  #enhancement

### ISSUE THREAD

**Issue by ratnojitsaha** [apu52/Travel_Website#97]
**Describe the bug**
The buttons of [Santorini ,Aegean Sea],  [Machu Picchu ,Peru] , [Grand Canyon National Park ,Arizona]  does not work on-click, I 
want to add dedicated pages for them as they are in display without view all. Later i may put issue to create more pages for the rest of the places. 
Also I want to fix the pricing review section and testimonial section both needs some alignment.

**Expected behavior**
For the alignments the section images are partially trimmed (**goes down) or the heading of the below section is partially visible when visited by the **nav links**

**Screenshots (Mandatory)**
![Screenshot (484)](https://github.com/apu52/Travel_Website/assets/110903082/5d9b4695-f7c0-45a5-bd87-9a6ba692f6ac)

![Screenshot (485)](https://github.com/apu52/Travel_Website/assets/110903082/b4b0220b-9e9e-415f-b1f1-9bb7f79cb48d)

***Are you contributing under any open-source program ?***
  - JWOC 2024

**Comment by apu52** [comment]
@ratnojitsaha JUST make the different pages for the 3 places by clicking on the **"book now"** button in this issue
I am assigning you

**Comment by ratnojitsaha** [comment]
@apu52 sure

**Comment by ratnojitsaha** [comment]
@apu52  sry for the delay from my side haven't worked on it yet, someone in my family passed away. I understand the importance of quick updates. Please consider an extension of 2 days, will submit u by day after tommorrow.

**Comment by apu52** [comment]
> @apu52 sry for the delay from my side haven't worked on it yet, someone in my family passed away. I understand the importance of quick updates. Please consider an extension of 2 days, will submit u by day after tommorrow.

Take as much time as you want . Don't worry . Don't take any pressure. Just go ahead

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by ratnojitsaha** [comment]
@apu52,  Should I change anything ******please check******

Here is a sample for one of the destinations (Santorini ,Aegean Sea.)
***THE NEXT & PREV buttons changes the pics of the destinations
***THE  CHECKOUT button takes to the PAYMENT.html page!!

![Screenshot (490)](https://github.com/apu52/Travel_Website/assets/110903082/921ee11e-7192-48cc-bf41-105bb79a6d88)
![Screenshot (491)](https://github.com/apu52/Travel_Website/assets/110903082/a7c1ca4b-9903-4c85-965b-748a406affe5)

**Comment by ratnojitsaha** [comment]
@apu52 okay
