### ISSUE TITLE
Remove second social media from footer

### ISSUE THREAD

**Issue by IshaanXCoder** [apu52/Travel_Website#970]
<img width="966" alt="image" src="https://github.com/apu52/Travel_Website/assets/75419419/3d578423-11ce-4259-8de0-fed99b2c5b86">

There are two social media divs as shown in the picture above, and the second one needs to be deleted.

**Comment by IshaanXCoder** [comment]
@apu52, please assign this issue to me. I'm confident you'll like my work!

**Comment by apu52** [comment]
@IshaanXCoder this issue is not too much descriptive & not clear to me .please use the issue templates to raise your new issues which are already present in this issue .
Sorry to close this issue for now
