### ISSUE TITLE
[Bug]:  Redesign Contact Us Section and Integrate Feedback Form in Footer

### ISSUE THREAD

**Issue by AsmitaMishra24** [apu52/Travel_Website#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current placement and elements of the contact us section on our website need to be redesigned for better usability and visual coherence. The issues include improper button styling, poor visibility of the input box, and the need to integrate the feedback form into a more accessible area of the website, away from the footer.

**Current Issues:**
1. Button Styling: The buttons within the contact us section lack proper styling, which affects their consistency with the overall website design.
2. Input Box Visibility: The input box for user contact details is not prominently visible or clearly distinguishable from surrounding elements.
3. Feedback Form Integration: The feedback form is currently located in the footer, which makes it less accessible and disrupts user interaction flow.

### Expected behavior

**Desired Corrections:**
1. Button Design: Ensure that buttons in the contact us section are styled consistently with the website's design language, including hover and active states for improved user feedback.
2. Input Box Visibility: Enhance the visibility and usability of the input box, making it more prominent and user-friendly.
3. Optimal Feedback Form Placement: Integrate the feedback form into a more prominent and accessible area of the website, such as the sidebar or a dedicated contact page, to improve user engagement and usability.

The redesigned contact us section should be visually appealing, easy to use, and seamlessly integrated into the website's navigation and user experience. Users should find it straightforward to locate and utilize the contact options provided.

### Add ScreenShots

![Screenshot 2024-07-04 013227](https://github.com/apu52/Travel_Website/assets/146121869/a2bf1edb-c67e-43c0-8ad1-3b9a8f1aa456)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@AsmitaMishra24 I have assigned u , just want to request u that can u provide the SS of the new contact us section after your contribution , so that it will be helpful

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 I have assigned u , just want to request u that can u provide the SS of the new contact us section after your contribution , so that it will be helpful

@apu52, Sure, also I will move the feedback section to the footer. Is that okay, or should I keep the feedback as it is?

**Comment by apu52** [comment]
> > @AsmitaMishra24 I have assigned u , just want to request u that can u provide the SS of the new contact us section after your contribution , so that it will be helpful
> 
> @apu52, Sure, also I will move the feedback section to the footer. Is that okay, or should I keep the feedback as it is?

no keep it as it is .or maybe u can implement this button in more advanced UI

**Comment by AsmitaMishra24** [comment]
> > > @AsmitaMishra24 I have assigned u , just want to request u that can u provide the SS of the new contact us section after your contribution , so that it will be helpful
> > 
> > 
> > @apu52, Sure, also I will move the feedback section to the footer. Is that okay, or should I keep the feedback as it is?
> 
> no keep it as it is .or maybe u can implement this button in more advanced UI

ok
