### ISSUE TITLE
[Feature Request]: Redesign Destinations Section with Hover Card Effect

### ISSUE THREAD

**Issue by AsmitaMishra24** [apu52/Travel_Website#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The destinations section on our website requires a redesign to enhance visual appeal and user interaction. The objective is to incorporate hover card effects to provide users with more interactive and engaging information about each destination.

**Redesign with Hover Card Effect:**
1. Implement hover card effects to display additional information (such as description, key attractions, and images) when users hover over each destination.
2. Ensure the hover cards are visually appealing, consistent with the website's design language, and easy to navigate.
3. Use animations or transitions to create a smooth and engaging user experience.

**Enhance Visual Appeal:**
1. Improve the overall visual design of the destinations section to attract and retain user attention.
2. Consider using high-quality images and clear typography to enhance readability and visual appeal.

### Use Case

1. User Engagement: Users can hover over destinations to quickly access key information, enticing them to explore further.
2. Information Accessibility: Provides a more intuitive way for users to learn about each destination's unique features without navigating away from the main page.
3. Enhanced Navigation: Allows users to interact directly with destination details, improving overall user experience and satisfaction.

### Benefits

1. Improved User Experience: Enhances user interaction by providing informative hover cards that display relevant details instantly.
2. Increased Engagement: Encourages users to explore destinations more deeply by making information readily accessible and visually appealing.
3. Reduced Bounce Rate: Provides a more engaging interface that reduces the likelihood of users leaving the site due to lack of information or interest.
4. Enhanced Visual Appeal: Elevates the aesthetic quality of the destination section, making it visually appealing and modern.
5. Promotes Exploration: Facilitates easier exploration of destinations, potentially leading to increased bookings or conversions.

### Add ScreenShots

Currently:
![Screenshot 2024-07-04 014330](https://github.com/apu52/Travel_Website/assets/146121869/2b89c1f5-7e9b-4369-8957-197cc3d0b994)

Example:
![maxresdefault (1)](https://github.com/apu52/Travel_Website/assets/146121869/c9eeb16b-bff6-40e0-901a-7338b564aff7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@AsmitaMishra24 the issue is good.go for it
