### ISSUE TITLE
Adding social media icons 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [apu52/Travel_Website#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding social media icons  for different sections such as home , contact , rate us etc:- on the navbar would enhance the website look .

### Use Case

This feature would enhance user experience  for your website.

### Add ScreenShots

![Screenshot 2024-07-05 020927](https://github.com/apu52/Travel_Website/assets/117037441/3491961f-5c1a-44ba-beec-de5495405835)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Soumya6Tiwari** [comment]
@apu52  kindly assign me this issue under gssoc'24

**Comment by apu52** [comment]
@Soumya6Tiwari actually we already have social media icons in the Footer section . so I think there is no need to add icons in all of the fields . SO ,Sorry to close this issue .
But u can still make new issues on which u want to work on
