### ISSUE TITLE
[Feature Request]: Improve view more page, Add same footer to all pages

### ISSUE THREAD

**Issue by sau-mili** [apu52/Travel_Website#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Footer not same in all pages
UI of view more in packages section hyperlink, does not have a good UI

### Use Case

For any user who want to check out packages

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by sau-mili** [comment]
can you assign me this @apu52 ?

**Comment by apu52** [comment]
> can you assign me this @apu52 ?

I have assigned u .now u can start contributing

**Comment by abhisek2004** [comment]
i want to contribute add me

**Comment by sau-mili** [comment]
it's already assigned to me. you should raise some other issue
