### ISSUE TITLE
Feature_Request : Addding more footer classes

### ISSUE THREAD

**Issue by TanushreeBorase** [apu52/Travel_Website#99]
**Is your feature request related to a problem? Please describe.**
I would like to give a suggestion to add more footer classes. 

**Describe the solution you'd like**
I would like to add footer class Explore: Write a review, Traveller's choice, Travel articles, add a Place, seasonal and holiday deals; under Support: How we work, safety resource center.

**Describe alternatives you've considered**
we may add Connect with us feature also as footer class  : Twitter, youtube, facebook. I thought we have footer classes currently: Support and  Adress  along with Tourguide. Adding more classes and making space even would make ui look more good.

**Demo Video/Screenshot (Mandatory )**
<img width="936" alt="image" src="https://github.com/apu52/Travel_Website/assets/130696335/3936dc1d-1192-48ac-b078-3aeb0ff8eb3c">

***Are you contributing under any open-source program ?***
JWOC'24

**Comment by apu52** [comment]
@TanushreeBorase You are assigned . you can start working on this issue
