### ISSUE TITLE
Redesigning section

### ISSUE THREAD

**Issue by Jasleen1210** [apu52/Travel_Website#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/apu52/Travel_Website/assets/144164397/be8dfbf7-2e63-455b-ae8f-a14b2f3e88b5)

I'd like to redesign this section such that the timer counts up to the current number at the same time (currently there is a time lag among them) 
also: 
-Add hover styles to the cards
-Edit the card colours and border styles a bit 

### Use Case

Counter currently takes up way too much time, id like to implement a shorter timer that wont grab too much of the users time and make it look dynamic and attractive

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@Jasleen1210 u are assigned
