### ISSUE TITLE
[Documentation Update]: Duplicate social media icons

### ISSUE THREAD

**Issue by Saipradyumnagoud** [apu52/Travel_Website#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

There are duplicate social media icons in the footer

### Suggested Change

I will remove on of them

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by Saipradyumnagoud** [comment]
@apu52 Please assign me the issue

**Comment by apu52** [comment]
@Saipradyumnagoud I didn't get your point in the issue .Can you please explain more

**Comment by Saipradyumnagoud** [comment]
i have merged the pull request you can check the changes please

**Comment by Meeta-28** [comment]
@apu52 please assign this issue to me
