### ISSUE TITLE
[Bug]: Chatbot Visible During Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [apu52/Travel_Website#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the preloader is displayed, the chatbot remains visible. This results in a cluttered UI and a potentially confusing user experience. Ideally, the chatbot should be hidden while the preloader is active.

### Expected behavior

The chatbot should be hidden while the preloader is visible, and it should reappear only after the preloader has finished and the main content is displayed.

### Add ScreenShots

![Screenshot 2024-07-06 021104](https://github.com/apu52/Travel_Website/assets/146121869/4eb52fe2-8d63-4932-bf3d-bd44d44a5091)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@AsmitaMishra24 I think I have already assigned u 2 issues before . so I have put  this issue in the WAITING . After successful completion of the previous 2 issues , ping me here , I will assign u this issue

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 I think I have already assigned u 2 issues before . so I have put this issue in the WAITING . After successful completion of the previous 2 issues , ping me here , I will assign u this issue

ok

**Comment by AsmitaMishra24** [comment]
@apu52 , @itsekta please assign me this issue. Out of 2 issues, the first one is completed, and I am working on the second one.
