### ISSUE TITLE
[Feature Request]: Add a top arrow on bottom right in place of button at bottom.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is a button at the top. I can an arrow symbol at the right which on click takes the scroll to the top.

### Use Case

This button lacks styling and is at the extreme bottom. Arrow symbol will be added with appropriate styling and animations.

### Add ScreenShots

![Screenshot (631)](https://github.com/apu52/Travel_Website/assets/143121854/7819b377-8483-4806-9162-7106464f7ff1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 this issue is already existing in this repo .Sorry to close this issue. looking =forward to see more of your new issues
