### ISSUE TITLE
[Feature Request]: Add a navbar on the login/signup page.

### ISSUE THREAD

**Issue by meetarora10** [apu52/Travel_Website#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Navbar is missing from the login/signup page. I can add the navbar on this page similar to other pages.

### Use Case

Due to the missing navbar we cannot go to any other page from this page.

### Add ScreenShots

![Screenshot (632)](https://github.com/apu52/Travel_Website/assets/143121854/2a555240-f433-41ce-823b-a4853a24d2f7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@meetarora10 I think there is no need to add unnecessary navbar in login page . Sorry to close this issue . But looking forward to see more of your issues
